- BuildLoader.py
When there are multi versions of VS installed on the Windows host
system, BuildLoader.py often set up old VS version for the toolchain
variable. Resolve it by changing the structure type of vs_ver_list.
Signed-off-by: Augustine Chen <augustine.chen@intel.com>
> Resolve the problem that VS toolchain is often set to older version

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/ConsoleInLib.h
- BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.c
- BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.inf
- BootloaderCommonPkg/Library/ShellLib/Shell.c
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
Current implementation assumes serial port is the only input console
device supported.  But other input console devices can be added later
on. This patch added a ConsoleInLib to abstract the input console
interfaces.  It also added PCDs to control enabled input console
devices.
> Add ConsoleInLib to abstract console input

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
When copying boot option from configuration data to
internal boot option structure, the code should just
copy exact size required for boot options.
> [APL] Fix size bug when copy BootOption

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
On APL platform, all PCI MMIO range is set to UC in current
implementation. It includes graphics framebuffer MMIO. It
caused the system performance issue due to large mount of
framebuffer write access. This patch set framebuffer as
WC (WriteCombining) per recommendation to enhance system
performance.
> Enable graphics framebuffer as WriteCombining

- BootloaderCorePkg/Tools/GenCfgData.py
Currently GenCfgData.py tool could open generated
CfgDataDef.dsc, but could not open CfgDataDef.dsc
in the source code since it includes other DSC files
in CommonBoardPkg. The files could not be found by
default if SBL_SOURCE is not defined.
This patch would search DSC in CommonBoardPkg, so
even SBL_SOURCE is not defined, it could still open
CfgDataDef.dsc.
> Enhance GenCfgData tool

- Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/PciDrc.asl
On APL platform, the chipset SoC reserved MMIO resources are not
reported properly to OS through ACPI. It should report it using
_CRS method. This patch fixes #28.
> Report APL SoC reserved MMIO resources through ACPI

- BootloaderCommonPkg/Include/Library/ShellLib.h
- BootloaderCommonPkg/Library/ShellLib/CmdDmesg.c
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
This patch adds a new shell command `log` to print out the contents of
the boot log buffer.
> Add shell command to print contents of log buffer

- BootloaderCommonPkg/Include/Library/ElfLib.h
- BootloaderCommonPkg/Include/Library/MultibootLib.h
- BootloaderCommonPkg/Library/ElfLib/Elf32.h
- BootloaderCommonPkg/Library/ElfLib/ElfCommon.h
- BootloaderCommonPkg/Library/ElfLib/ElfLib.c
- BootloaderCommonPkg/Library/ElfLib/ElfLib.inf
- BootloaderCommonPkg/Library/MultibootLib/Multiboot.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2.inf
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/OsLoader.inf
In order to support ELF format payload in Stage2, ElfLib is
separated from MultibootLib.
Change-Id: Iac45e8511101e2d12cb9a9f7f9bb2394a1e7be39
> Support ELF format payload

- BootloaderCommonPkg/Library/DebugAgentLib/DebugAgentLib.c
QEMU FSP reports that CAR base is 0x0, but DebugAgent cannot access
the memory space since MEMORY_READY is not set.
In order to disable low memory filtering, simply check CAR space and
then trigger MEMORY_READY.
Change-Id: I9e1703215c95fd64e2a0be3afd001c59f736e81b
> [DebugAgent] Fix image info loading failure in QEMU CAR stage

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpFuncs.nasm
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLibInternal.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BuildLoader.py
- Platform/ApollolakeBoardPkg/ApollolakeBoardPkg.dec
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
SBL has no intention to support SMI. However, on many hardware
platform, there is no reliable way to prevent SMI from generating
through SMI SPI.  In case it occurs, CPU will jump to the default
0x38000 location for execution, which exposes huge security issues.
The recommended solution is to do basic SMM base relocation and put
a dummy SMI handler (RSM) there. In this way, the SMI will be ignored,
and it also closes the security concerns. This patch implemented
basic SMM relocation.
It is under the control of a new PCD PcdSmmRebaseEnabled. By default,
it is disabled.  To enable it, please set ENABLE_SMM_REBASE in
BoardConfig.py. As part of it, platform library needs to set
PcdSmramTsegBase and PcdSmramTsegSize properly in PreSiliconInit board
hook. Please take APL platform for reference. …
> Add basic SMM rebasing support

- BootloaderCorePkg/Library/MpInitLib/Ia32/MpFuncs.nasm
Current MpFuncs.nasm used hard coded opcodes to support 16bit ASM.
It makes it difficult to maintain. Per suggestion, this patch
convered the 16bit opcodes into instruction directly.
> Convert ASM opcode to instructions in MpFuncs

- BootloaderCommonPkg/Library/DebugAgentLib/DebugAgentLib.c
This reverts commit 8cba382774c2300a8e4c603029f875826f7adb54.
The original fix still has the issue on Windows UDK Debugger and
a simpler way can resolve the QEMU specific issue. In UDK debugger
configuration, 'NoAccessLimit = 0' is required for QEMU only.
[Target System]
NoAccessLimit = 0x0
This change has been verified on both Linux and Windows UDK Debuggers
and user guide will include this information.
Change-Id: I09de713d7a9a892230475cbc4aca70b1a5c11b3c
> Revert '[DebugAgent] Fix image info loading failure in QEMU CAR stage'

- BootloaderCorePkg/BootloaderCorePkg.dsc
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Silicon/ApollolakePkg/Include/Library/VtdLib.h
- Silicon/ApollolakePkg/Library/VtdLib/VtdLib.c
- Silicon/ApollolakePkg/Library/VtdLib/VtdLib.inf
When VTD_ENABLE sets to '0', a compile error occurs because some .inf
files refer to VtdLib. Therefore, VtdLib is included to default
libraries - dsc_libs['IA32'].
Additionaly,
- Rename VTD_ENABLED to ENABLE_VTD to make feature enabling name
consistent
- Remove hard-coded UART2 BAR for ACRN
Change-Id: I22969c0e4509ab0a0dc21d50e6afbdfb893f25a8
> Fix a compile error when VTD is disabled on APL

- BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.inf
BootloaderCoreLib use same File_GUID and Base_NAME
with BootloaderLib, this patch updates INF to fix
this issue.
> Update file Guid and name in BootloaderCoreLib

- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/HashStore.h
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.c
- BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.c
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.h
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2Support.c
- BuildLoader.py
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Silicon/ApollolakePkg/Library/PsdLib/PsdLib.c
Current code refers hash store as "key store". It is confusing
since there is no key stored in the image at all.  Instead, the
public key hash is stored.  The patch renames the KeyStore
to HashStore.
> Rename KeyStore to HashStore to reduce confusion

- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/KeyManagement.c
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/SeedSupport.c
There are 'uninitialized' errors and size exceed error in PAYLOAD
with old gcc versions. This change has been verified with gcc-4.8,
gcc-5, gcc-7 and gcc-8 on Ubuntu 18.04 LTS.
> [GCC] Fix gcc compile errors

- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Ia16/Real16ToFlat32.asm
This patch retains the cache disable bit status
at reset vector. Needed for secure boot.
Signed-off-by: Vijay B S <vijay.ballagere.siddalingaiah@intel.com>
> Retain the state of cache disable bit

- BootloaderCorePkg/Tools/GenCfgData.py
Remove SBL_SOURCE env dependency when searching DSC
file, instead it uses GenCfgData tool path to find
the slim boot source root.
> Update GenCfgData tool

- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
Current SitchLoader.py does not verify if the BP1 partition size
is big enough to hold a duplicated BPDT from BP0. And it will
result in invalid BPDT partition format if it occurs. This patch
added a check so that it will error out if insufficient space is
detected.
> [APL] Add BP1 partition size check in StitchLoader.py

- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
fastboot protocol allows communication between host and device bootloader
via USB or Ethernet. This patch provides initial configuration in SBL
so that device can enter fastboot mode on device when all previous boot
options are failed.
Typically fastboot is used to provision OS images to eMMC with fastboot
client tool.
The fastboot executable is required to be packaged in IAS format
then integrated into SPI image or copied into the first FAT partition on
a USB key.
This change fixed build configuration to load fastboot code either from
SPI or USB.
Signed-off-by: Huang Jin <huang.jin@intel.com>
> Integrate external fastboot code as a boot option

- BuildLoader.py
The latest SBL source code does not build on certain environment.
For example, when PYTHON_HOME is not set manually, it will cause
build failure due to invalid path for python.exe.  This patch will
set the PYTHON_HOME env variable if it has not been set already.
> Set PYTHON_HOME env variable for Windows build

- Platform/ApollolakeBoardPkg/BoardConfig.py
On APL platform, default EPAYLOAD size is more than 1MB to enable
UEFI payload. However, if UEFI payload is not used, the space is
still reserved in flash. A more flexible way is to reserve the
EPAYLOAD size only when it is specified in the build command line.
This patch added this capability.
> [APL] Make EPAYLOAD size dynamic

- Platform/ApollolakeBoardPkg/BoardConfig.py
SBL supports open source stitching mechanism based on an existing
IFWI binary. It can also support FIT stitching mechanism. For FIT
stitching, it is required to add certain padding in the layout so
that each component in IBB and OBB partition can be 4KB aligned.
Current padding component IPAD/OPAD size needs to be updated to
match the number of the component inside IBB and OBB partition.
This patch adjusted the padding size accordingly.
> [APL] Adjust flash layout padding for stitching

- BootloaderCommonPkg/Library/FileSystemLib/FileSystemLib.c
- PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
File system is not initialized when invalid parameter is
given to InitFileSystem(). This bug causes FWU payload
fails to load capsule using shell command fwupdate.
Signed-off-by: Huang Jin <huang.jin@intel.com>
> Fix firmware update bug to load capsule from USB

- PayloadPkg/OsLoader/OsLoader.c
Enable USB keyboard by default.
> Make USB keyboard not depend on OS boot option.

- BootloaderCommonPkg/Library/UsbBlockIoLib/PeiAtapi.c
The current USB block read library trancated the number of blocks
to read from UINT32 to UINT16. It caused read issue for large file
on USB disk. This patch fixed #63. It has been verified on LeahHill
CRB platform.
> Fix large file read issue on USB device

- Platform/ApollolakeBoardPkg/BoardConfig.py
This change makes more space for SBL paylaod to load
larger IAS image (e.g. Ubuntu kernel + initrd ~ 33MB)
The payload heap memory is reusable as long as crash mode
is disabled.
TEST=Loaded and booted IAS image containing Ubuntu kernel and
initrd from USB flash drive on UP2 board.
Signed-off-by: Huang Jin <huang.jin@intel.com>
> [APL] Enlarge payload heap size from 64MB to 128MB

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
SBL supports putting platform packages in a separate repo tree
defined by environment variable PLT_SOURCE. Current build process
will always retrieve the latest commit id info from open source
repo as version even when the platform uses a separate repo tree.
This patch corrected this behavior. When a platform package is in
a separate repo, the git commit id info will be retrieved from that
platform repo instead.
> Retrieve version info from proper platform repo

- BootloaderCorePkg/Stage2/Stage2.c
When UEFI payload or epayload is enabled and firmware update mode
is enabled, current code in prepare payload function will consider
firmware update payload as multi payload. This is causing failure
and end up as halting cpu.
This patch will add an additional check for firmware update mode
and do hash verification
TEST=Verified that firmware update is working when UEFI payload
is enabled.
> Fix firmware update failure

- BootloaderCommonPkg/Include/Library/LitePeCoffLib.h
- BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2Support.c
Previously SBL expects UEFI payload entrypoint and base at
hardcoded address of FV header. With this patch, SBL could
parse FV to get these info.
TEST=Tested on Leafhill and boot UEFI payload success.
> Enhance UEFI payload support

- BootloaderCorePkg/Stage2/Stage2.c
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
This patch enabled payload loading into high memory by default. It
is a more general way to allocate memory for payload image instead
of hard-coded base address.  However, in some special cases, such
as UEFI payload, it still needs to be executed at pre-compiled address.
This patch also handled this special case in the flow.
> Enable payload loading to high memory by default

- BootloaderCommonPkg/Include/Library/LiteFvLib.h
- BootloaderCommonPkg/Include/Library/LitePeCoffLib.h
- BootloaderCommonPkg/Library/LiteFvLib/FvLib.c
- BootloaderCommonPkg/Library/LiteFvLib/FvLib.h
- BootloaderCommonPkg/Library/LiteFvLib/LiteFvLib.inf
- BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
This patch did some clean up for LiteFvLib and LitePeCoffLib.  It
also moved LoadFvImage() API from Stage2 core code into the LiteFvLib.
> Refactor LiteFvLib/LitePeCoffLib implementation

- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage2/Stage2.c
Print a debug message if EXT CFG Data fails to append
in the config database. ALso, print the Payload ID in
stage2.
> Adding print for EXT CFG data and payload ID

- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/OsLoader.inf
This is a feature implementation to enabled chained payloads loading
for UEFI. Current SBL boot flow requires UEFI payload to be built in
flash in order to boot UEFI payload. However, for convenience, if
somebody just wants to try UEFI payload, it is better to allow them to
chain-loading the UEFI payload from media devices such as USB, SATA, etc,
and then boot to UEFI payload directly. This patch enabled this feature.
The new supported boot flow is:  SBL->OsLoader->UefiPayload->OS. The
same applies to other ELF/PE32 based other payloads.
To do this the UEFI payload needs to be packed into IAS image using
iasimage script. The command line is as below:
python iasimage.py create -d TestSigningIasPrivateKey.pem UefiPld.fd
-o iasimage.bin -i 0x30000
Please use the latest iasimage script from …
> Enable UEFI payload boot from IAS image

- BootloaderCorePkg/Tools/GenCfgData.py
CFGDATA name should be unique in the whole CFGDATA database. Current
tool does not check this and will keep silent for this error. This
brings issue into later development stage. The build process should
be enhanced to check this and error out if duplicated CFGDATA item is
found. This patch added this check.  It fixed #81 .
> Add duplicated CFGDATA check in GenCfgData.py

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
In current implementation, FspDebug/BldDebug flag is saved into
VerInfo.txt. But it should be always determined by the build flags
instead of the VerInfo.txt file. This patch fixed #84 .
> Remove Debug/Release field from VerInfo.txt file

- BuildLoader.py
- Platform/QemuBoardPkg/CfgData/CfgData_CapsuleInformation.dsc
- Platform/QemuBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch fixed some QEMU firmware update related issues.
It enabled firmware update testing on QEMU using script.
> Enable QEMU firmware update test

- BuildLoader.py
BuildLoader.py will failure to run git command if Slim bootloader
source code is not in a git repo. Update Buildloader.py to check
if git repo could not be detected, it will not run git command to
clean un-tracked git files.
TEST=Tested to build/clean APL success without git repo.
> Enhance build script for clean command

- Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/Dsdt.asl
- Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/Gfx.asl
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch enabled APL GFX OpRegion in ACPI table. The OpRegion ASL code
was commented out in current DSDT.  It was causing Windows boot issue
due to invalid ASLB field value in ACPI GNVS. This patch addressed this
issue, and it fixed #88 .
> [APL] Enable GFX OpRegion in ACPI

- BaseTools/Source/C/GenVtf/GenVtf.c
- BaseTools/Source/C/Makefiles/header.makefile
This change includes below commits from the latest EDKII.
- The build failure has been identified on Fedora 29 with gcc version
8.2.1 20181215 (Red Hat 8.2.1-6).
- Verified no compile errors with below changes from EDKII.
commit 9de306701312f986c9638cb819d3f1f848d55cab
Author: Laszlo Ersek <lersek@redhat.com>
Date:   Fri Mar 2 17:11:52 2018 +0100
BaseTools/GenVtf: silence false "stringop-overflow" warning with memcpy()
commit 03252ae287c4a61983b3793ff71baeabe2ff3df7
Author: Laszlo Ersek <lersek@redhat.com>
Date:   Wed Jul 25 22:40:09 2018 +0200
BaseTools/header.makefile: remove "-c" from BUILD_CFLAGS
commit 9222154ae7b3eef75ae88cdb56158256227cb929
Author: Laszlo Ersek <lersek@redhat.com>
Date:   Fri Mar 2 17:11:52 2018 +0100
BaseTools/header.makefile: add "-Wno-restrict"
commit …
> BaseTools: Fix build failure on Fedora29 with gcc 8.2.1

- BootloaderCorePkg/Include/Library/AcpiInitLib.h
- BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Stage2/Stage2.c
- Platform/ApollolakeBoardPkg/AcpiTables/AcpiTables.inf
- Platform/CommonBoardPkg/AcpiTables/Fpdt/Fpdt.aslc
- Platform/QemuBoardPkg/AcpiTables/AcpiTables.inf
This patch adds FPDT table into ACPI table, and updates all the performance data for S3 path. Some other
It also update basic boot performance data for reset end. other basic boot performance data could be updated by UEFI payload.
> Add ACPI Firmware Performance Data Table (FPDT) support

- BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- PayloadPkg/OsLoader/KeyManagement.c
- PayloadPkg/OsLoader/OsLoader.c
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
LOADER_PLATFORM_INFO.LdrFeatures is used to for feature updates
and this need to be checked by loader and payloads.
LOADER_PLATFORM_INFO.HwState for Hw supported features as
Boot guard profiles.
> Security Flags updates to LOADER_PLATFORM_INFO

- BootloaderCommonPkg/Library/FatLib/FatLiteAccess.c
- BootloaderCommonPkg/Library/FatLib/FatLiteApi.c
- BootloaderCommonPkg/Library/FatLib/FatLiteLib.c
- BootloaderCommonPkg/Library/FatLib/FatLitePeim.h
Current FAT library can only support loading file from the root
directory of FAT file system. This patch enhanced it to support
load file from FAT file system with any give full path. Both unix
and Windows style path are supported. For example, "efi\boot.cfg",
"\efi\boot.cfg", "/efi/boot.cfg", etc, all are valid path string.
> Add full path support for FAT file loading

- BootloaderCommonPkg/Include/Guid/SmmInformationGuid.h
- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpFuncs.nasm
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLibInternal.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Smm bases for all the procs need to be relocated on the
S3 resume path (as payload is not run) for Windows boot.
> Relocate SMM bases on S3 resume path

- Platform/ApollolakeBoardPkg/BoardConfig.py
A work-around for ACRN hypervisor hang loaded by SBL.  The complete
fix requires iasimage tool to support correct alignment for subcomponents
This reverts commit c467303715a6b0358a3ad9a53744ba2706de3fd9.
> Revert "[APL] Enlarge payload heap size from 64MB to 128MB (#68)"

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
- PayloadPkg/OsLoader/BootConfig.c
- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/OsLoader.inf
- PayloadPkg/PayloadPkg.dec
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/BoardConfig.py
This patch added a simple parser for grub.cfg to make it easy to boot
Ubuntu ISO image using OsLoader payload. Without it, it is required to
copy vmlinuz/initrd to root directory and create a config.cfg to list
the kernel boot command line in order to boot the ISO image. This patch
makes it possible to boot the original Ubuntu ISO (16.04 or 18.04)
directly. It provides better user experience for people who wants to
try out SBL.
Please note, same as before, when verified boot is enabled, only debug
build will support this feature. Release build will disable this feature
due to security concern, please use IAS image boot mechnism instead.
> Add GRUB config file support to boot Ubuntu

- BootloaderCommonPkg/Library/FatLib/FatLiteAccess.c
- BootloaderCommonPkg/Library/FatLib/FatLiteApi.c
- BootloaderCommonPkg/Library/FatLib/FatLiteFmt.h
- BootloaderCommonPkg/Library/FatLib/FatLitePeim.h
This patch enhanced the FAT library to support long file name. The
old driver only supports 8.3 short name. Combined with FAT full path
support, the FAT library now can load any file from the partition.
> Add FAT long file name support

- BuildLoader.py
Stage2 and Payload are NOT verified by Intel BootGuard component.
Instead, Slimbootloader verfifies Stage2 and Payload using SBL hash store.
Signed-off-by: Agrawal <sachin.agrawal@intel.com>
> Remove Stage2 and Payload support for Intel BootGuard

- PayloadPkg/OsLoader/BootConfig.c
- PayloadPkg/OsLoader/LoadImage.c
Since grub.cfg is already supported in SBL. It makes sense to support
the similar syntax in config.cfg. This patch enabled config.cfg to
follow grub.cfg format to provide multiple boot options. The old
config.cfg format will still be supported. This patch also added
support for single/double quote around boot menu entry name.
> Allow more flexible config.cfg format

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
Fixes #95 by adding a simple check for OpenSSL and NASM before building.
The Build`*`.py scripts could really use some refactoring in general, but especially around parts that invoke external tools Such refactoring should be handled by a follow-up PR, as the focus of this PR is to just inform the user that OpenSSL/NASM cannot be found.
> Add basic pre-build check for OpenSSL/NASM

- BootloaderCommonPkg/Include/Library/MultibootLib.h
- BootloaderCommonPkg/Library/MultibootLib/Multiboot.c
Multiboot defined framebuffer structure.  However, it was not
implemented in SBL.  This patch added this support by filling in
the framebuffer information into the multiboot table.
> Add framebuffer info into Multiboot table

- BootloaderCommonPkg/Library/TpmLib/TpmLib.c
When Boot guard is enabled, Locality event would be
logged from Boot guard library.
> Log startup locality only when Boot Guard is not enabled

- BootloaderCommonPkg/Include/Library/MmcAccessLib.h
- BootloaderCommonPkg/Include/Library/MultibootLib.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
- BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLibGeneric.c
- BootloaderCommonPkg/Library/MmcTuningLib/MmcTuningLib.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
- PayloadPkg/Library/DebugPrintErrorLevelLib/DebugPrintErrorLevelLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/PayloadSupportLib/PayloadSupportLib.c
- PayloadPkg/Library/TrustyBootLib/TrustyBootLib.c
- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/KeyManagement.c
- PayloadPkg/OsLoader/LoadImage.c
- Platform/ApollolakeBoardPkg/Library/ShellExtensionLib/CmdFwUpdate.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/SeedSupport.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch enabled DISABLE_NEW_DEPRECATED_INTERFACES build option by
default so that the deprecated APIs cannot be used in SBL source tree.
It is to enhance the coding for security.
> Disable deprecated EDKII API interfaces

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BuildLoader.py
- MdePkg/Include/Guid/SystemResourceTable.h
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
- PayloadPkg/PayloadPkg.dec
This patch added support for FWST ACPI table. This table
contains generic address structure which has pointer to the
EFI System Resource Table.
ESRT table for now supports only system firmware. This table
will provide the operating system and tools knowledge of what
is the last attempt status and version of the system firmare
update.
> Added support for FWST OEM ACPI table

- BootloaderCorePkg/Tools/ConfigEditor.py
This patch added support to load CFGDATA directly from command line
interface. Minor clean-up work is also done to remove unused and
duplicated functions.
> Add command line loading CFGDATA support in ConfigEditor

- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
This script creates a new Apollo Lake Slim Bootloader IFWI image using
FIT tool and other ingredients. The FIT tool and some stitching
ingredients are not public available. Please contact your Intel
representative to get them.
This script can support both Linux and Windows environment.
> [APL] Add full IFWI stitching python script

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- Platform/QemuBoardPkg/CfgData/CfgDataExt_Brd1.dlt
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current SBL depends on GEN_CFG_DATA.PayloadId to determine which payload
to boot if multiple payloads exist. With this patch, when PayloadId is
set to "AUTO", QEMU will use the QEMU command line parameter
'-boot order' to determine which payload to boot.
For example, adding '-boot order=dba' in QEMU commadn line will boot to
UEFI payload. This provides a simple way to test different payloads using
the same SBL image.
> [QEMU] Allow select UEFI payload from QEMU command line

- BootloaderCorePkg/Tools/GenReport.py
- Platform/QemuBoardPkg/BoardConfig.py
Current QEMU build will produce many different SPI layouts due to
different build feature flags, such as source level debug support.
Since QEMU is a virtual platform, it is better to relax the size
so as to have consistent SPI layout. It will make it easier for
debug. This patch produces fixed QEMU image size (2MB).
> [QEMU] Adjust SPI image layout to have fixed size

- MdePkg/Include/IndustryStandard/SmBus.h
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Silicon/ApollolakePkg/Include/Library/SmbusLib.h
- Silicon/ApollolakePkg/Include/ScRegs/RegsSmbus.h
- Silicon/ApollolakePkg/Include/SocRegs.h
- Silicon/ApollolakePkg/Library/SmbusLib/SmbusLib.c
- Silicon/ApollolakePkg/Library/SmbusLib/SmbusLib.inf
For APL, the board might need SMBUS communication to talk to some
devices, such as PMIC. This patch ported the SMBUS library from
open sourced EDK2 Minnowboard3. Basic test was done on LeafHill
CRB to read/write PMIC registers through SMBUS.
> [APL] Add SMBUS access library

- BootloaderCorePkg/Stage2/Stage2Support.c
The message was displayed before the value was copied.
So adjust the sequence to correct it.
> Fix debug message display issue

- BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.c
TE image has stripped header to reduce the image size. When calculating
the preferred base for TE image, the gap should be added back in order
to match the actual TE image base. This patch fixed #133.
> Fix incorrect image base for TE image

- BootloaderCorePkg/Tools/BuildUtility.py
When specify a payload file in the build command line, the current
searching folder is: PayloadPkg/PayloadBins, Platform/$(PlatformBoardPkg)
/Binaries. This patch added another searching folder in the Build FV
if the payload file cannot be found in the listed folders above. This
is useful when the payload image itself is generated from the build
process.
> Allow searching payload file in build FV folder

- BootloaderCorePkg/Tools/PatchFv.py
The usage information cannot be printed properly in PatchFv.py.
This patch fixed #136.
> Fix help information for PatchFv.py

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/BootloaderCorePkg.fdf
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.inf
- BuildLoader.py
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/Include/Library/PayloadEntryLib.h
- PayloadPkg/Include/Library/PayloadLib.h
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/TrustyBootLib/TrustyBoot.h
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
Some OSes may require a pre-OS checker executable
to run before actually jumping to the OS. Add
support for this pre-OS checker loading & execution
as part of the OS Loader payload when it is compiled
as an FV and when ENABLE_PRE_OS_CHECKER option is
enabled in BoardConfig.py (per the following command):
SblBuild.py build <plat> -p Misc.Fv:LLDR:Lz4
The pre-OS checker entry point takes in a single
parameter which provides a handle to the loaded
OS for the pre-OS checker to launch after it executes
(e.g. pre-OS checker does not return to Slim Bootloader).
> Add pre-OS checker support

- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
This patch updated the logic to check if Boot Guard is enabled in
the base IFWI image.
> [APL] Enhance Boot Guard check logic for IFWI image

- BuildLoader.py
The GCC build is failing due to recent check-in for OS Loader FV
building. GCC5 is throwing an error that the required fv size
of 0x37718 is exceeding the set fv size of 0x37000. Bump up the FV
size (by 36KB) to address this issue.
> Fix the GCC OS Loader FV build error

- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
For SATA boot option, the hardware partition is mapped into AHCI
port. Current implementation requires a specific AHCI port in order
to boot from that hard drive. This patch added support to boot
from the first detected AHCI port when the hardware partition is
set to 0xFF.
> Allow SATA boot option to boot from any AHCI port

- PayloadPkg/OsLoader/LoadImage.c
This patch added some additional error message print during the
boot media initializtion and file loading. It makes it easier to
identify issues in case of failure.
> Enhance error message print for OsLoader

- BootloaderCorePkg/Tools/BuildUtility.py
This patch added the additional existence check for payload binary.
If the file does not exist, it will error out.  Also if the binary
is already under build FV folder, skip the unnecessary copy.
> Add payload binary file check in BuildUtility.py

- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
An issue was reported on APL that MRC will start to do full training
after 119 boot cycles. APL MRC training data contains two parts. One
part will not change, and the other part will change for every boot.
To avoid frequently erasing flash, a rolling method was applied to
save this data into different slot for each boot. When all slots are
full, the whole block will be reclaimed. However, some boundary
condition was not handled properly which caused the NVS data cannot
be located when the slot is close to the end of the block.
This patch addressed this issue by:
- Force the max slot number to be 8 aligned so that the map is always
at byte boundary (1 bit for 1 slot in the slot map).
- When all slots are marked with 0 (all slots are full), set default
slot to be the last slot so that the …
> Fix MRC NVS data reading issue

- PayloadPkg/Include/Library/PayloadLib.h
- PayloadPkg/Library/TrustyBootLib/TrustyBoot.h
- PayloadPkg/OsLoader/OsLoader.c
For the pre-OS payload/checker pass in a parameter
that contains additional information for heap space,
heap address, and additional CPU registers that may
need to be set before the pre-OS payload/checker
passes control to the OS.
> Update the pre-OS payload/checker parameter

- Platform/ApollolakeBoardPkg/CfgData/CfgData_BootOption.dsc
To ensure ConfigEditor can handle the configuration data type properly,
the default value needs to be valid. For string type configuration item,
the value should start with single quote. The APL default value for OS
image name is set to number 0 instead of '' to indicate empty string.
This patch corrected this and fixed #151.
> [APL] Fix ConfigEditor error on changing Boot Option

- PayloadPkg/OsLoader/BootConfig.c
Current GRUB config parser can only handle UNIX EOL style. For DOS
EOL style config file, an extra '\r' will be left at the line end
which might cause failure for initrd file loading due to incorrect
file name string. This patch enhanced the GRUB config file parser
to handle both UNIX and DOS EOL style.
> Enhance GRUB config file parser

- BootloaderCommonPkg/Include/Library/GraphicsLib.h
- BootloaderCommonPkg/Library/GraphicsLib/BmpFormat.c
- BootloaderCorePkg/Stage2/Stage2Support.c
Current implementation of splashing a BMP image to the
display requires the allocation of a temporary buffer
to store the BMP image into a GOP Blt friendly format
that can then be used to splash the image to the display.
Instead of using a buffer for the whole image we can
allocate a smaller buffer to splash one line at a time
since splashing is already performed one line at a time.
Also fix a small print message regarding frame buffer
format.
> Enhance BMP image splashing

- PayloadPkg/Include/Library/PayloadLib.h
- PayloadPkg/OsLoader/OsLoader.c
It might be useful for the pre-OS payload/checker
to have a handle to the HOB list data for additional
support or data checking that the HOB list contains.
> Add HobListPtr to pre-OS payload param struct

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf
- MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.uni
- MdePkg/Library/BaseMemoryLibSse2/CompareMemWrapper.c
- MdePkg/Library/BaseMemoryLibSse2/CopyMemWrapper.c
- MdePkg/Library/BaseMemoryLibSse2/Ia32/CompareMem.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/CopyMem.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/IsZeroBuffer.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/ScanMem16.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/ScanMem32.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/ScanMem64.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/ScanMem8.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem16.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem32.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem64.nasm
- MdePkg/Library/BaseMemoryLibSse2/Ia32/ZeroMem.nasm
- MdePkg/Library/BaseMemoryLibSse2/IsZeroBufferWrapper.c
- MdePkg/Library/BaseMemoryLibSse2/MemLibGuid.c
- MdePkg/Library/BaseMemoryLibSse2/MemLibInternals.h
- MdePkg/Library/BaseMemoryLibSse2/ScanMem16Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/ScanMem32Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/ScanMem64Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/ScanMem8Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/SetMem16Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/SetMem32Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/SetMem64Wrapper.c
- MdePkg/Library/BaseMemoryLibSse2/SetMemWrapper.c
- MdePkg/Library/BaseMemoryLibSse2/ZeroMemWrapper.c
Copying the MdePkg BaseMemoryLibSse2 library into
SBL for faster CopyMem and other routines to improve
boot performance during splash screen displaying
and OS Loader payload execution.
The BaseMemoryLibSse2 folder was copied from EDK2
GitHub based on the following commit ID:
9344f0921518309295da89c221d10cbead8531aa
> Add BaseMemoryLibSse2 library

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/MpInitLib.h
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Some platform might need do some platform specific init
on all the threads. So add a MP hook using a PCD.
Np impact for the platform that doesn't need this hook.
This patch also enable InSMM bit for APL.
> Add MP hook point for platform CPU init

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Silicon/ApollolakePkg/Library/HeciLib/HeciLib.c
- Silicon/ApollolakePkg/Library/HeciLib/MkhiMsgs.h
Firmware update with latest code broke on APL platform.
This patch fixed #162 by:
- Corrected the HECI command response flag check
- Always read FWU state machine using SPI command instead memory map
> [APL] Fix firmware update failure

- BootloaderCommonPkg/Include/Library/PartitionLib.h
- BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c
- PayloadPkg/OsLoader/LoadImage.c
The FindPartitions() allocates memory for PART_BLOCK_DEVICE instance.
This allocated memory needs to be de-allocated if no more necessary
to avoid memory leak.
TBD: Current partition info needs to be cleared before going to next
boot option.
> [PartitionLib] Added ClosePartitions to clean-up partition data

- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
This patch will update GenCapsuleFirmware.py tool to package
multiple firmware update images into single capsule.
Example:
python GenCapsuleFirmware.py -p BIOS pld1.bin -p <GUID> pld2.bin
-p CSME Pld3.bin -p CSMD Pld4.bin -o img.bin -k  TestSigningPrivateKey.pem
The following are the changes made
1) Capsule header format is changed to align with
EFI_FIRMWARE_MANAGEMENT_CAPSULE_HEADER
2) Each firmware image in the capsule will have
EFI_FIRMWARE_MANAGEMENT_CAPSULE_IMAGE_HEADER
3) BIOS, CSME, CSME Update Driver (CSMD) and CFGData payloads
can be passed to the tool using their names as suggested in
example.
4) Unknown payloads can also be passed to the tool with associated
guid as input.
> Package multiple firmware Images into single capsule

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/ApollolakePkg/Include/RegAccess.h
- Silicon/ApollolakePkg/Library/GpioLib/GpioLib.c
- Silicon/ApollolakePkg/Library/GpioLib/GpioLib.inf
- Silicon/ApollolakePkg/Library/PlatformHookLib/PlatformHookLib.c
- Silicon/ApollolakePkg/Library/PlatformHookLib/PlatformHookSupport.c
- Silicon/ApollolakePkg/Library/ScSbiAccessLib/ScSbiAccessLib.c
- Silicon/ApollolakePkg/Library/ScSbiAccessLib/ScSbiAccessLib.inf
- Silicon/ApollolakePkg/Library/SerialPortLib/SerialPortLib.c
- Silicon/ApollolakePkg/Library/VtdLib/VtdLib.c
Common MM_PCI_ADDRESS() provided PCI device BDF to PCIE MMIO base address.
So remove MmPciAddress() and MmPciBase () defined in platform and update
code to use MM_PCI_ADDRESS().
Add TO_PCI_LIB_ADDRESS() in common library.
> Clean up PCI MM address

- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage2/Stage2.c
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Silicon/ApollolakePkg/Include/PlatformData.h
Add ACPI_ENABLED() to align with MEASURED_BOOT_ENABLED().
Update MEASURED_BOOT_ENABLED() by checking PcdMeasuredBootEnabled
firstly.
Update PlatformFeaturesInit () in stage1b to fix potential
inconsistent.
Update other code for changes above.
> Add ACPI_ENABLED()

- BootloaderCommonPkg/Include/Library/SpiFlashLib.h
- BootloaderCommonPkg/Library/SpiFlashLib/RegsSpi.h
- BootloaderCommonPkg/Library/SpiFlashLib/ScSpiCommon.h
- BootloaderCommonPkg/Library/SpiFlashLib/SpiFlashLib.c
- BootloaderCommonPkg/Library/SpiFlashLib/SpiFlashLib.inf
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Cleaned up SpiFlashLib in APL platform, and move it into
BootloaderCommonPkg, so that other platform could reuse
this SpiFlashLib
> Move SpiFlashLib into bootloader common package

- BootloaderCommonPkg/Library/FatLib/FatLib.c
- PayloadPkg/OsLoader/BootConfig.c
In current FAT lib, the file path matching code will just compare
the 1st N chars and ignored the remaining. The end of the string
should be checked to ensure exact matching. As part of this fix,
the GRUB config parsing library needs to be updated since the file
name length field is one less than expected.
It fixed #183.
> Fix FAT file path matching issue

- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf
- Silicon/CoffeelakePkg/Include/Register/CpuRegs.h
On WHL, if using Boot Guard profile 0, booting from BP1 will be
significantly slower than BP0. It is because some code region in BP1
is not covered by MTRR cache settings. This patch adjusted MTRR
settings during PostTempRamInit notification to cover full flash
code region if Boot Guard profile 0 is used.
It fixed #188.
> Fix boot performance issue for BP1

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Change DEBUG_ERROR to DEBUG_INFO for reporting UpdateFspmSgxConfig() and
UpdateFspsSgxConfig() return statuses since failing to update FSP
variables for Intel(R) SGX is not necessarily due to an error.
Signed-off-by: Iyer, Naveen <naveen.iyer@intel.com>
> Change DEBUG_ERROR to DEBUG_INFO for update fail

- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c
- BootloaderCorePkg/Stage2/Stage2.c
Current SBL does not call board ReadyToBoot & EndOfFirmware phases
in Stage on normal boot flow. Current open source UEFI payload does not
do it either. It caused some security concerns. The patch enforced
these notification calls on normal boot flow in SBL for all payloads
except for those that can handle board and FSP notification on its own.
It fixed #191.
> Add call to board notifications by default

- BootloaderCorePkg/Stage2/Stage2.c
Previous commit 4061d47f3041e95a23c9307d38ea07c4dd62b9cd missed one
condition while handling the board notification calls. For built-in
payload such as OsLoader and FwUpdate, it will issue notifications
from payload through SBL platform services. So for these payloads,
board notification should not be called in SBL Stage2. This patch
fixed this.
> Exclude board notifications for built-in payloads

- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext2FsDiNode.h
The current EXT2/3 library does not support EXT4 partition
reading namely due to a limitation with handling extents
instead of block maps within an I_node's I_block data.
There is a todo currently to support 48-bit logical block
addressing, the code currently does not support reading
larger than 32-bit addresses; throw an ASSERT if upper
16-bits are non-zero.
> Add support for EXT4 partition reading

- BootloaderCommonPkg/Include/Library/ElfLib.h
- BootloaderCommonPkg/Library/ElfLib/Elf32.h
- BootloaderCommonPkg/Library/ElfLib/ElfCommon.h
- BootloaderCommonPkg/Library/ElfLib/ElfLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- PayloadPkg/OsLoader/OsLoader.c
The previous implementation has a little confusion in license header.
To avoid further annoying, simply re-implement ElfLib.
- 32bits, little-endian, executable elf only supported
- elf32.h/elf_common.h from BaseTools
- LoadElfImage() interface changed
> Re-implement ElfLib for ELF32 format image

- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
When determining which extent node to fetch
the filesystem block address from for a file's
data we should count from block 0 of the file
and when we enter into a non-zero extent node
we need to subtract the starting block number
from the file block number we are looking for
so that we don't skip over any blocks.
> Fix EXT4 extent calculations

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
When SBL calls board notification ReadyToBoot and EndOfFirmware in
Stage2, OsLoader will assert on APL platform. It was caused by NULL
pointer access in ClearFspHob(). This patch added NULL pointer check
before zeroing out memory. It fixed #197.
> [APL] Fix boot failure in OsLoader

- Platform/CoffeelakeBoardPkg/CfgData/CfgDataInt_Whl.dlt
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch allows payload ID selection toggling using GPIO. When
the payload ID is set to "AUTO" in CFGDATA, the actual payload ID
will be updated according to current GPIO level. If the GPIO is low,
the payload ID will be set to 0 to boot OsLoader/FwUpdate payload.
If the GPIO is high, the payload ID will be set to 'UEFI' to boot
UEFI payload.
> :[WHL] Enable payload selection using GPIO

- BootloaderCorePkg/Tools/ConfigEditor.py
In ConfigEditor, when open DSC files, many files will show up. It
is expected to only open the CfgDataDef.dsc. This patch changed
the file match pattern to only list *Def.dsc file.  In this way,
user will not make mistake to open some include DSC file.
> Filter out include DSC files in ConfigEditor open dialog

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Memory.dsc
Whiskeylake platform contains memory SPD data in memory configurations.
Since it has 4 SPD tables, loading is very slow in ConfigEditor. The SPD
table can be broken down into individual page for display to enhance the
loading performance in ConfigEditor.
> [WHL] Split memory SPD CFGDATA into sub-pages for display

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Memory.dsc
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
There is a invalid value(8MB) in CfgData_Memory.dsc which causes
an WARNING when opening memory setting in ConfigEditor.
WARNING: Value "8388608" is an invalid option for "TsegSize" !
Update TsegSize from 0x00800000 to 0x01000000 !
In FspmUpd.h description, Tseg Size is "0x400000 for Release build
and 0x1000000 for Debug build".
Tseg size 4MB(0x400000) is enough with SBL regardless of build type.
Therefore, let's remove config option and use fixed size(4MB) simply.
It fixed #205.
> [WHL][CFL] Use fixed Tseg size (4MB)

- BootloaderCorePkg/BootloaderCorePkg.fdf
- BuildLoader.py
This patch allows platform to use BoardConfig.py to override the
LOGO_FILE path so that customized logo file can be used instead of
the common one.
> Allow to use platform specific logo file

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current default GPIO payload ID selection is UEFI on APL platform
since the GPIO pin is high without any jumper set. This patch
changed the default paylod ID to OsLoader when the GPIO is set to
high.
It fixed #208.
> Change default behavior for GPIO payload ID selection

- Silicon/ApollolakePkg/Library/SocInfoLib/SocInfoLib.c
Updated the mBxtSocRevInfo table to support APL F1 stepping by adding it's 'RevId' and 'PlatformId'.
Signed-off-by: Vegnish Rao <vegnish.rao.paramesura.rao@intel.com>
> [APL] Update mBxtSocRevInfo table to support APL F1 stepping

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_GpuConfig.dsc
ConfigEditor returns a warning in GPU Config page.
WARNING: Value '2' is an invalid option for 'InternalGfx' !
Update InternalGfx from 0x02 to 0x01 !
The InternalGfx does not provide proper options and its default value
must be '1' or '0' instead of '2'.
Additionally, renamed 'GPU Config' page name to 'Graphic and Display'
and also removed unnecessary sub-page 'GPU'.
> [WHL][CFL] Fix invalid config in default GFX CFGDATA

- BootloaderCommonPkg/Library/SmbiosInitLib/SmbiosInitLib.c
If the platform provides an empty or a NULL string,
Smbios type might end abruptly and the Types are
reported incorrectly.
> Handle empty and NULL strings in Smbios types

- Platform/ApollolakeBoardPkg/CfgData/CfgData_Ext_Gpmrb.dlt
The PCIe Root Port utilization for GP MRB is:
RP0 - /
RP1 - /
RP2 - CFB I210
RP3 - CFB M2 Cellular
RP4 - I210
RP5 - BT/WIFI
CFB = Customer Feature Board
Issue:
PCIe device BT/WIFI was not enumerated.
This corrects the complete PCIE_RP_CFG_DATA configuration
for the GP MRB board.
Signed-off-by: Markus Schuetterle <markus.schuetterle@intel.com>
> [GPMRB] Correct PCIe RP configuration for GP MRB

- Platform/ApollolakeBoardPkg/CfgData/Template_CfgData.dsc
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Remove the requirement for the end user to know
community, group etc. And just expose GPIO pins
to select to program PlatformID.
> [APL] Enhancce PlatformID via GPIO pin code

- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
Issue:
The Bios.xml generated from StitchIfwi.py is referring to Stitch_PROV.bin.
But the SBL Output Stitch_Components.zip contain instead Stitch_FB.bin.
Fix for issue #224:
Consistently use input file names for IFWI stitching, by chosen for 'FB'
instead of 'PROV'.
Signed-off-by: Markus Schuetterle <markus.schuetterle@intel.com>
> [APL] Fix inconsistent file name on IFWI stitch

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Revert 'Determine Firmware Update boot mode at post tempram exit #210'
- Enable SMI on S3 resume path ONLY with UEFI payload
- Move EnableSmi from PrePciEnumeration to EndOfFirmware
> [WHL][CFL] Fix S3 resume with OsLoader payload

- PayloadPkg/OsLoader/Linux.c
- PayloadPkg/OsLoader/OsLoader.h
When loading a Linux kernel we should not
limit the size of the kernel being loaded
to 15MB but we should verify that the kernel
will not overwrite the payload which can
some times be located in low memory where
the kernel is being loaded.
> Modify kernel size loading check

- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
Currently there is some limitation with mounting an
EXT4 partition to retrieve a file for booting when
the partition was not properly umounted during the
previous usage (ex. powering off an OS without
using 'poweroff' command, unplugging power, etc.).
There is recovery support in the Ext23Lib but as
a temporary solution we can ignore the recovery
bit to avoid boot issues when the recovery bit is
flipped due to unexpected power loss.
> Add EXT2F_INCOMPAT_RECOVER to EXT2F_INCOMPAT_SUPP

- PayloadPkg/OsLoader/BootParameters.c
There may be additional boot params
specified by a platform that needs to
be added without updating the boot
option data (ex. IAS cmdline.txt).
These optional additional boot params
can be included via CFG data, Shell
command, etc., and applied by setting
the mAppendParams pointer.
> Append optional boot params

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Include/Library/MpInitLib.h
- BootloaderCorePkg/Include/Library/S3SaveRestoreLib.h
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLibInternal.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c
- BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestoreLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Restore the register information saved during the
normal boot, on S3 resume path for UEFI payload only.
> [CFL] Restore regsiters on S3 resume

- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
SmmRebase should not be done while using OsLoader
payload. Added PayloadId check to make sure we do
it only for UEFI payload for now.
> Fix S3 resume issue with OsLoader payload

- BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
When writing flash in SMM mode, some platform need disable SMM write
protection. when this flag is set, it means this platform need disable
SMM write protection.
> Add a platform flag for SPI flash SMM write disable

- BootloaderCommonPkg/Library/ElfLib/ElfLib.c
SBL only support ELF type: EXEC (Executable file)
This changes also allow loading ELF type: DYN (Shared object file)
This is required to boot recent ACRN Hypervisor.
Signed-off-by: Markus Schuetterle <markus.schuetterle@intel.com>
> Add support for ELF type: Shared object file

- BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
TPM type as dTPM and fTPM is utilized in UEFI payload to
update TPM instance
> Update TPM Type to Loader Platform info HOB

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
This patch added GenContainer.py script to reate, extrace, replace,
sign and display a container image. If platform provides
GetContainerList() in BoardConfig.py, the build process will consume
it to create container images.
> Add GenContainer tool script

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Guid/LoaderPlatformDataGuid.h
- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.inf
- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.c
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.h
- BootloaderCorePkg/Stage1B/Stage1B.inf
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/Include/Library/PayloadLib.h
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/PayloadLib/PayloadLib.c
This patch added a ContainerLib to support load and location a
component from a specified container. It copies the component
from flash to memory, authenticate it, and then decompress it if
required. It can also be used to support load component from flash
map in SBL stage2 or payload, such as payload or e-payload.
> Add ContainerLib to support sub-region

- BootloaderCommonPkg/Include/Library/SecureBootLib.h
Recent update to DoHashVerify routine is no longer
working for HASH_INDEX_PAYLOAD_DYNAMIC (ex. UEFI
Payload). Need to add COMP_TYPE_PAYLOAD_DYNAMIC
and increase COMP_TYPE_INVALID to resolve the
issue.
> Add COMP_TYPE_PAYLOAD_DYNAMIC for DoHashVerify

- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCorePkg/Include/HashStore.h
- BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.c
- BootloaderCorePkg/Stage2/Stage2.c
Since HASH_INDEX_* is a 1:1 mapping with
COMP_TYPE_* we can remove HASH_INDEX_* and
replace with COMP_TYPE_*.
Also fix some misspellings.
> Replace HASH_INDEX_* with COMP_TYPE_*

- BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
- PayloadPkg/Library/AbSupportLib/AbSupportLib.c
- PayloadPkg/Library/SblParameterLib/SblParameterLib.c
- PayloadPkg/OsLoader/BootParameters.c
- Platform/CommonBoardPkg/CfgData/Template_BootOption.dsc
Mender is a A/B partitioning scheme
for Linux OSes. Adding initial support
for specifying the root partition label
that should be tried. Later on the root
partition label should be acquired based
on the value of the env files stored in
the EFI/FAT32 partition of the boot media.
> Add initial support for Mender boot

- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.inf
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Tools/BuildUtility.py
- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch enabled container use case for EPAYLOAD loading.
It also switched to use LoadComponent() API for Stage2 and
payload loading. An example in QEMU was added to demonstrate
on how to add a container in build and load it in stage2 code.
To define a container layout, it is required to provide
GetContainerList() in BoardConfig.py. Then in stage or payload
code, LoadComponent() can be used to load a component from the
container.
> Switch to use container for EPAYLOAD

- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
Currently, Ext23Lib accesses device index 0 only.
It must access proper hardware partition when reading blocks.
- Reproducible with QEMU which has SATA port 5
> [Ext23Lib] Fix EXT filesystem booting failure

- BootloaderCommonPkg/Include/Library/ShellLib.h
- BootloaderCommonPkg/Library/ShellLib/CmdHelp.c
- BootloaderCommonPkg/Library/ShellLib/Shell.c
- BootloaderCommonPkg/Library/ShellLib/Shell.h
- BootloaderCommonPkg/Library/ShellLib/ShellCmds.c
- BootloaderCommonPkg/Library/ShellLib/ShellCmds.h
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
Currently, all shell commands are statically defined in header file.
Add shell command registration API to allow include/exclude shell
commands dynamically.
Later, some debug shell commands will be added according to build
mode or debug mask.
- TBD: Sorting shell commands by name
> [ShellLib] Add ShellCommandRegister API

- Platform/CoffeelakeBoardPkg/AcpiTables/Ssdt/TpmSsdt.asl
EOS bit set issues are fixed in SBL. Removed the
work around done for setting EOS before SMI
is triggered.
Signed-off-by: lsubash <subashx.lakkimsetti@intel.com>
> Remove SmiEn EOS bit set in TpmSsdt asl

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/CoffeelakePkg/Include/Register/PchRegsPmc.h
S4 resume sets PWRBTN_EN. And since SCI_EN is set to 0,
this situation will generate spurious SMI# once GblSmi
is enabled.
Also moving RestoreS3regs before ProcessAllLocks, as SMI_LOCK
setting will prevent enabling GblSmi on S3 resume path.
> [CFL] Fix S3/S4 resume

- BootloaderCommonPkg/Library/ShellLib/Shell.c
Since OsLoader will restart from beginning and all memory will be
reclaimed, it is required for Shell library to re-initialize the
global varaibles, for example, command list. Otherwise, the old
memory pointer will be used and cause issues. This patch added the
link list re-initialization in Shell lib.  It fixed #253.
> Reinitialize Shell command list

- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
- Platform/CoffeelakeBoardPkg/Script/StitchLoader.py
Because of an error in Stitchloader.py, input file
slimbootloader binary data is not patched to the input
Ifwi. This error is now fixed which will produce correct
Ifwi image.
> Fix - IFWI built using Stitchloader.py is failing

- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
Current SBL code depends on PixelInformation to fill kernel
framebuffer parameters. However, this info is only valid if
PixelFormat is PixelBitMask type. Since FSP will only produce
8bit per pixel format, it is better to use PixelFormat to
determine the pixel bit size and position information. This
patch added this logic. It also fixed #260 .
> Fix Linux framebuffer boot parameters

- BootloaderCommonPkg/Include/Library/LinuxLib.h
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
- PayloadPkg/OsLoader/OsLoader.c
This patch splitted LoadBzImage() into two functions.  One is just
for kernel loading.  The other one UpdateLinuxBootParams() is for
Linux boot parameter updates. It is required to do so because when
kernel loading in Stage2 is enabled the loading occurs before all
HOBs are finalized. The Linux boot parameters depend on HOBs to fill
correct information, such as frame buffer. With this patch, the boot
parameters can be updated at the very end.
> Break Load Linux BzImage into more functions

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch enabled Linux as payload support on QEMU platform. To build
Linux as payload, please follow instructions mentioned in commit:
4a5af4f8b0824f298b9f91bdd874c8cb60f46fb6
In addtion, to boot Linux payload on QEMU, please append following
into QEMU command line to set Payload ID to 'LINX' dynamically.
-boot order=abc
> Enable Linux as payload support

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/GenCfgData.py
- Platform/QemuBoardPkg/CfgData/CfgDataExt_Brd1.dlt
- Platform/QemuBoardPkg/CfgData/CfgDataExt_Inc.dlt
To make it easier to share the most common configuration items in a
DLT file, it is better to support '!include' in DLT file. This patch
added this feature.  It also added examples in QEMU to test this.
> [Tools] Add !include support for DLT files

- Platform/CoffeelakeBoardPkg/CfgData/Template_CfgData.dsc
Update the indices for Dw0, DW1 in Gpio Template after
the PinOffset Dword has been removed in the previous commits
> [CFL] Use correct indices for Gpio DW0,DW1 in Template

- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
- Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.inf
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
Getting platform name from config data and set platform name is
common almost for all the platforms. So move it to common library.
Loading external configuration data from SPI is also common, so
add it into common library. Platform could still use its own method
to load config data if the common one doesn't work.
> Add common functions on PlatformName and external config data

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
When downloading FSP and Microcode into local tree, it is required
to support board/silicon packages at different locations since the
board/silicon packages might be located outside of the SBL tree pointed
by PLT_SOURCE environment variable. Current code always assumes the
board/silicon is inside SBL tree, and it needs to be fixed. This
patch fixed #269 .
> Fix FSP and Microcode download path issue

- BootloaderCorePkg/BootloaderCorePkg.fdf
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.inf
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/OsLoader.inf
Since we may want to perform FW update on
pre-OS checker/payload binaries separately
from the OS Loader payload we will search
for pre-OS checker/payload in the container
entries instead of adding it into the OS
Loader FD.
> Switch to use container for pre-OS checker/payload

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
There is a small bug in the ContainerLib
where the check for whether the data is
stored in the flash needs to be adjusted.
> Fix ContainerLib flash bug

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- BuildLoader.py
- Silicon/ApollolakePkg/FspBin/FspBin.inf
- Silicon/CoffeelakePkg/FspBin/FspBin.inf
- Silicon/CoffeelakePkg/Microcode/Microcode.inf
Removing hard code in PrepareBuildComponentBin.py, so it could
support other platforms. And enhance its logic to support to
run in different places.
Moving repo and commit information to driver INF so this script
could reuse code to support different drivers.
> Enhance build support for binary downloading

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/UefiVariableLib.h
- BootloaderCommonPkg/Library/UefiVariableLib/FtwLastWrite.c
- BootloaderCommonPkg/Library/UefiVariableLib/FtwLastWrite.h
- BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.c
- BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
This patch provides a library to get read access
to the UEFI variables stored in NV region.
> Add UEFI Get Variable support

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- BuildLoader.py
With this change, customer could copy only board package folder
outside of SBL repo and build it without copying silicon folder.
It could help customer create their own repo and use SBL open
source repo as a submodule.
> Enhance build script to support build flexibility

- PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
This patch fixed a logic bug in firmware update library when
de-allocating memory in error handling flow. It fixed #275.
> Fix firmware capsule loading assertion issue

- Platform/CoffeelakeBoardPkg/Script/StitchLoader.py
This patch added detailed flash map print in BIOS region for WHL
stitching script StitchLoader.py. In this way the script will
have consistent print format as APL.
> [WHL] Add flash map print in StitchLoader script

- Platform/ApollolakeBoardPkg/BoardConfig.py
APL build hit into exception: File 'PAYLOAD.lz' size 0x224B5 is greater than padding size 0x22000 !
This patch to increase the payload size to fix the build issue. 
Test and booted on JuniperHill board to SBL Shell and Uefi Shell
Signed-off-by: Teo Boon Tiong <boon.tiong.teo@intel.com>
> [APL]Increase payload size to fix build error.

- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Build.py
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/ConfigEditor.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BootloaderCorePkg/Tools/GenCfgData.py
- BootloaderCorePkg/Tools/GenContainer.py
- BootloaderCorePkg/Tools/GenReport.py
- BootloaderCorePkg/Tools/IfwiUtility.py
- BootloaderCorePkg/Tools/PatchFv.py
- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- BuildLoader.py
- IntelFsp2Pkg/Tools/SplitFspBin.py
- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
- Platform/CoffeelakeBoardPkg/Script/StitchLoader.py
EDK II build has enabled python3 support. Since SBL has its own scripts,
it is required to port them accordingly to support python3. This patch
added python3 build support for SBL.
> [TOOLS] Add python3 build support

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataStitch.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- BuildLoader.py
- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Some misc enhancements for build scripts including:
- Adding all required exectuable check for build
- Removng hardcoded Python27 path
- Printing out used python version and path
- Using EDKII stable201905 tag to build QEMU FSP
> [TOOLS] Misc enhancements for build scripts

- .travis.yml
- Dockerfile
Current travis build only performs debug build with python 2.
This patch allows to test debug and release build, python2 and
python3 build.
> Enable more build options in travis

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
This patch run repo clean to remove previous generated files before
starting a new QEMU FSP build.
> [QEMU] Add repo clean command before building QEMU FSP

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Silicon.dsc
This patch will fix an invalid string in the
configuration data for CFL/WHL platforms.
> Fix invalid string in Configuration data

- BootloaderCorePkg/Tools/IfwiUtility.py
- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
This patch will remove FitHelp.py dependency from StitchIfwi
and reuses code from IfwiUtility to patch ACM binary.
This patch also fixed some case dependency required for python
in xml file patching. without this fix, fit does not work as
expected.
> Remove using FitHelp.py in StitchIfwi

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
If capsule header is NULL or no payloads
found in the capsule return EFI_NOT_FOUND.
> Resolve Klocwork issue in FWU code

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/PreMemGpioTables.h
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/GpioTables.h
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Currently in Stage1B it defined gpio table for pre-memory, but no one
program that gpio table. This patch adds it.
Move full GPIO table program from Stage1B to Stage2
Remove unused global variable mRsvdSmbusAddressTable in Stage1B.
TEST= Build success.
> [CFL] Add pre-memory GPIO program

- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Ia16/Init16.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Ia16/Real16ToFlat32.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Main.asm
- clear interrupts at EarlyInit16
- Restore BIST value to EAX register
Signed-off-by: Himanshu Sahdev aka CunningLearner <sahdev.himan@gmail.com>
> Optimize Stage1A early boot init

- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1A/Ia32/SecEntry.nasm
- BootloaderCorePkg/Stage1A/Stage1A.c
- add BistVal in STAGE1A_ASM_HOB structure
- use MM0 register to preserve the BIST value
- push BistVal while setup HOB in stack
- add check for CPU BIST failure and halt the system when failed
Signed-off-by: Himanshu Sahdev aka CunningLearner <sahdev.himan@gmail.com>
> BootloaderCore: Handle BIST failure in SecEntry

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
QEMU supports '-smp' option to emulate up-to maximum 255 CPUs, but failed
to do MpInit with '-smp' option. Currently, there are only fixed size(4)
Processor Local APIC entries in QEMU MADT and its ApicId does not match
with detected CPU info.
- Append ProcessorLocalApic entries into MADT in runtime with MpInfo
- Make PcdCpuMaxLogicalProcessorNumber configurable in each BoardConfig
- Set PcdCpuMaxLogicalProcessorNumber to 255 in QEMU BoardConfig.py
Test>
qemu-system-x86_64 -machine q35 -nographic -serial mon:stdio
-pflash Outputs/qemu/SlimBootloader.bin
-smp 8
Signed-off-by: Aiden Park aiden.park@intel.com
> [QEMU] Support -smp option

- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
Error: conversion from 'UINT32' to 'UINT8', possible loss of data
MADT ProcessorId and ApicId has the size of UINT8. Cast the size from UINT32 to UINT8.
Change-Id: I3f46b2015b0d21c2b3e2f9389ecb8d5364ed5a5e
> [AcpiInitLib] Fix build failure on Windows

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Gpio.dsc
- Platform/CoffeelakeBoardPkg/CfgData/Template_CfgData.dsc
Current Gpio config provides a way to select PadMode. But
Native Functions for a PCH are just numbered #1,2, etc. and
do not provide enough information for the end user while
configuring the PadMode.
This patch adds the required Native Function information help
strings in the drop down menu while configuring the PadMode.
> [CFL] Add Native Function help in Gpio config

- Platform/ApollolakeBoardPkg/CfgData/CfgData_BootOption.dsc
In order to make ACRN to boot, it is required to set boot from eMMC
RAW partition 1. However, current boot option is set to 0, which
caused the boot failure. This patch updated the SwPart to 1 and filled
the LBA with expected format. It fixed #317.
> [APL] Fix boot option settings for ACRN

- PayloadPkg/OsLoader/LoadImage.c
Current code will try to append a NULL char at the end of the
config file buffer to ensure the tring is terminated properly.
However, it did that without considering the buffer size. The
current config buffer could have been fully used and no more
space is available to append an extra NULL char. If this happens,
during the pool de-allocation, the assertion will be seen due to
buffer overflow. This patch increased the config buffer buffer
size by 1 to ensure it will have space to append string terminator.
It fixed #319.
> Fix config file buffer overflow issue

- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
This patch will change the code to always use absolute path
for stitching zip file, if relative path is provide, code will
convert it to absolute path.
> Use absolute path for Stitching zip

- BootloaderCommonPkg/Include/Dbg2.h
- Platform/CommonBoardPkg/AcpiTables/Dbg2/Dbg2.act
This patch provides the basic infrastructure to add a
Debug Port Table  2 (DBG2) to specify one or more ports
for debugging purposes. More info reg DBG2 @ :
https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn639131(v=vs.85)?redirectedfrom=MSDN
If the platform wants to report a debug port to Windows,
it should patch the DBG2 template provided with the
corresponding debug port information. And this updated
DBG2 must be referenced in RSDT.
> Add DBG2 ACPI table infrastructure

- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
QEMU compiling will fail when EXECUTE_IN_PLACE is set to 1 due to
size issue.  Even after fixing size issue, the execution will still
fail. It is because the variable services will try to put SPI into
command mode while code fetching will fail if it is executed from flash.
This patch added necessary code to skip variable tests in Stage1B and
Stage2 when XIP is enabled. It fixed #324.
> [QEMU] Fix QEMU build and boot issue

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
To assist source level debug, it is better to always load PE/TE images
at page aligned memory address so that the script can locate the image
much easier. This patch changed the AllocatePool to AllocatePages for
component loading inside a container.
> Allocate page aligned memory for component loading in container

- BootloaderCorePkg/BootloaderCorePkg.fdf
This patch sets the default PEIM rule to use TE image format.
In this way it does not need rule overriding anymore.
> Remove FDF rule overriding

- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
In addition to supporting IAS format for loading
kernel images, this patch adds support to load
the images present in a container. Set the token
ENABLE_PODS_BOOT to 1 to achieve this. Default is
0 i.e, IAS image is expected by default.
GenContainer.py tool can be used to create a container
with the boot files as follows:
python %SBL_ROOT%\BootloaderCorePkg\Tools\GenContainer.py create
-cl CMDL:<cmdline.txt> KRNL:<vmlinuz> INRD:<initrd>
-od <OutDir> -kd %SBL_ROOT%\BootloaderCorePkg\Tools\Keys
<cmdline.txt> = command line file
<vmlinuz>     = kernel image
<initrd>      = initrd image
<OutDir>      = dir where final PodsImage.bin is copied
> Add support to boot kernel from container

- BootloaderCorePkg/Tools/GenCfgData.py
This patch to fix the GenCfgData tool that wrongly parsing the dword data from an array.
For exmaple: 
CfgData1 |  *| 0x8 {0x5fff, 0x7fff, ...}, but generate result for CfgData1[0] = 0 and so on.
> Fix cfgdata dword parsing issue

- BootloaderCommonPkg/Library/Ext23Lib/ExtLib.c
- BootloaderCommonPkg/Library/FatLib/FatLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdMem.c
- BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Stage2/Stage2Support.c
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
Compile optimization sometimes needs to be disabled for debugging.
EDKII BaseTools provide NOOPT target, so leverage it.
The default GCC '-O0' and VS '/Od' option results in huge size image,
so the optimization level is adjusted with approximately level.
Add a new build option '-no' or '--noopt' for NOOPT target
- Release build option '-r' will ignore '--noopt' option
ex) python BuildLoader.py build qemu --noopt
> Enable NOOPT target for debugging purpose

- BootloaderCorePkg/Tools/ConfigEditor.py
- BootloaderCorePkg/Tools/GenCfgData.py
- Platform/QemuBoardPkg/CfgData/CfgDataDef.dsc
Current ConfigEditor only supports UINT8 format cell in table.
This patch added support for variable cell width including UINT8,
UINT16, UINT32 in table widget. Test configuration items were
also added in QEMU to test these format.
> Add support for variable cell width in ConfigEditor

- Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf
- Silicon/CoffeelakePkg/Include/Register/PchRegsLpc.h
- Silicon/CoffeelakePkg/Library/PlatformHookLib/PlatformHookLib.c
- Silicon/CoffeelakePkg/Library/SerialPortLib/SerialPortLib.c
On UP Xtreme board current code only supports PCH UART debug port.
But this board has two extra UART ports behind SIO chip F81801.
This patch added required initialization for the SIO chip to enable
UART on SIO. It can be enabled through platform data during stitching.
For exmaple,
"-p 0xAA000210" parameter in stitching will select PCH UART2.
"-p 0xAA00FF10" parameter will select SIO COM1 as debug device.
"-p 0xAA00FE10" parameter will select SIO COM2 as debug device.
> [CFL] Enable UPX SIO debug UART for COM1 and COM2

- BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c
If FPDT->Length is just the size of FIRMWARE_PERFORMANCE_TABLE,
BOOT_PERFORMANCE_TABLE and S3_PERFORMANCE_TABLE are overwritten
by the next Table in ACPI init. Therefore, make the size in the
header as sizeof(INTERNAL_FIRMWARE_PERFORMANCE_TABLE) so that
the next table starts after INTERNAL_FIRMWARE_PERFORMANCE_TABLE.
Otherwise, S3 Perf Table can't be located on S3 resume path.
> Update FPDT length

- BootloaderCorePkg/Tools/GenContainer.py
- PayloadPkg/OsLoader/OsLoader.c
Container type can be input from command line
from a list of [NORMAL, CLASSIC, MULTIBOOT] while
generating a container using GenContainer.py.
Setting default as NORMAL.
> Add image type param for GenContainer.py

- Platform/CoffeelakeBoardPkg/AcpiTables/Dsdt/Gpe.asl
On WHL after booting to Windows, SCI interrupt storm was seen due
to GPE event 111 (2-tier GPE event). This event needs to be handled
when RTD3 table is implemented. However, current code has _L6F
ASL code without RTD3 table. This causes the SCI event to be enabled
in Windows. Since there is no real handler to clear the SCI event,
SCI interrupt storm will occur. This patch commented out the _L6F ASL
method.
Tested this on WHL. The CPU utilization drop down from original 10%
to close to 0% for system interrupts.
> [WHL] Remove _L6F GPE handler in ASL code

- BootloaderCorePkg/Tools/IfwiUtility.py
This patch removes unused regions in SPI descriptor so that the
IFWI layout can be printed correctly even when some region is
disbled.
> Filter out unused region in SPI descriptor for IfwiUtility.py

- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- BootloaderCommonPkg/Library/IasImageLib/IasImageLib.inf
Current SBL code will assert if HAVE_VERIFIED_BOOT is 0. This patch
added check for PcdVerifiedBootEnabled to decide if IAS verification
is required.
> Skip IAS image verification if VERIFIED_BOOT is disabled

- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c
- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLibInternal.h
Current SBL USB keyboard driver cannot handle the key input nicely.
If typing is too fast, some chars will be missing. On the other side,
sometimes singe key press will generate multiple repeated chars.
This patch reimplemented the logic to detect key press/release using
similar flow as EDK2 UsbDxe driver. With this logic, USB keyboard
worked pretty well. It has been tested on APL platform.
> Enhance USB keyboard input experience

- BootloaderCommonPkg/Library/BootloaderDebugLib/BootloaderDebugLib.inf
- BootloaderCommonPkg/Library/BootloaderDebugLib/DebugLib.c
SBL allows debug message to be redirected to output console besides
the serial port. However, serial port itself could be part of the
output console device as well. In this case the debug message will
be printed twice. This patch added check to this condition and skip
the redundant print.
It fixed #349.
> Fix double debug message output on serial port

- BootloaderCommonPkg/Library/BootloaderDebugLib/DebugLib.c
The latest code has debug message output issue. It is caused by
the following CommitId: 56867c3bc674097b5982fed19d3ee1b022112e39.
This patch provided proper fixes for this issue. The root cause
is due to incorrect string length.
> Fix debug message output issue

- BootloaderCommonPkg/Include/Library/TimeStampLib.h
- BootloaderCommonPkg/Library/TimeStampLib/Ia32/TimeStampLib.c
- BootloaderCorePkg/Include/Library/SocInitLib.h
- BootloaderCorePkg/Stage1A/Stage1A.c
- Silicon/ApollolakePkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.c
- Silicon/CoffeelakePkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.c
- Silicon/QemuSocPkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.c
This patch implemented the common API to get CPU frequency and 
used the common API GetTimeStampFrequency() to get CPU
TSC frequency instead of the original GetCpuTscFreqency(). As part
of it, all SOC specific instances for GetCpuTscFreqency() were
removed.
> Implement common API to get CPU TSC frequency

- Platform/CoffeelakeBoardPkg/Library/ShellExtensionLib/ShellExtension.c
{CoffeelakeBoardPkg}ShellExtension.c: Drop undefined and unused shell command
mShellCommandCse is not defined in CoffeelakeBoardPkg so can't extern.  
It is not either used in current context.
> [CFL] Drop undefined and unused shell command

- BootloaderCorePkg/Tools/ConfigEditor.py
Current SBL display long help string in single line in ConfigEditor.
If the line is too long, only part of the line is visible on screen.
By change widget from Label to Message, it allows multiple lines
help string display.
> Display multiline help string in ConfigEditor

- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
- BootloaderCommonPkg/Library/Ext23Lib/LibsaFsStand.h
The EXT library has some unused code that
we can remove to help reduce the size and
to clean things up some more. Also add a
routine for dumping the group descriptor
table which can be helpful for debugging
issues.
> Clean up EXT library

- BootloaderCorePkg/Tools/GenCfgData.py
Current ConfigEditor does not run well with PY3. The generated DLT
file has invalid strings. It was caused by the incompability between
PY2 and PY3. This patch rewrote some code with compatibility for both
PY2 and PY3.
> Fix ConfigEditor with Python3 issue

- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
StitchIfwi.py supports '-q' parameter to enable SPI QUAD mode.
However, it does not work as expected. When the script tries to
modify the XML file, it used 'yes' and 'no' as option values.
But it is case sensitive, and should use 'Yes' and 'No' instead.
This patch fixed this issue.
Test was done on LeafHill board and it enabled SPI QUAD mode
in IFWI after the fix. It fixed #370.
> [APL] Fix IFWI stitiching issue for SPI QUAD mode

- Platform/CoffeelakeBoardPkg/BoardConfig.py
This is to fit the size of the latest Debug UEFI Payload.
Increase the size from 0x00180000 to 0x00190000.
> [WHL] Increase EPAYLOAD_SIZE

- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
This patch fixed the pointer check before de-allocating memory
previously allocated for AHCI controller.
> Fix AHCI memory de-allocation issue

- BaseTools/Scripts/PatchCheck.py
This patch will skip TAB check in all python files for now.
THis change will be reverted after cleanup all TABs.
> PatchCheck: Skip TAB check in .py files

- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c
- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLibInternal.h
When USB keybaord input console is enabled, current code will keep
sending interrupt transfers to poll the USB keyboard state. However,
according to USB spec, it needs to be polled at certain interval
returned by the device. If the polling rate is too high, sometime,
host will fail to schedule the SPLIT transfer. This patch adjusted
the polling rate to the required interval.
> Adjust USB KB polling rate

- BootloaderCommonPkg/Include/BlockDevice.h
- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
- BootloaderCommonPkg/Library/MemoryDeviceBlockIoLib/MemoryDeviceBlockIoLib.c
- BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.c
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.c
- BootloaderCommonPkg/Library/SpiBlockIoLib/SpiBlockIoLib.c
- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c
- BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.c
- PayloadPkg/OsLoader/OsLoader.c
This patch added basic deinit support in the media DevInit() interface.
It uses a special DevDeinit phase to inform the media driver to do
device de-initialization. This de-initialization flow will be called
before OsLoader restarting and OS booting.
> Add device deinit support

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current code set payload id depending on the gpio settings
and user selection from configuration data. When UEFI payload is
selected using GPIO or config data, payload id is being set to
UEFI irrespective of boot mode, which cause notification function
to get called, this locks the spi which inturn fails firmware update
Modified code to set payload id only in non-firmware update boot mode.
> [WHL] Fix firmware update failure

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Silicon/CoffeelakePkg/Include/Register/PchRegsPmc.h
power button 4 second press will cause power button override
bit to set in PM1 status register, this bit is not cleared on
reset and is causing SMI storm during booting to OS.
Power button override bit if set is cleared now in stage1b and
this fixed the SMI storm issue.
> [WHL] Fix power button overrride smi storm issue

- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch changes the default behavior of gpio pin for payload
selection, currently user configured GPIO pin being high boots
to uefi payload, modified code will boot to OS loader when GPIO pin
is high.
> [CFL] Change default payload sel based on GPIO

- BootloaderCorePkg/BootloaderCorePkg.dsc
DEBUG_OUTPUT_DEVICE_MASK can be used to control debug output devices.
When frame buffer is enabled as debug output devices, it will only
work after GFX init. However, the code will still be linked into Stage
1A/1B/2 binary and increase the size. GFX debug device should only be
enabled in payloads. This patch used separated PCD values for stages and
payloads to optimize the binary size.
> Limit debug output devices in stages

- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
The 'boot' command is resetting the current
boot option to be option zero any time the
command is invoked which conflicts with the
'c' command which allows a user to select the
next boot option that should be tried. Remove
the resetting to resolve the issue when doing
'c' sub-command in the 'boot' command.
> Remove boot option reset from boot cmd

- PayloadPkg/OsLoader/PreOsChecker.c
Fix type cast error from pointer to function pointer
> Fix build failure in PreOsChecker on Windows

- BootloaderCommonPkg/Library/ShellLib/History.c
- BootloaderCommonPkg/Library/ShellLib/History.h
- BootloaderCommonPkg/Library/ShellLib/Shell.c
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
This patch added command line history upport in SBL Shell. It makes
it easy to run a previous command using Up/Down arrow key.
> Add Shell command line history support

- Silicon/ApollolakePkg/FspBin/FspBin.inf
There is an issue with Vbt.bin in MR5; MR6 has this fixed.
Test: compiles OK, boots Linux OK.
Signed-off-by: Ursula Maplehurst <ursula@kangatronix.co.uk>
> [APL] Update FSP to MR6 (#392)

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
This patch is a follow-up patch of #380. If a platform disables HS400 mode,
silicon init code will configure eMMC in HS200. Other modes not in scope.
This will also fix #406.
> Silicon init with eMMC HS400 mode config

- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c
- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLibInternal.h
Since SBL shell added support for command line history. It is required
to support it from USB keyboard console as well. This patch added USB
keyboard arrow key handling to convert arrow key scan code into ANSI
escape sequence so that Shell can recognize the arrow key from keyboard.
> Add USB arrow key support

- BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
- PayloadPkg/Library/AbSupportLib/AbSupportLib.c
- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
This patch allows OsLoader to handle all Boot Options without restarting.
Currently, OsLoader restarts to handle next Boot Option from the beginning.
This behavior does not preserve allocated memories from Payload heap,
so it makes hardware/software state hard to maintain.
> [OsLoader] OsLoader lifecycle change

- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
The 'boot' command is making use of a global
variable declared in the OS Loader but it might
not always be available if the Shell lib is
used with other code. This patch removes the
dependency on the global variable.
Also fixes a small issue with not providing a
value at the prompt; instead prompt the user
with a error message when no valid value has
been provided.
> Remove global variable in boot cmd

- BootloaderCorePkg/Tools/GenContainer.py
Container parse logic cannot handle NORMAL (default) case
currently. So, if -t option is not used while generating a
Container, unsupported image type is reported during runtime.
Change the default type to CLASSIC, and end-user can use
-t option to switch to MULTIBOOT if needed.
> Set default Container type to CLASSIC

- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Currently, only absolute path is allowed in '-w' stitch_dir and '-s'
stitch_zip file. In addition, if stitch_dir is not absolute path, the
stitch tool looks for 'SBL_SOURCE' which does not exist in OS environment.
This patch allows the StitchIfwi.py tool to use relative path as well.
Change-Id: I08826406995a8d81a01be6951169b1302e5aafb7
> [WHL] Allow relative path in StitchIfwi.py

- BootloaderCommonPkg/Library/ShellLib/CmdPci.c
"MM" SBL Shell command can be used to dump PCI configuration space
registers. On the other side, "PCI" command can be used to list all
PCI devices. This patch enhanced "PCI" command to support PCI
configuration space dump by redirecting it to "MM" command internally.
> Add PCI configuration space dump with PCI command

- MdePkg/Include/Library/DebugLib.h
This patch replace the standard ASSERT macro with klocwork specific
implementation as indicated on:
https://docs.roguewave.com/en/klocwork/current/tuningccanalysis
This can provide hints to klocwork scanning on the ASSERT() statement
so as to avoid false positives.
> Replace ASSERT macro in DebugLib for klocwork scanning

- BootloaderCommonPkg/Include/Library/Ext23Lib.h
- BootloaderCommonPkg/Include/Library/FatLib.h
- BootloaderCommonPkg/Include/Library/FileSystemLib.h
- BootloaderCommonPkg/Include/Library/PartitionLib.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext23Lib.inf
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext2FsLs.c
- BootloaderCommonPkg/Library/Ext23Lib/ExtLib.c
- BootloaderCommonPkg/Library/Ext23Lib/LibsaFsStand.h
- BootloaderCommonPkg/Library/FatLib/FatLib.c
- BootloaderCommonPkg/Library/FatLib/FatLiteAccess.c
- BootloaderCommonPkg/Library/FileSystemLib/FileSystemLib.c
- BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdFs.c
- BootloaderCommonPkg/Library/ShellLib/ShellCmds.c
- BootloaderCommonPkg/Library/ShellLib/ShellCmds.h
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
This 'fs' shell command can be used for basic file system check.
Usage: fs init [device no.] [hwpart no.] [swpart no.]
fs close
fs info
fs ls [dir or file path]
- 'device no.' is from Platform Device Table.
- all 0s by default if 'fs init' has no parameters
- root dir by default if 'fs ls' has no dir or file path
> Add FS (File System) shell command

- MdePkg/Include/Library/DebugLib.h
Klocwork has issue to handle the CR macro in SBL code and it reported
false positives such as unused variables, uninitialized variables, etc.
This patch added special handling to resolve the issues reported by
Klocwork scanning.
> Redefine CR macro to address Klocwork scanning issue

- BootloaderCommonPkg/Include/Library/Ext23Lib.h
- BootloaderCommonPkg/Include/Library/FatLib.h
- BootloaderCommonPkg/Include/Library/FileSystemLib.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
- BootloaderCommonPkg/Library/Ext23Lib/Ext2FsLs.c
- BootloaderCommonPkg/Library/Ext23Lib/ExtLib.c
- BootloaderCommonPkg/Library/FatLib/FatLib.c
- BootloaderCommonPkg/Library/FileSystemLib/FileSystemLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdFs.c
This allows 'fs ls' command to print directory or file lists to both serial
and display console according to CONSOLE_OUT_DEVICE_MASK.
> CmdFs: Support display console print in 'fs ls'

- PayloadPkg/Library/SblParameterLib/SblParameterLib.c
It should use local variable ResetReason instead of OsBootOptionList
in case of OS boot option is not available.
> Fix KW issue

- Platform/CoffeelakeBoardPkg/CfgData/Template_CfgData.dsc
ConfigEditor.py tool reports a warning regarding the
incorrect Interrupt Configuration for pins on Upx boards.
Certain board's default PAD CFG values may have none of
NMI/SMI/SCI/IOAPIC set and also RXEVCFG set to Disable,
so add a corresponding option in the drop-down for IntConfig.
> [WHL] Handle Gpio Int Config warning

- .travis.yml
This will run PatchCheck.py in travis before building a target.
If the format is invalid, travis will exit immediately.
> Enable PatchCheck in travis

- .travis.yml
PatchCheck was using 'TRAVIS_COMMIT_RANGE' travis variable to get commit
range, but it lost tracks when doing force push or rebase. There are many
issue reports about this variable.
To avoid potential issue, let's get the range from git command directly
instead of TRAVIS_COMMIT_RANGE variable.
> Fix invalid PatchCheck commit ranges in travis

- Platform/CoffeelakeBoardPkg/Script/GenGpioData.py
GenGpioData.py is a utility that converts
GPIO pin data from one format to other.
The formats currently supported are [h, csv, txt, dsc, dlt].
[h, csv, txt] formats are external to SBL and [dsc, dlt] formats
are known to SBL. So, this tool provides a way to convert one
of the [h, csv, txt] to [dsc, dlt] and vice-versa.
> Add GenGpioData.py tool

- Platform/CommonBoardPkg/AcpiTables/Tpm/TpmSsdt.asl
UEFIPayload uses SMM dispatch for Physical Presence (Tcg2SMM) SMI.
Updated SMI port usage in asl to trigger SMI registered for
Physical Presence operation
> Update TPM Physical Presence asl for SMM Dispatch usage in payload

- BootloaderCommonPkg/Include/Library/SortLib.h
- BootloaderCommonPkg/Library/SortLib/SortLib.c
- BootloaderCommonPkg/Library/SortLib/SortLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLibInternal.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
There are multiple instances of sorting use case in SBL. For example,
memory map sorting and CPU APIC ID sorting. This patch added a generic
quick sort library to provide common sort API. As part of the change,
the quick sort API will be used for memory map and CPU APIC ID sorting.
> Add SortLib support in BootloaderCommonPkg

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
hash_type parameter added to build tool API's as required and
current supported hash in tools is for SHA2_256.
Added functionality for retriving RSA private key type.
> Add hash type param to bootloader build and signing tools

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/sha384.c
- BootloaderCommonPkg/Library/IppCryptoLib/sm3.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
Functionality to Crypto Hash function is guarded with an
PcdIppHashLibSupported.
PcdIppHashLibSupported indicates IPP crypto algo supported
> Add SHA384 and SM3 wrapper library support for IPP crypto

- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
OsBootOption config data provides addendum field to support multiple boot
option config data into a single boot option.
This patch updates a single boot option properly with multiple addendums.
> Fix invalid addendum update in OsBootOption

- BootloaderCommonPkg/Include/Library/IasImageLib.h
- BootloaderCommonPkg/Include/Library/MultibootLib.h
- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- PayloadPkg/Include/Library/SblParameterLib.h
- PayloadPkg/Library/SblParameterLib/SblParameterLib.c
- PayloadPkg/Library/TrustyBootLib/TrustyBootLib.c
- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
While trying to boot all boot options, some allocated memory are not
de-allocated properly. To avoid memory leak while booting next boot
options, OsLoader will track all image data and free the unnecessary
memory at failing to boot current boot option.
Tested and verified with
- Traditional linux image on debug build
- IAS type image
- Container type image
- MultiBoot image
- BootSlot (A/B Boot)
- Trusty image
> OsLoader: Free all allocated memory at failing on a boot option

- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
Added hash type to be used in signing process for
GenCapsuleFirmware.
Parameter added: -a alg_hash
> Signing hash type in GenCapsuleFirmware tool

- BootloaderCommonPkg/Include/Library/SortLib.h
- BootloaderCommonPkg/Library/ShellLib/Shell.c
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
- BootloaderCommonPkg/Library/SortLib/InsertionSort.c
- BootloaderCommonPkg/Library/SortLib/SortLib.inf
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
This provides basic insertion sort API for Linked List. As part of change,
this insertion sort is used for PCI BAR calculation by its alignment
and for shell commands list by its name.
> Add InsertionSort for Linked List

- BootloaderCorePkg/Tools/CfgDataTool.py
Auth_type param is set to RSA2048SHA256 for default cases.
> Set auth type to default in CfgDataTool

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Library/SerialPortLib/SerialPortLib.c
- BootloaderCommonPkg/Library/SerialPortLib/SerialPortLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- Silicon/ApollolakePkg/Library/SerialPortLib/SerialPortLib.c
- Silicon/ApollolakePkg/Library/SerialPortLib/SerialPortLib.inf
SerialPortLib sets UART Scratch Register to a known value at the first
initialization to avoid unnecessary re-initialization afterward. But,
one of Windows driver(SIO) re-configures UART Registers while the Scratch
Register is preserved. As a result, SBL skips serial port initialization
after restarting from Windows.
Therefore, force to initialize Serial Port at Stage1A all the time simply.
> Fix no SBL serial output after restart Windows

- BootloaderCommonPkg/Include/Library/ConfigDataLib.h
- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/BootloaderCorePkg.fdf
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.inf
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Current SBL has platform specific GetBuiltInConfigData() implementation
because the internal CFGDATA blob is embedded into Stage1B data section.
Instead, it can be put into Stage1B FV FFS file, and then use a PCD to
get the base. In this way, it can be handled directly in core code and
remove platform specific implementation.
> Remove platform specific GetBuiltInConfigData()

- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
Signing hash type is defaulted to SHA2_256.
> GenCapsuleFirmware: Hash type is made optional param

- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- Platform/ApollolakeBoardPkg/CfgData/CfgData_Gpio.dsc
- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Gpio.dsc
- Platform/QemuBoardPkg/CfgData/CfgDataGpio.dsc
This patch added additional information in the GPIO CFGDATA header
structure so that the full GPIO info can be extracted out later on
by tool. This additional information including GPIO SKIP bit position,
GPIO ID position and length.
> Adjust GPIO CFGDATA structure header

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current SBL calls ClearFspHob() too early. Since HOB is required
during the whole FSP life cycle. It is better to clear it at the
end after the last call. Otherwise, some previous API call will
potentically encounter issues.
> Move clear HOB to the very end of the boot flow

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataStitch.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/ConfigEditor.py
- BootloaderCorePkg/Tools/GenCfgData.py
This patch enhanced the CFGDATA script to extract CFGDATA BIN
files from IFWI and further generate DLT using default DSC.
In this way, the default CFGDATA binaries and DLT files are no
longer requried to be provided in the release package in order
to customize the CFGDATA in an existing IFWI image.
> Enhance CFGDATA tools to support generating DLT from IFWI

- BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
- PayloadPkg/OsLoader/OsLoader.c
By adding an additional flag for the pre-OS
checker execution flow it is possible to determine
at run time whether to attempt loading/execution
of the pre-OS checker during OS Loader time. From
platform code the decision to attempt to run the
pre-OS checker can be controlled.
> Add features flag for pre-OS checker boot

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/ExtraBaseLib.h
- BootloaderCommonPkg/Library/ExtraBaseLib/ExtraBaseLib.inf
- BootloaderCommonPkg/Library/ExtraBaseLib/Ia32/CpuSupport.nasm
- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/auth/Ia32/pcpsha512g9as.nasm
- BootloaderCommonPkg/Library/IppCryptoLib/auth/Ia32/pcpsha512w7as.nasm
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcphash.h
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha256ca.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha512ca.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpvariant_abl.h
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLibInternal.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
Enable CPU AVX support if available. EnableAvx ASM is included as part ExtraLibs.
Add support for AVX and SES4 optimizations in IPP SHA384 is added to IPP crypto lib. PcdCryptoShaW7Enabled is added and default is set to SES4 (W7).
> IPP Crypto SHA384 AVX and SES4 optimizations

- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha256ca.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha512ca.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpvariant_abl.h
- Platform/QemuBoardPkg/BoardConfig.py
The previoius IPP library updates used UpdateSHA256V8 as default for
SHA256. It works on real platform. However, QEMU's default CPU config
does not support SSE3 instructions and will generate exception. This
patch added the UpdateSHA256Compact as default SHA256 function if no
advanced optimization flags are set. The same is applied for SHA512
functions too.
> [QEMU] Fix QEMU boot issue with new IPP library change

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch updated the PayloadId detection logic on APL platform
to make it easy to understand.
The current policy is as below:
- If PayloadId CFGDATA is not AUTO, use whatever provided in CFGDATA.
- If PayloadId CFGDATA is AUTO, and GPIO based PayloadId detection
is enabled, uses GPIO level to determine the actual PayloadId to
use. (HIGH:OsLoader LOW:UEFI)
- If PayloadId CFGDATA is AUTO, and GPIO based PayloadId detection
is disabled, uses default PlatfomrId 0 (OsLoader).
> Adjust GPIO based PayloadId selection policy

- BootloaderCommonPkg/Library/ExtraBaseLib/Ia32/CpuSupport.nasm
- BootloaderCorePkg/Stage1A/Stage1A.c
System reset occurs after returning from AsmEnableAvx() in Stage1A.c
because ebx register is used for cpuid, but not restored.
- Save/Restore ebx register
- Move AsmEnableAvx () after init idt and serialport
> Preserve ebx register in AsmEnableAvx()

- BootloaderCommonPkg/Include/Guid/KeyHashGuid.h
- BootloaderCorePkg/Include/HashStore.h
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Tools/BuildUtility.py
Current code only counted used hash store size as the whole
buffer size. This is not correct and will cause buffer overflow.
It is required to use the whole hash store buffer size including
the unused space at the end. This patch fixed this.
It also adds HeaderLength field in Hash Store header.
> Fix hash store buffer size issue in SBL global data

- BootloaderCorePkg/Tools/CommonUtility.py
There are many cases that it is required to print the values of
byte-array for debug. It is not convenient in current SBL python
scripts. This patch added a print_bytes() function in CommonUtility
to provide generic function to print out a byte array object.
> Add bytes print function in CommonUtility

- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Include/Library/IasImageLib.h
- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.h
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BootloaderCorePkg/Tools/GenContainer.py
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
Added pubKey and signature updates to storage and implementation of these changes to secure boot and crypto libs. This patch set adapted changes for only RSA2048 & SHA256 in signing tools and secure boot/crypto libs.
Data reversal is removed while computing Hash of the data.
Adapted updated structures in Stage1B and ContainerLib where RSA_Verify() gets used.
For IAS image, data is transformed from IAS header to Cryptolib structures.
FwCapsuleupdate component and corresponding tool are be updated
> Publickey and Signature data structure updates

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
This patch removed duplicated RSA signing implemention in
CfgDataTool script and used the common one in CommonUtility.
It also removed PrintByteArray(), and use common print_bytes()
instead.
> Use the common function from CommonUtility

- BaseTools/Scripts/PatchCheck.py
- BaseTools/Source/C/Makefiles/NmakeSubdirs.py
- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
This issue happens under two conditions
1. Unicode language environment in Windows
2. A python calls 'BaseTools/toolsetup.bat'
(In EDKII, edksetup.bat directly in Windows command shell)
- 'BuildLoader.py' calls 'BaseTools/toolsetup.bat' in a subprocess
- 'BaseTools/toolsetup.bat' calls 'nmake cleanall'
- 'cleanall' target runs 'python NmakeSubdirs.py' directly
- 'NmakeSubdirs.py' creates multi-threads
-  The threads create another subprocesses
But, one of multi-threads is on deadlock when python handles stdout and
stderr in a subprocess pipe only if the output includes unicode chars.
Therefore, only stderr will be handled in the pipe same as a single
thread call.
> Build stuck on unicode locale Windows

- BuildLoader.py
When firmware updated is not enabled, it will not build firmware update
payload, so there is hash for FWUPDATE.hash.
Update the build tool only require it when firmware update is enabled.
> Fix the build failure when firmware update is not enabled

- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Include/Library/IasImageLib.h
- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1B/Stage1B.c
- PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
Hash and RSA signing parameters were hardcoded in
Crypto wrappers and secure boot libraries. This patch
address support for multiple hash and key sizes to 
these libraries.
> IPP Crypto and Secure boot lib to support multiple hashes

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- BootloaderCorePkg/Stage2/Stage2.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Platform/CoffeelakeBoardPkg/AcpiTables/AcpiTables.inf
- Platform/CoffeelakeBoardPkg/AcpiTables/Dsdt/Dsdt.asl
- Platform/CoffeelakeBoardPkg/AcpiTables/Dsdt/Platform.asl
- Platform/CoffeelakeBoardPkg/Library/ShellExtensionLib/CmdFwUpdate.c
- Platform/CoffeelakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch does the following
1) Enable triggering firmware update from OS
2) When firmware update mode is given control, state machine
is set to capsule processing and firmware update platform
specific trigger is cleared. State machine will be used
hereafter to track firmware update
3) Created CheckStateMachine method in BoardSupportLib.c to
check state machine to see if firmware update is in progress
and set boot mode to firmware update.
4) Removed CMOS way of triggering firmware update and wrote code
to use Over-Clocking WDT Scratchpad (OC_WDT_SCRATCH) bits for
triggering firmware update
5) Update shell fwupdate command to use OC_WDT_SCRATCH bits.
6) Removed extra reset during sbl firmware update
7) Removed reset after updating configuration data update
Signed-off-by: Raghava Gudla …
> [CFL] Trigger firmware update from OS

- BootloaderCommonPkg/Include/Guid/DeviceTableHobGuid.h
- MdePkg/Include/Library/SmbusLib.h
- Silicon/CommonSocPkg/Library/SmbusLib/RegsSmbus.h
- Silicon/CommonSocPkg/Library/SmbusLib/SmbusLib.c
- Silicon/CommonSocPkg/Library/SmbusLib/SmbusLib.inf
Add a common SmbusLib support for Intel PCH
Define PLT_MEDIUM_MISC_TYPE in device table for
devices that are not for OS boot.
> Add SmbusLib

- BootloaderCommonPkg/Library/ShellLib/CmdMm.c
If dumping address not aligned at 16 boundary, the current Shell
will print the aligned address in the dump. It makes sense for
a memory block display, but it is a little bit confusing for single
memory address display. This patch fixed this issue by printing the
exact address when the display count is 1.
> Print exact address for Shell memory dump command

- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.c
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.h
- BootloaderCorePkg/Stage1B/Stage1B.inf
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2Support.c
This patch did some of the following clean up:
- Rename *_HOB to *_PARAM for Stage1A/Stage1B/Stage2.
This is to avoid confusion between real HOB and the parameter
data block passed through stages.
- Rename BistVal to CpuBist.
This is to make it more clear.
- Add BUF_INFO definition.
BUF_INFO will be used as a general structure.
- Remove CarBase/Top in Stage1B HOB
They are not used at all.
- Clean memory allocation in Stage1A
Restructured the buffer allocations for Stage1A global
data so that it is easier to read and maintain.
> Clean up BootloaderCorePkg stage code

- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
Configuration data blob is supported only from Bios region.
Removing CfgData in PDR as its no longer getting used.
Updated to copy signed data structure length for max supported.
Max supported is for RSA3072 size.
> Remove PDR CfgData support

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
Enable RSA3072 and SHA384 signing support
This patch introduces support for RSA3K and SHA384 signing
And verifications support to Slimbootloader. Component hash
verification is done using PcdCompSignHashAlg.
To enable RSA3072 and SHA384,
- Signing hash algorithm SIGN_HASH_TYPE should be set to ‘SHA2_384’
- RSA 3K private keys should be configured in platform board configs.
- Set IPP_CRYPTO_ALG_MASK to inlcude SHA2_384
- Enable required IPP_CRYPTO_OPTIMIZATION_MASK
- Default siging hash type is set to SHA2_256. Use hash type option
while using the tools as Gencontainer, CfgDataTool in standalone
mode.
Pending: Measured boot support for SHA384  to be enabled.
> Enable RSA3072 and SHA384 signing support

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
This patch will run version check only for SBL update and will
skip for all other components.
Version check for all other components will be added in future
patches.
> Execute version check only for SBL update

- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
In Python 3 built-in function next() is used to get the next result
from an iterator. next method causes post build failure.
> Python3 Next() compatibility fix

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/FspApiLib/FspmApiLib.inf
- BootloaderCorePkg/Library/FspApiLib/FspsApiLib.inf
- BootloaderCorePkg/Library/FspApiLib/FsptApiLib.inf
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- BuildLoader.py
- Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
This patch enabled Visual Studio 2017 Community build support.
The following were done:
- Added new method to detect VS2017 installation path and version
- Droped VS2005, VS2008, VS2010 and VS2012 build support. Only
VS2013 and VS2015 are supported.
- Fixed build issue in FspApiLib due to new compiler optimizations
- Synced the build support for QEMU FSP patch
> Add Visual Studio Community build support

- BaseTools/Scripts/PatchCheck.py
The PatchCheck.py will skip specified file types in skip_check_file_types.
As of now, .patch and .pem files are in skip list.
> [PatchCheck] Add exception file types

- .travis.yml
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
Since Python 2.7 is EOL already. SBL needs to drop the support.
This patch enforced the python version to be 3.6 or above for SBL
build.
> Enforce Python 3.6 or above for build

- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/IasImageLib/IasImage.c
- BootloaderCommonPkg/Library/IasImageLib/IasImageLib.inf
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.inf
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
Hash verification of Public key hash should be based on
hash alg used with Hash store. Previously hash alg in
signature info is used. There would be instances where
hashstore hash algorithm differs from signing alg.
> Pass Hash Alg param for verifying hash data with RsaVerify

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
This patch added routine to get component entry from flash map
this is required in case when component entry flags are required.
GetComponentInfoByPartition function will reuse the newly added
routine GetComponentEntryByPartition.
> Added routine to get comp entry from flash map

- BootloaderCorePkg/Tools/GenContainer.py
If running GenContainer tool with python3, 'view' sub-command will
throw out errors.  This patch fixed it.
> Fix GenContainer tool issue with python3

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1A/Ia32/SecEntry.nasm
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BuildLoader.py
This patch allows to setup Stage1 stack/data in any CAR range.
By default, the stack base offset is 0 from CarBase.
> [Stage1] Add Stage1 stack base setup offset

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
In GenContainer tool auth definitions for RSA cases were
updated to include hash alg used. In current implementation
auth type is generated from hash type and private key while
container created. This patch removes hash type param
and auth type is used for hash alg generation.
Platform code to be updated as per updated auth definitions
> GenContainer: Converge hash param and auth type usage

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Include/Library/TpmLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCommonPkg/Library/TpmLib/Tpm2Help.c
- BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c
- BootloaderCommonPkg/Library/TpmLib/TpmEventLog.h
- BootloaderCommonPkg/Library/TpmLib/TpmLib.c
- BootloaderCommonPkg/Library/TpmLib/TpmLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.inf
- PayloadPkg/OsLoader/OsLoader.h
Current Slimbootloader supports only TPM for SHA256 PCR
This patch introduces flexibility for user to select TPM
PCR bank available while build. Support of SHA384 and
SM3 to TPM measured boot are added.
For first boot SHA256/default TPM PCR would be available which
is default for most supported TPM's. Selected TPM PCR will be
available after reboot.
TPM selection would be based on config data and support would
be added in subsequent patches.
> TPM and Measured boot support SHA384 and SM3

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
This patch added routines to support update for any
component identified by flash map. Also, if the capsule
container components inside the container, Support is added
to update these container components.
> Added support for container component update-from-OS

- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
Allocate pages is used now to allocate memory during block update
but was freed using freepool which is throwing exception. Changed
code to use FreePages
Also removed an unused function
> Free memory using FreePages instead of Freepool

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
GIT is required to get FSP binary, ucode patch and so on.
This patch will check GIT availability.
> Add GIT tool check for build

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
- Silicon/CoffeelakePkg/Include/CpuPowerMgmt.h
- Silicon/CoffeelakePkg/Include/PowerMgmtNvsStruct.h
- Silicon/CoffeelakePkg/Include/Register/CpuRegs.h
This will allow update PSS table in a common way.
For a platform specific power calculation,
a function pointer can be provided.
> Add a common api to patch PSS table

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
There are many parameter passing to AcpiPatchPssTable().
A single PSS_PARAMS structure pointer will be passed to simplify.
> Update AcpiPatchPssTable() parameter

- BootloaderCorePkg/Stage1A/Stage1A.c
Current FLASH_MAP address is hard-coded at 0xFFFFFFF8. It will work
in most of the cases.  However, if region is added on top of the
Stage1A FV, it will cause FLASH_MAP address shift.  Instead, the code
can use relative address to locate FLASH_MAP.  The address can be
calculated with (Stage1AFvBase + Stage1AFvSize + 0xFFFFFFF8).
> Avoid hardcoded flashmap address

- BuildLoader.py
This patch allows the platform to add EMPTY component in the
flash layout definition in BoardConfig.py.  Without this patch,
it will cause build error because it expects EMPTY as an actual
component file.
> Allow adding EMPTY component in flash layout

- BootloaderCorePkg/Stage1B/Stage1B.c
After memory init, FSP reset request is handled by FspResetHandler.
Remove unnecessary duplicated code.
> Remove duplicated code for Fsp reset request

- BootloaderCommonPkg/Include/Library/LinuxLib.h
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/PreOsChecker.c
This will allow OsLoader to use LinuxLib for legacy linux boot
and remove duplicated code.
> OsLoader clean-up to use common LinuxLib

- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
Currently BN buf is statically defined and this
would increase stack sizes. Allocate the required memory.
> Allocate BN Buf with Rsa Verification

- Silicon/QemuSocPkg/Library/SpiFlashLib/SpiFlashLib.c
After erasing flash on QEMU, it needs to be returned to normal
read state to allow normal read access. However, this is missing
in current SBL QEMU SpiFlashLib.  This patched added the code to
switch back to read mode. It also fixed #552.
> Fix QEMU Flash read issue after erasing

- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch printed out the loaded data from the test container.
It is helpful for tool to parse the boot log and verify if the
component inside the container has been loaded properly.
> [QEMU] Add test container data print

- BootloaderCorePkg/Tools/GenCfgData.py
This patch fixed the GenCfgData failure with Python 3.
> Fix GenCfgData script issue with Python 3

- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
1) GetComponentInfoByPartition does not check FlashMapPtr, added code
to return error if FlashMapPtr is NULL
2) In GetComponentHash function, there is no check for if HashEntryPtr is
greater than or equal to HashEndPtr. In this case HashEntryData will be
corrupted.
3) In InitFirmwareUpdate function, if we could not find corresponding image in
capsule, there is an error message but after that we continue to update
reserved region based on ImageHdr which is not valid. Added code to continue
if image is not found in capsule.
4) In UpdateSblComponent function, Status is uninitialized. Initialized Status to
not found.
> Fix several minor issues in the code

- BootloaderCorePkg/Include/Library/AcpiInitLib.h
- BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- Platform/CommonBoardPkg/AcpiTables/Fpdt/Fpdt.aslc
FPDT size should be FIRMWARE_PERFORMANCE_TABLE. And updated
this logic to correct the size and adjust next ACPI table
starting address.
> Fix FPDT size issue

- BaseTools/Source/Python/AutoGen/GenMake.py
With the lastest EDK2 201911 BaseTools, the generated Makefile has
missing dependcy file for the map file target. It results in staled
map file when source code is modified.  This patch added the missing
dependencies.
> Fix BaseTools FFS map file dependency issue

- BaseTools/Scripts/PatchCheck.py
If a submodule is being updated in a
commit there is inadvertently some line
ending issues that will cause PatchCheck.py
to report an error; since we cannot change
the line ending in the submodule files
we should skip over a line in a patch that
matches the format of a submodule being
updated.
> Skip submodules during PatchCheck.py

- Platform/QemuBoardPkg/Script/qemu_fwu.py
This patch added a script to test QEMU firwmare update flow.
To use it:
- Build SlimBootloader.bin for QEMU
python BuildLoader.py build qemu
- Generate firmware update capsule
python BootloaderCorePkg\Tools\GenCapsuleFirmware.py
-p BIOS Outputs\qemu\SlimBootloader.bin
-k BootloaderCorePkg\Tools\Keys\TestSigningPrivateKey.p
-o Test\FwuImage.bin
- Run the script
python qemu_fwu.py  Outputs\qemu\SlimBootloader.bin Test
> Add QEMU firmware update test script

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/IfwiUtility.py
- BuildLoader.py
This patch allows to extract individual microcode binary from the
IFWI image. It can also replace the microcode in the IFWI image.
FIT entries will be patched accordingly as part of the microcode
replacement.
For example:
To extract microcode to directory Ucode:
python BootloaderCorePkg\Tools\IfwiUtility.py  extract -i
Outputs\cfl\SlimBootloader.bin  -p IFWI/BIOS/RD0/UCOD -u Ucode
To replace all microcode binaries (*.mcb) under directory Ucode
into IFWI image:
python BootloaderCorePkg\Tools\IfwiUtility.py replace -i
Outputs\cfl\ifwi_whl.bin  -p IFWI/BIOS/RD0/UCOD -u Ucode -o
Outputs\cfl\ifwi_whl_new.bin
The example only handled BP0. If required, needs to do the similar for
BP1 by changing the component path.
> Add microcode extract and replace support

- Platform/ApollolakeBoardPkg/Library/ShellExtensionLib/CmdFwUpdate.c
- Platform/ApollolakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ApollolakeBoardPkg/Script/StitchLoader.py
- Silicon/ApollolakePkg/Include/ScRegs/RegsPmc.h
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch added code to:
- Trigger FWU using sticky register in SBL Shell
- Detect FWU mode using combination of sticky register and state
machine
- Clear the trigger flag at the end of FWU
> [APL] Enable firmware update trigger through sticky register

- BuildLoader.py
When python is installed to a path with spaces, it would build failed.
This patch will fix this issue.
> Fix build issue

- BootloaderCorePkg/Tools/CfgDataTool.py
This patch added checks for the CFGDATA length in CfgDataTool.py.
It will help catch invalid CFGDATA format during the build process.
> Add CFGDATA length check in the build process

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
PciEnumeration() scans a single PCI root bridge currently.
The PCI_ENUM_POLICY_INFO structure will be generated at build time,
and this will allow PCI enumeration more flexible.
typedef struct {
UINT8           DowngradeIo32;	// default:1
UINT8           DowngradeMem64; // default:1
UINT8           DowngradePMem64;// default:1
UINT8           Reserved;
UINT8           BusScanType;    // default:0 (0: list, 1: range)
UINT8           NumOfBus;       // the number of BusScanItems
UINT8           BusScanItems[0];
} PCI_ENUM_POLICY_INFO;
> Add PCI Enumeration policy info

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Current code does not clear firmware update trigger incase
of failures like, capsule image not found or capsule image
authentication failed.
Code is modified to fix this issue. As part of this change,
EndFirmwareUpdate function is moved from platform code to
core firmwareupdate.c. EndFirmwareUpdate function will call
ClearFwUpdateTrigger and this will end firmware update.
> End firmware update incase of failure

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
A build fails on Windows due to PCI Enum Policy patch (#559).
This will resolve the build failure.
> Fix a build failure on Windows

- Platform/QemuBoardPkg/AcpiTables/AcpiTables.inf
- Platform/QemuBoardPkg/AcpiTables/Dsdt/Dsdt.asl
This patch added ACPI WMI based firmware update trigger interface
for QEMU. It provides standard interface for SBL to trigger firmware
update.
If with SBL sbl wmi driver integreated, use the following to trigger
FWU:
echo "1" > /sys/bus/wmi/devices/44FADEB1-B204-40F2-8581-394BBDC1B651
/firmware_update_request
> [QEMU] Add WMI based firmware update trigger mechanism

- PayloadPkg/OsLoader/OsLoader.c
Current OsLoader used the component count in the container header to
handle the image loading. But it does not exclude the reserved _SG_
component in case of monolithic signing. This patch fixed this issue
by using the actual detected image count.
> Adjust component count calculation in OsLoader

- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
SBL PCI enumeration code will zero out all PCI command registers and
PCI bridge control registers. However, FSP might have programmed some
of the registers already, and some of the bits are expected to be
preserved through the PCI enumeration. This patch addressed this issue
by only clearing the bits that are required during the PCI enumeration.
> Preserve PCI some command/control register bits during enumeration

- Silicon/ApollolakePkg/Library/PsdLib/PsdLib.c
- Silicon/CoffeelakePkg/Library/PsdLib/PsdLib.c
platform security discovery driver having bug it was wrongly doing
pointer arithmetic and causing memory overwrite. this may cause
intermittent fault.
Removing ZeroMem call since its not required, ACPI table is already
ZeroMem allocated from PSD aslc code.
Signed-off-by: Prakash Chandra <prakash1.chandra@intel.com>
> PSD Fixed memory overwrite issue.

- BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
For non UEFI boot, it is required to put an SMBIOS entry in legacy F
segment at 16-byte aligned boundary so that OS can locate the SMBIOS
by searching the region. This patch added this logic to add SMBIOS
entry at fixed location 0xFFF60. ACPI table has the similar legacy
root pointer at fixed location 0xFFF80.
> Add SMBIOS entry in legacy region

- BootloaderCommonPkg/Include/Library/BlMemoryAllocationLib.h
- BootloaderCommonPkg/Library/FullMemoryAllocationLib/FullMemoryAllocationLib.c
- BootloaderCommonPkg/Library/FullMemoryAllocationLib/FullMemoryAllocationLib.inf
- PayloadPkg/Include/Library/PayloadMemoryAllocationLib.h
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
Current SBL AddMemoryResourceRange() API interface is not scalable.
If more memory type needs to be added, the interface does not allow
to do that. This patch changed the interface to use array and entry
count as parameter so that more ranges can be passed in using the
standard interfaces.
> Change AddMemoryResourceRange API interface

- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Silicon/CommonSocPkg/Include/IndustryStandard/Vtd.h
- Silicon/CommonSocPkg/Include/Library/VtdPmrLib.h
- Silicon/CommonSocPkg/Library/VtdPmrLib/IntelVtdPmr.c
- Silicon/CommonSocPkg/Library/VtdPmrLib/VtdPmrLib.inf
This patch added the VTd PMR memory protection library. It can be
used to support DMA memory protection feature later on. It also
enabled basic build on APL platform so that it can be tested as part
of the automatic build.
> Add VTd PMR memory protection library

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/IoMmuLib.h
- BootloaderCommonPkg/Library/IoMmuLib/IoMmuLib.c
- BootloaderCommonPkg/Library/IoMmuLib/IoMmuLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
This patch added IoMmuLib support so that device can allocate/free
DMA memory and map/unmap host memory to DMA memory. This lib was
added into AHCI inf file so that it can be tested for build. Later
on more patches will be submitted to enable DMA protection for each
media library such as AHCI, XHCI, eMMC, UFS, NVMe, etc.
> Add IoMmuLib implementation

- .gitignore
The change in slimbootloader/documentation from pull request [#67](https://github.com/slimbootloader/documentation/pull/67) creates the directory 'Download/', which needs to be ignored by git.
> added /Download to .gitignore

- Platform/CommonBoardPkg/CfgData/CfgData_Common.dsc
By default 4MB was allocated for OS crash mode support. Hoever, no
project is really using it at all. The default should be changed
not to reserve any memory for it. For platform needs it, it can
override using platform specific CFGDATA.
> Disable OS crash mode memory allocation

- BootloaderCommonPkg/Include/Guid/LoaderPlatformDataGuid.h
- BootloaderCommonPkg/Library/FullMemoryAllocationLib/Page.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.c
- BootloaderCorePkg/Library/MemoryAllocationLib/MemoryAllocationLib.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
- BuildLoader.py
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.inf
- Silicon/CommonSocPkg/Include/Library/VtdPmrLib.h
- Silicon/CommonSocPkg/Library/VtdPmrLib/IntelVtdPmr.c
- Silicon/CommonSocPkg/Library/VtdPmrLib/VtdPmrLib.inf
This patch added DMA memory type into memory allocation pool for payloads.
This DMA memory buffer with PcdDmaBufferSize is located at address
aligned at PcdDmaBufferAlignment after Payload reserved memory. Memory
type EfiRuntimeServicesData is used to indicate DMA memory type.
Stage1B calculates the DMA memory location using fixed PCDs so that
platform can set up DMA protection as early as possible after memory is
ready. In Stage1B or Stage2 platform code should use platform VTd
information to setup PMR to protect all low memory except for the DMA
buffer range. DMA memory will be added into memory pool at the entry
point of the payload. Before transfering to OS, the DMA memory protection
can be disabled, and the DMA memory pool can be reclaimed for OS usage.
Currently only boot media …
> Add DMA protection in core code

- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c
- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHcMem.c
- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHcMem.h
- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHci.c
- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsInternal.h
This patch added support for IoMmu interfaces. It will allow the
library to use DMA buffer for I/O transactions.
> Add IoMmu support for UFS library

- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.c
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.h
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressBlockIo.c
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressBlockIo.h
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressHci.h
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressLib.inf
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressPassthru.c
This patch added IoMmu support for NVMe block access library.
This will allow the library to use DMA buffer for I/O transactions.
> Add IoMmu support for NVMe library

- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
- BootloaderCommonPkg/Library/AhciLib/AhciDevice.c
- BootloaderCommonPkg/Library/AhciLib/AhciDevice.h
- BootloaderCommonPkg/Library/AhciLib/AhciLib.inf
- BootloaderCommonPkg/Library/AhciLib/AhciMode.c
- BootloaderCommonPkg/Library/AhciLib/AhciMode.h
This patch added support for IoMmu interfaces. It will allow the
library to use DMA buffer for I/O transactions.
> Add IoMmu support for AHCI library

- BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.inf
- BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLibGeneric.c
- BootloaderCommonPkg/Library/MmcAccessLib/SdMmcPciHcDxe.h
- BootloaderCommonPkg/Library/MmcAccessLib/SdMmcPciHci.c
This patch added support for IoMmu interfaces. This will allow the
eMMC library to use DMA buffer for I/O transactions.
> Add IoMmu support for eMMC library

- BootloaderCommonPkg/Library/XhciLib/UsbHcMem.c
- BootloaderCommonPkg/Library/XhciLib/UsbHcMem.h
- BootloaderCommonPkg/Library/XhciLib/XhcPeim.c
- BootloaderCommonPkg/Library/XhciLib/XhcPeim.h
- BootloaderCommonPkg/Library/XhciLib/XhciLib.inf
- BootloaderCommonPkg/Library/XhciLib/XhciReg.h
- BootloaderCommonPkg/Library/XhciLib/XhciSched.c
- BootloaderCommonPkg/Library/XhciLib/XhciSched.h
This patch synced up to the latest EDKII XHCI library and then
added support for IoMmu interfaces. This will allow the library
to use DMA buffer for I/O transactions.
> Add IoMmu support for XHCI library

- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/LoaderLib/LoaderLib.inf
- Platform/ApollolakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Silicon/ApollolakePkg/Include/PlatformData.h
- Silicon/ApollolakePkg/Library/PsdLib/PsdLib.inf
- Silicon/CoffeelakePkg/Include/PlatformData.h
- Silicon/CoffeelakePkg/Include/Register/SaRegs.h
- Silicon/CommonSocPkg/Include/Library/VtdPmrLib.h
This patch added required code flow to prepare to enable DMA
protection for APL platform. Platform code needs to build a
VTD_INFO structure, and then call SetDmaProtection to enable
and disable DMA protection at different initialization phase.
Platform needs to enable DMA protection as early as possible
after memory is ready. For APL, since VT-d is only enabled
in FspSiliconInit, it was postponed to Stage2.
> [APL] Enable APL DMA protection code flow

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch fixed incorrect GPIO pin used for BOM ID detection for
UPX board.
> Fix incorrect BOM ID detection for UP Xtreme board

- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
USB2 port 8 (index 7) is connected to MCU on UPX board. It does not
respond to USB enumeration.  The original code disabled port 10, but
it should be port 8. This patch fixed it.
> Disable malfunction USB2 port

- BootloaderCorePkg/Tools/GenCfgData.py
This patch added subregion value output into full delta file so
that it is easier to update the value directly intead of fields.
For example, the new GPIO output in delta will be:
GPIO_CFG_DATA.GpioPinConfig0_GPP_A00.GPIOPADMode_GPP_A00 | 0x1
This 1st comment line is newly added by the patch.
> Output subregion values into delta file

- PayloadPkg/OsLoader/BootConfig.c
This is a regression on the grub.cfg file parsing. When parsing
each menu entry in grub.cfg, the index should not be advanced
at the end. It will cause the boot index shift by 1 if doing so.
This patch fixed this issue. Tested with Ubuntu boot.
It fixed issue #606.
> Fix OsLoader grub config parsing issue

- BootloaderCorePkg/Tools/IfwiUtility.py
- BuildLoader.py
This patch renames all instances of ACM3 to Diagnostic ACM.
No change in the functionality.
Signed-off-by: Grandhi <sindhura.grandhi@intel.com>
> Rename ACM3 to Diagnostic ACM.

- .gitignore
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Bin/ResetVector.inf
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Build.py
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Ia16/Init16.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Ia16/Real16ToFlat32.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Main.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/PageTables.asm
- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Vtf0.nasmb
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
This an initial patch to add x64 build for SBL.  A new build flag
'-x64' is added to indicate x64 arch build. This cannot be fully
used at this moment because it has many dependencies on other x64
libraries. Only VTF reset vector x64 build is tested.
VTF x64 flow is different from IA32.  It switches to 32 bit
mode as usual and then calls into FspTempRamInit to set up CAR.
Once CAR is ready, it builds 4GB identical mapping page table for
x64 and then switches to x64 long mode. Finally, it locates the
STAGE1A entry point and tranfers the control to STAGE1A in pure
64 bit mode.
> Add SBL x64 build for VTF

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1A/Ia32/Stage1AArch.c
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
- BootloaderCorePkg/Stage1B/Ia32/Stage1BArch.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.h
- BootloaderCorePkg/Stage2/Ia32/Stage2Arch.c
- BootloaderCorePkg/Stage2/Stage2Support.c
This patch opitmized GDT loading in different stages. The old code
put GDT in code segment so it needs to be relocated every time when
code relocation/remapping occurs. By putting GDT into heap, it avoids
the GDT reloading. It only needs to be done twice, PreMem and PostMem.
> Optimize GDT loading in stage core code

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.c
- BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
When multiple USB mass storage boot devices are connected, current
SBL will only boot from the 1st one enumerated by the USB bus. This
patch added support to boot from the remaining devices. This feature
will be controlled by PcdMultiUsbBootDeviceEnabled. And it can be
overridden by board using ENABLE_MULTI_USB_BOOT_DEV. When it is enabled
for USB block IO interface, the hardware partition n boot option
will be used to indicate the index of the USB mass storage devvice.
> Add multiple USB boot device support

- BootloaderCorePkg/Tools/PatchFv.py
This patch enhanced the map format parsing for map files generated
by x64 MSFT compiler.
> Add support for 64bit compiling map file

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/BootloaderCorePkg.fdf
In SBL dsc/fdf file, PLATFORM_PACKAGE was defined. But it is actually
BootlaoderCorePkg. It is confusing. Instead, it can be just removed.
> Remove PLATFORM_PACKAGE in DSC/FDF file

- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch added UP2 board memory SKU3 support. This was enabled
by trying different memory configurations to find the working
configurations. It might not be optimal, but a good start point.
Speical acknowlegement to andreyv1978 who did the enabling on his
board and contributed the code back.
> [UP2] Add memory SKU 3 support

- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcphash_rmf.h
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcptool.h
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Tools/PatchFv.py
- BuildLoader.py
- Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
This supports XCODE toolchain in Mac OS.
- Tested on macOS Catalina version 10.15.2
- Tested with Apple clang version 11
- Verified QEMU target
> Support XCODE build for Mac OS

- PayloadPkg/OsLoader/LoadImage.c
Current SBL used AllocatePool for IAS image or container image
loading. It is not ideal since some file, such as InitRD, requires
page aligned address. It is better to use AllocatePages to allocate
the buffer instead. This patch fixed this.
It fixed #627.
> Use AllocatePages for file buffer allocation

- BootloaderCorePkg/Stage2/Stage2.c
After merging back x64 support, UEFI payload loading starts to fail
with SBL. It is due to the pointer was not properly initialized
for the component loading. This patch fixed this issue.
> Fix UEFI payload loading issue

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
Fix for: Klockwork flags variable 'CompLoc' for being used uninitialized.
Signed-off-by: Vegnish Rao <vegnish.rao.paramesura.rao@intel.com>
> Fix Klockwork issues flagged in BootloaderCommonPkg

- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/BoardConfig.py
Current build only allows board to customize the DSC libraries.
It is better to allow more flexible DSC customization. This patch
enabled this capability. Board can override library, PCDs, etc.
As part of it, the old GetDscLibrary() interface will be deprecated.
Please use GetPlatformDsc() instead.
> Allow more flexible DSC customization by board

- BootloaderCorePkg/Include/Library/FspApiLib.h
- BootloaderCorePkg/Library/FspApiLib/FspApiLibInternal.h
- BootloaderCorePkg/Library/FspApiLib/FspMemoryInit.c
- BootloaderCorePkg/Library/FspApiLib/FspNotifyPhase.c
- BootloaderCorePkg/Library/FspApiLib/FspSiliconInit.c
- BootloaderCorePkg/Library/FspApiLib/FspTempRamExit.c
- BootloaderCorePkg/Library/FspApiLib/Ia32/DispatchExecute.c
- BootloaderCorePkg/Library/FspApiLib/X64/DispatchExecute.c
- BootloaderCorePkg/Library/FspApiLib/X64/Thunk64To32.nasm
- BootloaderCorePkg/Stage1A/Stage1A.c
In certain condition, the FspTempRamExit() API will be executed from
CAR. If so, the thunk call itself cannot be in CAR otherwise the
call will hang immediately after the CAR teardown. To resolve it,
the thunk call needs to be copied over to memory before calling the
FspTempRamExit() API. This patch implemented this.
> Improved thunk call for 32 bit FSP API

- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch enabled APL X64 boot. In X64 mode, more heap is required
for Stage1A since it needs to build page tables. As part of it, APL
CAR region map has been re-arranged so as to save more space. This
has been tested on LeafHill CRB board.
> [APL] Enable X64 boot

- BuildLoader.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
This patch adjusted the Stage1A heap size and OsLoader size to
satisfy CFL build and boot requirment. This has been tested on
UPX board. It has dependeny on preivous PR #636.
> [CFL] Enable SBL X64 boot

- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
This will fix stage transition failures for X64 targets built with gcc
which is caused by mis-matched EFIAPI calling convention.
- Add EFIAPI to STAGE_ENTRY interface for Stage1A -> Stage1B
- Add EFIAPI to PAYLOAD_ENTRY interface for Stage2->OsLoader Payload
- Remove unused KERNEL_ENTRY interface
> Fix Stage1B/Payload loading failure on gcc built X64 target

- Platform/CommonBoardPkg/CfgData/CfgData_Common.dsc
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
- Platform/QemuBoardPkg/CfgData/CfgDataExt_Brd1.dlt
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current SBL does not provide CFGDATA to change the current boot
option although it can be done in SBL shell. This patch added this
into CFGDATA so that it can changed using board CFGDATA. A special
option AUTO is introduced to indicate the priority between CFGDATA
and board specific overriding. When AUTO is selected, board specific
overriding should be used. Otherwise, CFGDATA should be used for
CurrentBoot option.
> Add CurrentBoot CFGDATA option

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
Fix for: Klockwork flags possible null pointer variable 'CompressHdr' being dereferenced.
Signed-off-by: Vegnish Rao <vegnish.rao.paramesura.rao@intel.com>
> Fix Klockwork issue flagged in BootloaderCommonPkg

- BootloaderCommonPkg/Library/PagingLib/PagingMap.c
Lastest SBL IA32 build failed with VS2017 due to typecasting issue.
This patch fixed it.
> Fix VS2017 build failure

- BootloaderCorePkg/Tools/IfwiUtility.py
This patch fixed the string issue in IfwiUtility script. It will
cause the failure for the APL BIOS image parsing.
> Fix BIOS image parsing issue with Python3

- BootloaderCorePkg/Library/FspApiLib/X64/DispatchExecute.c
This will fix a function pointer type cast error.
- a function pointer to data pointer 'void *'
> Fix type cast error on X64 build

- .travis.yml
- BaseTools/Source/Python/build/build.py
This patch added build for Windows VS2017 in Travis. The following
build will be verified on Travis now:
- QEMU GCC x86 Debug
- QEMU GCC x64 Release
- APL  GCC x64 Debug
- CFL  GCC x86 Release
- APL  VC  x86 Debug
- APL  VC  x64 Release
- CFL  VC  x86 Release
- CFL  VC  x64 Debug
> Travis Windows build test

- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
For APL StitchIfwi.py script, if relative path is provided for the
stitching workspace, the stitching process will error out. This
patch fixed this issue by converting the relative path to absolute
path before passing it into the stitching functions.
> [APL] Allow relative path for workspace directory

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Fix unresolved external and type-cast issues for X64 build.
> Fix windows build error when DEBUG_PCI_ENUM=1

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/IppCryptoLib/auth/ippcp.h
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcphash_rmf.h
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpmgf1ca_rmf.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpngrsapss_rmf.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcprsa_pss_preproc.h
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
This patch adds support for RSA PSS verification.
Ported IPP Crypto for PSS from latest IPP github repo.
Secure boot lib and RSA wrappers functions are
updated. RSA verfication sheme is would be
based on SigType in Signature Header.
> RSA PSS verification scheme

- PayloadPkg/OsLoader/OsLoader.c
Current SBL OsLoader call DeinitBootDevices() once at the end of
the boot option loop. This is not right because it will only DeInit
the current active boot device. Instead, DeInit() should be called
inside the loop for every boot device. Specially, if USB is used as
console, USB DeInit() cannot be called at the moment. It will be
deferred until OS transfering.
> Call DeInit() for every boot device

- BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHcMem.c
- BootloaderCommonPkg/Library/XhciLib/UsbHcMem.c
Assertion will occur when booting from USB behind hubs. This was
caused by duplicated freeing the same address page. The for loop
in UsbHcFreeMemPool() does not move to next node in the list. The
similar bug exists in UFS driver. This patch fixed both.
It fixed #659.
> Fix USB boot assertion

- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
This patch fixed an issue which will cause memory leak in OsLoader.
The previous LoadedImagesInfo should be de-allocated before reusing
for other image loading. Or memory leak will occur.
> Fix memory leak issue in OsLoader

- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
- BootloaderCommonPkg/Library/AhciLib/AhciMode.c
- BootloaderCommonPkg/Library/AhciLib/AhciMode.h
This patch fixed AHCI memory de-allocation issue by checking the
correct pointer before calling FreePool/FreePages.
> Fix AHCI library memory de-allocation issue

- BootloaderCommonPkg/Library/FullMemoryAllocationLib/Page.c
This patch added support to report free memory resource lenghth.
It will search for all used memory pages and add them together.
The "virtual" free address will be returned to indicate the
virtual start point of the free memory top. It is virtual since the
memory allocation can be fragmented. This is just an indicator to
calculate the actual used memory size:
UsedMemSize = EndAddr - FreeAddr
> Add support to report free memory resource

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/BoardConfig.py
PcdVerifiedBootHashMask is no longer used while
verification except for stage1B. Remove Hash mask and
added PcdVerifiedBootStage1B for stage1B verification.
> Remove Verified Boot Hash Mask

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Correct the index reported while dumping the
PCI resource information.
> Fix the BarType reported in PciResource Dump

- BootloaderCommonPkg/Library/UsbBusLib/UsbPeim.c
This patch added function UsbDeinitDevice() in UsbBusLib to free
memory allocated for all USB devices.
> Add function to free UsbBusLib allocated memory

- BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.c
- BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBotPeim.c
This patch added UsbDeInitBot() to de-allocation memory alloaced in
UsbBlockIoLib.
> Add USB BOT device memory de-allocation

- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.c
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressHci.h
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressPassthru.c
This patch added NVMe de-initialization function to stop the controller
and de-allocate all memory allocated.
> Fix NVMe library memory de-allocation issue

- BootloaderCommonPkg/Include/Library/XhciLib.h
- BootloaderCommonPkg/Library/UsbInitLib/UsbInitLib.c
- BootloaderCommonPkg/Library/UsbInitLib/UsbInitLibInternal.h
- BootloaderCommonPkg/Library/XhciLib/UsbHcMem.c
- BootloaderCommonPkg/Library/XhciLib/XhcPeim.c
- BootloaderCommonPkg/Library/XhciLib/XhciSched.c
This patch added code to XHCI de-initialization funciton to free
all used memory.
> Fix XHCI library memory de-allocation issue

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
This patch added build hooks for boards so that each board can do
specific actions in different build phases. This patch also added
an example for QEMU to use build hook to generate new binaries into
the flash layout.
> Add build hooks for board

- BootloaderCommonPkg/Include/Library/XhciLib.h
- BootloaderCommonPkg/Library/UsbInitLib/UsbInitLib.c
- BootloaderCommonPkg/Library/XhciLib/XhcPeim.c
- BootloaderCommonPkg/Library/XhciLib/XhcPeim.h
- BuildLoader.py
If Platform code assigns 64-bit BAR address to XHCI,
get the full 64-bit address to access MMIO space.
Behavior is undefined if building IA32 and assigning
64-bit XHCI resources.
> Support 64-bit XHCI MMIO address

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Library/LoaderPerformanceLib/ExtendedFirmwarePerformance.h
- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformanceLib.inf
- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c
FSP could produce a FSP boot performance HOB.
So add the capability to print FSP performance data.
Also add a PcdBootPerformanceMask to enable/disable
boot performance data print.
> Add FSP boot performance data

- BootloaderCommonPkg/Include/Library/LinuxLib.h
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.inf
- PayloadPkg/OsLoader/OsLoader.h
Recent Linux kernel accepts acpi_rsdp=0x.. in kernel command line.
This will make Linux kernel look for ACPI RSDP address in the kernel
commad line first prior to in DMI or F-segment.
> Add 'acpi_rsdp' Linux kernel parameter in cmdline

- BootloaderCorePkg/Tools/ConfigEditor.py
Scrolling mouse in ConfigEditor with Python3 will trigger some
error message. During the scroll unit calculation, it is required
to convert float into int type. This patch fixed it.
> Fix ConfigEditor mouse scroll issue with Python3

- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformanceLib.inf
- BootloaderCommonPkg/Library/ShellLib/CmdFs.c
- BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
In Shell FS after media initialization,  the de-initialization
should be called to free all allocated memory.
> Add media DeInit for Shell FS command

- Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
Current APL StitchIfwi.py does not enable PDR region due to incorrect
XML option. This patch fixed this and also adjusted the default PDR
region to be 4KB to save space.
> [APL] Fix PDR region stitching

- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c
This patch added support for arrow keys on PS2 numeric keypad.
The original code only supports the dedicated arrow keys.
> Add keypad arrow key support

- BootloaderCommonPkg/Library/ElfLib/Elf64.h
- BootloaderCommonPkg/Library/ElfLib/ElfLib.c
- BootloaderCommonPkg/Library/ElfLib/ElfLib.inf
- BootloaderCommonPkg/Library/ElfLib/ElfLibInternal.h
This will load and execute 64-bit ELF image.
- Load image from ELF program header
- 32-bit ELF on IA32 only. 64-bit ELF on X64 only
- TBD: Relocate ELF
> Support 64-bit ELF loading

- Platform/ApollolakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Silicon/ApollolakePkg/Include/Library/BootGuardLib20.h
- Silicon/ApollolakePkg/Include/PlatformData.h
- Silicon/ApollolakePkg/Library/BootGuardLib20/BootGuardLibrary.c
- Silicon/ApollolakePkg/Library/PsdLib/PsdLib.c
- Silicon/CommonSocPkg/Include/Library/BootGuardLib.h
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibCBnT.inf
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibrary.c
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardRegister.h
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
Currently BootGuard library is maintained for     every supported silicon. Most of Slimboot supported     platforms support CBnT standard. Adding to SOC common  for platforms to consume.
Rename BootGuardLib header in APL.  APL follows BootGuard 2.0 and other supported platforms
follows CBnT standad. Its conflicting with CBnT header.
> Add Converged BootGuard Library to Soc common

- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1A/Stage1A.h
- BootloaderCorePkg/Stage1A/Stage1A.inf
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Stage1B/Stage1B.inf
Current container library cannot be used before memory is initialized
because the structure will only be initialized after memory. This
patch moved the initialization into Stage1A so that the library can be
used much earlier. At this moment, the containers loaded before memory
will not be migrated into memory automatically. Instead, the container
structure will be reseted post memory to avoid potential invalid
pointer access.
> Move container initialization earlier

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CommonUtility.py
PublicKey hashes stored in HashStore use hash alg type of
PcdCompSignHash defined with Build config. In container we
support cases where hash type could differ from Sbl default
signing hash.
Adjust the hash algorithm in external KeyHashStore manifest
based on key size. Use SHA256 for size 2K and SHA384 for 3K.
> Adjust hash algorithm used for KEYH based on key size

- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
This will fix MpInit failure on X64 build.
The ApFunc() gets invalid parameters due to mismatched calling convention.
- Add EFIAPI to match calling convention
This can be verified with '-smp' option on QEMU target.
qemu-system-x86_64
-machine q35 -m 256 -nographic -serial mon:stdio
-pflash Outputs/qemu/SlimBootloader.bin
-smp 255
> [X64] Fix MpInit failure

- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/X64/S3Wake.nasm
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
This will support S3 resume path on X64 thru 16-bit waking vector.
- Port WakeUp code from EDKII
- Remove duplicated calls of FindS3Info from CpuInit
- Verified with Yocto on a WHL board
- TBD: 64-bit waking vector with supported OS
> [X64] Support S3 resume on 64-bit build

- BootloaderCommonPkg/Library/ElfLib/ElfLib.c
This will fix invalid offset calculation of ELF program header.
> Fix ELF image loading failure

- BootloaderCommonPkg/Include/Guid/LoaderPlatformDataGuid.h
- BootloaderCommonPkg/Include/Library/DebugLogBufferLib.h
- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
- BootloaderCommonPkg/Library/DebugLogBufferLib/DebugLogBufferLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdDmesg.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- PayloadPkg/OsLoader/OsLoader.h
This will allow debug log buffer to record logs in ring buffer
if the buffer is full.
> Enhance debug log buffer as ring buffer

- BootloaderCommonPkg/Include/Library/PagingLib.h
- BootloaderCommonPkg/Library/PagingLib/PagingLib.c
- BootloaderCommonPkg/Library/PagingLib/PagingMap.c
- BootloaderCorePkg/Library/StageLib/StageLib.c
This patch enhances MapMemoryRegion subroutine to
add PDP entries for mapping addresses > 4GiB.
Only 1:1 mapping is provided for Above4Gb addresses.
And linear addresses are mapped to 1GiB pages.
> Support paging for Above4Gb addresses

- BootloaderCommonPkg/Include/Library/MtrrLib.h
- BootloaderCommonPkg/Library/MtrrLib/MtrrLib.c
- BootloaderCommonPkg/Library/MtrrLib/MtrrLib.inf
- BootloaderCommonPkg/Library/ShellLib/CmdMtrr.c
- BootloaderCorePkg/BootloaderCorePkg.dsc
To help debug boot performance, add MTRR print function.
This function could be invoked multiple times with different
string to know where this MTRR data is printed.
> Add MTRR print function

- BuildLoader.py
A typo. fix for pre-build:after
> Fix a typo in board_build_hook

- BootloaderCommonPkg/Library/TpmLib/Tpm2Capability.c
- BootloaderCommonPkg/Library/TpmLib/Tpm2Help.c
*Safety comparison checks in accordance with TPM2.0 Specification data structures
*Fix comment typos
> TpmLib: Add appropriate safety comparison checks

- BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
- BootloaderCommonPkg/Include/Library/TpmLib.h
- BootloaderCommonPkg/Library/TpmLib/TpmLib.c
- BuildLoader.py
- MdePkg/Include/Register/Intel/Msr/ArchitecturalMsr.h
- PayloadPkg/OsLoader/KeyManagement.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
Platform debug mode is extended to PCR[7]
as part of secure boot policy. Added a bit setting
to LoaderPlatformInfo for payloads to consume and
debug mode is checked in platform code.
ArchitecturalMsr.h ported fom EDK2 repo.
> Measure firmware debugger launch

- BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
- BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformanceLib.inf
This patch added missing C header files in INF file. It fixed the
build warning message.
> Fix build warning for missing header files

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciAri.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciAri.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciCommand.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciCommand.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
This will enable ARI(Alternative Routing-ID Interpretation).
- Controlled by PcdAriSupport (SUPPORT_ARI in BoardConfig)
- Disabled by default
> Add PCI ARI Support

- BootloaderCorePkg/Include/Library/S3SaveRestoreLib.h
- BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c
- BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestoreLib.inf
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch will generate a SW smi on S3 resume path when using
UEFI payload. Handler for this Sw smi in UEFI payload will
program SMRR base and mask for BSP and all AP's.
> Reprogram SMRR base and mask on S3 path for CFL

- Silicon/ApollolakePkg/FspBin/FspBin.inf
- Silicon/CoffeelakePkg/FspBin/FspBin.inf
From https://github.com/IntelFsp/FSP.git
To   https://github.com/intel/FSP.git
> Update Intel FSP git repository URL

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
- BootloaderCorePkg/Library/PciEnumerationLib/PciIov.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciIov.h
- BuildLoader.py
This will support PCI SR-IOV(Single Root I/O Virtualization).
- Controlled by PcdSrIovSupport (SUPPORT_SR_IOV in BoardConfig)
- Disabled by default
> Add PCI SR-IOV Support

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- PayloadPkg/FirmwareUpdate/CmdFwUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch adds generic functionality to process Flash descriptor lock. It follows
Capsule Firmware update flow and interface is updated. Command (CMDI) interface is added
to GenCapsuleFirmware which takes file with command as input.
Sample Command format in text file input,
{FLASHDESCLOCK}
Firmware update lib handler parses high level commands
Specific command process and functionlity would be
performed by platform specific libraries.
> Firmware update in command mode

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/FspApiLib/FspApiLibInternal.h
- BootloaderCorePkg/Library/FspApiLib/FspMemoryInit.c
- BootloaderCorePkg/Library/FspApiLib/FspmApiLib.inf
- BootloaderCorePkg/Library/FspApiLib/Ia32/FspSwitchStack.nasm
- BootloaderCorePkg/Library/FspApiLib/X64/DispatchExecute.c
- BootloaderCorePkg/Library/FspApiLib/X64/FspSwitchStack.nasm
- BuildLoader.py
FSP 2.1 introduced new requirement to use bootloader stack for FSP-M. It
will cause issue for SBL since SBL only uses a small stack in Stage1. To
address this isue, a new PCD PcdFSPMStackTop is added to control the
stack settings for FSP-M.
- If it is 0, it will not switch stack before calling FspMemoryInit API.
- If it is 0xffffffff, it will switch to the new default FSP before
calling FspMemoryInit API.
- For other values, it will switch to the new stack at specified value
before calling FspMemoryInit API.
This PCD will be set automatically by FSP_M_STACK_TOP variable in
BoardConfig.py file.
This code has been tested on UP Extreme board with latest FSP version.
> Allow using bootloader stack to call FspMemoryInit

- BuildLoader.py
SIGN_HASH_TYPE and IPP_HASH_LIB_SUPPORTED_MASK are derived from
_SIGN_HASH. AT times only _SIGN_HASH is configured in
BoardConfig.py which causes in incorrect hash set to
respective PCDs.
> Validate board config hash types in pre-build

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Include/Library/SmbiosInitLib.h
- BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- Platform/QemuBoardPkg/BoardConfig.py
- Default SMBIOS Table initialized when SMBIOS is enabled.
- If required, Every Platform can override platform specific information.
- Enable SMBIOS in Qemu platform
Signed-off-by: Sm NARAYANAN <s.m.narayanan@intel.com>
> SMBIOS Implementation - Adding SMBIOS Default Table.

- BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.c
- BootloaderCorePkg/Stage2/Stage2.c
IA32 UEFI payload uses PE format and X64 UEFI payload uses
PE+ format. So update LitePeCofflib to support both PE and
PE+.
> Support X64 UEFI payload

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/FspApiLib/FspSiliconInit.c
- BootloaderCorePkg/Library/FspApiLib/FspsApiLib.inf
FspsUpd variable made global so that it could be accessed out of
FspSilicon function
Patchable PCD has been created for FspsUpd and Memory pool allocated.
Signed-off-by: Perni <ramesh.chandra.perni@intel.com>
> FspsUpd Updated to Global Variable

- BootloaderCorePkg/Tools/CfgDataStitch.py
- BootloaderCorePkg/Tools/GenContainer.py
TestSigningPrivateKey is defaulted for container
creation in non-layout form and key dir is used.
In CfgDataStitch also TestSigningPrivateKey is
defaulted when key dir is specified.
> Remove TestSigningPrivateKey as default in GenContainer

- BootloaderCommonPkg/Library/SpiBlockIoLib/SpiBlockIoLib.c
- PayloadPkg/OsLoader/LoadImage.c
- Platform/CommonBoardPkg/CfgData/Template_BootOption.dsc
SPI driver is updated to support read linux from
BIOS and PDR region, When boot device SPI is
selected.
Signed-off-by: Mutha <naga.naveen.mutha@intel.com>
> Booting linux from BIOS and PDR region.

- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/SingleSign.py
This patch adds support to key ids in single sign script.
Following pre-requistes to enable usage of key ids,
- Generate required RSA keys as per GenerateKeys.py
- SLIMBOOT_KEY_DIR env variable set to key folder
- Set private key paths to respective ids in
buildloader.py and boardconfigs files
- Update key hash store generation to use respective key ids
Enabling keyids in slimboot would be done subsequent patches.
> Add key ids to single sign script

- BootloaderCorePkg/Tools/GenerateKeys.py
RSA keys are generated based on key ids defined.
User can append signing_keys as per thier requirements.
> Generate default test keys for RSA2048 and RSA3072

- BuildLoader.py
Maintaining individual public hashes for components in external key hash and
considering SHA384 size of hash store increases.
> Increase hash store size allocated in bootloader

- BootloaderCommonPkg/Library/ResetSystemLib/ResetSystemLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
The unnecessary wbinvd() is removed from the common ResetSystemLib,
and it moves to a platform specific reset routine.
> Remove wbinvd() in warm reset

- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
At PciScanBus, a PCI bridge sets PCI Bridge Subordinate Bus to 0xFF
temporary to go thru any PPB. But, a platform has some reserved buses
(ex. 0xFB-0xFF) on PCI hierarchy, and writing 0xFF regardless of
reserved bus ranges causes system hang.
Therefore, PciGetMaxBusNumber will be used for PCI Bridge Subordinate
Bus and it gets the number of buses from PCI Enum Policy to skip the
reserved buses.
> Add PciGetMaxBusNumber for PCI Bridge Subordinate Bus

- .travis.yml
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataStitch.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BootloaderCorePkg/Tools/GenContainer.py
- BootloaderCorePkg/Tools/GenerateKeys.py
- BootloaderCorePkg/Tools/SingleSign.py
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Script/TestCases/firmware_update.py
This patch enables usage of key id for private keys  in slimboot repo. Key ids are configured in
BuildLoader and platform BoardConfig files.  SLIMBOOT_KEY_DIR is set to default folder outside
sblopen. 
Generation of extrenal Keyhash OS key hash to be configured  for QEMU/CGL/APL with appropriate keys.
Update travis for private key generation. GenerateKeys.py is invoked before auromated build gets triggered.
> Enable key ids usage for private keys

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
A PPB PCI_IO_DEVICE instance has BIT31 in its Address field to identify
the device as PPB type. But, the bit is set after scanning the PPB.
This skips PPB type check in PciGetMaxBusNumber() and let a caller
guarantee PPB type check instead of adding a field in PCI_IO_DEVICE
for PPB device.
> Fix invalid PPB check in PciGetMaxBusNumber()

- BootloaderCorePkg/Tools/CfgDataStitch.py
Do not check for key file when KEY ID is
used.
> Handling CFGDATA_KEY_ID in CfgDataStitch

- BootloaderCommonPkg/Library/Ext23Lib/Ext2FsLs.c
- BootloaderCommonPkg/Library/FatLib/FatLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdFs.c
The 'fs' shell command initializes media device with media type info,
but it's not able to initialize another controller of same media type.
Therefore, 'fs init' accepts device instance number.
ex) SATA(0), SATA device instance 1, hwpart 2, swpart 3
fs init 0:1 2 3
Additionally, print file size in unsigned format in 'fs ls'.
> Support media instance in 'fs' shell command

- BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c
Removed Checking for MBR/GPT partitions.
In FindPartitions() identifying memory device
using MediaGetInterfaceType().
Signed-off-by: Mutha <naga.naveen.mutha@intel.com>
> OS loader Optimization for Raw Partition Boot.

- BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
Smbios spec advises to use 'Handle' field in the
Type header to get the type information. This patch
updates the Handle field with the 'Type' value to
be unique. Also, update the Entry Point struct to
report the number of Types implemented currently.
> Fix smbiosview issue on Uefi payload

- Platform/CoffeelakeBoardPkg/Script/GpioDataConfig.py
- Platform/CommonBoardPkg/Tools/GpioDataConvert.py
Gpio convert tool can be common and accepts a
platform specific config file with Group Info
and other settings as input.
Example for CFL/WHL:
Convert gpio.csv into .dsc format:
python
($SBL_ROOT)\SblOpen\Platform\CommonBoardPkg\Tools\GpioDataConvert.py
-if gpio.csv
-of dsc
-cf ($SBL_ROOT)\SblOpen\Platform\CoffeelakeBoardPkg\Script\GpioDataConfig.py
> Make Gpio convert tool common

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataStitch.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BootloaderCorePkg/Tools/GenContainer.py
- BootloaderCorePkg/Tools/GenerateKeys.py
- BootloaderCorePkg/Tools/SingleSign.py
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/BoardConfig.py
- Platform/QemuBoardPkg/Script/TestCases/firmware_update.py
KEY IDs are extended to include key type and sizes.
Platforms can configure corresponding RSA2048 and
RSA3072 KEY IDs. Updated tools to adjust hash type
based on key size.
> Extend Key Ids to include sign and size types.

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfig.py
Add svn field to container generation. SVN need
to be verified while doing container capsule
update. svn is added as end parameter to layout.
Format expected for container creation using '-cl' option for specifying components,
CMDL:Inp\cmdline.txt:$SVN
> Security version number to container

- BootloaderCorePkg/Stage2/Stage2Support.c
Just clear the memory after the HOB is built to avoid Platform
code forgot to init some fields.
> Zero the LOADER_PLATFORM_INFO HOB

- Platform/CoffeelakeBoardPkg/CfgData/CfgDataDef.dsc
- Platform/CoffeelakeBoardPkg/CfgData/Template_CfgData.dsc
This patch fixed incorrect hiding conditions for CFL GPIO pins.
Verified the GPIO configuration options can show/hide depending
on the state of GPIO skip option. It fixed #762.
> [CFL] Incorrect hiding condition for GPIO pin

- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch fixed incorrect GPIO pointer check while appending new GPIO
entries for QEMU.
> [QEMU] Fix GPIO pointer check condition

- BootloaderCommonPkg/Include/Library/ContainerLib.h
- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
Add support for security version check for
container and its components with ones available
in flash for capsule updates.
First check container svn and subsequently its checks components in capsule image and one in flash.
Test= Verified with Qemu platform. Platform tests are in progress.
> Container capsule update svn check

- BootloaderCorePkg/Tools/GenContainer.py
Use default svn while creation of container using command line
when user do not specify svn. Using layout format, user still need
to specify the SVN value.
> Add default svn for command line container creation

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
LocateComponentEntry is modified to locate only container
entry. Additional checks are required at consumer end
for Container entry and CompEntry.
> Check LocateComponentEntry outputs before its consumed

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/CmdFwUpdate.c
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Capsule Command support added for anti rollback
security version number. User can create command
in text file and create capsule with CMDI mode.
{ARBSVNCOMMIT}
Platform APIs would be invoked to do SVN
commit operations by useing HECI interfaces.
> Capsule update command for SVN commit

- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/GenerateKeys.py
- BootloaderCorePkg/Tools/SingleSign.py
Currently this tools creates keys and replaces existing ones.
Added user confirmation before existings ones are replaced.
Selecting all replaces subsequent keys getting generated.
Update OS private key name to OS1_TestKey_Priv_RSA3072.pem.
> Enhancements to GenerateKeys tool

- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/PreOsChecker.c
- PayloadPkg/OsLoader/PreOsChecker.h
The pre-OS checker/payload flow can support more than
just Linux image type launching; there are use cases
for adding multiboot image support to this flow and
there may be others in the future.
> Add Multiboot image support to PreOsChecker flow

- MdePkg/Include/IndustryStandard/LowPowerIdleTable.h
this header file is copied from EDK2 MdePkg and used for low power support.
> Add LowPowerIdleTable header file

- Platform/CommonBoardPkg/CfgData/CfgData_Common.dsc
This patch utilizes the standard CFGHDR_TMPL for GEN_CFG_DATA.
> Use standard template for GEN_CFG_DATA CFGDATA

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch fixed some ACPI issue on APL platform.  When VT-d is
disabled, DMAR table should not be populated in ACPI. This patch
fixed it.
> Add handling for removing certain ACPI table at runtime

- .travis.yml
This patch switched to use python3 for Windows travis build.
> Enable python3 in windows travis build

- BootloaderCorePkg/Tools/SblFwUpdate.py
Added firmware update trigger script for Linux
This script is intended to be called by firmware update
application to trigger firmware update after receiving
update capsule in Linux. This script is provided as a
reference implementation and does the following:
1. Copies the capsule to a known location where SBL
will look for (/boot/efi/FwuImage.bin)
2. Signals FW update to SBL using the WMI interface
provided by SBL. The WMI interface is provided
by the ASL (https://github.com/slimbootloader/slimbootloader
/blob/master/Platform/CommonBoardPkg/AcpiTables/Dsdt/FwuWmi.asl)
and linux kernel driver (https://lkml.org/lkml/2020/4/27/1289)
Reboot command was removed from the script, need to be
included if required.
> Added firmware update trigger script for yocto

- BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c
When a SATA controller has no Ports Implemented
behind it, AHCI mode init returns error even before
allocating buffers for RFis, CommandTable, CommandList.
So, AHCI de-init expects them to be NULL, else any
garbage value for these fields forces the code to do
a FreePool on non-allocated memory.
> Fix AHCI init failure when NumPort=0

- Platform/ApollolakeBoardPkg/BoardConfig.py
Since SBL moved to use YAML rather than DSC. The refrence needs to
be fixed to use yaml files too.
> [APL] Fix reference to DSC file in output image

- BootloaderCorePkg/Tools/BuildUtility.py
This patch will enforce to use python 3.6 or above to build SBL.
Python 2.x is EOL, so drop the support from now.
> Enforce Python3 for SBL build

- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Capsule payload size is checked for 4K block allign
and this restriction is not required. Updates as container
or other components generated capsule size can be
any size.
> Remove check for capsule payload size alignment

- Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/HostBus.asl
This patch enables OS to allocate 64bit PCI resource on APL platform.
It will help resolve some cases where 32bit PCI resource is very
limited.
> [APL] Add MEM64 PCI resource in ACPI

- BootloaderCommonPkg/Include/Library/ConfigDataLib.h
- BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.c
- BootloaderCommonPkg/Library/ShellLib/CmdCdata.c
- BootloaderCorePkg/Stage1A/Stage1A.c
- BootloaderCorePkg/Stage1B/Stage1B.c
- BootloaderCorePkg/Tools/BuildUtility.py
- BootloaderCorePkg/Tools/CfgDataTool.py
- BootloaderCorePkg/Tools/GenCapsuleFirmware.py
- BuildLoader.py
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
Add support for security version check for
config data blob update. SVN is checked
for redundant region which would be updated.
Fixed python warnings in CfgDataTool and GenCapsuleFirmware.
> Configdata firmware update svn check

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
When multiple level of PCI bridges exists on a platform, current
SBL PCI bus library could not find all devices. This issue was
caused by incorrect root bridge bus limit got from the data
structure. This patch fixed this issue.
It also fixed #800.
> Fix PCI enumeration issue with mulitple PCI bridges

- BootloaderCorePkg/Tools/GenExtKeyHashStore.py
This patch adds initial support for external public
key hash store generation in container format.
It uses layout file as input with usage and key file or id.
Common functionality available is resued for KEYH
component generation. Also componet is aligned to 4K size
to use for firmware component update.
> Tool for External Key Hash store generation

- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpvariant.h
- Platform/QemuBoardPkg/CfgData/CfgDataDef.yaml
This patch added the missing general configuration settings for
QEMU platform.  It also addressed a build issue due to non-ascii
chars in the IPP file.
> [QEMU] Add general setting CFG page

- BuildLoader.py
When the Stage FD size is set to be smaller than the FSP component
size, it will produce negative FV size value in DSC file and cause
build exception. This patch added more checks to catch this in the
pre-build process.
> Add error check for Stage FV size

- BootloaderCommonPkg/Include/Library/LinuxLib.h
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
Linux framebuffer screen_info has been extended to support 64bit
address. This patch added extra fields and set the upper 32 bit
for the framebuffer base.
> Fix Linux Framebuffer

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
The following commit 9fcb3a6be1ff5482c3062fc10f17a9e8879d0500
caused a regression on PCI bridge resource allocation. At minimum
the PCI bridge needs to have IO apperture aligned at 4KB and MMIO
apperture aligned at 1MB. The new code did not adjust the
alignment for P2P bridge following this rule.  This patch fixed
this issue.
> Fix P2P bridge alignement issue

- Silicon/CommonSocPkg/Include/Library/BootGuardLib.h
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibrary.c
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardRegister.h
ME PCI device number is platform dependent and
heci base address is provided with common
CBnT GetBootGuardInfo.
For server platforms ME dev is 24.
> Provide HeciBaseAddr with GetBootGuardInfo

- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.inf
- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLibNull.c
- BootloaderCommonPkg/Library/UsbKbLib/UsbKbLibNull.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- PayloadPkg/HelloWorld/HelloWorld.c
- PayloadPkg/HelloWorld/HelloWorld.h
- PayloadPkg/HelloWorld/HelloWorld.inf
- PayloadPkg/Library/DebugPrintErrorLevelLib/DebugPrintErrorLevelLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/PlatformHookLib/PlatformHookLib.c
- PayloadPkg/PayloadPkg.dsc
This patch added an example on how to build a HelloWorld payload
from separate DSC file.
To build a standalone HelloWorld payload, use the following command:
BuildLoader.py build_dsc -p PayloadPkg\PayloadPkg.dsc
> Add HelloWorld payload example

- BootloaderCommonPkg/Include/Library/ConfigDataLib.h
- BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.c
This patch added new function to build a full set of the CFGDATA set
from the memory for current platform. It is useful for exporting
current platform CFGDATA for further processing.
> Add functions to build CFGDATA from database

- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciIov.c
All child devices under a PPB must be in scope of its PPB's decode space.
Therefore, all PPB checks the decode capability and downgrades its child
devices' resources accordingly.
> Check PPB decode space and assign BAR accordingly

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
This patch fixed an issue in firmware update. During the saved capsule
signature verification against the capsule signature to make sure
that the capsule did not change during the reboot, instead of using
length of the signature, used the size of the macro that indicate the
length of the signature.
Verified that firmware update is able to pass on WHL.
> Fix an issue in firmware update

- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
The boot command currently does not allow you
to enter the BootFlags value which is needed
for some boot images.
Also fix a small issue in the FsType selection
code block.
> Add BootFlags selection to 'boot' command

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/GenContainer.py
Generate zero size dummy data in the Component Entry
This patch generate a component binary of zero size if not
already present.
> Check for dummy data in the Component Entry

- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
Check fit entry read from fit entry offset before
its dereferenced.
> Klocwork: Validate fit entry ptr

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Allocate framebuffer resource even if  ENABLE_FRAMEBUFFER_INIT=0
Signed-off-by: Andrey Vinokurtsev <avinok@gmail.com>
> Always set framebuffer cache attribute

- BootloaderCommonPkg/Include/Library/PagingLib.h
- BootloaderCommonPkg/Library/PagingLib/PagingLib.c
- BuildLoader.py
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.inf
A device in boot options can have a BAR greater than 4GB depending on PCI
64Mem/PMem resource policy.
This will allow Payload to build a paging table to cover high MMIO area.
> PayloadPkg: Build paging table to cover high MMIO region

- BootloaderCorePkg/Tools/GenContainer.py
Add svn parameter when component is signed
using command line mode.
> SVN for container component signing

- BuildLoader.py
When HAVE_VERIFIED_BOOT is disabed in the latest SBL, the build will
fail because of missing key hashes. This patch resolved this issue.
> Resolve build issue when verified boot is disabled

- Silicon/CoffeelakePkg/Library/BootGuardLib/BootGuardTpmEventLogLib.c
This patch adds code to check FitEntry for NULL to avoid null pointer
dereference.
Signed-off-by: Praveen <praveen.hodagatta.pranesh@intel.com>
> [CFL] Fix klockwork issue

- IntelFsp2Pkg/Include/FspEas/FspApi.h
- IntelFsp2Pkg/Include/Guid/FspHeaderFile.h
- IntelFsp2Pkg/IntelFsp2Pkg.dsc
- IntelFsp2Pkg/Tools/SplitFspBin.py
There are several definitions that have
been added to the IntelFsp2Pkg in order
to support FSP v2.2. These changes are
backwards compatible with FSP 2.0 and 2.1.
For more info please see the Intel
FSP External Architecture Specification
v2.2 at the site below:
https://www.intel.com/content/www/us/en/intelligent-systems/intel-firmware-support-package/intel-fsp-overview.html
> Sync IntelFsp2Pkg to support FSP 2.2

- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Silicon/CoffeelakePkg/FspBin/FspBin.inf
- Silicon/CoffeelakePkg/Microcode/Microcode.inf
This patch adds following chnages,
- Revise FSP github commit id to use latest FSP 7.0.74.20.
- Add latest Microcode Release Tag.
- starting from FSP 7.0.65.50 FSP shares same stack with Bootloader
to run FSP-M, hence adjust stack using  FSP_M_STACK_TOP variable in
BoardConfig.py file.
Test: Build and Boot test on CFL,WHL platforms and verified successfull
boot till yocto OS.
> [CFL] Use Latest FSP and microcode release

- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcphash.h
This patch fixed GCC x64 Crypto boot issue. The issue was related
to the calling convention. "EFIAPI" was missing for several ASM
provided functions.
> Fix GCC x64 Crypto boot issue

- BootloaderCommonPkg/Include/Library/CryptoLib.h
- BootloaderCommonPkg/Include/Library/SecureBootLib.h
- BootloaderCommonPkg/Library/IppCryptoLib/sha256.c
- BootloaderCommonPkg/Library/IppCryptoLib/sha384.c
- BootloaderCommonPkg/Library/IppCryptoLib/sm3.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
- BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
Added EFIAPI to missing APIs in Secureboot library interfaces.
> Naming convention update for secureboot and IppLibs

- PayloadPkg/OsLoader/OsLoader.c
This patch add code to check OsBootOptionList for NULL to avoid
NULL pointer dereference.
> Fix klockwork scanning issue

- BootloaderCorePkg/Stage2/Stage2.c
EndOfStage callback is missing in S3 boot flow.
so just add it in case platform need do something.
> Add EndOfStage callback in S3 flow

- BootloaderCorePkg/Tools/ConfigEditor.py
- BootloaderCorePkg/Tools/GenCfgData.py
- Platform/ApollolakeBoardPkg/CfgData/CfgData_CapsuleInformation.yaml
- Platform/ApollolakeBoardPkg/CfgData/Template_PcieRp.yaml
- Platform/CoffeelakeBoardPkg/CfgData/CfgData_CapsuleInformation.yaml
- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Silicon.yaml
- Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml
- Platform/QemuBoardPkg/CfgData/CfgData_CapsuleInformation.yaml
Current ConfigEditor relies on the original input data format in YAML
to determine how to represent data in GUI. For example, if the data
value is HEX in YAML, then the data will be displayed in HEX format.
This patch switched to use the specified format type to reformat the
value string so that the display is always consistent with the required
format type.
It fixed #844.
> Represent data in required format in ConfigEditor

- Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml
The SATA and USB HwPart usage for BootOption
config data varies from the other block device
types. This patch adds clarification to explain
the meaning of HwPart for these 2 media types
respectively.
> Clarify SATA and USB HwPart usage

- BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
- BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
Currently SBL library has GetDeviceAddr() to get the device
address based on device type and instance. This patch adds
SetDeviceAddr() to update a given device type and address so
that platform could update the device table dynamically.
> Add SetDeviceAddr() for device table update

- .travis.yml
This patch enabled CML & CMLV test script for travis build.
> Enable cml & cmlv boot options in travis

- BuildLoader.py
This patch added support to allow platform to add specific include
folders for the build. All include paths will be relative to the
SBL $(WORKSPACE).
To eanable this feature, please add similar definitions as below
into BoardConfig.py. For example,
self._EXTRA_INC_PATH = ['Silicon/QemuSocPkg/Include/Fsp']
> Enable extra including path for build

- BuildLoader.py
Currently the build tool will always find FSP binaries from
Silicon'\self._board.SILICON_PKG_NAME\FspBin folder.
This patch enhance the build tool to support to get FSP from
_FSP_PATH_NAME. If _FSP_PATH_NAME is not specified, the default
behavior is same with current build.
If user wants to use a different one, they could override it
in BoardConfig.py as below:
self._FSP_PATH_NAME  = 'Silicon/Fsp'
> Enhance FSP build path support

- BootloaderCommonPkg/Include/Library/ThunkLib.h
- BootloaderCommonPkg/Library/MultibootLib/MultibootLib.inf
- BootloaderCommonPkg/Library/MultibootLib/X64/BootJump.c
- BootloaderCommonPkg/Library/MultibootLib/X64/MultibootJump.nasm
- BootloaderCommonPkg/Library/ThunkLib/Ia32/DispatchExecute.c
- BootloaderCommonPkg/Library/ThunkLib/ThunkLib.inf
- BootloaderCommonPkg/Library/ThunkLib/X64/DispatchExecute.c
- BootloaderCommonPkg/Library/ThunkLib/X64/Thunk64To32.nasm
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/FspApiLib/FspApiLibInternal.h
- BootloaderCorePkg/Library/FspApiLib/FspmApiLib.inf
- BootloaderCorePkg/Library/FspApiLib/FspsApiLib.inf
During X64 enabling, there was a pending task to enable 32bit
MultiBoot support. It is not implemented.  This patch added the
support to allow X64 SBL to boot a 32bit MB image through thunking.
As part of this patch, the ThunkLib is separated from the FspApiLib
so that it can be shared by other component.
> Add MultiBoot support for X64 build

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
This will fix the ucode repo checkout issue on 'cfl' target.
FYI, here are simple steps to reproduce.
1) Build 'apl' target first
2) Build 'cfl' target -> fails to checkout ucode repo
> [CFL] Fix the ucode checkout issue

- BootloaderCommonPkg/Include/Service/HeciService.h
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/ApollolakePkg/Library/MeChipsetLib/MeChipsetLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.inf
- Silicon/CommonSocPkg/Include/Library/HeciLib.h
- Silicon/CommonSocPkg/Library/HeciLib/HeciCore.c
- Silicon/CommonSocPkg/Library/MeChipsetLib/MeChipsetLib.c
This patch expanded HECI service to include send, receive and
reset interface functions. This helps in making firmwareupdatelib.c
and PSDlib common across platforms.
> Expand HECI service to add more API's

- BootloaderCommonPkg/Library/IppCryptoLib/auth/owncp.h
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha256ca.c
- BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsm3ca.c
- BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressPassthru.c
- BootloaderCommonPkg/Library/ShellLib/CmdPerf.c
- BootloaderCommonPkg/Library/TimeStampLib/TimeStampLib.c
- BootloaderCorePkg/Library/DebugDataLib/DebugDataLib.c
- PayloadPkg/OsLoader/BootParameters.c
- Platform/QemuBoardPkg/BoardConfig.py
This patch fixed NOOPT build failure for QEMU.
It fixed #871.
> [QEMU] Fix NOOPT build failure

- BootloaderCommonPkg/Include/Library/LiteFvLib.h
- BootloaderCommonPkg/Include/Library/LitePeCoffLib.h
- BootloaderCommonPkg/Include/Library/ThunkLib.h
- BootloaderCommonPkg/Library/LiteFvLib/FvLib.c
- BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.c
- BootloaderCommonPkg/Library/ThunkLib/Ia32/DispatchExecute.c
- BootloaderCommonPkg/Library/ThunkLib/X64/DispatchExecute.c
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2.inf
- PayloadPkg/OsLoader/OsLoader.c
Since SBL could be built into either x86 or x64 mode, and the payload
can also be x86 or x64 mode. When mixed modes are used, it is required
to switch to proper mode first before calling into payload entrypoint.
This patch added this check to switch to required mode before calling
into payload entry point.
> Enable mixed payload mode calling

- Silicon/CommonSocPkg/Library/SpiFlashLib/SpiFlashLib.c
Check for Write access permission during
Write/Erase Flash cycles for BIOS/FLAHD regions.
> Fix permission check during Spi access

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/ApollolakePkg/Library/GpioLib/GpioLib.c
- Silicon/ApollolakePkg/Library/SocInfoLib/SocInfoLib.c
This patch fixed link error for APL NOOPT build due to compiler
intrinsics functions. However, due to APL hardware requirements,
it is not feasible to fit NOOPT build into real flash. This
patch will not fix the NOOPT build error caused by code size issue.
For example, the following error might still occur for APL NOOPT
build:
Invalid the required fv image size 0xe3b0 exceeds the set fv image
size 0x6000
The APL SOC requires Stage1A to fit into 32KB. Since FSP-T will take
8KB, it only gives 24KB for SBL Stage1A code. NOOPT build will create
about 56KB for Stage1A, and it is impossible to fit into the layout.
> [APL] Fix compiler intrinsics link error for NOOPT build

- BootloaderCorePkg/Tools/ConfigEditor.py
In ConfigEditor, while scrolling page using mouse middle wheel,
the Combo configuration items will change its default value. It
is because Combo control will bind MouseWheel event by default.
To address it, added code to unbind it explicitly.
It fixed #878.
> Fix default value change issue in ConfigEditor

- BootloaderCorePkg/Tools/ConfigEditor.py
- BootloaderCorePkg/Tools/GenCfgData.py
Current ConfigEditor produces the same result for
"Save full cfg data" vs "save cfg changes".  This patch provided
a fix for it.  It fixed #882.
> Fix save full delta file issue in ConfigEditor

- Silicon/CommonSocPkg/Include/Library/HeciLib.h
- Silicon/CommonSocPkg/Library/HeciLib/HeciLib.c
- Silicon/CommonSocPkg/Library/HeciLib/HeciRegs.h
o This is a common HECI PCI config space across platforms which
return STS6 space.
o HeciGetManufactureMode() returns if the platform is in debug mode
or production (EOM)
Signed-off-by: Divneil Rai Wadhawan <divneil.r.wadhawan@intel.com>
> [CommonSocPkg]: Add HeciGetManufactureMode() to get EOM Status

- BootloaderCorePkg/Tools/GenCfgData.py
Using ConfigEditor to save back DLT changes, it will produce two
PlatformId lines in DLT file. This patch removed the extra line.
> Fix duplicated PlatformId in DLT file

- BootloaderCorePkg/Stage2/Stage2Support.c
This will report pcie config space region as a reserved memory in e820
and let Linux use the PCI MMCONFIG which has bus range information.
If it is not reserved, the pcie config space region will be freed/available
for PCI devices.
> Reserve Pcie config space region as a reserved memory

- Silicon/CometlakevPkg/Include/Register/PchRegsPmc.h
Fix register R_PMC_PWRM_GPIO_CFG to the correct
value: 0x1920.
> [CMLV] Fix PMC register offset value

- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch addressed an issue while detecting the
BOM ID for Upx platform which is causing the MRC
to fail.
> [CFL] Fix BOM ID detection for Upx platform.

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
In 64-bit operation, some PCI devices have high mmio BARs,
but 32-bit FSP can only access 32-bit memory space.
This introduces and additional PCI resource downgrade option
to downgrade all PCI devices under Bus-0.
- self._PCI_ENUM_DOWNGRADE_BUS0 = 1
Force to have 32-bit BAR for all Bus-0 devices
> Add PCI resource downgrade option for all Bus-0 devices

- BaseTools/Conf/tools_def.template
* Enable frame pointers (via /Oy-) for 32-bit modules. From the
documentation: "If you specify a debug compiler option (/Z7, /Zi, /ZI),
we recommend that you specify the /Oy- option after any other
optimization compiler options."
* /O1b2s is equivaled to /O1 (/Ob2 and /Os are included in /O1)
* /Z7 for debug info is obsolete, replace with /Zi
Signed-off-by: Mircea Gherzan <mircea.gherzan@intel.com>
> Fix the compiler flags for MSVC 2017 and 2019

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BuildLoader.py
Microcode module locates in different place.
so each platform could specify the path by
MICROCODE_INF_FILE in BoardConfig.py.
By default, it uses the same path if there
is no MICROCODE_INF_FILE defined in platform.
> Update Microcode path to support customization

- BuildLoader.py
Use the default path only when MICROCODE_INF_FILE
is not defined in platform board. Currently it will
override the one defined in platform.
> Fix MicroCode path

- IntelFsp2Pkg/Tools/SplitFspBin.py
Current FSP rebasing script SplitFspBin.py has support for both
PE32 and PE32+ image formats. However, while updating the ImageBase
field in the image header, it always assumed the ImageBase field is
32bit long. Since PE32+ image format defined ImageBase as 64bit,
the current script will only update the lower 32bit value and leave
the upper 32bit untouched. It does not work well for PE32+ image
that requires update in the upper 32bit ImageBase field. The
expected behavior is to update the full 64bit field. This patch
implemented this fix.
> IntelFsp2Pkg: Fix FSP binary rebasing issue for PE32+ image

- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/BootloaderCorePkg.fdf
- BuildLoader.py
In current SBL BootloaderCorePkg dsc and fdf files, it contains
hard-coded INF file path for SOC or board, such as ACPI INF
file and SOC/Board init library INF file. It makes it hard for
platform to provide its own overriding using different path.
This patch addressed this issue by allowing platform to override
the default paths in BoardConfig.py.
> Allow platform to override SOC or board specific inf files

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
- BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.inf
- BuildLoader.py
Current SBL code will build pointers in E/F segment for ACPI
and SMBIOS table. On some platforms, E/F segment is not supported.
So a new configuration ENABLE_LEGACY_EF_SEG is added.  When
it is enabled, SBL will not use legacy E/F segment memory.
> Add legacy EF segment memory config

- BootloaderCommonPkg/Include/Library/LinuxLib.h
- BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c
For UEFI Linux boot, a new parameter was added into BOOT_PARAMS.
This patch added this parameter support so that ACPI base can
be passed directly to kernel.
> Add ACPI RSDP to Linux BOOT_PARAMS

- PayloadPkg/OsLoader/LoadImage.c
Current SBL used AllocatePool to allocae space for Linux files
including Kernel and InitRd. However, since InitRd is required to
be aligned at page boundary, it needs to use AllocatePages instead.
This patch addressed this issue. It fixed #908.
> Fix InitRd image alignment issue

- PayloadPkg/OsLoader/BootConfig.c
- PayloadPkg/OsLoader/LoadImage.c
CentOS live CD iso image has different path for grub.cfg file. It
also used "linuxefi" and "initrdefi" for keywords. This patch added
support for it. With this patch, verified it can boot to CentOS
live-cd on APL platform.
> Enhance grub.cfg to support CentOS

- .azurepipelines/azure-pipelines.yml
This patch enabled Windows build targes for APL, CFL, CML, CMLv
and QEMU.
> Enable Windows build target for Azure Pipelines

- BaseTools/Conf/tools_def.template
Removed the Oy- flag for DEBUG_VS2017_IA32_CC_FLAGS
which was introduced recently in commit 9f3d2b5fc39b45f34ce22d462b25d24c1d559ed8
it causes hang when calculating SHA384 by CryptoLib call by SecureBootLib driver
Signed-off-by: Chin Keong Ang <chin.keong.ang@intel.com>
> Fix hang at STAGE1B when compile with MSVC 2017 for IA32 Debug

- BootloaderCorePkg/Tools/ConfigEditor.py
User experience improvement:
If there is no yaml found in current directory
then default to start browsing at platform directory
Signed-off-by: Chin Keong Ang <chin.keong.ang@intel.com>
> Config Editor: Update default yaml file search dir

- .azurepipelines/azure-pipelines.yml
The current PatchCheck does not work properly in Azure Pipelines.
Synced up with EDK2 to update script to address this issue.
> Enable PatchCheck script for Azure Pipelines

- .azurepipelines/azure-pipelines.yml
The master build trigger does not have PullRequest variable.
This will allow PatchCheck to be run only in PR condition.
> Allow PatchCheck only in PR condition

- BootloaderCommonPkg/Include/Library/GraphicsLib.h
- BootloaderCommonPkg/Library/GraphicsLib/BmpFormat.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiBgrt.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLibInternal.h
This patch enabled ACPI BGRT support. It is used to pass splash
display information from bootloader to payload and OS.
> Enable ACPI BGRT table support

- BuildLoader.py
This patch fixed one issue on the WORKSPACE path. The current
script used "realpath" instead of "abspath".  It will cause issue
if "subst" is used for the drive path since it returns the real
path before "subst".  The expected behavior is to use the
path after "subst".
> Fix path issue for WORKSPACE variable

- Platform/CoffeelakeBoardPkg/BoardConfig.py
Current CFL SBL build with DEBUG FSP will fail due to size issue.
This patch fixed this issue by adjusting size properly when DEBUG
FSP is used.
> [CFL] Fix DEBUG FSP build error

- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
Since the EXT library we have in OS Loader
supports 2, 3, and 4 it will help to reduce
confusion for users who have noticed that
only 2 and 3 are currently printed.
> Add EXT4 to print in 'boot' command

- Silicon/ApollolakePkg/Library/MeChipsetLib/MeChipsetLib.c
This will fix an invalid data size of HECI_REQ_IFWI_PREPARE_FOR_UPDATE
command. Due to the invalid data sent, CSE rejected the IFWI prepare
update request and it caused infinite reboot issue.
The Issue #925 will be addressed with this patch.
> [APL] Fix the infinite reboot issue in firmware update

- BootloaderCommonPkg/Include/Guid/PciRootBridgeInfoGuid.h
- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
This introduces a new PCD 'PcdPciResAllocTableBase' to allow a platform
to provide its specific PCI resource allocation pool at runtime.
PCI Enumerator will allocate required resources in the range.
If the PCD is not provided, a default range will be used.
> [PCI] Platform builds PCI Resource Allocation Table

- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/SingleSign.py
- BuildLoader.py
Openssl 1.1.1 is an installable and it creates
openssl.exe in a bin folder.
default slimboot path: c:\Openssl\bin\openssl.exe
Download location: https://slproweb.com/products/Win32OpenSSL.html
Added support to populate OPENSSL_PATH
from bin dir incase its available.
> Openssl 1.1.1i tool support

- .azurepipelines/azure-pipelines.yml
- BootloaderCorePkg/Tools/CommonUtility.py
To make SBL scripts/tools more OS-agnostic the
lz4 (de)compression module can be used instead of
relying on the BaseTools LZ4 package/executable.
Need to update the azure pipeline to install
the python lz4 module before running the builds.
TEST=Confirmed that the python lz4.block.compress
routine is compatible with Lz4DecompressLib
during SBL runtime to decompress LZ4 binaries.
> Use Python lz4 module for LZ4

- .azurepipelines/azure-pipelines.yml
- BootloaderCorePkg/Tools/CommonUtility.py
To avoid any dependency on non-standard python modules
it is preferred to make the binary Lz4 compression the
default flow and try the python module as a backup. Also
recommend to use a known working version of the lz4
python module, 3.1.1.
> Make Python lz4 module optional

- Silicon/ApollolakePkg/Library/PsdLib/PsdLib.c
- Silicon/CoffeelakePkg/Library/PsdLib/PsdLib.c
- Silicon/CommonSocPkg/Include/Library/HeciLib.h
- Silicon/CommonSocPkg/Include/MeBiosPayloadDataCommon.h
- Silicon/CommonSocPkg/Library/HeciLib/HeciLib.c
- Silicon/CommonSocPkg/Library/HeciLib/HeciLib.inf
o MBP is platform specific data which may be different for derivative
platforms, so, the handling is moved back to platform code
Signed-off-by: Divneil Rai Wadhawan <divneil.r.wadhawan@intel.com>
> [CommonSocPkg]: Remove ME BIOS Payload (MBP) handling from HeciLib

- BootloaderCorePkg/Tools/CommonUtility.py
- BuildLoader.py
- Platform/ApollolakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/BoardConfig.py
- Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
- Platform/CometlakeBoardPkg/BoardConfig.py
- Platform/CometlakeBoardPkg/Script/StitchIfwi.py
- Platform/CometlakevBoardPkg/BoardConfig.py
- Platform/CometlakevBoardPkg/Script/StitchIfwi.py
- Platform/CommonBoardPkg/Tools/GpioDataConvert.py
- Platform/QemuBoardPkg/BoardConfig.py
Python 3.4 and above have deprecated imp module in favor of
importlib.  This patch removed imp module usage from SBL, and
used importlib instead.
> Removed deprecated python imp module usage

- BootloaderCorePkg/Tools/CommonUtility.py
run_process is used several places. Sometime
the extension name is not given for windows build.
In this case, if same file without file extension
exist (e.g. fit and fit.exe), then fit will be used
for windows build. It is not expected, so this patch
will add the missing .exe extension for this case.
> Add '.exe' extension if missing for windows build

- BootloaderCorePkg/Library/PciEnumerationLib/PciIov.c
ProgramBar() routine uses 'OrgBarType' field to
determine BarType. So, if a BarType is valid, copy
it to OrgBarType for VF also.
> Update correct BarType field for VF Bar program

- BootloaderCommonPkg/Library/TpmLib/TpmLib.c
- BootloaderCommonPkg/Library/TpmLib/TpmLib.inf
- Platform/CometlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/CometlakevBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Silicon/CommonSocPkg/Include/Library/BootGuardLib.h
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibrary.c
- Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardRegister.h
As per TCG spec, if a Tpm2Startup(TPM_SU_STATE) fails during
S3 resume, a host reset should be done.
When BootGuard is enabled, ACM will notify of this failure via Bit46 in
BootGuardBootStatus register.
Signed-off-by: Sachin Agrawal <sachin.agrawal@intel.com>
> Handle TPMStartup error during S3 resume

- Silicon/CometlakevPkg/Include/Register/PchRegsPmc.h
This reverts commit b53de73b5304e89c161dd37f2e9ee374ab832150.
Revert the particular commit to solve Gpio error.
> Revert "[CMLV] Fix PMC register offset value (#887)"

- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
WHL CRB board is configured to boot different payload based on GPIO pin
status, which is not working currenly.
this patch ensures to boot to Osloader payload when PayloadSelGpioData=1
otherwise boot to UEFI payload.
TEST= Boot test on WHL CRB and verified board able to switch between
OSloader & UEFI payload based on DIP switch R4H1B_4 status.
> [CFL]Fix payload selection issue

- BootloaderCorePkg/Include/Library/GpioLib.h
- Silicon/CommonSocPkg/Include/GpioLibConfig.h
- Silicon/CommonSocPkg/Include/Library/GpioPlatformLib.h
- Silicon/CommonSocPkg/Include/Library/GpioSocLib.h
- Silicon/CommonSocPkg/Library/GpioLib/GpioHelpersLib.c
- Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
- Silicon/CommonSocPkg/Library/GpioLib/GpioLib.c
- Silicon/CommonSocPkg/Library/GpioLib/GpioLib.inf
- Silicon/CommonSocPkg/Library/GpioLib/GpioLibInternal.h
This patch adds a common GpioLib that all platforms
can link to. Common GpioLib requires platforms to
implement the GpioInfoLib to provide platform-specific
information like GroupInfo etc.
> Add common GpioLib

- Silicon/CommonSocPkg/Include/GpioLibConfig.h
- Silicon/CommonSocPkg/Include/Library/GpioSocLib.h
- Silicon/CommonSocPkg/Library/GpioLib/GpioLib.c
Adding the EFIAPI modifier to make sure all lib
function calls follow correct calling convention.
> Add missing EFIAPI in GpioSocLib.h

- BootloaderCommonPkg/Include/Library/GraphicsLib.h
- BootloaderCommonPkg/Library/GraphicsLib/BmpFormat.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiBgrt.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Stage2/Stage2Support.c
BGRT can be used by bootloader to pass logo to OS. But BGRT can
only support 24bit or 32bit BMP format. If the bootloader uses
other bit format or indexed color format, the image has to be
converted before passing it to BGRT. This patch added support
to convert other BMP image format into 32bit format required by
BGRT.
This has been tested with Windows on Leafhill board. The SBL
logo was dispalyed properly while booting Windows.
> Enhance BGRT BMP support for logo display

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
Different projects might use different repo to get binaries.
or different project might be built at same time. so change
to use different workspace for different project to avoid
potential conflict.
> use different workspace to prepare binaries

- BootloaderCorePkg/Tools/CommonUtility.py
- BootloaderCorePkg/Tools/SingleSign.py
- Platform/CometlakeBoardPkg/Script/StitchIfwi.py
- Platform/CometlakevBoardPkg/Script/StitchIfwi.py
- Platform/TigerlakeBoardPkg/Script/BtgSign.py
Tools as MEU used for signing and generating key manifests
expects to pass abosulte openssl paths. Updating
get_openssl_path to return paths for linux cases.
> Update get_openssl_path to return absoulte path

- BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
- BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
- PayloadPkg/Include/PreOsHeader.h
- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/KeyManagement.c
- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
- PayloadPkg/OsLoader/OsLoader.inf
- PayloadPkg/OsLoader/PreOsSupport.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/SeedSupport.c
SBL support to load PreOS and normal OS in a single boot option.
This patch tries to standardize the PreOS support.
The PreOS could be TrustyOS, PreOsChecker or others.
As long as PreOS flag is set in boot option, SBL will load and
boot PreOS before normal OS. If the preOS has specific requirement,
it could be addressed using PreOS image type.
> Enhance PreOS support

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakevPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
During firmware update svn check for SBL region, Current code
assumes that Stage1A base does not change, because of this when
Stage1A base changed in capsule image, getting svn version from
the capsule fails and firmware update is failing.
This patch addressed above issue by reading stage1A base from
capsule image, this way even if stage1A base changes, code will
be able to read it and get svn version from capsule.
> Get SVN ver from capsule during firmware update

- BootloaderCommonPkg/Library/ThunkLib/Ia32/DispatchExecute.c
Current Execute32BitCode() passes in 64bit arguments into stack.
It should use 32bit arguments instead according to 32bit calling
convention. This patch fixed this issue.
> Fix 32bit payload calling convention

- BuildLoader.py
- Platform/QemuBoardPkg/BoardConfigOverride.py
This will allow inherited BoardConfig from the existing one
in the same BoardPkg. It will be useful when a new BoardConfig
has very minimum difference from the existing one.
See Platform/QemuBoardPkg/BoardConfigOverride.py as a reference.
> [BoardConfig] Support Inherited BoardConfig

- BootloaderCommonPkg/Library/PagingLib/PagingLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
In 32 bit SBL, when PCI PMEM64 exists, the OsLoader will hang
during boot in CreateIdentityMappingPageTables().  The function
is inteneded to be used in X64 mode only, and cannot handle
32bit well. So OsLoader should not call it for 32 bit build.
This patch also zeroed the allcated memory to ensure the unused
entries are all 0.
> Fix paging issue when PCI PMEM64 resource exists

- Silicon/CoffeelakePkg/Library/PsdLib/PsdLib.c
- Silicon/CometlakePkg/Library/PsdLib/PsdLib.c
- Silicon/CometlakevPkg/Library/PsdLib/PsdLib.c
- Silicon/ElkhartlakePkg/Library/PsdLib/PsdLib.c
- Silicon/TigerlakePkg/Library/PsdLib/PsdLib.c
CFL, CML, EHL, TGL platforms are using PSD version 0.3.
as per PSD Spec v0.3 secureboot status indication as ber below,
000 – Secure boot is Disabled
001 – UEFI Secure boot is enabled
010 – Boot Guard is Enabled
100 – Bootloader Verified boot is Enabled
> Fix Secureboot status in PSD

- Silicon/CommonSocPkg/Library/PchSpiLib/PchSpiLib.c
1. Disable EISS if BLE is not set in DisableBiosWriteProtect()
2. Enable EISS if BLE is not set in EnableBiosWriteProtect()
> Enable/Disable EISS in CommonSocPkg

- .azurepipelines/azure-pipelines.yml
- Platform/TigerlakeBoardPkg/BoardConfig.py
This patch enabled auto build for TGL Azure Pipelines.
Only Windows build is enabled. GCC build has IASL issue.
> Enable Azure Pipeline build for TGL

- BootloaderCommonPkg/Library/PagingLib/PagingLib.c
- PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
This will fix invalid PDP/PDE generation with PAE 2MB Pages,
and high bit calculation at PayloadEntry additionally.
> Fix a bug in PAE 2MB paging

- .azurepipelines/azure-pipelines.yml
This patch moves the Linux build environment into latest Ubuntu
20.04 and updated to use latest ACPICA. All GCC build now is
enabled.
> Enable Azure Pipelines with Ubuntu-20.04

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Current PCI resource PCD bases are defined as fixed type. It
makes it impossible to dynamically adjust the base at runtime.
This patch changed it to be module patchable so that platform
can update when required.
> Change PCI resource PCD to patchable type

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakevPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/ElkhartlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch fixed a failure occured during CSME firmware
update. CSME firmware update library expects PCI read buffer
with a specific format, there is mismatch with input and output
parameter with the current code. Added a wrapper function
with the expected format to fix the failure.
> Fix failure during csme firmware update

- Platform/TigerlakeBoardPkg/BoardConfig.py
Since image form Linux build is a little bigger,
so enlarge the payload region size to fix linux build.
> [TGL] Enlarge Payload region Size

- Platform/CoffeelakeBoardPkg/AcpiTables/AcpiTables.inf
- Platform/CoffeelakeBoardPkg/AcpiTables/Ssdt/TpmSsdt.asl
similar to CML, CFL also uses both IOB2 & IOB3 ports to pass the info and generate an SMI.
where as common code ACPI implementation uses only IOB2, hence TPM2 ACPI tables are ported
from CML platforms. This patch fixes physical presence query and TPM clear issue on windows.
TEST: boot to windows on CFL-H platform and verified TPM physical presence and TPM clear command is
successfull.
> [CFL] Add TPM2 ACPI table

- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/HdaVerbTable.h
This patches fixes the audio record issue using onboard 3mm jack.
TEST= booted to windows on both CFL-S & CFL-H board and verified
Audio playback and record is working using onboard 3mm jack.
> [CFL] Fix audio record issue

- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2.h
- BootloaderCorePkg/Stage2/Stage2Support.c
In some cases FSP does not support GFX and does not produce
GFX hob. But platform will be able to initialize its GFX after
PCI enumeration. This patch allows splash to be displayed post
PCI if the splash has not been displayed yet.
> Add splash support post PCI enumeration

- BootloaderCorePkg/Include/Library/FspSupportLib.h
- BootloaderCorePkg/Library/FspSupportLib/FspSupportLib.c
- Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch will display FSP HOBs. It will help the debug when FSP
produce incomplete HOBs.
> Add FSP HOB print function

- Silicon/CommonSocPkg/Library/SpiFlashLib/SpiFlashLib.c
The RegionPermission doesn't usually represent the current state of
the Region. There is a need to re-read the permission bit for each
read/write. There by making the variable accurately represents the
HW status.
Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>
> commonSocPkg: SpiFlashLib: Permissions bit read per read/write

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
This introduces an additional PCI Enumeration option.
- self._PCI_ENUM_FLAG_ALLOC_PMEM_FIRST
By deafult, the option will allocate PCI resource by ascending order
(MEM32->PMEM32->MEM64->PMEM64). If it's set to 1, by reversed order.
> [PCI] Add an option to allocate PCI PMEM resource first

- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
during CSME firmware update process, CSME update library throw error
"Could not access PCI device".this patch fixes this issue by adding
back "PciReadBuffer".
TEST=Verified CSME FWU on CFL-H & WHL platforms.
> [CFL] Fix CSME firmware update failure

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakevPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/ElkhartlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch fixed a failure in firmware update that
occur during SBL version check. Current code assume
that the SBL layout does not change between the existing
firmware and the capsule, when the layout change, stage1A
address change and this is causing error while obtaining
the firmware version.
Code is modified to use the last 4 bytes of the SBL region
which contain Stage1A FV address and this is used to obtain
the version information.
Signed-off-by: Raghava <raghava.gudla@intel.com>
> Fix firmware update failure during sbl svn check

- BootloaderCorePkg/Stage2/Stage2Support.c
In some cases Bootloader will build GFX HOB. This patch updated
SBL to check the bootloader GFX HOB first before building a new
GFX HOB from FSP. This is to avoid duplicated GFX HOB to be
generated in bootloader HOB.
> Avoid build duplicated GFX HOB

- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
- BootloaderCorePkg/Stage2/Stage2.c
- BootloaderCorePkg/Stage2/Stage2Support.c
There is request to utilize MP in OsLoader. To support it, it is
desired to delay MP init done signal to the end of the OsLoader.
This patch moved the MP init done signal into board ReadyToBoot
notification so that MP is still alive in OsLoader phase.
> Delay MP init done for OsLoader payload

- Silicon/CoffeelakePkg/Library/MeFwUpdateLib/MeFwUpdateLib.inf
This patch adds support to build CSME firmware update driver.
BUILD_CSME_UPDATE_DRIVER in BoardConfig.py must set 1 to build csme FWU
driver.
> [CFL] Add CSME FWU driver build support

- Platform/CometlakeBoardPkg/Script/StitchIfwi.py
- Platform/CometlakevBoardPkg/Script/StitchIfwi.py
This Patch fixes below error,
"ModuleNotFoundError: No module named 'defusedxml'"
> [CML] Fix StitchIfwi script error

- Platform/ElkhartlakeBoardPkg/AcpiTables/AcpiTables.inf
- Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Power.yaml
- Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiTable.c
- Silicon/ElkhartlakePkg/Include/Register/PmcRegs.h
Resolved yocto hang issue after booted into OS
for non Fusa sku.
Enabled s0ix for yocto and windows.
> [EHL] Fix yocto hang issue and s0ix enable

- BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
- Silicon/QemuSocPkg/FspBin/FspBin.inf
- Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
This patch changed QEMU FSP to use INF file to provide commit id.
It also synced up to the latest EDK2 stable tag edk2-stable202011.
> Update QEMU FSP build to latest EDK2

- Platform/ElkhartlakeBoardPkg/BoardConfig.py
Add LOADER_RSVD_MEM_SIZE in BoardConfig
to fix UEFI payload debug boot ASSERT
error.
> [EHL] Fix UEFI Payload debug boot issue

- BootloaderCommonPkg/Include/Guid/MpCpuTaskInfoHob.h
- BootloaderCorePkg/Include/Library/MpInitLib.h
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/MpInitLibInternal.h
The ApDataPtr->CProcedure was wrongly updated in previous patch.
This patch fixed it and CPU task name from CProcedure to TaskFunc
to avoid confusion.
> Fix the MP hang issue

- Silicon/CommonSocPkg/Include/Library/GpioPlatformLib.h
- Silicon/CommonSocPkg/Library/GpioLib/GpioLib.c
- Silicon/TigerlakePchPkg/Library/GpioPlatformLib/GpioPlatformLib.c
Certain platforms can't support GpioLockUnlock, so let
them use PrivateControlWrite when they do an SBI exec.
Also updated dependent platform.
> Enhance GpioWriteLockReg in common GpioLib

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCommonPkg/Include/Library/LocalApicLib.h
- BootloaderCommonPkg/Include/Register/Intel/ArchitecturalMsr.h
- BootloaderCommonPkg/Include/Register/Intel/Cpuid.h
- BootloaderCommonPkg/Include/Register/Intel/LocalApic.h
- BootloaderCommonPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c
- BootloaderCommonPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.inf
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf
- BuildLoader.py
This patch added X2APIC support. It is to enable the case when
APIC ID is greater than 255. This patch only handle core wakeup
portion. Platform still needs to handle ACPI related changes for
X2APIC.
X2APIC lib is backward compatible with XAPIC lib. So there is no
need to use XAPIC lib anymore.
> Add CPU X2APIC support

- BootloaderCorePkg/Stage1A/Ia32/Vtf0/Main.asm
- BootloaderCorePkg/Stage1A/X64/SecEntry.nasm
Currently, the 1st time stamp includes FSP-T execution time in X64.
This will read the 1st time stamp before TempRamInit.
> [X64] Read the first time stamp before TempRamInit

- Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
It is not necessary to set WDT for FSPM.
So remove it to avoid potential issue.
> [TGL] Remove WDT

- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
This patch removed duplicated X2APIC enabling code. Instead, it
enables X2APIC in a common function. By doing so, the very first
waking up will be done in APIC mode. Afterwards, it will be using
X2APIC mode if enabled by PCD.
This patch also fixed an X2APIC ACPI MADT issue.
> Move X2APIC enabling to common function

- BootloaderCommonPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c
It was reported that some platform had MP waking up issue after
switching to using X2APIC library. By comparing the library, found
X2APIC removed 2nd IPI sending in the flow. This 2nd IPI is
required per IA specification. The patch added it back.
Tests have been done and confirmed it fixed the issues seen on
thos platforms.
> Fix MP waking up issue on some platforms

- Platform/CoffeelakeBoardPkg/CfgData/CfgData_Memory.yaml
- Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This Patch did the following
-  TsegSize config options is defined in CfgData_Memory.yaml.
-  with 64GB RAM, slow boot issue was reported on ubuntu_20.0.
Root cuase of the issue is due out of MTTR's and unable to cover
portion of higher memory ranges. this patch fixes this issue.
> [CFL] Set Tseg size to 16MB.

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c
CsmePciReadBuffer function prototype is aligned as
per the CSME fwupdate lib. It fixes issue with
CSME capsule fw update.
> Update CsmePciReadBuffer callback prototype params

- BootloaderCorePkg/Tools/FspSwap.py
This patch added FSP swapping script to support replace a FSP
binary inside SBL IFWI or BIOS image.
To use it, use
python BootloaderCorePkg\Tools\FspSwap.py ifwi.bin fsp.bin
The default output directory is "Out".
> Add FSP swapping script

- PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
This patch fixed an error that occur during updating a
binary that is not aligned to 4k. Current code will always
update next 4K block. This patch adjusted the block length
to remaining size other than 4K.
> Fix bug while updating binary not aligned to 4k

- BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h
- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Current PCI Enum Lib scopes for only Apperture resources
for a PPB. But some OSes (like ESXi) expect BAR0 & BAR1
(Offset 0x10/0x14) to be allocated resources accordingly.
Otherwise, PPB enumeration doesnt happen correctly and
devices behind PPB are not registered at all.
This patch adds the functionality to assign valid resources
to BAR0(0x10) and BAR1(0x14) for a PPB also.
> Program BAR0/1 for PPB

- BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h
- PayloadPkg/FirmwareUpdate/CmdFwUpdate.c
- PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/CometlakevPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/ElkhartlakePkg/Include/Library/HeciInitLib.h
- Silicon/ElkhartlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/ElkhartlakePkg/Library/HeciInitLib/HeciPeiDxe.c
- Silicon/ElkhartlakePkg/Library/HeciInitLib/MbpData.c
- Silicon/ElkhartlakePkg/Library/HeciInitLib/MeBiosPayloadData.h
- Silicon/ElkhartlakePkg/Library/HeciInitLib/MkhiMsgs.h
- Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
- Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
EHL, TGL supports multiple OEM keys and their revocation
by CSE. This patch supports,
- CMDI interface to perform key revocation using
OEMKEYREVOCATION string in cmd file.
- EHL HECI APIs for OemkeyRevoke and to get key status
- FW components are sorted as per required order.
CSME and BIOS should be signed with new keys and
both components would go together with capsule update.
- CSME can be updated for same version.
> Oem Key revocation feature support

- PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c
This patch removed next line character printed during
progress update of csme firmware update, this would remove
lot of prints in the next line and show progress much more
user friendly.
> Remove next line char during csme fw update

- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Current APL SBL code will enable IA_UNTRUSTED mode only at end of
firmware notification. It might be too late for certain conditions.
This patch moves it to be set at end of stage in SBL. In this way,
it ensures the bit is set before launching any external payload.
> [APL] Enable IA untrusted mode at end of SBL stage

- Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
SMIE is checked in Tpm asl before SMI is triggered.
Removal of this definition causes physical presence
usecases failure.
TEST=Verified TPM clear usecases with windows boots
> [EHL] Operational region for ACPI Control SMI_EN access

- Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
- Platform/ElkhartlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/ElkhartlakePkg/Library/PlatformHookLib/PlatformHookLib.c
This CL fixes the long time issue where EHL SBL failed to init
properly and solely relies on FSP to handle the UART unit, and
hence the limitation of Hidden Mode UART only, as we observed
the UART output gone missing after PCI enumeration if we set
respective UART port into PCI mode in FSP. By hiding the UART,
OS will not be able to see the UART device as PCI device and
lose control to the UART device.
Due to hardware design, different uart could use different
LPSS_IO_MEM_PCP register offset for UART clock setup.
This CL includes dynamic configuration for clock setup by
reading the size of UART control register. Since this is pretty
generic for most of platforms, will plan to move more UART codes
to common codes in the future.
Second fix changes the default UART mode for both FSP-T and …
> [EHL] Fix UART init issue and set UART PCI mode as default

- Platform/CommonBoardPkg/Script/security_stitch_help.py
Some platforms FIT tool do not detect sourceDir.
Change to absoulte path.
> Update path for oem key manifets

- Silicon/TigerlakePchPkg/Include/Library/HeciInitLib.h
- Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciPeiDxe.c
- Silicon/TigerlakePchPkg/Library/HeciInitLib/MbpData.c
- Silicon/TigerlakePchPkg/Library/HeciInitLib/MeBiosPayloadData.h
- Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h
- Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
TGL supports multiple OEM keys and their revocation
by CSE. This patch supports HECI APIs for OemkeyRevoke
and to get key status. This is port from TGLH platform
implemetation.
> [TGLU] Oem Key revocation feature support

- Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
As reported in issue #1055, when "--enable-kvm" flag is enabled
within QEMU, SBL does not boot. It is because KVM does not allow
certain MSR access. This patch removed NO_EVICTION_MODE MSR access
from QEMU FSP TempRamInit. By doing so, it allows QEMU to boot
with KVM enabled.
> Fix QEMU boot issue with KVM enabled

- Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Pch.asl
- Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Pep.asl
SPI clock source was on and gating s0ix entry, due to linux OS could
trigger SPI Write Protection Disable bit and hence set the SPI
Synchronous SMI Status bit. This CL fixes it by clearing the SPI
Synchronous SMI Status bit prior to S0ix entry.
Traditionally, it is expected for bootloader to clear this bit in
SMI handler upon S0ix entry, due to SBL being free of SMI, clearing
this bit from ACPI table has the same effect.
Signed-off-by: LeanSheng <lean.sheng.tan@intel.com>
> [EHL] Fix SPI clock source gating s0ix issue

- BootloaderCommonPkg/Library/MtrrLib/MtrrLib.c
Current MTRR lib assumes the MTRR number is always 10. Instead,
this patch follows the IA manual to get the actual MTRR number
through MTRR capability register.
> Fix Shell MTRR print issue

- BootloaderCorePkg/Library/MpInitLib/X64/MpFuncs.nasm
GCC x64 build requires stack to be aligned at 16 bytes. In MpInit
nasm file, SBL set the initial stack to be 16-byte aligned. However,
later on unbalanced push/pop breaks the 16-byte alignment. This
patch removed extra stack pop so that the stack will always stay at
the original initial value.
> Fix stack alignment issue in x64 build

- Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/LpcDev.asl
- Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Pep.asl
Fix typo error in \_SB.PC00.SPIF.SPIS()
De-assert the TIMER1_INT_ENB_CNF bit upon
entering s0ix in ACPI
> [EHL] HPET acpi fix for s0ix

- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
Current SBL always uses the latest VS toolchain detected to build
SBL. However, sometimes a different verion might be preferred.
This patch added a build option "-t" to specify the perferred VS
toolchain version. It is useful when mulitple VS toolchain versions
are installed.
For example, add '-t vs2015' to use VS2015 as the toolchain for
SBL build.
> Add Visual Studio toolchain version select option

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
- PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
This patch enforces to use the SBL version for current boot
to check against the new version in capsule. Only when the
new SVN version in capsule is greater than or equal to current
SBL SVN version, the update is allowed.
> [APL] Firmware update flow fix

- BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
Need initialize global variable mSysCpuTask.CpuCount to actual
CPU count.
> Update MP lib to fix CPU task

- PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
As part of the commit e21c74f42ef7c455f22f34c9f2137e7747b0d3aa,
it used the HOB to get the firmware version info. However, the
HOB firmware version structure is not exactly the same as SBL
firmware version structure. It needs to be adjusted accordingly.
This patch addressed this issue.
> Fix firmware update version check

- BootloaderCorePkg/BootloaderCorePkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf
- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLibInternal.h
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
- Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLibInternal.h
This patch implemented a common method for platform to create ACPI
table dynamically. Platform can provide ACPI tempalte array through
PCD PcdAcpiTableTemplatePtr. If provided, ACPI core code will try to
call platform code to patch the table, and then install the table to
ACPI RSDT/XSDT.
It also added sample code implementation in QEMU to show case how to
do it from platform code.
> Allow platform to create ACPI table dynamically

- PayloadPkg/OsLoader/OsLoader.c
The boot logic has been adjusted in OsLoader. As a result, the
mCurrentBoot does not point to the current boot option any more.
It is always 0. This patch adjusted the value for it to indicate
the current boot option.
> Set current boot option in OsLoader

- PayloadPkg/OsLoader/BootParameters.c
- PayloadPkg/OsLoader/LoadImage.c
- PayloadPkg/OsLoader/OsLoader.c
- PayloadPkg/OsLoader/OsLoader.h
Before normal OS boot, some images need run firstly.
These images will return to SBL after complete.
This patch uses OS boot option extra images to
support this use case.
It uses a string in the boot option to indicate this
container image need run before OS.
Container component name format: "!XXXX\YYYY:ZZZZ"
"XXXX" and "YYYY" are container and component signature.
For "ZZZZ", Value "POSN" means this component will be
run before OS. Value "POSR" means this component need
runtime memory to run it.
> Add extra images boot support

- BootloaderCommonPkg/BootloaderCommonPkg.dec
- BootloaderCorePkg/BootloaderCorePkg.dsc
- Platform/CommonBoardPkg/CfgData/CfgData_Tcc.yaml
- Silicon/CommonSocPkg/Include/Library/TccLib.h
- Silicon/CommonSocPkg/Library/TccLib/TccLib.c
- Silicon/CommonSocPkg/Library/TccLib/TccLib.inf
- Silicon/CommonSocPkg/Library/TccLib/TccRtctHob.h
1) Add PCD PcdTccEnabled so that TCC could build out when disabled
2) Add HOB gTccRtctHobGuid produced by FSP if FSP support TCC V2
3) Add a common TCC config data in common platform package
4) Add a common TCC lib to update TCC RTCT table.
> Add TCC V2 support

- Platform/ApollolakeBoardPkg/CfgData/CfgData_Ext_Up2.dlt
This patch configured UP2 GPIO213 default to be output with level
high. It will select the PCIe interface as default. The original
default was mSATA.
> [UP2] GPIO fix for PCIe slot

- .azurepipelines/azure-pipelines.yml
This patch enabled auto build for EHL Azure Pipelines.
> Enable Azure Pipeline build for EHL

- PayloadPkg/OsLoader/LoadImage.c
- Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml
- Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
When PreOS is configured from OS boot option data, the common function
FillBootOptionListFromCfgData () need update it to OS correct boot option
image LoadImageTypePreOs. Similarly when extra image is specified, need
update to extra image.
Update ImageType value and fix an image load issue for RTCM.
> Fix the boot option

- BootloaderCommonPkg/Library/IppCryptoLib/auth/ippbase.h
- BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
- BootloaderCorePkg/Tools/BuildUtility.py
- BuildLoader.py
This patch will enable CLANG toolchain build on Windows.  Currently
CLANG toolchain build still needs Visual Studio to provide nmake
utility.
To build with CLANG, please add build option "-t clang". It assume
CLANG is installed at default path. It has been tested with SBL
QEMU x86 build.
> Add CLANG toolchain build support

- BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
- Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Silicon/CoffeelakePkg/Library/SgxLib/SgxLib.c
Current SBL release debug output has more than what is expected.
This patch reset some of the debug message to proper level to limit
debug message for release build.
> Clean up release build debug output

- BootloaderCommonPkg/Include/Library/PagingLib.h
- BootloaderCommonPkg/Library/PagingLib/Paging32To64.c
- BootloaderCommonPkg/Library/ThunkLib/Ia32/DispatchExecute.c
- BootloaderCommonPkg/Library/ThunkLib/Ia32/Thunk32To64.nasm
- BootloaderCommonPkg/Library/ThunkLib/ThunkLib.inf
This patch added thunk support from 32bit to 64bit. It allows SBL
to call 64bit API entry from 32 bit compatible mode.
> Thunk support from 32bit to 64bit

- BootloaderCommonPkg/Library/ThunkLib/Ia32/Thunk32To64.nasm
On some build environment, NASM will fail to compile Thrun32To64.nasm.
It is because of "BITS 64" usage in WIN32. This patch removed the BITS
64 usage and used opcode prefix instead to resolve this issue.
> Fix thunk build issue for some environment

- Platform/QemuBoardPkg/Script/qemu_test.py
This patch added argument support for qemu_test.py so that a
specified test case can be launched separately. Wilecard chars
are supported for the test case name.
> [QEMU] Allow to run specific test case

- BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
- BootloaderCorePkg/Stage2/Stage2.c
This patch printed Playload ID in human readable string format
instead of HEX string.
> Print Payload ID in human readable format

- PayloadPkg/CsmeUpdateDriver/CsmeUpdateDriver.c
This patch fixes the default 32bit typecasting of a pointer.
Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>
> csmeupdatedriver: Fix incorrect typecasting.

- BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
This will disable all PCI bus master by default, and enable it only if
- the original bus master was enabled before PCI enumeration
- Or the device is PCI Bridge
> [PCI] Disable PCI devices bus master by default

- Platform/CommonBoardPkg/CfgData/CfgData_Tcc.yaml
Update TCC config data strings to use the formal names.
And change the default value to make TCC disabled by default.
> Update TCC config data strings

- Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Memory.yaml
- Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
- Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
FSP-M and FSP-S UPD update
Enabled IBECC by default and for Fusa
> [EHL] FSP UPD update

- Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
DebugConsent related UPD configs should be able to updated via
YAML configs, hence restore to the intended design which allows
user to update these configs via YAML/SBL config editor tool.
This CL also add debug print for these configs.
When DebugConsent is set to manual, DebugInterfaceEnable should
be set to 0 to disable CPU run control.
Part 2 will bring changes to YAML to properly reflect the right
setup combo for Debug Settings and a separate Debug CfgData.
In the end, DebugConsent configs are pretty standard across most
of platforms and should be moved to common codes.
Signed-off-by: leanshen <lean.sheng.tan@intel.com>
> [EHL] Rework DebugConsent related code part 1

- Platform/ElkhartlakeBoardPkg/BoardConfig.py
Rework flash map to prepare extra empty size for FW update and
future growth.
Here are related changes:
1. Expand the SBL size to 13MB
2. Hardcode and increase Redundant size to 0x360000
3. Allocate the remaining space for Non-Redundant space
Signed-off-by: leanshen <lean.sheng.tan@intel.com>
> [EHL] Rework flash map
