slimbootloader/slimbootloader

BootloaderCorePkg/Library/MpInitLib/Ia32/MpFuncs.nasm, BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, BootloaderCorePkg/Library/MpInitLib/X64/MpFuncs.nasm, BootloaderCorePkg/Stage2/Stage2.c, BootloaderCorePkg/Stage2/Stage2.h, BootloaderCorePkg/Stage2/Stage2.inf
When SMRR is enabled too early, it blocked TSEG access in Stage2.
And it caused S3 related issues. This patch delays the SMRR enabling
to be after PrePayloadLoading BoardInit().
=> Delay SMRR enabling

BootloaderCommonPkg/Include/Guid/MpCpuTaskInfoHob.h, BootloaderCorePkg/Stage2/Stage2Support.c, PayloadPkg/Include/Library/PayloadEntryLib.h, PayloadPkg/OsLoader/ExtraModSupport.c, PayloadPkg/OsLoader/LoadImage.c, PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/OsLoader.h, PayloadPkg/OsLoader/OsLoader.inf, PayloadPkg/PayloadPkg.dsc
SBL allows extra module to be called before tranfering into the main
boot option. For example, RTCM module can be called for boot option
with TCC feature support. This patch enabled this support.  Since the
extra module might have different ARCH mode from current SBL mode,
thunk will be provided if mismatching is detected.
=> Enable SBL call into extra module in boot option

BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
Current SBL SMM rebasing check is only performed when PcdSmmRebaseMode
is enabled. It does not cover the case to boot UEFI payload. This patch
enhaced the check to cover UEFI payload S3 path as well.
=> Enhance SMM rebase check condition

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
With latest core code change, it would boot hang.
So need set SMM related PCD early and update platform
to enable SMM rebase.
=> [TGL] Fix boot issue and enable SMM rebase

BootloaderCorePkg/Include/Library/S3SaveRestoreLib.h, BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
For appending Save/Restore structs in TSEG area,
bootloader should reserve space for TotalSize and
for certain structs, only header info should be
actually populated. Rest should be all Zeros.
=> Fix buffer overflow for copy in S3SaveRestore lib

Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Silicon/CoffeelakePkg/Include/Register/PchRegsPmc.h
When S3 resume fails for some reason, the power button status will
be not be cleared on next boot. It might trigger shutdown event in
payload. This patch will clear power button status bit on normal
boot flow so that system can still boot properly.
=> [WHL] Clear power button status on normal boot flow

BootloaderCorePkg/Tools/GenCfgData.py, BootloaderCorePkg/Tools/GenCfgDataDsc.py, BootloaderCorePkg/Tools/SblSetup.py, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Memory.yaml
EHL CFGDATA has missing options for Combo type configuration. And
it will cause ConfigEditor exception. This patch added the missing
options. And it also fixed typos.
It fixed issue #1122.
=> [EHL] Fix CFGDATA issues on EHL

BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.c, BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.h
With recent code change of disabling all PCI bus master
by default, NVME may not work in some platform (e.g., Qemu).
This patch set/clear bus master during NVMe init/deinit.
=> Fix NVMe failure because of bus master not enabled

BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
Need to add some typecasting to resolve a build
issue with MpInitLib when using VS2015 compiler.
=> Resolve issue with MpInitLib VS2015 compiling

Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
This is an regression introduced with platform asl updates.
SMIE is checked in Tpm asl before SMI is triggered.
Removal of this definition causes physical presence
usecases failure.
TEST=Verified TPM clear usecase with windows boots
=> [TGL] Operational region for ACPI Control SMI_EN access

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Pep.asl, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c
S0ix failed to enter when pcie card is attaching.
The _OFF method of RP01 power resource didnt get
called upon entering s0ix.
Workaround with performing the action in _OFF method
in low power idle entering callback.
=> [EHL] fix s0ix issue for pcie attach

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
This CL is a follow up on these CL to enable SMRR programming:
https://github.com/slimbootloader/slimbootloader/pull/1106
https://github.com/slimbootloader/slimbootloader/pull/1114
In normal UEFI payload case, the UEFI will handle SMM rebasing.
If SMM rebasing is handled by SBL, SBL will put a dummy SMI handler
at the new SMBASE to prevent SMM hang. Beyond SMM rebasing, it
is also required to program SMRR registers.
This patch added this support for EHL by setting ENABLE_SMM_REBASE
flag to auto mode.
=> [EHL] Enable SMRR programming in SMM rebasing flow

PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/OsLoader.h, PayloadPkg/OsLoader/PreOsChecker.c, PayloadPkg/OsLoader/PreOsChecker.h, PayloadPkg/OsLoader/PreOsSupport.c
This patch enhanced OsLoader to support ELF image boot on top of
PE, FV, Multiboot and Kernel. As a result, a new image flag
LOADED_IMAGE_ELF is added to indicate ELF image type.
Verified SBL can boot uboot ELF image (non-Multiboot) on QEMU.
=> Add ELF image support for OsLoader

Silicon/ElkhartlakePkg/Include/Register/PchRegsLpc.h, Silicon/ElkhartlakePkg/Library/PchCycleDecodingLib/PchCycleDecodingLib.c
1. Add missing definition for PchCycleDecoding.
2. Remove PCH H checking.
=> [EHL] PchCycleDecoding support

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c, BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
In the Ext23Lib support for symbolic links was recently enabled
but there was a limitation imposed to use the CFG data boot
option filepath limit of 16 bytes which does not need to be also
be imposed on symbolic link paths. This will allow symbolic link
paths to be up to 260 characters long.
=> Allow Ext23Lib symbolic links to have longer paths

Platform/QemuBoardPkg/BoardConfig.py, Platform/QemuBoardPkg/CfgData/CfgDataExt_QSP.dlt, Platform/QemuBoardPkg/Include/ConfigDataDefs.h, Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/QemuSocPkg/Include/PlatformBase.h
Officially add Simics QSP board (X58Ich10Board) support on top of
QEMU package.
Here are the changes:
1. Add Simics QSP detection based on Host Bridge DID
2. Add new QSP dlt file (Platform ID: 2) and QSP name changes
3. Set the PCI_MEM32 base to 0xF0000000 for QSP
4. Update minor version and date
Signed-off-by: LeanSheng <lean.sheng.tan@intel.com>
=> [QSP] Add Simics QSP board support based on QEMU package

Platform/QemuBoardPkg/AcpiTables/Dsdt/Dsdt.asl, Platform/QemuBoardPkg/CfgData/CfgData_BootOption.yaml, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch includes several enhancements for QSP and QEMU:
- Change boot option to use 1st AHCI port with drives attached
- Add ACPI APIC routing table and enable APIC mode
- Add 64bit PCI resource
- Update GFX HOBs using correct PCI device
Verified Linux boot on both QEMU and QSP.
=> [QSP/QEMU] Enhance virtual platform

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/HdaI2sCodec.asl, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_GpuConfig.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
1. Add missing HDAC initialization in ACPI
2. Add PchHdaDspUaaCompliance in CfgData to allowed modification
using Config Editor tool
=> [EHL] Enable SOF driver for audio

Platform/CoffeelakeBoardPkg/BoardConfig.py, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
This patch added required support to enable PCI 64 bit resource
allocation. By default, all downgrading is enabled so that it has
the same behavior as current code. To enable 64 bit resource,
set related downgrading flag to 0.
=> [CFL] Add PCI 64bit resource support

BootloaderCorePkg/Tools/ConfigEditor.py, BootloaderCorePkg/Tools/GenCfgData.py
This patch enhanced ConfigEditor to handle the case that the app
will crash when "Value" is not provided in YAML. It also fixed
an hide/show issue for Table type widget.
=> Enhance ConfigEditor to handle error condition

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/Library/GpioLib/GpioHelpersLib.c, Silicon/ElkhartlakePkg/Library/GpioLib/GpioLib.c
Issue seen in Yocto RT kernel that PSE GBE0 Transmission.
Found out that GPPC_A_5.pmode=0 (RGMII0_TXCTL) which expected
to be 0x1.
override become 0x0.
After investigation these PADCFGLOCK_GPP_A_0 and PADCFGLOCKTX_GPP_A_0
registers should be 0xFFFFFF to lock the GPIO GPPC_A_x to prevent
modificaiton to the GPIO.
Implemented GpioLock function in GpioLib.c to fix this issue.
=> [EHL] GpioLock update

BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.c, BootloaderCommonPkg/Library/MmcAccessLib/SdMmcPciHcDxe.h
When the bus master decoding was disabled by default in PCI bus, the
device driver should try to enable it on its own. However, eMMC
driver does not have the enabling code. It caused the eMMC access
failure.
It fixed #1153.
=> Fix eMMC controller driver issue

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
This patch changes the return code of SearchDirectory
to EFI_NOT_FOUND when a file to search cannot be found
=> Fix return code of SearchDirectory

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py, Platform/CometlakeBoardPkg/Script/StitchIfwi.py, Platform/CometlakevBoardPkg/Script/StitchIfwi.py, Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py, Platform/TigerlakeBoardPkg/Script/StitchIfwi.py
Currently final IFWI gets generated output path.
Copy the signed slimboot binary to out path.
=> Generate signed slimboot binary to output path

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c, BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h, BootloaderCommonPkg/Library/Ext23Lib/ExtLib.c
This patch runs basic check during EXT FS initialization
by opening root directory to ensure superblock been
validated.
=> Add EXT FS check in initialization

BootloaderCommonPkg/Include/Library/ElfLib.h, BootloaderCommonPkg/Library/ElfLib/ElfLib.c, BootloaderCommonPkg/Library/ElfLib/ElfLibInternal.h, BootloaderCorePkg/Stage2/Stage2.c
This allows to load and execute ELF32 or ELF64 format payloads
regardless of Ia32 or X64 SBL operation modes.
=> Support ELF32/64 format payloads regardless of operation mode

PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
This will fix an invalid pointer operation while copying capsule filename
from capsule info config data to a unicode buffer.
=> [FWU] Fix a pointer misusing in capsule name

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c
The PCI address consumed by CSME FW update library is in
EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL_PCI_ADDRESS format.
- when register offset is  < 0x100, it is :    bbddffrr
- when register offset is >= 0x100, it is : rrrbbddff00
Consider the two different cases in CsmePciReadBuffer()
=> Fix PCI address check in CsmeFwUpdate

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c, PayloadPkg/FirmwareUpdate/CsmeFwUpdate.c, Platform/QemuBoardPkg/BoardConfig.py
- fix __aullshr link error for NOOPT build in Windows
due to compiler intrinsics functions
- adjust Stage1A/TopSwap/OsLoader FD size for NOOPT target
- adjust Stage2 size for NOOPT target when DEBUG FSP is used
=> [QEMU] Fix compiler error for NOOPT build in Windows

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Recent addition of '-op' argument may have
unintentionally created an issue by using an
unassigned variable 'work_dir' where the
intended variable to be used may have been
'stitch_dir'. This patch resolves the issue
and able to successfully stitch an IFWI once
again.
=> [CFL] Resolve StitchIfwi.py issue

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
If the PlatformId is already set by stitch data, the platform code
should skip platform settings to avoid PlatformID override.
This patch adds the PlatformId check in platform code.
=> [TGL] Fix PlatformId override issue

Platform/TigerlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Silicon/TigerlakePkg/Library/PlatformHookLib/PlatformHookLib.c
On TGL platform, if change current DEBUG UART to PCH UART, there
is no output from SBL at all.
This patch fixed this issue by:
- Skip UART init in FSP-T and let SBL do UART init itself.
- Disable any debug output before UART init is done.
=> [TGL] Fix TGL PCH Debug UART issue

BootloaderCorePkg/Stage1A/Stage1A.c, BootloaderCorePkg/Stage1A/Stage1A.h
Set debug print error level to 0 by default.
This will prevent code to print debug messages via
UART, if it is not yet initielized.
After PostTempRamInit, when platforms did UartInit,
we can set it back to default PCD value, or leave it
as it is if the platform has set a custom level.
=> Disable debug prints before serial init

Platform/TigerlakeBoardPkg/CfgData/CfgData_Gpio.yaml, Platform/TigerlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
When PCH UART is used as debug UART, the later stage code should
not do re-initializaiton. This patch will skip PCH UART GPIO
reprogramming and FSP-S UART re-initialization.
=> [TGL] Skip PCH UART init in later stages

BootloaderCorePkg/Tools/BuildUtility.py, BuildLoader.py
When redundant partition is enabled, the FSP-T microcode base UPD
always points to the microcode region in 1st partition. Instead,
it should points to the microcode rgion in its own partition. This
patch fixed this issue.
=> Patch FSP-T UPD microcode base

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Change BiProcHot value to 0 for Fusa sku as per
requested from PMC team to fulfill Fusa requirement
=> [EHL] BiProchot changes for Fusa

Platform/CommonBoardPkg/CfgData/CfgData_Tcc.yaml
Make Error logging capability configurable under
Tcc mode. This will be consumed later.
=> Add TccErrorLogEn feature in Tcc mode

PayloadPkg/OsLoader/ExtraModSupport.c, PayloadPkg/OsLoader/LoadImage.c
RTCM will sit in OS boot media instead of IFWI image
So update SBL logic to load RTCM from OS boot media.
If the RTCM could not be found, SBL should continue
boot normal OS.
=> Get RTCM from OS boot media instead IFWI

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/TigerlakePkg/FspBin/FspBin.inf, Silicon/TigerlakePkg/Microcode/Microcode.inf
MR2 FSP is available so update SBL to use MR2 FSP.
and also use new Microcode required by new FSP
Update platform code on FSP UPDs, especially enable TCC feature.
Update TGL platform version to 1.2 since MR2 released.
=> [TGL] Use MR2 FSP and Microcode for TGL-U

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Include/Library/PciEnumerationLib.h, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf
This patch adds a platform hook function ability
in Pci Enum Lib to enable platform to perform a
PCI Enum specific work-around routine to detect
some controllers.
=> Add a Pci Enum Hook function

BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
FEATURE_PRE_OS_CHECKER_BOOT is not used by any core or platform code.
So just remove it.
=> [EHL] Remove unused feature flag for PreOS checker

Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py
- Add knob for setting up the ISI configuration file (isi_conf)
- Fix PT test mask value to be aligned with default PT binary
capabilities. Only add mask when PT is enabled.
- "pt" parameter always requires isi_conf file. Dependency added
automatically. isi_conf is also externally configurable since can
be used without PT.
Signed-off-by: Pedro Queiros <pedro.queiros@intel.com>
=> Rework Fusa PT settings

BootloaderCommonPkg/Include/Library/IasImageLib.h
As per specification of the IAS-Image format 
https://github.com/intel/iasimage/blob/master/docs/02_mcd.md
the signature and public key are optional.
As per specification of the header format 
https://github.com/intel/iasimage/blob/master/docs/02_mcd.md#image-type
The 8th bit indicate if the signature is included, while the 9th bit indicates whether
the public key is included.
While the previous solution checked if public key is enabled, it did not check if
the signature is included, but rather assumed that it is always included.
This will lead to a miss-calculation of the `IAS_IMAGE_END` and `IAS_IMAGE_SIZE`
which on the other hand will cause `IsIasImageValid()` to fail, which will fail the loading
of unsigned IAS-Images.
=> [IAS] Consider signature for size only if enabled

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Fix mPchSciSupported flag checking before changing the
flag value of boot option.
This bug was introduced from commit
b78cbcf128866b8835116a6ba77d9e7ac5c8ab00
=> [EHL] Fix Stage2 Boot Option checking

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_BootOption.yaml
Enable POSC for all boot medium in Cfgdata_BootOption.yaml
by default
If Non-Fusa sku was detect and the boot flag will
change to exclude POSC
User can modify the boot flag to exclude the POSC in
yaml file as well
=> [EHL] Enable POSC for all boot option

BootloaderCommonPkg/Include/Guid/LoaderPlatformDataGuid.h, BootloaderCommonPkg/Include/Library/ConsoleInLib.h, BootloaderCommonPkg/Include/Library/ConsoleOutLib.h, BootloaderCommonPkg/Include/Library/DebugPortLib.h, BootloaderCommonPkg/Library/BootloaderDebugLib/BootloaderDebugLib.inf, BootloaderCommonPkg/Library/BootloaderDebugLib/DebugLib.c, BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.c, BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.inf, BootloaderCommonPkg/Library/ConsoleOutLib/ConsoleOutLib.c, BootloaderCommonPkg/Library/ConsoleOutLib/ConsoleOutLib.inf, BootloaderCommonPkg/Library/DebugPortLib/DebugPortLibNull.c, BootloaderCommonPkg/Library/DebugPortLib/DebugPortLibNull.inf, BootloaderCorePkg/BootloaderCorePkg.dsc, Platform/CoffeelakeBoardPkg/BoardConfig.py, Platform/CoffeelakeBoardPkg/CfgData/CfgDataExt_Upx.dlt, Platform/CoffeelakeBoardPkg/Library/DebugPortLib/DebugPortLib.c, Platform/CoffeelakeBoardPkg/Library/DebugPortLib/DebugPortLib.inf, Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CoffeelakeBoardPkg/Script/MailboxDebugPort.py, Platform/CommonBoardPkg/CommonBoardPkg.dec, Platform/CommonBoardPkg/Include/Library/GpioDebugPortLib.h, Platform/CommonBoardPkg/Include/Library/MailboxDebugPortLib.h, Platform/CommonBoardPkg/Library/GpioDebugPortLib/GpioDebugPortLib.c, Platform/CommonBoardPkg/Library/GpioDebugPortLib/GpioDebugPortLib.inf, Platform/CommonBoardPkg/Library/MailboxDebugPortLib/MailboxDebugPortLib.c, Platform/CommonBoardPkg/Library/MailboxDebugPortLib/MailboxDebugPortLib.inf
This patch set added GPIO debug port support.  It also provides an example in CFL.
=> Enabling GPIO Debug Port

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_BootOption.yaml
Re-enable sbl_rtcm in EHL boot option due to
mistakenly removed it in previous commit of
f01a5b33fba3da04bc6c0d632ce9450413a4651a
=> [EHL] Enable tcc in boot option

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Update EHL BoardPkg version to 2.0 to allign with current
software package version:
PROJ_MAJOR_VER -> 2 (Maintenance Release candidate)
PROJ_MINOR_VER -> 0 (1st revision of MR1 release)
=> [EHL] Update the EHL BoardPkg version to 2.0

Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py
Enable DAM option in stitchifwi script for
ITP/CCA debug purpose with -o debug paramter
Example: To enable SATA and DAM enabled "-o sata;debug"
=> [EHL] Enable DAM option stitchIfwi update

BootloaderCommonPkg/Library/UsbInitLib/UsbInitLib.inf
Resolve link error when using UsbInitLib
UsbInitLib invokes UsbDeInitBot() which is defined in UsbBlockIoLib
=> add missing UsbBlockIoLib in UsbInitLib.inf

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch replaces the original hard-coded iTBT root ports control with
a CFG option. The default value is to enable them.
=> [TGL] Add iTBT PCIe root port enablment config

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
If the capsule file is too small, it should not only
show "the guid is not expected" that may mislead users
using a release-build image. This patch prints out
specific error if opening a small-than-expected capsule.
=> Fix error logs for capsule file too small

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Int_IotgRvp1.dlt
Added Gpio Lock config in dlt file for RVP board
=> [EHL] Fix in RVP board support

Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml, Platform/CommonBoardPkg/Include/ConfigDataCommonDefs.h
Current index only support up to 0xF as the CFGHDR_TMPL
as it amend into 0x05 (eg. 0x05$(1))
Update the logic to (0x050 + $(1)) instead to support
index larger than 0xF
=> [Common] Fix config data boot option index

BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c
Currently it will return a valid SMMBASE_INFO if SMMBASE_INFO_COMM_ID
is found in SMM S3 resume memory. It will cause issue in S3 path if there
is no one fill correct data when MpInit uses it to rebase SMM.
This patch adds a check to SMMBASE_INFO to avoid this issue.
=> Fix SMM rebase S3 issue

BootloaderCommonPkg/Library/IppCryptoLib/auth/Ia32/pcpsha512w7as.nasm
IA32 build from VS2019 toolchain has security violation
because Digest value from SHA512_384 is not matching the
value calculated and stored in hashstore during build.
Aligning the stack to 32-byte boundary during SHA_Update
fixes this error.
=> Fix security violation for IA32 build in VS2019 toolchain

Platform/TigerlakeBoardPkg/AcpiTables/CpuSsdt/Cpu0Hwp.asl
CPOC is defined in both Cpu0Hwp.asl and Dsdt/Cpu.asl,
which results in Linux kernel warning and wrong CPU
base speed shown in Windows 10.
=> [TGL] Fix CPOC Duplication ACPI Error (#1233)

BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/TigerlakePchPkg/Include/PchAccess.h, Silicon/TigerlakePchPkg/Include/Register/PmcRegs.h, Silicon/TigerlakePchPkg/Include/Register/RtcRegs.h
This patch clears RTC Alarm when RTC is the S3 wake up source.
Without clearing it, SMI# will be triggered once SMI_EN is set
by RestoreS3RegInfo, but no handler to clear it which results
in hang.
=> [TGL] Fix RTC S3 wake hang

Platform/CommonBoardPkg/Tools/GpioDataConvert.py
when pin number in pad name is not in <group name><xx> where
xx is pin number format. for example GPIO_VER2_LP_GPP_C2 instead of
GPIO_VER2_LP_GPP_C02, current code has a bug which does not give the
desired output which is GPP_C02.
This patch fixed this issue.
TEST= Verified on multiple platforms that the issue is fixed
Signed-off-by: Raghava <raghava.gudla@intel.com>
=> Fix normalization error

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Default Bpmgen params created by bpmgen tool
has unicode characters. This patch fixes reading the
file with unicode chars.
=> [CFL] Fix reading bpmgen2 params

Platform/QemuBoardPkg/Script/TestCases/linux_boot.py
Recently, github CI test case, Qemu-linux_boot.py, randomly fails.
Comparing the logs between failed and pass cases, we can find:
1. the failure is caused by timeout before Minimal Linux
completely boots into console and shows "Welcome to Minimal
Linux" messages.
Although such timeout can be a real error (true-positive),
it is also possible just a false alarm (false-positive)...
2. for a failed case, a force push to trigger another CI check
can result in pass, even no code changes. Thus, the timeout
failure points to CI environment (e.g., loading) - a false alarm.
3. the margin (of pass case to timeout) is about 0.4 sec.
This patch increases timeout for 2 seconds to avoid unexpected
test timeout caused CI envornment (e.g., loading).
=> [QEMU] extend auto test timeout

BootloaderCorePkg/Include/Library/BootloaderCoreLib.h, BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.c, BootloaderCorePkg/Stage1A/Stage1A.c, BootloaderCorePkg/Stage1B/Stage1B.c
Some platforms need TempRam Base & Size information to calculate
FspmArchUpd StackBase & Size at runtime.
The TempRam Base & Size info will be only valid until TempRamExit.
=> [CorePkg] Add GetTempRamInfo() API

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/CfgData/CfgData_Tsn_Feature.dlt
This patch refactors TSN enablement control by
- rename ENABLE_TSN_MAC_ADDRESS with ENABLE_TSN:
align the naming with ENABLE_TCC
- ENABLE_TSN can be used as a one-stop control knob
to reserve FW spaces and include proper TSN CfgData
- collect TSN-specific CfgData into CfgData_Tsn_Feature.dlt
With the new control, inconsistent TSN settings are fixed:
- TSN MAC FW space is reserved but PchTsnEnable is not set
=> [TGL] refactor TSN enablment controls

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/BoardConfig.py
Allow user to include TCC CRL binary to be included in SBL
binary build. The script will check if crl.bin is there (binary
folder) and then only include it.
=> [TGL][EHL] Allow TCC CRL binary to be included in SBL build

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
According to EDS, TCSS PTM Enable (PTME on [B0,D7,F0] offset 158h)
should not be set unless a associated downstream port already has
PTM Enable set.
This patch adds a CfgData control for each TCSS PCIe Root Port.
User can enable each of them when a downstream port meets the
requirement. The new CfgData control is similiar to the following
setup in UEFI BIOS Menu:
Intel Advanced -> SA -> TCSS -> PCIE RP[]
Last, this patch also removes redundant PTM configurations,
because (a) PTM settings will be overridden by built-in
CfgData_Silicon.yaml or customized DLT; b) even for customized 
SBL, FSP will use default PTM settings.
=> [TGL] add control for TCSS PTM Enable

Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_BootOption.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_GpuConfig.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Power.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Here are the changes:
1. Update mismatched & incorrect config options & variables
2. Fix invalid boot options configs
3. [common] Include 'preOS + mender' support for boot flags in
boot options template
=> [EHL] Fix ConfigEditor tool crash and invalid options

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c
Check Gbe device status and update it to D0
if non-D0 state was detected.
=> [EHL] Gbe device status fix

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c
Enabled TimedGPIO 0/1 in PCH Nvs referring to
FSP UPD of TimedPgio 0/1
=> [EHL] Enabled TGPIO

Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py
EHL stitchifwi script enables user to replace IFWI IPFW components
during stitching time.
This CL enables user to only replace IPFW component only if the
specific component is included in IPFW folder of stitch workspace
directory.
Besides, this CL also adds TCC CRL to the replaceable IFWI IPFW
components list.
=> [EHL] Enable stichifwi to dynamically replace IPFW components

Platform/ElkhartlakeBoardPkg/BoardConfig.py
For EHL, PCH & PSE TSNs are required to be turned on for ethernet
connection. However, TSN configurations binaries (TSN Mac address,
TSN manual config & PSE TSN IP config binaries) are optional, and
only used for refined controls.
This CL decouples optional TSN binaries loading and can be enabled
with BoardConfig flag "ENABLE_TSN". If those binaries are
not included, OS TSN driver will load TSNs with default configs and
assign MAC address to them dynamically.
ENABLE_TSN is turned off by default.
=> [EHL] Make TSN config binaries optional

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
MRC requires a larger stack when MrcSafeConfig is disabled
with FSP-m UPD.
=> [TGL] increase stack size for FSP-m

Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py, Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py
when 'tsn' is not specified in stitching option, TSN FWs
should be not replaced.
=> [EHL] fix stitching TSN fw without tsn option

BootloaderCorePkg/Include/Library/S3SaveRestoreLib.h, BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch fixes TSeg region full problem after multiple
warn reset. Each time of warm reset, except S3 resume, the
TSeg region should be clear.
=> fix TSeg full during warn reset

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c, Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Dts.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Dts.h, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/TigerlakePchPkg/Include/Register/PmcRegs.h, Silicon/TigerlakePkg/Include/CpuRegs.h
The patch adds a feature to read Dts at boot. The feature
is analogous to UEFI BIOS:
Thermal Conf -> Platform Thermal Conf -> Boot DTS Read
Specifically, the feature reads Tjunctions of PCH and CPU
and stores them as Smbios Type-28 entries.
The patch also fixes AppendSmbiosType in SmbiosInitLib:
A newly added structure should inherit the Handle from
previous Type-127 (end-of-table) structure.
=> [TGL] Read boot Tjunctions

Platform/CometlakeBoardPkg/Script/StitchIfwi.py, Platform/CometlakevBoardPkg/Script/StitchIfwi.py
The patch enables stitching CML/CMLV IFWI under Linux.
CML/CMLV stitch tools do not natively support for Linux.
A wrapper using 'wine' is required and works.
=> [CML] enable stitch tools for Linux

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
Boot command may attempt to use an index which
exceeds the max image type. Check if the value
is larger than the max allowed value and return
if there is an error.
=> Resolve KW issue in boot command

Platform/TigerlakeBoardPkg/CfgData/CfgData_Features.yaml, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Not every board will want to boot with
Fusa Enabled (ex. UPX i11 board). We can
allow for Fusa to be skipped using CFG
instead of just BoardConfig flag.
=> [TGL] Add Fusa Enable CFG option

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/CfgData/CfgDataExt_Upx11.dlt, Platform/TigerlakeBoardPkg/Include/PlatformBoardId.h
Support for Up Xtreme i11 TGL based board has
been started, with this patch we are able to
boot the board using Slim Bootloader via OS
Loader payload. The PCIe x4 slot on the board
is able to detect NVMe-to-PCIe x4 adapter media
but the other IO on the Up Xtreme i11 board
will need enabling in subsequent patches. Debug
output is coming from header CN11 on the board
(e.g. UART2).
To stitch the SlimBootloader.bin into the default
IFWI retrieved from the Up Xterme i11 use the
StitchLoader.py script with '-p' argument as given
below:
python Platform\TigerlakeBoardPkg\Script\StitchLoader.py -p 0xAA000204 -i board_default_ifwi_orig.bin -s Outputs\tgl\SlimBootloader.bin -o sbl_ifwi_tgl-upx.bin
=> [TGL] Enable UPX i11 basic boot

Platform/TigerlakeBoardPkg/BoardConfig.py, Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
This patch fixes a hang issue during fw update caused by
mismatching bios rom size. For a fw update, the TopSwap
size, Redundant Region size, and total BIOS region must be
identical.
This patch also adds check on rom size during fw update.
The check only works for a running SBL previously built with
this patch.
=> [TGL] fix fw update hang due to rom size change

BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
Ucode repo can be mapped to several different repos in SBL.
Current SBL uses the exactly same folder name for all UCODE
repo. It causes build issues when the UCODE repo switches
from one repo to another. To avoid this issue, this patch
allows to automatically use different folder name for UCODE
repo clone so that each UCODE repo has its own folder.
=> Fix build issue for UCODE repo clone

Platform/ElkhartlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Ext_IotgCrb.dlt, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Features.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiTable.c, Platform/TigerlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Features.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/Include/PlatformData.h, Silicon/ElkhartlakePkg/Include/TccConfigSubRegions.h, Silicon/TigerlakePkg/Include/PlatformData.h
For consistency and public understanding, rework to change 'LowPowerS0Idle' to 'S0ix'.
- rename LowPowerS0Idle to S0ix
- add s0ix variable in PlatformData.h
- add s0ix flag check in stage 1B
- move Tcc s0ix support flag from stage 2 to stage 1B
=> Rename LowPowerS0Idle to S0ix

Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Add check for Pointer 'HdaVerbTablePtr' returned from call to function
'AllocateZeroPool'
=> [CML][TGL] Fix klockwork scanning issues.

Platform/TigerlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
The default values for USB20Enable from FSP
is set to enabled. Some platforms need to
disable some of these USB20 ports (e.g. TGL-U
DDR4 and LPDDR4 RVP). Add CFG data field for
the USB20Enable settings per port.
=> [TGL] Add CFG for USB20Enable

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
With the recent additions to the CFG data (new DLT for
UPXi11 and new fields added) the CFG data size alloced
in memory seems to have run out of space, need to add
space to load the CFG data. Also, we need to specify
in FSP-M to skip UART init for the debug port we are
using when it is a PCH UART or we lose debug messages
in Stage2 onward if using a debug FSP.
=> [TGL] Increase CFG data mempool and skip debug UART init

BootloaderCommonPkg/Library/LiteFvLib/FvLib.c
When FV extended header exists, the first FFS pointer returned by
GetFirstFfsFileInFv() might not be 8-byte aligned. This patch
adjusted the pointer accordingly to ensure it is aligned per UEFI
spec.
=> Enforce FFS alignment in FvLib

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
For the UPX i11 board we need to set
the SA display table (same as DDR4 RVP),
populate the VBT callback routine (also
same DDR4 RVP), and update the SMBIOS
base board string.
=> [TGL] Update UPX GFX and SMBIOS data

Platform/ElkhartlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Ext_IotgCrb.dlt, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Gpio.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/Include/Register/GpioPinsVer3.h
This patch added payload selection GPIO configuration
hardcoded GPIO pin for payload selection.
It also fixed #1196.
Co-authored-by: Lean Sheng Tan <lean.sheng.tan@intel.com>
=> [EHL] Add GPIO payload selection configuration

Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch upstreams previous CML patch for RC3 hotfix:
[CMLV] Fix chipsec SMM issues in S3 path:
Trigger SMI in S3 path to let UEFI payload restore registers.
=> [CML] Fix chipsec SMM issues in S3 path

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Update EHL BoardPkg version to 1.2 to allign with current
software package version:
ERINFO_PROJ_MAJOR_VER: 1 PV Quality release
VERINFO_PROJ_MINOR_VER: 0: PV  1: MR1  2: MR2 etc.
PROJ_MAJOR_VER -> 1 (Maintenance Release candidate)
PROJ_MINOR_VER -> 2 (1st revision of MR2 release)
=> [EHL] Update the EHL BoardPkg version to 1.2

Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
This patch enabled vs2019 toolchain build for QEMU FSP.
=> [QEMU] Enable VS2019 build for QEMU FSP

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Current PciBus lib expects the root bridge resource base should not be
greater than limit. It is true for normal case. However, to mark the
source is unavailable, the base could be less than the limit in some
case. PCI bus lib should only validate the resource that does have a
request.
=> Adjust PCI resource check condition

BootloaderCorePkg/Tools/GenCfgData.py
Current CFGDATA item can only be displayed under one single page
defined in YAML. In some special case it might need to duplicate
the same item under a differnt page. This patch added this feature
by introducing a new "altpage" attribute for a CFG item. When a
item needs to be displayed on a 2nd page, 'altpage' can be added
to indicate the 2nd page id.
=> Add support to show a configure item under multiple pages

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h, Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Currently the PLT_DEVICE_TABLE is limited
to only using OS_BOOT_MEDIUM_TYPE devices
but ideally should be capable of mapping
any system device into the table. For the
time being we will remove the OsBootDeviceGraphics
since it created some KW issue in the fs command.
=> Resolve fs cmd KW issue

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c, PayloadPkg/OsLoader/BootOption.c
Synced the PrintBootOptions fucntions to print
Pre-OS and extra images.
Fixed bug -> if pre-os or extra images are not enabled
in boot flag and it still output in PrintBootOptions
function
=> [Common] Sync boot option print function

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Ext_IotgCrb.dlt
Disable the new GPIO scheme by default in dlt file
Only enable this option for kernel version 4.18.0-315
Alternatively with kernel module parameter
'module_blacklist=pinctrl_elkhartlake' will works
without enabling this GPIO scheme.
=> [EHL] Disable New GPIO scheme by default

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
SBL defined SetDeviceAddr/GetDeviceAddr to abstract platform
device info. However, currently only boot media devices are
defined. It has cases that other platform device info is needed,
such as GFX device. This patch extended the concept to define
some other platform devices as an extenstion to
OS_BOOT_MEDIUM_TYPE. The enum values should not overlap with
the ones defined in OS_BOOT_MEDIUM_TYPE.
=> Add platform device type enum definitions

Platform/TigerlakeBoardPkg/BoardConfig.py, Silicon/TigerlakePkg/FspBin/FspBin.inf
- UP3 IoT FSP MR3
- change the FSP headers from FspBin folder to Include folder
- update TGL platform version to 1.3
=> [TGL] Update FSP and platform version since MR3 is released

BootloaderCommonPkg/Library/ThunkLib/X64/Thunk64To32.nasm
In some cases the paging will be enabled after returning from the
thunked function. To ensure the paging table can be reloaded before
switching back to x64 mode, the paging needs to be in disabled
state. This patch ensures the CR0 bit31 paging bit is cleared.
=> Enhance 64bit to 32bit thunk code

Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CometlakePkg/Include/RegAccess.h, Silicon/CometlakePkg/Include/Register/PchRegsPmc.h, Silicon/CometlakePkg/Include/Register/RtcRegs.h, Silicon/CometlakevPkg/Include/RegAccess.h, Silicon/CometlakevPkg/Include/Register/PchRegsPmc.h, Silicon/CometlakevPkg/Include/Register/RtcRegs.h
This patch clears RTC alarm when RTC is the S3 wake-up source.
Without clearing it, SMI# will be triggered once SMI_EN is set
by RestoreS3RegInfo, but no handler to clear it which results
in hang.
In addition to clearing RTC SMI#, this patch also clears other
SMI# as UEFI BIOS does.
Test method: rtcwake -m -s 15
=> [CML] Fix RTC S3 wake hang

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h, Platform/CommonBoardPkg/CfgData/CfgData_Common.yaml, Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c, Platform/QemuBoardPkg/CfgData/CfgDataExt_Brd1.dlt, Platform/QemuBoardPkg/CfgData/CfgDataExt_QSP.dlt, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
On SBL, it can support boot option selection through QEMU command line
"-boot order" parameter. However, it does not work anymore. It was
because of the MAX_BOOT_OPTION_CFGDATA_ENTRY adjustment in other commit.
This patch decoupled internal boot option index with the CFGDATA boot
option index so that it does not have impacts on each other. With this
change, QEMU boot option can be altered through command line again.
=> [QEMU] Fix AUTO boot option index

BootloaderCommonPkg/Include/Library/TimeStampLib.h, BootloaderCommonPkg/Library/TimeStampLib/TimeStampLib.c, BootloaderCommonPkg/Library/TimeStampLib/TimeStampLib.inf, Platform/CommonBoardPkg/Library/GpioDebugPortLib/GpioDebugPortLib.c
Current SBL code uses MSR(0xce) to calculate the CPU TSC frequency.
However, it is not very accurate. A better way is to use CPUID to
calculate the TSC frequency. This patch added new API to get accurate
TSC frequency.  It also added APIs to allow conversion between time
and TSC ticks.
=> Add accurate TSC frequency calculation support

Platform/CoffeelakeBoardPkg/BoardConfig.py
Seems some recent patches may have added additional
size to OS Loader and now the internal pre-commit build
test in Jenkins is failing due to not enough space
for PAYLOAD. Other platforms are also using 29000h
so might be best to increase the CFL value as well.
=> [CFL] Increase PAYLOAD size

Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglh_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt
1. HD Audio and TSN share pins. These are mutually exclusive features.
2. RVP board should be reworked to support legacy HD Audio mode.
=> [TGL] Disable Intel HD Audio (Azalia)

BootloaderCommonPkg/Library/ElfLib/Elf32Lib.c, BootloaderCommonPkg/Library/ElfLib/Elf64Lib.c
KW scan reported a couple errors regarding
Sec*Shdr value, need to check if they are
NULL before using these values.
=> Resolve KW possible NULL refs in ElfLib

Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
Current GPIO programming code in CommonSocPkg will override the
CFGDATA database. It tried to zero out the GPIO group ID and pad
ID from the GPIO CFGDATA entry. But it should only be applied to
the copied new entry, not the original entry in CFGDATA database.
This patch fixed this isue.
It fixed #1382.
=> Fix GPIO CFGDATA database overriding issue

PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf, PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
It is useful to have capsule image location info since
capsule image could be configured to different places.
=> Add capsule image location info

Platform/CoffeelakeBoardPkg/CfgData/Template_CfgData.yaml, Platform/CometlakeBoardPkg/CfgData/Template_CfgData.yaml, Platform/CometlakevBoardPkg/CfgData/Template_CfgData.yaml, Platform/ElkhartlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/TigerlakeBoardPkg/CfgData/Template_Gpio.yaml
Current GpioLib uses 2 bits from OtherSettings to
configure RxRaw field in GPIO PAD CFG DWORD 0. But
Gpio config templates are missing the option to configure
this feature. This patch adds the option in template.
Signed-off-by: Sai T <sai.kiran.talamudupula@intel.com>
=> Add RxRaw field to Gpio config template

Platform/TigerlakeBoardPkg/CfgData/CfgData_Memory.yaml
The patch updates CfgData yaml to align with FSP:
1. correct value range for SaGv
2. remove unused variables: FreqSaGvLow and FreqSaGvMid
=> [TGL] Fix SaGv CfgData to align with FSP

BootloaderCorePkg/Tools/ConfigEditor.py, BootloaderCorePkg/Tools/SblSetup.py
There are CFGDATA item that needs to be generated into DLT file,
but not to be displayed in ConfigEditor. The current "Reserved"
type prevents the item from being displayed in ConfigEditor,
but also prevents it from being generated in a DLT file. The new
"Constant" type is introduced here to resolve this issue. Item
with "Constant" type will not be displayed in ConfigEditor, but
will be generated in the DLT file.
=> Add new Constant type for CFGDATA

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/Include/Library/BootloaderCoreLib.h, BootloaderCorePkg/Include/Library/StageLib.h, BootloaderCorePkg/IncludePrivate/BootloaderCoreGlobal.h, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c, BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderArch.c, BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.c, BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.c, BootloaderCorePkg/Library/DebugDataLib/DebugDataLib.c, BootloaderCorePkg/Library/DebugPrintErrorLevelLib/DebugPrintErrorLevelLib.c, BootloaderCorePkg/Library/MemoryAllocationLib/MemoryAllocationLib.c, BootloaderCorePkg/Library/StageLib/StageLib.c, Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h
This patch moved SBL core private data strctures and definitions
into a private header file so that other packages cannot refer
to the private structures.
=> SBL clean up to split core private data out

BootloaderCorePkg/Stage2/Stage2.c, BootloaderCorePkg/Stage2/Stage2.h, BootloaderCorePkg/Stage2/Stage2Hob.c, Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CommonBoardPkg/Include/Library/BoardSupportLib.h, Platform/CommonBoardPkg/Library/BoardSupportLib/BoardGraphicsCache.c, Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c, Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.inf, Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
In order to improve the UEFI payload display performance, it is
desirable to have the framebuffer as write-combining for cache
attribute. This patch added a common API to enable this and it
enabled the GFX framebuffer cache for QEMU and TGL. Other
platforms still need porting.
=> Enable GFX framebuffer as WC by BAR parsing

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCommonPkg/Include/Guid/NvVariableInfoGuid.h, BootloaderCommonPkg/Include/Guid/SmmRegisterInfoGuid.h, BootloaderCommonPkg/Include/Guid/SmmS3CommunicationInfoGuid.h, BootloaderCommonPkg/Include/Guid/SpiFlashInfoGuid.h, BootloaderCorePkg/Include/Library/S3SaveRestoreLib.h, BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf, BootloaderCorePkg/Library/MpInitLib/MpInitLibInternal.h, BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestore.c, BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestoreLib.inf, BootloaderCorePkg/Stage2/Stage2.h, BootloaderCorePkg/Stage2/Stage2.inf, BootloaderCorePkg/Stage2/Stage2Hob.c, MdePkg/Include/Guid/SmramMemoryReserve.h
UEFI payload built from open sourced EDK2 supports SMM variable now.
So build the required HOBs to work with EDK2.
This patch just changed the common SBL code, so there is no platform
change required.
=> Build SMM HOBs for universal payload

Platform/CommonBoardPkg/Library/BoardSupportLib/BoardGraphicsCache.c
This is to initialize a Boolean variable to fix KW issue
=> Fix variable not initialized KW issue

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
For EXT2 filesystem revision 0, there are some fixed fields in the
super block structure according to the documentation. The code should
always use those fixed values for safe regardless of the value inside
the image.
=> Enhance Ext2 filesystem library

BootloaderCommonPkg/Include/Library/MtrrLib.h, BootloaderCommonPkg/Library/MtrrLib/MtrrLib.inf, BootloaderCommonPkg/Library/MtrrLib/MtrrSync.c, BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf, BootloaderCorePkg/Library/MpInitLib/MpInitLibInternal.h
SBL might change MTRR to enable framebuffer cache. Current code
only handles BSP MTRR programming, and it is necessary to sync
up the MTRR programming for all APs as well. This patch added
a function to sync up MTRRs for all APs.
Please note, this MTRR sync up is a simplified version for SBL
case since SBL will only add new MTRRs for GFX framebuffer.
To do a full generic MTRRs sync up, it is required to flush cache,
reload TLB, etc. And it will come with some performance impacts.
=> Sync up MTRR for MP before boot

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Disabled AC split lock by default in CfgData yaml file.
=> [EHL] Disabled AC split lock by default

BaseTools/Scripts/PatchCheck.py, Silicon/ElkhartlakePkg/Library/HeciInitLib/HeciCore.c, Silicon/ElkhartlakePkg/Library/HeciInitLib/MkhiMsgs.h, Silicon/ElkhartlakePkg/Library/PsdLib/PsdLib.c, Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciCore.c, Silicon/TigerlakePchPkg/Library/HeciInitLib/MkhiMsgs.h, Silicon/TigerlakePkg/Library/PsdLib/PsdLib.c
On TGL and EHL, to get FW capability, it will send GetFwCaps
command. However, the ACK buffer structure is used incorrectly.
It should use GET_FW_CAPS_SKU_ACK rather than
GET_FW_CAPS_SKU_ACK_DATA. This patch fixed it.
It fixed #1401.
Signed-off-by: Ma <maurice.ma@intel.com>
=> [TGL][EHL] Fix GetFwCap HECI communication issue

PayloadPkg/OsLoader/OsLoader.c, Platform/TigerlakeBoardPkg/CfgData/CfgDataExt_Upx11.dlt
When multiple USB devices are attached, current SBL will try to
boot the device with index specified by HwPart in the boot option.
However, it is hard to determine the USB device index order since
it depends on which port the device is connected to. Instead, for
USB devices, SBL can try to boot from each of them until the boot
image is loaded successfully or all USB devices have been tried out.
This patch added this support.
To enable this feature, it is required to set the USB boot option
HwPart to 0xFF.
=> Add boot from multiple USB devices

BootloaderCorePkg/BootloaderCorePkg.dsc, BuildLoader.py, PayloadPkg/OsLoader/ExtraModSupport.c, PayloadPkg/OsLoader/OsLoader.inf, PayloadPkg/PayloadPkg.dec
If the number of cores are more and the RTCM is
required to support HyperThreading, then it needs
more reserved size, preferably 511 pages instead of
current 255 pages.
So, add a FixedPcd and let each platform override
the default 255 pages value to whatever is required.
Signed-off-by: Sai T <sai.kiran.talamudupula@intel.com>
=> Add a PCD to set RTCM RSVD SIZE

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Increase epayload size to 0x00162000 for compilation
error with latest debug version of uefi-payload
=> [EHL] Increase epayload size

BootloaderCorePkg/Include/Library/SmbiosInitLib.h, BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c, BootloaderCorePkg/Stage2/Stage2.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Dts.c
This patch does the following updates to SmBiosInitLib:
1. Provide AddSmbiosType() to add a SmBios Type header.
2. Provide AddSmbiosString() to append strings to Type header.
3. Move Finalize() to after 'PrePayloadLoading' board init phase.
All Smbios related calls need to be done before this.
4. Modified TGL project to adjust to these changes.
Signed-off-by: Sai T <sai.kiran.talamudupula@intel.com>
=> Enhance Smbios Init Lib

BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c, BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.inf, BootloaderCorePkg/Library/SmbiosInitLib/SmbiosTables.h, BootloaderCorePkg/Library/SmbiosInitLib/SmbiosTemplate.c
This patch added required SMBIOS type 4 for processor info.
=> Add SMBIOS type 4 for processor info

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Enable Gbe TSN config in silicon yaml file below:
- PchTsnGbeSgmiiEnable
- PseTsnGbeSgmiiEnable
- PseTsnGbePhyInterfaceType
Signed-off-by: Kok Tong Ong <kok.tong.ong@intel.com>
=> [EHL] Enable Gbe TSN config in yaml

Platform/CommonBoardPkg/CfgData/CfgData_PayloadSelection.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgDataDef.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_GpioPadGroups.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglh_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
GPIO payload selection settings can be made
into a platform optional common config. This
will ensure that the options display the same
across all platforms which add support for
the GPIO payload selection feature. Each
platform will need to include the
CfgData_PayloadSelection.yaml and needs to
create their own CfgData_GpioPadGroups.yaml
to provide the list of GPIO pad groups to
select from.
=> Add common GPIO payload selection CFG

BootloaderCorePkg/Library/CpuExceptionLib/Ia32/CpuExceptionHandler.c, BootloaderCorePkg/Library/CpuExceptionLib/X64/CpuExceptionHandler.c
When we die due to a fatal exception, we get a debug message that
looks like this:
Exception #6 from 0x0020:0x000729A1 !!!
This message by itself is not incredibly useful for figuring out
which code caused the exception.
This patch borrows an idea from the Linux kernel, and extends the
exception information with a dump of the opcode bytes around the
instruction pointer, which means that the exception debug message
will now look like this:
Exception #6 from 0x0020:0x000729A1 !!!
Code: 89 E0 B9 40 00 00 00 48 8D 15 E3 12 00 00 E8 4D E0 FF FF 41 B8 00 00 07 00 B9 40 00 00 00 48 8D 15 E9 12 00 00 E8 36 E0 FF FF <0F> 0B E8 7D E5 FF FF BA 01 00 00 00 4C 8D 8C 24 90 00 00 00 4C 8D
The byte marked as <0F> indicates the byte that the instruction pointer
points to, and we additionally print a …
=> Print code bytes around eip/rip when taking a fatal exception

MdePkg/Library/BaseLib/Ia32/InternalSwitchStack.nasm
Much like the corresponding Stage1A patch, this patch aligns the
Ia32 Stage1B and Stage2 stacks to 16 bytes, like what is already the
case for X64, so that we follow Version 1.0 of the System V Intel386
ABI supplement, and satisfy any expectations our compiler may have
regarding stack alignment.
A nice side effect of this change is that it allows building an Ia32
Slimbootloader with -msse which can run on real hardware, which requires
16-byte stack alignment.  Slimbootloader currently already enables SSE
in XCR0 early on in Stage1A, and it has SSE versions of various helper
functions written in assembly, in other words, it already makes use of
SSE, but allowing the compiler to emit SSE instructions requires 16-byte
stack alignment, because access to unaligned on-stack SSE variables
will …
=> Align the Ia32 Stage1B/Stage2 stack to 16 bytes

BootloaderCorePkg/Stage1A/Ia32/SecEntry.nasm, BootloaderCorePkg/Stage1A/X64/SecEntry.nasm
Adding the following bit of debug code to DetectUsedStackBottom() in
BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c:
@@ -290,7 +290,10 @@ DetectUsedStackBottom (
{
UINT32  *StackBot;
+  DEBUG ((DEBUG_INFO, "StackTop is %x\n", StackTop));
StackBot = (UINT32 *) ((StackTop - StackSize) & ~ (sizeof (UINTN) - 1));
+  DEBUG ((DEBUG_INFO, "StackBot is %p %x\n", StackBot, *StackBot));
ASSERT (*StackBot == STACK_DEBUG_FILL_PATTERN);
while ((UINT32)(UINTN)StackBot < StackTop) {
shows this for the Stage1 stack on qemu X64, as expected:
StackTop is 2000
StackBot is 0 5AA55AA5
but it shows this on qemu Ia32, which appears to be incorrect:
StackTop is 2004
StackBot is 4 5AA55AA5
This Stage1 StackTop mismatch on Ia32 seems to be caused by the setup
code in …
=> Fix Stage1 StackTop computation for Ia32, and align stack to 16 bytes

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/Include/Library/PchInfoLib.h, Silicon/ElkhartlakePkg/Library/PchInfoLib/PchInfoLib.c
Removed hardcoded PSE PWM pin enable and adapt from
CfgData in Stage2.
=> [EHL] Removed hardcoded PSE PWM pin enable

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, Silicon/ElkhartlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c, Silicon/TigerlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Add BootMediaWriteByType and use for flash descriptor
update.
=> [TGL][EHL] Fix regression for Flash descriptor lock

BootloaderCorePkg/Tools/CfgDataStitch.py
This patch fixed the issue that "cfgdata_dir" argument is not
used properly by the CfgDataStitch script. The "cfgdata_dir"
will contain the CfgDataDef.yaml file and optional DLT files
if provided. Otherwise, the DLT files will be extracted from
the IFWI binary and stored in "cfgdata_dir".
=> Fix cfgdata_dir argument issue in CfgDataStitch

BootloaderCorePkg/Stage1A/Ia32/Vtf0/Main.asm
The timestamp value is saved in edi:esi at reset vector in X64, but
PreparePagingTable is using esi and makes 1st timestamp value invalid.
This saves/restores edi:esi before/after PreparePagingTable to keep
proper timestamp value at reset vector.
=> [X64] Fix invalid 1st timestamp at reset vector

Platform/TigerlakeBoardPkg/Script/StitchIfwiConfig_tglh.py
Config 1/3 RVP boards can't share same IFWI image
and it is required to adjust the FIT parameters.
Add -o cfg3 to support this.
=> [TGL] Add stitch option to support TGL-H RVP Config 3

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CommonSocPkg/Include/Library/WatchDogTimerLib.h, Silicon/CommonSocPkg/Library/WatchDogTimerLib/WatchDogTimerLib.c
This patch solves an infinite reset loop issue caused by bad DSO with the scenario:
- After platform reset (due to WDT timeout), FSPm asks for another reset, but before that, WDT_FLAG_TCC_DSO is already cleaned. As a result, in the thrid reset, stage1B will have no idea about the DSO is corrupted and it continues boot with Tcc Tuning flow, which causes WDT timeout reset again.
This patch introduces a WDT_FLAG_TCC_BAD_DSO flag in WDT scrachpad (bit 18). The flag is a marker that is set when a bad DSO is detected. The new booting flow for "bad DSO" case if Tcc_Tuning enabled will be:
- 1st boot: (after fwupdate)
- TCC_DSO and WDT set by stage1b and stage2
- FSP hangs and trigger WDT reset
- 2nd boot:
- Stage1b detects "bad DSO" because of WDT and TCC_DSO.
- It clears TCC_DSO and WDT.
- …
=> [TGL] Fix infinite reset loop caused by bad DSO

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Ext_Up6000.dlt, Platform/ElkhartlakeBoardPkg/Include/PlatformBoardId.h, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Aaeon UP2 6000 board first boot
1. Added platform ID support
2. Added BoardID read from GPIO
3. Added UP2 6000 dlt file
=> [EHL] UP2 6000 support

BootloaderCorePkg/Tools/BuildUtility.py, BuildLoader.py
Enhance the tool to get config dlt, vbt and VerInfo from
BOARD_PKG2_NAME when it is configured.
With this update, the build tool could find the dlt file
from both BOARD_PKG_NAME and BOARD_PKG2_NAME.
=> Enhance the tool

Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/CometlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
On CFL and CML, the board hook PostMemoryInit was called before
FspMemoryInit API. This should be called afterwards instead.
This patch fixed this issue. It is because of missing "break"
statement. It fixed #1435.
=> [CFL][CML] Fix board hook call sequence issue

BootloaderCorePkg/IncludePrivate/BootloaderCoreGlobal.h
Rearrange SBL Global Data Structure for POSC
issue workaround. This is due to the POSC accessing
SBL Global Data and it get corrupted when SBL rearrange
or restructure the data structure.
=> [EHL] WA for POSC issue

Platform/CommonBoardPkg/Script/BtgSign.py
Currently StitchLoader.py is under platform package, and
the common tool BtgSign.py should not depend on that tool.
And BtgSign.py indeed doesn't depend on it, so just update
it to make it could work without StitchLoader.py.
=> Update BtgSign tool

BootloaderCorePkg/Tools/SingleSign.py
Since openssl 3.0.0, in commit 10203a34725e ("Support writing RSA
keys using the traditional format again"), the default format of
private key has been changed to PKCS#8.
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
=> add private key check for PKCS8 format

Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibCBnT.inf, Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
For bootguard event log fit header location is retrieved
from fit pointer. Added a condition to check the FIT header
range to fix KW error.
=> Check fit header entry location

PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CommonSocPkg/Include/Library/WatchDogTimerLib.h
This patch invalidates the DSO region with a marker when a corrupted DSO hang is detected (by WDT timeout). With the marker, stage1b can know the DSO tuning should be skipped.
The bad DSO mark is defined as both signature and size in the TCCT component header are zero.
With this patch, the previous defined WDT scratchpad bit, WDT_FLAG_TCC_BAD_DSO, is removed..
=> [TGL] Invalidate bad DSO region

Silicon/CometlakevPkg/Library/PchInfoLib/PchInfoLibCmlv.c
According to H410 PCH EDS data, it should be 20.
=> [CMLV] Fix wrong value of PchMaxPciePort

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf, Silicon/CommonSocPkg/Include/Library/TccLib.h, Silicon/CommonSocPkg/Library/TccLib/TccLib.c, Silicon/CommonSocPkg/Library/TccLib/TccLib.inf
IsMarkedBadDso and InvalidateBadDso would be required for all
the platforms that support TCC. And the implementation is also
common, so just move them to common TccLib.
Also updated the implementation to remove SPI flash erase for
InvalidateBadDso().
=> Move DSO update/check to TccLib

PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c
BAD DSO mark is simplified to only use Signature=0
when moving DSO update/check to TccLib.
Related check in fwupdate has to be updated too.
=> Fix fwupdate check for BAD DSO mark

.azurepipelines/azure-pipelines.yml, BootloaderCorePkg/Tools/BuildUtility.py
For Azure and toolchain check we
can update to using IASL version
20190509 since some of the newer
SBL platforms require a newer
IASL version.
=> Update IASL to version 20190509

BootloaderCommonPkg/Library/BootloaderDebugLib/BootloaderDebugLib.inf
There is unresolved external symbol build issue with
BUILD_CSME_UPDATE_DRIVER enabled in BoardConfig.
By adding the BootloaderCommonLib in BootloaderDebugLib
inf file will address this issue.
=> [Common] Fix CSME update build issue

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Increase CFG_DATABASE_SIZE due to the addition
of up6000 dlt file in SBL EHL cfgdata.
=> [EHL] Increase CFGDATA SIZE

PayloadPkg/PayloadPkg.dsc
This patch fixed the HelloWorld payload build failure after the EDK2
code sync up. It was caused by missing RegisterFilterLib class instance.
It fixed #1455.
=> Fix HelloWorld payload build issue

PayloadPkg/HelloWorld/HelloWorld.c
This compiles, but I'm having some other problems which mean that I haven't been able to test the result yet.
I suspect that the automated checks will complain about the length of the quoted compiler output in the commit message. I can't really fix that without making the output unreadable or removing it altogether.
=> HelloWorld: Use ConsolePrint to simplify code and fix GCC build

BootloaderCorePkg/IncludePrivate/BootloaderCoreGlobal.h
Missing of removal MemUsableTop in the data structure
Revert the WA for POSC issue in commit below:
9cd53b6
=> [EHL] Revert the WA for POSC issue Pt2

Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
Current QEMU FSP will not reserve any space for TSEG. This patch
added the support. It will reserve 8MB TSEG space when running on
Simics QSP.
=> Fix QEMU FSP TSEG size issue on Simics

BuildLoader.py
When BOARD_PKG_NAME_OVERRIDE is configured, the tool will get
the payload from package BOARD_PKG_NAME_OVERRIDE instead of
package BOARD_PKG_NAME.
=> Enhance build tool

BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
It may be necessary to build Slimbootloader in situations where Internet
access is not available, or where it is important to ensure that there
is also a local copy of the build dependencies.
It's possible for the correct repositories to be cloned into the right
places outside the Slimbootloader build system. However,
PrepareBuildComponentBin previously insisted on attempting to
fetch from the remote repository every time.
If the .git directory exists, let's first try to check out the required
commit and only if that fails attempt to fetch.
This means that it's possible to stop the Slimbootloader build system
accessing the Internet by arranging for the correct repositories to be
cloned in the right places beforehand and setting the https_proxy
environment variables to unresolvable names …
=> PrepareBuildComponentBin: Avoid network access if commit is already available

BootloaderCorePkg/Tools/BuildUtility.py
The EDK II build tools support applying a prefix for GCC from an
environment variable (e.g. GCC5_BIN). For this to work correctly with
Slimbootloader it's also necessary to use the prefix for the version
check too.
Signed-off-by: Mike Crowe <mac@mcrowe.com>
=> BuildUtility: Support GCC5_BIN prefix

Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/SerialIo.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/SerialIo.h, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/TigerlakePchPkg/Include/GpioPinsVer2H.h, Silicon/TigerlakePchPkg/Include/Pins/GpioPinsVer2H.h
This patch fixes no activity on UART0 pins when enabling it for serial
communication.
In TGL, there are two UART0 instances while the one (GPP_F0 to GPP_F4)
is shared with CNVI. This patch enables GPP_C8~C11 as the UART0 instance
to reduce the conflict with CNVI.
This patch also fixes the GPIO pins definition for TGL-H and moves
serial io initialization code to SerialIo.c to simplfy Stage2BoardInitLib.c.
Test: TGL-UP3 RVP and TGL-H RVP
=> [TGL] Fix UART0 access

Platform/CommonBoardPkg/Tools/GpioDataConvert.py, Platform/ElkhartlakeBoardPkg/Script/GpioDataConfig.py
This patch enhanced GPIO convert tool so that it can handle the
new GPIO template format.
EX:
To convert GPIO from YAML format to CSV format:
python Platform\CommonBoardPkg\Tools\GpioDataConvert.py -cf
Platform\ElkhartlakeBoardPkg\Script\GpioDataConfig.py -if
Platform\ElkhartlakeBoardPkg\CfgData\CfgData_Gpio.yaml
-of csv -o gpio.csv
To convert GPIO from CSV to YAML format:
python Platform\CommonBoardPkg\Tools\GpioDataConvert.py -cf
Platform\ElkhartlakeBoardPkg\Script\GpioDataConfig.py -if
gpio.csv -of yaml -o gpio.yaml -t new
=> [EHL] Enhance GPIO convert tool

Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt
s0ix feature enabling flag also turn off some FSP configs
so that default SBL image can't detect the onboard Lan
and type c devices.
=> [TGL] Disable s0ix on TGLU RVP

.azurepipelines/azure-pipelines.yml
This patch updated python version to be 3.8.x for Azure Pipelines.
Without this change, the Azure Pipeline build will fail.
=> Upgrade python version for Azure Pipelines

BootloaderCorePkg/Tools/ConfigEditor.py
When enable TGL IBECC, the IbeccProtectedRegionMask should be
visible too in the Config Editor but its not happening this way.
Siged-off-by: Randy Lin <randy.lin@intel.com>
=> Fix condition fields may disappear in Config Editor tool

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/CommonSocPkg/Include/Library/PciExpressHelpersLib.h, Silicon/CommonSocPkg/Include/Library/PcieHelperLib.h, Silicon/CommonSocPkg/Include/Library/PciePm.h, Silicon/CommonSocPkg/Include/Library/PlatformInfo.h, Silicon/CommonSocPkg/Library/PciePmNull/PciePmNull.c, Silicon/CommonSocPkg/Library/PciePmNull/PciePmNull.inf, Silicon/TigerlakePchPkg/Include/Library/PchPcieRpConfig.h, Silicon/TigerlakePchPkg/Include/Library/PchPcieRpLib.h, Silicon/TigerlakePchPkg/Include/Library/PcieRpLib.h, Silicon/TigerlakePchPkg/Include/PchPcieRpInfo.h, Silicon/TigerlakePchPkg/Include/PcieConfig.h, Silicon/TigerlakePchPkg/Include/PcieRegs.h, Silicon/TigerlakePchPkg/Include/Register/PchPcieRpRegs.h, Silicon/TigerlakePchPkg/Include/Register/PcieSipRegs.h, Silicon/TigerlakePchPkg/Library/BasePcieHelperLib/BasePcieHelperLib.c, Silicon/TigerlakePchPkg/Library/BasePcieHelperLib/BasePcieHelperLib.inf, Silicon/TigerlakePchPkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.c, Silicon/TigerlakePchPkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.h, Silicon/TigerlakePchPkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.inf, Silicon/TigerlakePchPkg/Library/PcieClientRpLib/PcieClientRpLib.c, Silicon/TigerlakePchPkg/Library/PcieClientRpLib/PcieClientRpLib.inf, Silicon/TigerlakePchPkg/Library/PciePm/PciePm.c, Silicon/TigerlakePchPkg/Library/PciePm/PciePm.inf, Silicon/TigerlakePkg/Include/Register/CpuPcieRegs.h
The patch enables PCIe PM features by,
1. Store Root Port configuration before FSP-s.
2. Configure Pcie RP in PostPciEnumeration with the stored RP config.
The feature is controlled by ENABLE_PCIE_PM and the corresponding PcdEnablePciePm
The implementation is silicon-dependent, because of registers definition.
The PciePmNull component is a generic implementation. This patch also implements PciePm for TGL.
Verified: TGL-U RVP
=> [TGL] Enable PCIe PM features

Platform/AlderlakeBoardPkg/Script/StitchIfwi.py, Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py, Platform/CometlakeBoardPkg/Script/StitchIfwi.py, Platform/CometlakevBoardPkg/Script/StitchIfwi.py, Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py, Platform/TigerlakeBoardPkg/Script/StitchIfwi.py
When run as part of an automated system it's important to ensure that
any failure is reported to the calling process. Writing an error message
and then exiting indicating success leads to difficult-to-diagnose
problems.
=> StitchIfwi: Indicate failure through exit status

Platform/CoffeelakeBoardPkg/AcpiTables/Mcfg/Mcfg.act, Platform/TigerlakeBoardPkg/AcpiTables/Mcfg/Mcfg.act
Current TGL platform set 0 as the PCI end bus number in ACPI
MCFG table. And it caused incorrect MMCONFIG range calculation in
Linux. This patch updated the template to use 0xFF as the PCI
end bus number.
It should fix #1481, to be confirmed.
=> [TGL] Update MCFG table template with correct end bus number

Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/HostBus.asl, Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/Pep.asl, Platform/AlderlakeBoardPkg/AcpiTables/SaSsdt/CpuPcieRp.asl, Platform/AlderlakeBoardPkg/AcpiTables/Ssdt/PcieRpGenericPcieDeviceRtd3.asl, Platform/AlderlakeBoardPkg/AcpiTables/Ssdt/PcieRpSsdStorageRtd3Hook.asl, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
This patch enable S0ix feature in ADLP
1. Ported correct NVS value for ADLP.
2. Ported ACPI value refer to BIOS.
3. Implemented workaround for RP08.
Verified: ADL-P RVP
=> [ADLP] Enable S0ix feature

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/AlderlakePkg/Include/CpuPcieInfo.h, Silicon/AlderlakePkg/Include/Library/PchPcieRpConfig.h, Silicon/AlderlakePkg/Include/Library/PchPcieRpLib.h, Silicon/AlderlakePkg/Include/Library/PcieRpLib.h, Silicon/AlderlakePkg/Include/PcieConfig.h, Silicon/AlderlakePkg/Include/PcieRegs.h, Silicon/AlderlakePkg/Include/Register/PchPcieRpRegs.h, Silicon/AlderlakePkg/Include/Register/PcieSipRegs.h, Silicon/AlderlakePkg/Library/BasePchPciBdfLib/PchPciBdfLib.c, Silicon/AlderlakePkg/Library/BasePcieHelperLib/BasePcieHelperLib.c, Silicon/AlderlakePkg/Library/BasePcieHelperLib/BasePcieHelperLib.inf, Silicon/AlderlakePkg/Library/PchInfoLib/PchInfoLibAdl.c, Silicon/AlderlakePkg/Library/PchInfoLib/PchInfoLibPrivate.h, Silicon/AlderlakePkg/Library/PchPcrLib/PchPcrLib.c, Silicon/AlderlakePkg/Library/PchPcrLib/PchPcrLib.inf, Silicon/AlderlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.c, Silicon/AlderlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.h, Silicon/AlderlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.inf, Silicon/AlderlakePkg/Library/PcieClientRpLib/PcieClientRpLib.c, Silicon/AlderlakePkg/Library/PcieClientRpLib/PcieClientRpLib.inf, Silicon/AlderlakePkg/Library/PciePm/PciePm.c, Silicon/AlderlakePkg/Library/PciePm/PciePm.inf, Silicon/CommonSocPkg/Include/Library/PlatformInfo.h
The patch enables PCIe PM features by,
1. Store Root Port configuration before FSP-S.
2. Configure Pcie RP in PostPciEnumeration with the stored RP config.
The feature is controlled by ENABLE_PCIE_PM and the corresponding
PcdEnablePciePm
The implementation is silicon-dependent, because of registers definition.
The PciePmNull component is a generic implementation. This patch also
implements PciePm for ADL.
Verified: ADL-P RVP
=> [ADL] Enable PCIe PM features

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h, Silicon/AlderlakePkg/Include/Library/CpuPcieHsPhyInitLib.h, Silicon/AlderlakePkg/Library/PciePm/PciePm.c
With latest changes for S0ix, PciePm is expecting GetCpuSku and
GetCpuSkuInfo function declaration in header files. Added these
declarations in CpuPcieHsPhyInitLib header file
=> [ADL] Fix ADL build errors

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Linux build is complaning of an unused variable,
removed that variable to fix build issues.
=> [ADL] Remove unused variable

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Program SLP_A_MIN_ASST_WDTH to 0 on fast boot path
to reduce boot time
=> [ADL] Register change for boot time reduction

Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py, Platform/CommonBoardPkg/Tools/GpioDataConvert.py, Platform/ElkhartlakeBoardPkg/Script/GpioDataConfig.py, Platform/TigerlakeBoardPkg/Script/GpioDataConfig.py
Pass in a pch_series param to GpioDataConvert tool
to fetch the correct gpio group info for a platform
based on the pch series.
The tool expects the platform specific config file to
implement a function vir_to_phy_grp () that returns
a BOOL value based on:
If vir_to_phy_grp = False, SBL's config has A->0, B->1 etc. mapping.
And GpioSiLib.c or GpioInitLib.c corresponding libraries will map
this virtual group #s to real physical group #s (if not same).
If vir_to_phy_grp = True, SBL's config has A->G1, B->G2 etc.
physical mapping directly, so the GpioLib library uses this as is.
GpioDataConfig.py file was added for ADL platform.
Signed-off-by: Sai T <sai.kiran.talamudupula@intel.com>
=> Gpio data convert improvements

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
[ADL] Update Silicon UPD Config
As part of FSP updates for ADLPtest board, update
Silicon UPD settings.
TEST=Validated boot on the RVP board.
=> [ADL] Update Silicon UPD Config

Platform/TigerlakeBoardPkg/AcpiTables/CpuSsdt/CpuSsdt.asl
Fix two errors:
ACPI Error: Aborting method \_SB.PR00.GCAP due to previous error
(AE_INVALID_TABLE_LENGTH)
ACPI Error: Aborting method \_SB.PR00._PDC due to previous error
(AE_INVALID_TABLE_LENGTH)
UEFI BIOS always does dynamic loading, but SBL does static loading
instead.
=> [TGL] Fix ACPI Errors reported in kernel dmesg

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
This patch fixes the test case where when a bad dso is
provided, it will revert back to the default dso settings.
TEST= Ran the test case successfully on ADLS board.
=> [ADLS] Fix bad DSO failure test case

BootloaderCorePkg/BootloaderCorePkg.dsc, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, Platform/QemuBoardPkg/Script/TestCases/firmware_update.py
This patch enables graphics console when entering FWU payload.
FWU progress will show on both graphics console and serial port.
Signed-off-by: kokweich <kok.wei.chan@intel.com>
=> Enable Grahpics Console during firmware update

Silicon/CommonSocPkg/Include/Library/IgdOpRegionLib.h, Silicon/CommonSocPkg/Library/IgdOpRegionLib/IgdOpRegionLib.c
Current VBT patching uses a static big structure VBT_TABLE_DATA to
parse the VBT data. It is not reliable because the sub structures
within VBT_TABLE_DATA might change between different revision. A
better solution is to look through each block data using the common
block header info. It can provide better back compatibility.  This
patch implemented this.
It fixed #1504.
=> Update VBT patching by dynamically locating block

BootloaderCommonPkg/Library/ShellLib/CmdPci.c
According to PCI spec, it is required to check the multi-function
support in PCI configuration header type before scanning next PCI
function. Current SBL does not follow this, and it caused duplicated
PCI devices listed in Shell command "lspci".  This patch fixed
this issue.
=> Fix incorrect lspci behavior for multi-function PCI device

BootloaderCommonPkg/Library/SerialPortLib/SerialPortLib.c
If there is DEBUG output during PCI enumeration, it could cause SBL
hang due to invalid PCI bar resource. In this case, SBL will force
to return 0 for any serial port register read. And it might cause
dead loop because of LSR_TXRDY bit polling in SerialPortWrite().
To avoid this potential dead loop, it is required to set LSR_TXRDY
bit for LSR_OFFSET register read if the PCI resource is invalid.
=> Enhance SerialPortLib to handle debug output during PCI enumeration

BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.c, BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c, BootloaderCorePkg/Tools/BuildUtility.py, BuildLoader.py
Current SBL PCI enumeration does not allocate resource for PCI ROM
bar because SBL does not deal with option ROM at all. However, the
Linux kernel might expect the ROM bar resource to be allocated.
This patch introduces a static build configuration to allow support
PCI resource allocation for PCI ROM bar.
To enable this feature, please add following into the project
BoardConfig.py file:
self._PCI_ENUM_FLAG_ALLOC_ROM_BAR = 1
By default, it will be disabled to keep the same behavior as before.
=> Add support for PCI expansion rom resource allocation

BootloaderCorePkg/Stage1A/Stage1A.c, BootloaderCorePkg/Stage1A/Stage1A.h
CPU signature and ucode revision are ciritical info and should be
printed out as early as possible. This patch adds the info print
in SBL Stage1A.
=> Add CPU signature and ucode revision print

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/MiscInit.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
Removed RTC logic, it is problematic and should not be used,
all other platforms are not using this logic and
we should remove this from the code
=> [ADL] Remove RTC logic in payload switching

BootloaderCommonPkg/Include/Guid/MpCpuTaskInfoHob.h, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Include/Library/MpInitLib.h, BootloaderCorePkg/Stage2/Stage2Hob.c, MdePkg/Include/Protocol/MpService.h, PayloadPkg/Include/Library/MpServiceLib.h, PayloadPkg/Library/MpServiceLib/MpServiceLib.c, PayloadPkg/Library/MpServiceLib/MpServiceLib.inf, PayloadPkg/OsLoader/OsLoader.h, PayloadPkg/OsLoader/OsLoader.inf
This patch adds a MpServiceLib for payload so that a payload
can utilize this library to run tasks on specified processor.
=> Add MP service for payload

PayloadPkg/Library/PlatformHookLib/PlatformHookLib.c, PayloadPkg/Library/PlatformHookLib/PlatformHookLib.inf
Universal Payload defined new HOBs for serial port information.
This patch switched to use the new hob instead of the old one to
retrieve serial port information.
=> Use Universal Payload hobs for serial port info

BootloaderCommonPkg/Library/ShellLib/CmdFs.c, Platform/TigerlakeBoardPkg/BoardConfig.py
This patch adds "fs load" command to SBL shell so that it can be
used to load a file from boot media into memory. It also supports
loading file at specified memory address.
=> Add FS load Shell command

BootloaderCommonPkg/Include/Guid/SerialPortInfoGuid.h, BootloaderCorePkg/Stage2/Stage2Hob.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch added a new 64bit base field in the loader serial
port hob to support 64bit resource. The revision is updated
to 2. It is backward compatible with revision 1.
=> Update loader serial port hob to support 64bit base

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This patch adds control option for TCO timer.
Use case: the control option shall be enabled when Linux hw watchdog driver (iTCO) is enabled.
Verified: TGL-UP3 RVP
=> [TGL] add TCO Timer control option

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Some of the RTCT table entries werent populated due to this
missing UPD setting. Hence, assigning it to the correct value.
TEST= Verified the fix on ADLS board.
=> [ADLS] Fix Tcc issue caused due to incorrect UPD setting.

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Add PchPseAicEnabled and PchUnlockGpioPads in
CfgData_Silicon.yaml file to allow modification
using Config Editor tool.
=> [EHL] UPDs for Zephyr support

Silicon/TigerlakePchPkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.c
KW reported the expression 'Override->Table[Index].RevId'
can never reach the value '0xFFFF', where RevId is of type UINT8
=> [TGL] fix KW issue

Platform/CommonBoardPkg/CfgData/CfgData_PayloadSelection.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglh_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt, Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Previous commit fe6cf3272 unexpectedly changed the AUTO payload-switching behavior.
This patch restores the behavior to the original design.
Verified: TGL-UP3 RVP
=> [TGL] Restore AUTO payload-switching behavior

Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlTsn.h, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
Unlike ADLS, TSN link speed will be coming from the Cfg data.
New TSN GPIO table needed for ADLN board.
=> [ADLN] Add TSN support

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
The default big core number was set to 8, it has to be overridden if
the CPU number is not 8. Had better set to 0xFF to all active big cores.
Also it mentioned the default value is 0xFF in the help message.
=> [RPLS] Update big core number default value

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf
This patch fixed build issues caused by adding L2QosEnumerationEn UPD
which is not present on other ADL platforms.
=> [ADLS] Fix build issues

Platform/TigerlakeBoardPkg/BoardConfig.py, Silicon/TigerlakePkg/FspBin/FspBin.inf
- update FSP version to IoT FSP 4391_03 (0A.00.66.13)
- update TGL platform version to 1.5
=> [TGL] Update FSP and platform version since MR5 is released

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/TigerlakeBoardPkg/CfgData/CfgData_Tsn_Feature.dlt, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
New FSP (from 0A.00.66.12) supports switching TSN GbE ports
Enable/Disable individually. SBL requires CfgData change
accordingly to avoid build errors.
=> [TGL] Support individual TSN ports Enable/Disable

Platform/CometlakeBoardPkg/BoardConfig.py, Platform/CometlakeBoardPkg/Script/StitchIfwiConfig.py, Platform/CometlakevBoardPkg/BoardConfig.py, Platform/CometlakevBoardPkg/Script/StitchIfwiConfig.py, Silicon/CometlakePkg/FspBin/FspBin.inf, Silicon/CometlakePkg/Microcode/Microcode.inf, Silicon/CometlakevPkg/FspBin/FspBin.inf, Silicon/CometlakevPkg/Microcode/Microcode.inf
- FSP:
* 09.03.7B.20 for CML-S
* 09.01.7B.20 for CML-V
* bpmgen2_params: set VTD_BAR to 0xFED91000
- Microcode:
* m22A0653_000000EA.mcb  # G1-Step
* m22A0655_000000EC.mcb  # Q0-Step
- update CML platform version to 1.1
=> [CML] Update FSP, UCODE and platform version since MR1 is released

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BuildLoader.py, Platform/CometlakeBoardPkg/BoardConfig.py, Platform/CometlakevBoardPkg/BoardConfig.py
SBL uses PcdMemoryMapEntryNumber to control the max entry
number of memory map info HOB. In some platforms, CML
encountered "Memory map failure" due to the actual entry
number exceeding it. So increase the max to accommodate
the case.
=> [CML] increase the max memory map entry number

BootloaderCorePkg/Tools/GenContainer.py
During stitch phase, it would stitch failure if the data
is not signed and the data for the subregion is too small,
so enhance the tool to support the corner case.
=> Enhance GenContainer.py

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
This patch assigns Timed GPIO Cfg Data to the NVS variables
in order for the OS to load this driver.
=> [ADL] Expose Timed GPIO to OS

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
The CPU stepping condition is not needed anymore for ADLS.
Removing it for now.
=> [ADL] Remove Cpu stepping condition for HT

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
WRDS is not defined for ADLN. Hence, add a condition so that
it is skipped for ADLN.
=> [ADLN] Fix build issue

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCommonPkg/Library/UsbBlockIoLib/PeiAtapi.c, BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.inf, BootloaderCorePkg/BootloaderCorePkg.dsc, BuildLoader.py
A USB disk behind a hub may take longer time to respond command.
Prior to the patch, a magic 2000 ms is set. This patch introduces a python control (USB_CMD_TIMEOUT) for customizing the timeout if need. The patch also extends the default timeout to 0x1000 (4096) ms.
This patch does not impact booting time when a platform boots with a good-conditioning usb disk, because the timeout only takes effect when a disk does not respond to a USB inquiry for a long time.
Verified: Ehl RVP
=> Add USB command timeout control

PayloadPkg/OsLoader/OsLoader.c, Platform/CommonBoardPkg/CfgData/CfgData_Common.yaml, Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
By default OsLoader payload shell is only available in debug build.
In some case customer also wants to have shell in release build.
So add a BootToShell configuration item to enable shell in release build.
By default BootToShell is set to 0. When it is set to 1 the shell behavior
would be same in release and debug build.
NOTE: user could add this line in platform dlt file to set BootToShell.
GEN_CFG_DATA.BootToShell  |1
=> Add BootToShell configuration item

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf, BuildLoader.py
Different use case might want to have a different CPU order.
e.g. P-core first or E-core first.
This patch adds an option to help user sort CPU.
platform could add "self.CPU_SORT_METHOD  = value" to
BoardConfig.py to override the default value.
=> Support different CPU sort method

Platform/AlderlakeBoardPkg/BoardConfigAdlS.py
Match the FSP include path from Board Config to that of
FspBin inf file so it fixes the build issue.
=> [ADLS] Fix build error

.azurepipelines/azure-pipelines.yml
This patch enabled auto build for ADLS Azure Pipeline.
=> Enable Azure Pipeline build for ADLS

Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Only enabled IehMode when IBECC error injection is disabled
Iehmode will cause failure in IBECC error injection test
=> [EHL] Fix IBECC error injection

Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This reverts commit 1caacefeb508a41c4363e64ce45159b72f4b2f73.
The USB port that does not respond to USB bus enumeration is port 8 on
the newer UPX board. The old UPX board might have different behavior.
The original commit was valid on old UPX board only, and this patch
reverted it. Confirmed the USB error message disappeared on the new
UPX board after the reverting.
Signed-off-by: Maurice Ma <mauricemx.ma@gmail.com>
=> Revert "[UPX] Disable malfunctioned USB2 port"

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/BoardSaConfigPreMem.h, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Silicon/AlderlakePkg/Library/IgdOpRegionLib/GopConfigLib.h, Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c
This patch added changes required for ADLN FSP Sync and
also did the following
1) Added SA config for DDR5 CRB
2) Initialized VBT to enable 2 HDMI and a DP port
3) Moved FSPM config to delta file
=> [ADLN] Changes required for ADLN FSP Sync

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/FspBin/FspBin.inf
Also set the CpuTempSensorReadEnable = 1
It was renamed from PchCpuTempSensorEnable
and removed in commit 44faa431c97
=> [EHL] Update FSP version since MR3 is released

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
PSE is enabled by default.
During SBL building, it will check the existence of PSE FW binary.
If it is missing in binaries folder, the PSEF won't be appended in
container list and cause StitchIFWI script fail if it try to update.
=> [EHL] Refine the PSE FW stitch logic

Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Silicon/AlderlakePkg/Include/CpuRegs.h
FSPT doesn't allow to enable full flash code cache.
Bootloader configures MTRR in non BTG cases to avoid
performance penalty.
This fixes the ADL boot from BP1 partition.
=> [ADL] Configure MTRR to enable full flash region cache

Platform/AlderlakeBoardPkg/CfgData/CfgData_Gpio.yaml, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
Add GPP_T as part of the base cfg in order to use for
other ADL flavors like ADL PS.
=> [ADLN] Add GPIO configuration from Cfg Data

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Connectivity.asl
Sync from EHL BIOS.
Error: ACPI BIOS Error (bug): AE_AML_BUFFER_LIMIT, Field [IOF2] at
bit offset/length 712/16 exceeds size of target Buffer (664 bits)
=> [EHL] Fix ACPI error

BootloaderCorePkg/Tools/PrepareBuildComponentBin.py, BuildLoader.py
While attempting uCode capsule update on ADL-N and RPL-S, it was noticed that solution provided as part of #1569 does not consider platforms which have not yet been migrated into SBL open source. This patch adds that consideration.
=> Allow uCode Padding to Occur on Inner Source Platforms

Platform/AlderlakeBoardPkg/CfgData/CfgData_Power.yaml, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/CpuInfoLib.c, Silicon/AlderlakePkg/Include/Register/SaRegsHostBridge.h
This patch enable S0ix feature in ADLPS
1. Disabled PCH LAN.
2. Added ADLPS FSPS UPD update.
3. Added ADLPS NVS value update.
4. Added ADLPS CPU SKU Device ID.
Verified: ADL-PS RVP
=> [ADLPS] Enable S0ix feature

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
HsPhy feature is only applicable for ADLS and not for others.
Adding a condition to apply only for it.
=> [ADL] Fix HsPhyInit failure

BootloaderCorePkg/BootloaderCorePkg.dsc, BuildLoader.py
This change leverages the --align parameter on GenFw.exe to perform uCode slotting, when configured
=> Leverage EDKII Build System to Perform uCode Slotting

Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4.dlt
This patch fixes the hang seen during a reboot cmd on ADLS DDR4 board.
Setting the DmiMaxLinkSpeed to Auto mode.
=> [ADLS] Resolve reboot issue on DDR4 board

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
This patch fixed BDF for UFS device, bus number and function
number are improperly ported and this patch fixed the issue.
=> [ADL] Update BDF for UFS device

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
This patch fixes the KW issue that is reported due to NULL
pointer deference. Moved up the code where CfgData checks for NULL.
=> [ADL] Fix KW issue

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlPsPostMem.h, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
- Updated GPIO table to match BIOS PV ER3 release.
- Disable SCI for D13 and E00.
- Process the GPIO table from dlt file instead
of the hard-coded table. The mGpioTablePostMemAdlPsDdr5Rvp
is only for reference purposes.
- Move DEBUG CODE END to later part of the GPIO function in
order to add GPIO prints when required.
=> [WIP] [ADLPS] Process GPIO from Cfg Data

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlPsPostMem.h
SCI storm is happening for GPIO pins D13 and E00.
Disable them as not needed.
=> [ADLPS] Disable SCI for hibernate issue

BootloaderCommonPkg/Library/XhciLib/XhciSched.c
[KW] A buffer is not initialized before being passed as
an argument. Initializing it to null
=> KW fix for un-initialized buffer

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Security.yaml, Silicon/ElkhartlakePkg/Library/PsdLib/PsdLib.c, Silicon/ElkhartlakePkg/Library/PsdLib/PsdLib.inf
Found PSDS ACPI table reporting incorrect value
and fix by referring the BIOS method to retrieve
right value. Also Enable Platform Security Discovery.
Verify on CRB platform.
=> [EHL] Read SecCapability from Mbp Data HOB as priority

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlPsPostMem.h, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
- Process the GPIO table from dlt file instead
of the hard-coded table. The mGpioTablePostMemAdlPsDdr5Rvp
is only for reference purposes.
- Move DEBUG_CODE_END to later part of the GPIO function in
order to add GPIO prints when required.
=> [ADLPS] Updated GPIO table to match BIOS PV ER3 release.

Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4_Sodimm.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5_Sodimm.dlt
When S0ix feature is enabled, some controllers are disabled
and ethernet/lan is one of them. Hence, disable by default so
that other controllers can be enabled by default.
=> [ADLS] Disable S0ix by default

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
For enabling the M.2 SATA devcie in CRB,
The FiaLaneReversalEnable value is 16 in CfgData_Memory.yaml.
=> [EHL] Add FiaLaneReversalEnable FSP-M config

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/CpuInfoLib.c
- Enable Tcc code path for N series.
- Disable WDT lock UPD since its causing the WDT to expire
even when valid DSO is provided.
- Code clean-up.
=> [ADLN] Tcc enabling

Platform/AlderlakeBoardPkg/CfgData/Template_Gpio.yaml
Enable GrpIdx overwrite capability when using
Config Editor tool.
=> [ADLP] Enable GrpIdx overwrite capability

Silicon/CommonSocPkg/Include/GpioConfig.h, Silicon/CommonSocPkg/Include/Library/GpioLib.h, Silicon/CommonSocPkg/Library/GpioLib/GpioLib.c
This patch adds a new GpioGetStrapValue() helper function which allows
reading the pin-strap value of GPIO pins.  This is useful for reading
the value of hard straps or of BOARD_ID pins or of other GPIOs for
which the input buffer may be disabled, as the pin-strap value bit is
valid even when a pin's input buffer has been disabled.
=> Add GpioGetStrapValue() helper function

Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciPeiDxe.c
This PR fixes the following error for x64 TGL builds, observed on gcc 11.2 (Ubuntu 22.04).
```
Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciPeiDxe.c:568:1: error: conflicting types for ‘HeciRevokeOemKey’; have ‘EFI_STATUS(void)’ {aka ‘long long unsigned int(void)’}
568 | HeciRevokeOemKey (
| ^~~~~~~~~~~~~~~~
In file included from Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciPeiDxe.c:12:
Silicon/TigerlakePchPkg/Include/Library/HeciInitLib.h:391:1: note: previous declaration of ‘HeciRevokeOemKey’ with type ‘EFI_STATUS(void)’ {aka ‘long long unsigned int(void)’}
391 | HeciRevokeOemKey (
| ^~~~~~~~~~~~~~~~
make: *** [GNUmakefile:306: Build/BootloaderCorePkg/RELEASE_GCC5/X64/Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciInitLib/OUTPUT/HeciPeiDxe.obj] Error 1
```
=> [TGL] Fix x64 builds

Platform/ElkhartlakeBoardPkg/BoardConfig.py
verified on EHL CRB with ubuntu 20.04.
=> [EHL] Enable Ubuntu boot support

Platform/TigerlakeBoardPkg/BoardConfig.py, Silicon/TigerlakePkg/FspBin/FspBin.inf, Silicon/TigerlakePkg/Microcode/Microcode.inf
- update FSP version to IoT FSP 5143_01_MR6 (0A.00.7B.31)
- update VBT version to IoT FSP 5143_01_MR6 (250)
- update TGLU microcode version to A4
- update TGL platform version to 1.6
=> [TGL] Update FSP/VBT/UCODE/platform version since MR6 is released

PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
This patch fixes the support of a capsule file placed in a filesystem
whose fs type is specified by CAPSULE_INFO_CFG_DATA.FsType.
Verify method:
1. Set disk/partition CAPSULE_INFO_CFG_DATA to a volume of ext2 fs
2. Set CAPSULE_INFO_CFG_DATA.FsType = 2 (AUTO)
3. Place FwuImage.bin to the volume
4. Run firmware update test
Verified: EHL CRB
=> FWU: support capsule file placed in non-FAT FS

BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c
If customer uses a non-English version (e.g. Chinese)
Windows OS, the build error will happen.
Signed-off-by: Gavin Xue <gavin.xue@intel.com>
=> Fix build error caused by non-ASCII characters

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
In A/B update, after FWU updates partition B, it switches to and boots with partition B. If boot fails because of anything wrong with the update, CSME will switch back to booting with partition A.
Before this patch, unfortunately, the EnforceFwUpdatePolicy will immediately try to boot again with partition B, which results in an infinite FWU loop:
try B -> failed -> boot A -> try B -> failed ...
(Same for initial with "try A" scheme)
This patch adds a retry count field in FW_UPDATE_STATUS.
Using retry count field to determine if retry also reaches a max times. If so, stop the loop.
To simplify the implementation for SPI, the retry count field is implemented as continuous 1 (ONE) of a bit array.
Test scenarios:
Case 1. update bios region. Expectation: PASS
Case 2. update non-bios region. …
=> FWU: fix infinite fwu caused by a/b update failure

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Tcc_Feature.dlt, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
When some settings from DSO caused system hang,
the WDT would cause the system reboot.
And in the next boot, SBL would use the default
setting by not apply the DSO values.
Verify on EHL CRB.
Signed-off-by: Aiman Rosli <muhammad.aiman.rosli@intel.com>
=> [EHL] Enable WDT for TCC

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c, Silicon/ElkhartlakePkg/Include/PseConfig.h
EHL DMA controllers are hidden at PSF level in reference code,
DMA controllers are reported as ACPI devices if ownership is Host.
So should not check DMA PCI header for DSDT table patching.
Update the change follow EHL reference code.
Signed-off-by: Gavin Xue <gavin.xue@intel.com>
=> [EHL] Fix Kernel DMA driver cannot be registed issue

BootloaderCorePkg/Tools/GenCapsuleFirmware.py
When firmware update is processing BIOS payload, it will
locate Stage1A FV and get SBL version file for verification.
The files in FV are expected to be located at 8-byte aligned
offset. There is chance to break the alignment when a payload
of variable size, e.g. CMDI file, is packed in front of BIOS
payload. So this patch adjusts the starting offset of BIOS
payload to be 8-byte aligned with 0xFF paddings.
=> FWU: Adjust the starting offset of BIOS payload in capsule

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
This patch is to support OEM root key revocation feature.
When the firmware update is done processing CSME payload
containing OEM KM with revocation extension, the system
needs to reset for the changes to take effect. Otherwise,
the following CMDI {OEMKEYREVOCATION} command will fail.
=> FWU: reset the system after CSME firmware update

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Silicon/ElkhartlakePkg/FspBin/FspBin.inf, Silicon/ElkhartlakePkg/Microcode/Microcode.inf
- update FSP version to MR4 FSP (09.04.25.11)
- update VBT version to MR4 FSP (244)
- update microcode version to 16
- update EHL platform version to 1.4
=> [EHL] Update FSP/VBT/UCODE/platform version since MR4 is released

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, Platform/AlderlakeBoardPkg/AcpiTables/Fwst/Fwst.aslc, Platform/CoffeelakeBoardPkg/AcpiTables/Fwst/Fwst.aslc, Platform/CometlakeBoardPkg/AcpiTables/Fwst/Fwst.aslc, Platform/CometlakevBoardPkg/AcpiTables/Fwst/Fwst.aslc, Platform/ElkhartlakeBoardPkg/AcpiTables/Fwst/Fwst.aslc, Platform/TigerlakeBoardPkg/AcpiTables/Fwst/Fwst.aslc
The steps of OEM key revocation are:
1. Replace OEM KM (signed with key2) by updating CSME
2. Replace BIOS region (signed with key2)
3. Reboot with new BIOS region (to make key1 inactive)
4. Revoke key1
Before this patch, it requires 2 firmware updates and 2 capsules for
step 1~2 and step 4 respectively. The patch combines them into a single
update/capsule.
To implement the feature, the patch:
1. Double max # of payloads to allow CSME/CSMD/BIOS/CMDI update
in one capsule image.
2. Prevent from failing update of a critical component.
e.g., if step 1(CSME) fails, step 2(BIOS) should be skipped
Verified cases:
Case 1: Capsule having CSMD/CSMD/BIOS/CMDI.
Expectation: successful
$ python BootloaderCorePkg/Tools/GenCapsuleFirmware.py \
-p CSME FWUpdate.bin \
-p CSMD CsmeUpdateDriver.efi \
-p …
=> FWU: support OEM key revocation together with BIOS/CSME update

Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py, Platform/CommonBoardPkg/Tools/GpioDataConvert.py
The patch adds support of "GPD" group when parsing a .h header file.
It also
- adds supports for Pch-N,
- fixes leading whitespaces in h file
Test commands:
$ python Platform/CommonBoardPkg/Tools/GpioDataConvert.py \
-cf Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py \
-if example_adls.h -of dlt -p s \
-o out_adls.dlt
$ python Platform/CommonBoardPkg/Tools/GpioDataConvert.py \
-cf Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py \
-if example_adls.h -of yaml -p s \
-o out_adls.yaml
$ python Platform/CommonBoardPkg/Tools/GpioDataConvert.py \
-cf Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py \
-if out_adls.yaml -of h -p s \
-o out_h_from_yaml.h
$ python Platform/CommonBoardPkg/Tools/GpioDataConvert.py \
-cf Platform/AlderlakeBoardPkg/Script/GpioDataConfig.py \
-if …
=> [Tools] Enhance GpioDataConvert to support GPD group

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlNPostMem.h, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CommonBoardPkg/Tools/GpioDataConvert.py
- Process Gpio Cfg data from the dlt file instead of the hard-coded
GPIO table.
- The table in the PostMem hdr file is only for reference.
=> [ADLN] Gpio Cfg data from dlt file

Dockerfile
acpica-tools needed to be updated from 20190509-6 to 20190509-7 due to
package availability but the newer tool depends on a newer libc that is
not present in Ubuntu 18.04.
Update Ubuntu instead to fix both issues since Ubuntu now has acpica-tools
included in its repositories
Signed-off-by: Atharva Lele <atharva.lele@intel.com>
=> Dockerfile: Update Ubuntu container to 22.04

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/GpioTableTestPreMem.h, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Premem GPIO table for S17 board caused boot hang,
so revert the change back.
=> [TESTS] revert the premem gpio change for S17 board

BuildLoader.py
Allow for SG1B and UCOD to be moved into the TS region
The actual movement of these regions will occur in BoardConfig*.py files in the Intel internal SBL platform repo
=> Move SG1B and UCOD into TS region

Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/Pep.asl
Remove OS version check in PEPD _STA method. This is a change to the intelpep.sys ASL device (PEPD) for low power idle support. Previously, _STA would always return present/enabled for Win10 even if S0ix config flag was disabled. Changed version always returns status based on S0ix flag. Without this workaround, S4 resume was failing on ADL-N/P/PS.
=> [ADL-N/P/PS] Workaround for S4 resume when S0ix disabled.

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Previous setting of SW-first CM mode was causing a hang during S3/S4 entry. Likely this setting requires additional ACPI/driver support which is missing.
=> [ADL-P] Revert USB4 CM mode to FW CM only.

BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
- If BIOS update is followed by any payload,
reboot to ensure the update is completed.
- Before processing CMDI payload, ensure CSME update has
taken effect to prevent {OEMKEYREVOCATION} command failure.
=> FWU: refine the reboot timing for different payload combinations

BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHci.c, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHci.h, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsInternal.h, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsPciHc.h, BuildLoader.py, Platform/ApollolakeBoardPkg/BoardConfig.py, Platform/CometlakeBoardPkg/BoardConfig.py, Platform/CometlakevBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/BoardConfig.py
This Patch adds the support for UFS(Universal Flash Storage)
as a boot media.
- Added support to Enable all Lun's for UFS
- Added support to change power modes in UFS
- Enable Bus master for proper PCI addressing
Signed-off-by: Aakash Panwar <aakash.panwar@intel.com>
Signed-off-by: Chirag Vijay Kolhe <chirag.vijay.kolhe@intel.com>
=> Enable UFS support for common Intel Platforms.

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/LowPowerSupport.c
FSP-S UPD format for THC port assignment was updated, but PEP logic
was using the old format, and causing the PEP constraint to always be
enabled. This issue didn't seem to be causing a problem, but resulted
in noncompliant low power idle constraints.
=> [ADL] Fix for THC1 PEP constraints appearing when device is disabled.

BootloaderCommonPkg/Library/ShellLib/CmdUsbDev.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.h, BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
New shell command 'usbdev' added to enumerate USB bus and list down
all the USB devices that are found on the bus.
Signed-off-by: Biswas Arghya <arghya.biswas@intel.com>
=> Add shell command to list USB devices

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Restore SMM registers was done in the PostPciEnumeration.
so remove the duplicated code in EndOfStages
and call ClearS3SaveRegion() in normal path to avoid
appending multiple restore records.
=> [ADL] Remove duplicated S3 code

Silicon/ElkhartlakePkg/Library/HeciInitLib/HeciHpet.c, Silicon/TigerlakePchPkg/Library/HeciInitLib/HeciHpet.c
The HPET timer address is wrong at first time invoke.
Assign to fixed value directly.
Verified on EHL TGLU.
=> [TGL][EHL] Fix CSME FW update hang on debug fsp build

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Current PlatformNvs parameters are causing the power management
(S3, S4 and S5) in Windows OS. Removing the Nvs parameters will fixed
the issues.
=> [ADLPS] Remove PlatformNvs parameters

Platform/CommonBoardPkg/Tools/GpioDataConvert.py
For PAD name (e.g., GPD12), current GpioDataConvert.py get the
pad number using pad_name[4:6]. It should be changed to pad_name[3:5].
=> Enhance GPIO convert tool for GPD group support

BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5.dlt
- Increase PlatformMemorySize to get rid of FSP error caused
during Tcc SRAM init.
- Sort the CPUs in ascending order for Tcc validation purpose.
=> [ADLS] Tcc related fixes

Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Silicon/AlderlakePkg/FspBin/FspBin.inf, Silicon/AlderlakePkg/Microcode/Microcode.inf
- FSP version - 0C.00.69.74
- Vbt version - 1077
- Microcode version - m_07_90672_00000023
- Minor version updated to '2' for MR2.
=> [ADLS] Update FSP/VBT/UCODE/platform version since MR2 is released

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h, Silicon/AlderlakePkg/Include/Register/PmcRegs.h, Silicon/AlderlakePkg/Include/Register/RtcRegs.h
Clear the RTC EN SCI flag to avoid interrupt storming
that cause system hang when using rtcwake method to perform
powre management test
=> [ADL] Clear RTC EN SCI to avoid interrupt storming

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
Adds a null check before dereference of a pointer
in the FW recovery flow
=> Resolve Klocwork alarm

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Without initializing CPU fan control, EC will stop CPU fan after default
timeout. This patch initializes CPU fan control and fail safe control.
Some scenarios are related to the case: (1) bootloader shell;
(2) unexpected hang; (3) OS with no ACPI support; and (4) OS fails to
load ACPI driver
Test method:
1. monitor CPU fan under SBL / UEFI Payload shell: expect non-stop
2. check CPU fan status after Linux starts: expect ACPI controls it
Verified: TGL RVP
=> [TGL] Init EC CPU fan control

PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c, PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.inf
=> [Common] Fix Osloader hang when HAVE_ACPI_TABLE=0

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlPsPostMem.h
Add the hard-coded GPIO table to the header file for reference purposes.
This table is currently part of the configuration.
=> [ADLPS] Add GPIO table for PS CRB for reference.

BootloaderCommonPkg/Include/FirmwareUpdateStatus.h, BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h, BootloaderCommonPkg/Include/Library/FirmwareUpdateLib.h, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Include/Library/FirmwareResiliencyLib.h, BootloaderCorePkg/Library/FirmwareResiliencyLib/FirmwareResiliencyLib.c, BootloaderCorePkg/Library/FirmwareResiliencyLib/FirmwareResiliencyLib.inf, BootloaderCorePkg/Stage1B/Stage1B.c, BootloaderCorePkg/Stage1B/Stage1B.h, BootloaderCorePkg/Stage1B/Stage1B.inf, BootloaderCorePkg/Stage2/Stage2.c, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Silicon/AlderlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c, Silicon/AlderlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.inf, Silicon/CommonSocPkg/Include/Library/WatchDogTimerLib.h, Silicon/CommonSocPkg/Library/WatchDogTimerLib/WatchDogTimerLib.c
If TS bit flipped and it does not match FWU state,
assume ACM detected corruption in SG1A or SG1B and
recover broken BP
Add WDT trigger for recovery
Add ADL-specific WDT trigger for TS
=> Cover IBB corruption in SBL resiliency implementation

BootloaderCorePkg/Stage2/Stage2.c, PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
Stop TCO timer in beginning of FWU PLD
to ensure it is started without error
=> Stop TCO timer in beginning of FWU PLD

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Check EC UPD flag prior to publish ECDT table and send EC cmd. On Ecless board, EC ACPI object will not be invoked.
=> [ADLPS] resolve ACPI error from yocto dmesg

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Added M.2 related PlatformNvs GPIO value for CRB board
=> [ADLPS] Add PlatformNvs for CRB

Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/CmdGpio.c, Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf
Updated the GPIO shell command to take GPIO group and pin number as inputs.
Signed-off-by: M Karuppasamy <karuppasamy.m@intel.com>
Signed-off-by: Akshatha Thekkade <akshatha.thekkade@intel.com>
=> GPIO shell command enhancement for ADL platform

BootloaderCorePkg/Tools/CorruptComponentUtility.py
Create a pre-runtime tool that corrupts SBL components so that the SBL resiliency feature can more easily be tested and demonstrated
=> Create Python tool for SBL component corruption

BootloaderCommonPkg/Library/LiteVariableLib/LiteVariableLib.c
Argument DataLen of function InternalGetVariable() inside Reclaim() function is not initialized. This uninitialized value is assigned to another variable and compared, resulting in EFI_BUFFER_TOO_SMALL error when Data is NULL. Hence added Data NULL conditional check with DataLen to overcome EFI_BUFFER_TOO_SMALL error when Data is NULL.
Signed-off-by: M Karuppasamy <karuppasamy.m@intel.com>
=> [LiteVariable] Added Data NULL conditional check in InternalGetVariable()

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Plaform is halted when TPM is not detected.TPM support is enabled with BTG 0 and boot halted when PTT is not enabled in straps.
TPM should be able to boot when TPM is not present and this patch fixes this issue.
=> TPM: Continue boot platform when TPM is not present

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
MemTestOnWarmBoot UPD added into Config Editor. This UPD is enabled to ensure Base Memory Test is running in SBL.
Signed-off-by: Syahirah Sabryna <nur.syahirah.sabryna.mohmad@intel.com>
=> [EHL] Add MemTestOnWarmBoot UPD to Config Editor

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Change USB4 CM Mode to 0. This value is consumed by FSP and UEFI BIOS but not by SBL. Different setting causes issue with TBT device in Windows which might result in CATERR.
Tested to boot Windows and Yocto.
=> [ADLPS] Resolve CATERR issue from Windows shutdown

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c
The patch fixes SIO UART in COM mode by providing Acpi Gns correct values.
Test method: grep 16550A /proc/tty/driver/serial
If a SIO UART run in COM mode, its MMIO should be in
FE020000 ~ FE035FFF (EHL serial IO in ACPI mode).
Verfiied: EHL CRB
=> [EHL] Enable SIO UART in COM mode

Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/CmdGpio.c
This patch fixes initialization issue identified
by Klocwork in function GpioPadcalc.
Signed-off-by: M Karuppasamy <karuppasamy.m@intel.com>
Signed-off-by: Akshatha Thekkade <akshatha.thekkade@intel.com>
=> [ADL] GPIO shell command Klocwork issue fix

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.inf, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf
PcdTccEnabled was declared as a FeaturePcd which evaluates to a code symbol and can't be used in a #if. From the preprocessor perspective it is always undefined. Changed this pcd to a FixedPcd instead.
=> fix: [ADL] TCC was never getting enabled via the board config option.

BootloaderCorePkg/Stage2/Stage2Hob.c
PR #1695 possible NULL deregerence was triggering static analyzer failure. Added a NULL check before dereferencing.
=> fix: Check for possible NULL dereference introduced in #1695.

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Silicon/ElkhartlakePkg/FspBin/FspBin.inf, Silicon/ElkhartlakePkg/Microcode/Microcode.inf
- update FSP version to MR5 FSP (09.04.30.51)
- update microcode version to 17
- update platform version to 1.5
=> [EHL] Update FSP/UCODE/platform version since MR5 is released

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCommonPkg/Library/ShellLib/CmdCorruptComp.c, BootloaderCommonPkg/Library/ShellLib/CmdCorruptComponent.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.h, BootloaderCommonPkg/Library/ShellLib/ShellLib.inf, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Create a runtime tool that corrupts SBL components so that the SBL resiliency feature can more easily be tested and demonstrated
=> Create OS loader shell tool for SBL component corruption

BootloaderCorePkg/Include/Library/FirmwareResiliencyLib.h, BootloaderCorePkg/Library/FirmwareResiliencyLib/FirmwareResiliencyLib.c, BootloaderCorePkg/Stage1B/Stage1B.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Before this change, whenever SG02 is corrupted
in both BP0 and BP1, SBL will continuously loop
trying to recover BP0 via BP1 and vice versa
This change makes it so that, if a failure is
detected on a recovery flow, the CPU halts
=> Consider Simultaneous SG02 Corruptions in BP0 and BP1 for Resiliency

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
TCO timer could be enabled regardless resiliency feature. So just remove the resiliency conditional.
=> [ADL] enable TCO timer by default

Platform/QemuBoardPkg/BoardConfig.py, Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
Fix two errors that prevent building QEMU SBL with the debug FSP on Linux:
- 0001-Build-QEMU-FSP-2.0-binaries.patch adds a variable "RegMask8" to FspmInitEntryPoint() that is written but not read; GCC treats this as an error;
- the resulting STAGE2 binary is larger than the 0x18000 bytes allocated for it.
Signed-off-by: Bruno Achauer <bruno.achauer@intel.com>
=> [QEMU] Allow building with the debug FSP

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Currently, Slim Bootloader support for multiple VBT files doesn't work on EHL. Support for multiple VBT files, which works on other platform, does not work correctly for EHL. However, this change can fix it locally by adding the support from another platform into the EHL support once integrated into the public SBL
Signed-off-by: ldevathu <linggeis.daran.devathurai@intel.com>
=> [EHL] support multi VBT

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf
FspsUpdUpdateLIb was not enabling FspsUpd->FspsConfig.L2QosEnumerationEn based on PLATFORM_ADLS, which is no longer used. L2QosEnumerationEn is present in ADL-P,S,PS, and RPL-S,P FSP UPD, just not ADL-N, so need to prevent compiling this code for that platform only.
=> [RPL/ADL] L2 CAT not getting enabled when TCC enabled.

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Rtd3 SSDT have CRB and RVP versions. Verify Table ID to match Platfrom SKU when updating SSDT table.
=> [ADLN] Verify Table ID when updating Rtd3 SSDT

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
Currently, users are able to update the uCode component with a new binary that uses a different slot size than the existing binary. If these slot sizes do not line up, there is potential to trigger recovery (if enabled) or brick the system. This change disallows updates where these slot sizes do not line up.
=> Check that uCode slot sizes line up during uCode update

BootloaderCorePkg/Stage2/Stage2.c
If OS/UEFI payload is not found, stop the TCO timer before halting the CPU as there is no backup of
OS/UEFI payload
=> Stop TCO timer if OS/UEFI payload not found

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c, Platform/AlderlakeBoardPkg/CfgData/CfgData_BootOption.yaml
Change boot flag to 0 to enable booting Yocto and Ubuntu
TEST:Boot to yocto on ADL
=> [ADL/RPL] Update default boot options

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c, PayloadPkg/OsLoader/LoadImage.c, Platform/ElkhartlakeBoardPkg/BoardConfig.py
This patch fixes an invalid memory access issue caused by fs->Ext2FsGDSize is smaller than the size of EXT2GD.
The EXT2GD is a 64-byte structure, but fs->Ext2FsGDSize is not always 32.
Before this patch, Ext2fsOpen() allocates a smaller memory than expected, i.e., Ext2FsGrpDes = AllocatePool (Ext2FsGDSize * Ext2FsNumCylinder). When ReadGDBlock() loads data (E2FS_CGLOAD) into fs->Ext2FsGrpDes, it possibly accesses mem out of the allocated Ext2FsGrpDes space.
This patch loads each element into fs->Ext2FsGrpDes.
This patch also
1. show informative messages when OS Loader fails to load Linux files.
2. increase EHL's PLD_HEAP_SIZE (since the size of initrd in Ubuntu LiveCD
is over 130MB)
Test method:
1. create a huge EXT FS (says, at least 36GB)
2. In the fs, place the following file/dir:
a: …
=> [ExtLib] fix invalid memory access to support large EXT fs

Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c
This patch fixed the issue that no display seen
once the Windows system resumed from S4.
This issue happened in particular when the Iris
Xe Graphics driver is in place.
=> [ADLP] Update VBT data in Igd Op Region

BootloaderCommonPkg/Include/Library/PartitionLib.h, BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c
In the Ubuntu ISO image, it has 0xF8 partition entries. The partition library could not work as expected since it expects the partition entries are no more than 128.
Potentially it could have more partition entries, so just remove the check.
=> Remove unnecessary check in partition library

BootloaderCorePkg/BootloaderCorePkg.dec, Platform/AlderlakeBoardPkg/CfgData/CfgData_Power.yaml, Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.inf, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf
FSP UPD FuSa toggles will be set based on new config data fields where applicable or to predefined values when called for by the FuSa spec. This requires setting PcdFusaSupport at build time in case platform FSP doesn't support FuSa.
=> feat: [RPL-P] Add support for enabling FSP FuSa features.

.azurepipelines/azure-pipelines.yml
This patch enabled auto build for IDV Azure Pipelines.
=> Enable Azure Pipeline build for IDV

PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
When loading capsule from raw partition, some check prevent capsules signed by a RSA3072 from being recognized as a valid capsule. Remove obsolete checks which expect RSA2048, signature type is already checked at a later stage from AuthenticateCapsule.
=> Allow to load capsules signed with RSA3072 from raw partition

PayloadPkg/Library/SblParameterLib/SblParameterLib.c
This patch fixes the issue that OS Loader appends an unwanted mender setting (i.e., root=PARTLABEL=primary/secondary) to Linux kernel command line when the mender setting already exists.
With the patch, the mender setting is appended to kernel command line only if BOOT_FLAGS_MENDER AND no existing mender setting.
=> OSLoader: Append mender command line only if not exist

BootloaderCorePkg/BootloaderCorePkg.dsc
PR #1760 mistakenly included a debug change to increase the default debug print level. Reverting that one change.
=> fix: Revert PcdDebugPrintErrorLevel change made mistakenly in #1760.

Platform/AlderlakeBoardPkg/BoardConfigAdlP.py, Silicon/AlderlakePkg/FspBin/FspBin.inf, Silicon/AlderlakePkg/Microcode/Microcode.inf
- update FSP version to IoT ADL-P MR2 (0C.01.73.10)
- update Microcode version to 423
- update platform version to 1.2
=> [ADLP] Update FSP/UCODE/platform version for MR2 release

Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Silicon/AlderlakePkg/FspBin/FspBin.inf, Silicon/AlderlakePkg/Microcode/Microcode.inf
- update FSP version to IoT ADL-S MR3 (0C.00.73.10)
- update Microcode version to 25
- update platform version to 1.3
=> [ADLS] Update FSP/UCODE/platform version for MR3 release

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Needed to set DdiPortAConfig to eDP for DDR5 RVP.
=> fix: [RPL-P] eDP output not working on DDR5 RVP board.

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.inf
Setup FSPM stack base and size based on the car size and SBL stack and heap size.
This change could avoid the boot issue caused by FSP stack overflow.
=> [ADL/RPL] Update FSPM Stack

BootloaderCommonPkg/Include/Library/MultibootLib.h, BootloaderCommonPkg/Library/MultibootLib/Multiboot.c, BootloaderCommonPkg/Library/MultibootLib/Multiboot2.c, BootloaderCommonPkg/Library/MultibootLib/MultibootLib.inf, BootloaderCommonPkg/Library/MultibootLib/MultibootLibInternal.h, BootloaderCommonPkg/Library/MultibootLib/multiboot2.h, PayloadPkg/OsLoader/BootParameters.c, PayloadPkg/OsLoader/LoadImage.c, PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/OsLoader.h, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Platform/ApollolakeBoardPkg/BoardConfig.py
- Add (partial) multiboot-2 support as specified in https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html
- header file imported (and adjusted to SBL OsLoader) from https://github.com/NetBSD/src/blob/trunk/sys/arch/i386/include/multiboot2.h
Signed-off-by: Bruno Achauer <bruno.achauer@intel.com>
=> OsLoader: Add Multiboot-2 support

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
This patch fixes an issue that SBL fails to load a file in Ext4 partition, when
1. the ext4 partition uses Extent
2. the inode's first extent block is an internal node
3. the node has only one entry (i.e., eh_entries = 1)
Under the above conditions, the data block may point to the child of first ei_block when accessing the data within the range of child node.
Test method:
1. Install Ubuntu 20.04.5 LTS/(min install) in an eMMC disk
Note: this issue is only reproducible when loading a file satisfying all conditions mentioned above (i.e., eh_entries = 1).
So far, the /boot/initrd.img after installing Ubuntu in an eMMC (where part table: 500MB(FAT), 20GB (EXT4), 4GB (Swap)) satisfies the conditions. However, for some reasons, when using USB SATA disk, it will not generate a /boot/initr.rd …
=> [ExtLib] fix the failure of loading files in Ext4 partition

BootloaderCorePkg/Library/FirmwareResiliencyLib/FirmwareResiliencyLib.c, BootloaderCorePkg/Stage1A/Stage1A.c, BootloaderCorePkg/Stage1A/Stage1A.h, BootloaderCorePkg/Stage1A/Stage1A.inf, BootloaderCorePkg/Stage1B/Stage1B.c, BootloaderCorePkg/Stage1B/Stage1B.inf, BootloaderCorePkg/Stage2/Stage2.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Silicon/CommonSocPkg/Include/Library/TcoTimerLib.h, Silicon/CommonSocPkg/Library/TcoTimerLib/TcoTimerLib.c
It was discovered that, when BiosRedAssistance = Enabled, CSME actually uses the ACM active timer to time all of SG1A through the beginning of SG1B (up to end of FSP-M), flipping the TS and rebooting if a certain timeout is reached. This change closes the resiliency gap in SG1B while ensuring that there is as little overlap as possible between the TCO timer and the ACM active timer.
=> Move TCO Timer Status Check/Start Right Before FSP-M

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c, BootloaderCommonPkg/Library/Ext23Lib/Ext2FsLs.c, BootloaderCommonPkg/Library/Ext23Lib/LibsaFsStand.h
This patch fixes 2 issues related to symbolic links:
1. when "fs ls" a directory, symbolic links are not shown. 
It is because Ext2fsLs() only shows regular files and directories.
2. when "fs ls <symbolic_link>" the output is incorrect.
It is because File->FileNamePtr points to a local variable, "NameBuf" in Ext2fsOpen(), if the file is a symbolic link
This patch replaces File->FileNamePtr with FileNameBuf. It slightly increases Ext2fsLs/Ext2fsOpen/SearchDirectory time, because of the use of strcpy and strcat.
Test method:
1. create a regular file, "a", in directory "x"
2. create a symbolic link file, "b", pointing to "a".
3. under the shell of OSLoader, 
- "fs ls x" - expected result: a, b (symbolic link) 
- "fs ls x/a" - expected result: a and its file size is shown
- "fs ls x/b" - …
=> [ExtLib] fix the list of symbolic links

Platform/AlderlakeBoardPkg/BoardConfig.py, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py
PcdAdlNSupport is only true for ADLN platforms. Remove for others.
=> [ADL] Clean up ADLN PCD value

Platform/QemuBoardPkg/Script/TestCases/uefi_upld_boot.py
To align with universal payload ID,
a new file for Universal Payload is added.
Updating the test case to the new file in repo.
Payload: https://github.com/slimbootloader/slimbootloader/files/10221853/UniversalPayload.zip
Reference Issue: https://github.com/slimbootloader/slimbootloader/issues/1781
=> [QEMU] Updating test case for UEFI Payload

BaseTools/Scripts/PatchCheck.py
PatchCheck.py currently checks for files without terminating newlines but takes no action. This change will report this as a code format error.
=> feat: Enforce newlines at the end of all text files in PatchCheck.py.

BootloaderCommonPkg/Include/Library/LoaderPerformanceLib.h, BootloaderCommonPkg/Library/ShellLib/CmdPerf.c, BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
When running "perf" command from OsLoader shell, it would print the performance data but it is difficult to know what they are mean. The patch adds the description to performance data.
=> Add description for performance data

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
RPL-S FSP UPD was updated so PchTsnEnable is now a 2-byte array with a separate byte for each port. This is now different from the ADL platforms and needs to be included selectively at build time.
=> fix: [RPL-S] Fix for TSN build error caused by FSP UPD updates.

Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adlps_Crb_Ddr5.dlt, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
On ECless platforms, Sio is initialized during boot flow. However, when S0ix is enabled, Sio need not be initialized.
=> [ADL] Skip SioInit when S0ix is enabled.

BootloaderCorePkg/Library/FirmwareResiliencyLib/FirmwareResiliencyLib.c, BootloaderCorePkg/Stage1B/Stage1B.c, BootloaderCorePkg/Stage2/Stage2.c
When SG02 is failing on both partitions, a shutdown is supposed to occur after trying to boot from each partition 3 times. However, it was noticed that this was not occurring as the shutdown function was left empty. This caused dead loops and further ACM active timer expirations.
This change resolves this issue by moving the TCO timer check and start until after the ACM active timer has been stopped. This change also converts the shutdown to a CPU halt for further clarity.
=> Halt boot retries when SG02 is failing on both partitions

Platform/CoffeelakeBoardPkg/AcpiTables/AcpiTables.inf, Platform/CoffeelakeBoardPkg/AcpiTables/Dmar/Dmar.aslc, Platform/CoffeelakeBoardPkg/AcpiTables/Dmar/Dmar.h, Platform/CoffeelakeBoardPkg/BoardConfig.py, Platform/CoffeelakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/CoffeelakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/CoffeelakePkg/Include/Library/DmaRemappingTable.h, Silicon/CoffeelakePkg/Include/Library/VTdLib.h, Silicon/CoffeelakePkg/Include/PlatformData.h, Silicon/CoffeelakePkg/Include/Register/PchRegsP2sb.h, Silicon/CoffeelakePkg/Include/Register/SaRegs.h, Silicon/CoffeelakePkg/Include/Register/VtdRegs.h, Silicon/CoffeelakePkg/Include/SaNvsAreaDef.h, Silicon/CoffeelakePkg/Library/Stage2SocInitLib/Stage2SocInitLib.c, Silicon/CoffeelakePkg/Library/Stage2SocInitLib/Stage2SocInitLib.inf, Silicon/CoffeelakePkg/Library/VTdLib/VTdLib.c, Silicon/CoffeelakePkg/Library/VTdLib/VTdLib.inf
This patch adds ACPI DMAR table for CFL.
Some VT-d init code are ported from EDK2.
Test method:
1. dump acpi tables: acpidump -b
2. check the dmar table: iasl -d dmar.dat
Verify: CFL-s RVP
=> feat: [CFL] add ACPI DMAR table

Platform/TigerlakeBoardPkg/BoardConfig.py, Silicon/TigerlakePkg/FspBin/FspBin.inf, Silicon/TigerlakePkg/Microcode/Microcode.inf
- update FSP version to IoT FSP 5505_01_MR7 (0A.00.7D.72)
- update TGLU microcode version to A6
- update TGLH microcode version to 42
- update TGL platform version to 1.7
Signed-off-by: Vincent <vincent.chen@intel.com>
=> [TGL] Update FSP/UCODE/platform version for MR7 release

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Getting FIPS might take long time since CSME could be busy. And FIPS is disabled by default in CSME. So update the code just enable it when it is configured to enable it.
=> [ADL/RPL] Update FIPS

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
During S3 resume, bootloader must not set VBT pointer. Otherwise the i915 driver in newer kernel will fail to load GuC.
Test method:
1. S3 suspend, says 5 seconds: rtcwake -m mem -s 5
2. check the display and dmesg
Verify: EHL CRB + Linux kernel 5.15.49 and 5.15.71
=> feat: [EHL] support gfx(i915) S3 resume for Linux kernel 5.15.71+

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
TCC and TSN enabling code was being platform limited to exclude RPL-P.
=> fix: [RPL-P] TCC/TSN not being enabled  correctly on RPL-P.

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
When SioInit code configures the COM ports in stage 2, it might have settings conflict with debug interface. Remove it from FSP debug interface to resolve conflict and boot issue.
=> fix: [ADL-N] Removed COM port config from debug interface

BootloaderCommonPkg/Library/ShellLib/CmdMmap.c
0x03 is ACPI Reclaim Memory
0x04 is ACPI NVS Memory
As defined in BootloaderCommonPkg/Include/Guid/MemoryMapInfoGuid.h and ACPI Specification Chapter 15.
Signed-off-by: Atharva Lele <atharva.lele@intel.com>
=> ShellLib/CmdMmap: fix MemTypeToStr() strings

Silicon/AlderlakePkg/Library/PsdLib/PsdLib.c, Silicon/AlderlakePkg/Library/PsdLib/PsdLib.inf, Silicon/CommonSocPkg/Library/HeciLib/HeciLib.c, Silicon/IdavillePkg/Library/PsdLib/PsdLib.c
This change fixes a bound range exception thrown in HECI call for FW capabilities and prioritizes use of HOBs over HECI calls in PSD-related code.
=> [ADL/RPL] Enhance PSD-related code

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
During S3 resume, bootloader must not set VBT pointer. Otherwise the i915 driver in newer kernel will fail to load GuC.
Test method:
1. S3 suspend, says 5 seconds: rtcwake -m mem -s 5
2. check the display and dmesg
Verify: ADLS and TGLU RVP + Linux kernel 5.15.71
=> feat: [ADL/TGL] support gfx(i915) S3 resume for Linux kernel 5.15.71+

BootloaderCommonPkg/Include/Library/ContainerLib.h, BootloaderCommonPkg/Include/Library/IasImageLib.h, PayloadPkg/OsLoader/OsLoader.c
This PR attempts to streamline the container types supported by OsLoader.
1. Normal: Used for PE, FV, bzImage, ELF images
2. Classic Linux: Used for a traditional Linux booting setup (cmdline, kernel, initrd, etc.). This type was renamed to CLASSIC_LINUX from CLASSIC to avoid any confusion.
3. Multiboot: Multiboot-compliant MB/MB-2 images
All 3 container types support ACPI table updates
This PR also adds one feature for the Linux container. Earlier, any additional files (blobs) loaded with the kernel were just loaded into memory. However, the OS did not know where these resided. To fix this, we add a placeholder in the kernel cmdline which will be updated with the actual address of the blob. The placeholder will be "SBL.XXXX=0x0000000000000000" where XXXX is the component name.
The …
=> OsLoader - Container Type Cleanup

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
When PcdVtdEnabled or MemCfgData->VtdDisable were disabled, Fspmcfg->VtdDisable was being left at default value.
=> fix: [ADL/RPL] VTD not getting disabled in FSPM when PcdVtdEnabled=0.

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
This is a silicon requirement for S0ix support.
=> fix: [ADL/RPL] Force CPU Root Port MultiVC to disabled for S0ix.

Platform/IdavilleBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
The UART1_[RT]XD modes for the UART1 pins are function #2, not #1.
The UART2_[RT]XD pins are L12/L13, and the UART modes are function #2.
=> ICXD: Fix Stage1A UART setup functions for UART1

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/LowPowerSupport.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/SioChip.c
- Fix the  interrupt config table.
- Update some NVS data.
- Cleanup debug prints so it is generic.
- Sync Pep constraints default value.
=> [ADLN] Update and cleanup

BootloaderCorePkg/Tools/GenContainer.py, BootloaderCorePkg/Tools/SingleSign.py
When GenContainer.py extracts a container image, a layout file is created that specifies the format of header and components. For container header with BOOT name, the signing key is expected to be KEY_ID_OS1_PRIVATE. Correct it for not misleading.
=> fix: correct the default key for signing BOOT container

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Revert FIPS mode debug info for automation test.
=> fix: [ADLN] Revert FIPS mode debug info

Platform/AlderlakeBoardPkg/CfgData/CfgData_PepConstraints.yaml, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/LowPowerSupport.c, Silicon/AlderlakePkg/Library/PchInfoLib/PchInfoLibAdl.c
- Match the Pep constraints cfg with that of default.
- Sync few FSP cfg settings.
- Minor clean up.
=> [ADLN] Sync different settings

BootloaderCommonPkg/Library/ElfLib/ElfLib.c
Currently, loading an ELF image will relocate the image (to its preferred load address) only if there is at least one ELF segment that is not completely contained in the file loaded (i.e. the memory segment size is larger than the size inside the file. This behavior is generally triggered by the segment that contains the .bss section).
Consequently, images that contain initialized data only (e.g. QNX IFS files) don't get relocated, and will usually crash when jumping to the image entry point.
This change checks whether the ELF image is already loaded at the preferred address, and forces image relocation if not.
=> Ensure that ELF images are loaded at their preferred address

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Re-scanning PCI devices to find NVME controllers was adding an additional ~20ms to the end of Stage 2. Moving this to the existing PCI scan that is part of PCI enumeration saves this time. However, this EfiPciBeforeResourceCollection phase was not actually getting called and needed to be added.
=> fix: [ADL/RPL] Move NVME boot option update to PCI Enumeration hook.

BootloaderCommonPkg/Library/TpmLib/TpmLib.c, BootloaderCorePkg/Stage1B/Stage1B.c
These changes ensure that:
- Each TPM2 event type matches the structure of the data associated with it
- Aligns TPM2 events between BIOS and SBL
=> Fix TPM2 Event Logging

BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.c
On platforms where only serial console input is enabled, enabling source debug will lead to an infinite loop in ConsoleRead(). Newer compilers detect this and generate a build error.
=> fix: [RPL-P] Build error when ENABLE_SOURCE_DEBUG=1.

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BuildLoader.py, PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/OsLoader.inf
OsLoader should not attempt to boot images that are not packaged as containers.
Earlier, OsLoader would attempt to load and boot a non-container image and fail in
SetupBootImages() as the LoadedImage struct would not be populated correctly.
Now, ParseBootImage() will report a non-container file as unsupported and OsLoader
will move on to the next entry in the boot options.
=> Fix OsLoader handling of non-container images and remove PcdContainerBootEnabled

Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adln_Crb_Ddr5.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adln_Rvp_Lpddr5.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
SBL config data PlatformMemorySize is used to set FSP UPD PlatformMemorySize which is used by FSP to check available memory range size for FSP reserved memory.
A too small size might cause FSP to use a small available memory range used for other purpose. So change the default value of PlatformMemorySize to 64MB.
Since default value change, remove unnecessary override.
=> [ADL/RPL] Update PlatformMemorySize default value

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Silicon/ElkhartlakePkg/FspBin/FspBin.inf
- update FSP version to MR6 (09.04.51.31)
- update platform version to 1.6
Verify on EHL CRB.
=> [EHL] Update FSP and platform version since MR6 is released

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
The type for SBL config MrcSafeConfig is missing.
Missing type will cause this item is not shown
from ConfigEditor tool.
=> [ADL/RPL] Add the missing type for SBL config data

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf
Firmware update got failed when verified boot was turned off. While fwupdate capsule is always generated with signing key,
it should be verified only when verified boot is enabled. Otherwise, raise a warning to inform that the capsule is not authenticated.
=> fix: verify fwupdate capsule only when Verified Boot is enabled

Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
The PCH decodes MMIO accesses to the top of 4GB to SPI flash for a maximum window size of 16MB. For SBL images larger than 16MB, this PostTempRamInit hook was causing the MTRR to overlap with NEM stack set up by FSP-T, causing a hang.
=> fix: [ADL/RPL] SBL image larger than 16MB hangs after TempRamInit.

Platform/AlderlakeBoardPkg/CfgData/CfgData_BootOption.yaml
ADL boards come with emmc as an in-built boot media. Add EMMC option in the default list in order for the OS to boot up when using OS loader payload.
=> [ADL/RPL] Add MMC option for OS loader

BootloaderCommonPkg/Library/LiteVariableLib/LiteVariableLib.c
Description:
- GetVaraibelStoreBase to GetVariableStoreBase
Change-Id: I79ddb319d733ebb53131f0df6143bd18bb9aaee7
=> fix: variable is not named correctly

PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c, PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.inf
HelloWorld consumes BootloaderCoreLib but the entry for this LibraryClass was missing in the PayloadPkg DSC file.
=> fix: address HelloWorld payload build failure

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Silicon/AlderlakePkg/AlderlakePkg.dec, Silicon/CommonSocPkg/Include/Library/CrashLogLib.h, Silicon/CommonSocPkg/Library/CrashLogLibNull/CrashLogLibNull.c
New CrashLog support design is for FSP to collect CrashLog info and report in HOB. Bootloader responsibility is just to populate ACPI BERT with FSP collected CrashLog Data now. That way bootloader has no Silicon code.
=> feat: [ADL/RPL] Update CrashLog support implementation for latest FSP.

BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHci.c, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsHci.h, BootloaderCommonPkg/Library/UfsBlockIoLib/UfsInternal.h
This Patch add the support to set UFS clock frequency.
- Added the function to read or write specified attribute of a UFS device
- Shifted function which switch the link power mode and gear after ref_clock setting because if an unsuported clock frequency being set, it won't be able to overwrite the corrupted UFS attributes.
=> feat: Added support to set ref_clock frequency for UFS device

BootloaderCommonPkg/Include/Library/TpmLib.h, BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c, BootloaderCommonPkg/Library/TpmLib/TpmLib.c, BootloaderCommonPkg/Library/TpmLib/TpmLib.inf, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibCBnT.inf, Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
These changes addresses @kvparikh89's post-merge comments on https://github.com/slimbootloader/slimbootloader/pull/1859.
These changes accomplish the following in TPM-related files:
- Update copyright years
- Initialize pointers to NULL
- Check pointers for NULL before de-reference
=> [ADL] Additional TPM-related cleanup

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
This change only sets the GFX framebuffer cache type to Write-combining when not booting the UEFI payload. The UEFI payload PCI hostbridge driver will override the WC setting anways for the whole PCI root bridge memory range, so it wasn't gaining the write-combining performance bonus, and was causing a CPU exception in this particular case for RPL-P.
=> fix: [RPL-P] CRB hang in UEFI payload when PCIe switch present.

BuildLoader.py
Build script will not copy FSP, VBT and Microcode bin files from repository if it finds these files existing in taget folder.
Above step keeps them from unintentional update in series of build process. Adding a board name to clean command helps to get latest binaries from repository in next build.
=> Add board name option to clean command

Platform/AlderlakeBoardPkg/Include/PlatformBoardId.h, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Update Platform ID and display configuration.
Bootable with Ubuntu 22.04.1. Display supported via HDMI.
To stitch the SlimBootloader.bin with IFWI uses StitchLoader.py script with '-p' as given below:
python Platform/AlderlakeBoardPkg/Script/StitchLoader.py -i <BIOS_IMAGE_NAME> -s Outputs/adlp/SlimBootloader.bin -o sbl_upx12_ifwi.bin -p 0xAA000104
=> [UPX i12] Update Platform ID and display configuration

Platform/AlderlakeBoardPkg/CfgData/CfgDataExt_Upx12.dlt
Reset EC available flag to 0 in dlt file.
Resolved ACPI Errors from dmesg log that point to EC Hardware.
Tested to boot up Ubuntu and Windows.
=> [UPX i12] Disable EC from ACPI table

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Saved timeout from reading EC. Reduced up to 300ms. Adjusted Stage 1A & 1B region size for ADLN Fastboot feature.
=> [ADLN/ASL] Fastboot improvement

BootloaderCorePkg/Include/Library/AcpiInitLib.h, BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c, BootloaderCorePkg/Stage2/Stage2Support.c, PayloadPkg/OsLoader/BootParameters.c, PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/PerformanceData.c, Platform/CommonBoardPkg/AcpiTables/Fpdt/Fpdt.aslc
Adds the SBL boot performance data (Stage1 time, Stage 2 time, OsLoader time)
to the FPDT with type 0x3000 (Reserved for platform firmware Vendor usage)
=> Add SBL Boot Performance Data to FPDT

Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CommonSocPkg/Include/Library/GpioLib.h, Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
A GPIO YAML can refer to any platform ID's GPIO table as the base GPIO table. Since SBL supports upto 32 platform IDs, the number for the check in the if condition should be 32.
=> fix: update GPIO base table ID check

Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr4_Sodimm.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adls_Crb_Ddr5_Sodimm.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgData_FuSa.yaml, Platform/AlderlakeBoardPkg/CfgData/CfgData_Fusa_Feature.dlt, Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Silicon/AlderlakePkg/AlderlakePkg.dec, Silicon/AlderlakePkg/Include/Library/PchGspiLib.h
- MC and CMF Parity combined into one FSP UPD.
- Added SBL Config items for IehMode, TCSS D3Hot and D3Cold, CPU PCIe Power gating, VccSt, TCSS Cstate limit. These are all needed for the FuSa specific dlt file. ADL-S dlt files updated so D3Hot and VccSt defaults are unchanged, since these defaults were previously set by PCH sku.
- FuSa diagnostic mode PCD to track Diagnostic mode across stages. Crash Log Data PCD will not be used and has been removed.
- GSPI example driver header file added.
=> feat: [ADL/RPL] FuSa updates based on latest FSP and specification.

BootloaderCommonPkg/BootloaderCommonPkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/ElkhartlakePkg/Include/Library/HeciInitLib.h, Silicon/ElkhartlakePkg/Library/HeciInitLib/HeciCore.c, Silicon/ElkhartlakePkg/Library/HeciInitLib/HeciCore.h, Silicon/ElkhartlakePkg/Library/HeciInitLib/MkhiMsgs.h
EHL FSP does not send EOP (End Of Post) message at the Ready to Boot. The patch adds support for SBL to send the EOP during Ready to Boot.
=> fix: [EHL] send EOP message

BootloaderCorePkg/Include/Library/FspApiLib.h, BootloaderCorePkg/Library/FspApiLib/FspMemoryInit.c, BootloaderCorePkg/Library/FspApiLib/FspSiliconInit.c, BootloaderCorePkg/Library/FspApiLib/FspVariableServices.c, BootloaderCorePkg/Library/FspApiLib/FspmApiLib.inf, BootloaderCorePkg/Library/FspApiLib/FspsApiLib.inf, BootloaderCorePkg/Stage1B/Stage1B.c, BootloaderCorePkg/Stage2/Stage2.c, IntelFsp2Pkg/Include/FspEas/FspApi.h, IntelFsp2Pkg/Include/Guid/FspHeaderFile.h, IntelFsp2Pkg/Tools/SplitFspBin.py, Platform/ApollolakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/BoardConfig.py
FSP 2.4 adds a requirement for Bootloader to respond to FSP Variable requests in a way that is similar to UEFI variable services. This implementation adds support for using the updated SBL VariableLib so that the FspVariableServicesLib wrapper is no longer needed.
Additionally, support for Multi-Phase mem and SI init is added. FSP 2.4 introduces the mandatory MultiPhaseMemInit call, and makes the MultiPhaseSiInit call mandatory where it was previously optional.
=> feat: [FSP2.4] Added FSP variable serivices, Multi Phase Mem and SI.

Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Config data uses comma ',' instead of dot '.' as the option separator. Fix a typo in IehMode option which would cause ConfigEditor.py error.
=> [ADL/RPL]: Fix a typo

BootloaderCommonPkg/Include/Library/IasImageLib.h, BootloaderCommonPkg/Include/Library/MultibootLib.h, BootloaderCommonPkg/Library/MultibootLib/Multiboot.c, PayloadPkg/OsLoader/LoadImage.c, PayloadPkg/OsLoader/OsLoader.c, PayloadPkg/OsLoader/OsLoader.h
Required by multiboot spec (*1), a mod string is a zero-terminated ASCII string. The patch introduces LoadMultibootModString to load mod string from a IMAGE_DATA (allocating a new buffer when requiring to append zero-terminated char).
The patch does not reuse GetFromConfigFile because GetFromConfigFile was designed to be compatible with legacy format (e.g., EOF signature) and truncates new line chars (which is not required by multiboot mod).
For performance, the patch does not run "isascii" check.
Minor changes:
- Fix typo error (InitMultibootMmap)
- Declare FreeImageData in Library/IasImageLib.h
- Dump mod string for debug build
Reference:
1. https://www.gnu.org/software/grub/manual/multiboot/multiboot.html
Verify: EHL CRB
Acked-by: Jiaqing Zhao <jiaqing.zhao@intel.com>
Signed-off-by: …
=> fix: multiboot mod string in zero-terminated ASCII format #1913

BootloaderCorePkg/Tools/PatchFv.py
Some versions of ld (like 2.40 in Ubuntu 23.04) uses 32-bit address when generating map files for IA32 build. This patch enables PatchFv.py to parse these 32-bit addresses in GCC map properly.
=> BootloaderCorePkg/Tools: PatchFv: Handle 32-bit address in GCC map

Platform/AlderlakeBoardPkg/CfgData/CfgData_FuSa.yaml
FuSa Configuration YAML file introduced some description typos and display issues in the Configuration Editor.
=> fix: [ADL/RPL] Correct typos and display issues in FuSa YAML file.

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py
The patch allows SBL to add ChipsetInit binary by,
- build time: Platform/ElkhartlakeBoardPkg/Binaries/ChipInitBinary.bin or
- stitch time: IPFW/ChipInitBinary.bin
The binary is stored in IFWI/BIOS/NRD/IPFW/CHIP.
The ChipsetInit binary is optional to be stored in BIOS region, because the logic for FSP and CSE to use/update ChipsetInit is:
- Platform boots with default ChipsetInit in CSE data region.
- if FSP ChipsetInitBin does not exit -> END
- if FSP ChipsetInitBin is incorrect -> END
- if FSP and CSE ChipsetInit code are the same -> END
- Otherwise, update the ChipsetInit in CSE
Test process:
1. Cherry pick the patch under <mr6_source>
2. Place mr6 ChipInitBinary.bin (V11) in
<mr6_source>/Platform/ElkhartlakeBoardPkg/Binaries/
3. Build & Stitch <mr6> sbl IFWI, says final BiosRegion.bin …
=> feat: [EHL] support ChipsetInit binary

MdePkg/Include/Library/DebugLib.h
Fixed CWE 476 NULL Pointer Dereference
Prevent DebugAssert from Coverity scan
Missing from PR#1927 fix: [Common] Fix Coverity issues
=> fix: [Common] Fix Coverity issues

Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c
Verify Block Id of 2 to prevent VBT table mismatch when calling UpdateVbt.
Note: this change is discarded after below PR is merged.
feat: [Common] VBT header removal #1914
=> feat: [ADL] Verify VBT Block Id

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
When PcdFlashSize is > 16MB, the corresponding memory map entry will be incorrect since on ADL/RPL only the top 16MB of flash is mapped into memory by the PCH.
=> fix: [ADL/RPL] Fix up flash map memory map entry when flash size > 16MB.

BootloaderCorePkg/Include/Library/AcpiInitLib.h, BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c, BootloaderCorePkg/Stage2/Stage2.c, BootloaderCorePkg/Stage2/Stage2Support.c
In current code, BoardNotifyPhase() would update FPDT SBL performance table in S3 path. It could cause S3 issue since PcdAcpiTablesRsdp is not updated.
Move the FPDT related code to AcpiFpdt.c
Update FPDT SBL performance table in stage2 so that this table could be updated for all payloads.
=> feat: Fix ACPI FPDT SBL boot performance

Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c, Platform/ElkhartlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.inf
A recent commit (b9057d) changed the FspResetHandler by seperating FSP_STATUS_RESET_REQUIRED_COLD from the other undefined case with EfiResetPlatformSpecific reset. The common ResetSystemLib (BootloaderCommonPkg/Library/ResetSystemLib) does not handle EfiResetPlatformSpecific.
On EHL, FSP may register a EfiResetPlatformSpecific reset if some platform configuration changed, including but not limited to the cases:
- disable PSE on PSE CPU sku
- update ChipsetInit FW Therefore, EfiResetPlatformSpecific must be handled.
Therefore, EfiResetPlatformSpecific must be handled.
Verify: EHL CRB
=> feat: [EHL] add ResetSystemLib

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
End of post is not notified at end of firmware
fromFSP for osloader boot.
=> fix: [ADL/RPL] Set FSPS for End of Post notify.

Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/IdavilleBoardPkg/Library/Stage2BoardInitLib/SmbiosInit.c, Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
If the function actually returns a null value,
a null pointer dereference will occur.
In InitializeSmbiosInfo: Return value of function which returns null is dereferenced without checking (CWE-476)
=> fix: [Common] Dereference null return TempSmbiosStrTbl

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Enabled eMMC boot with OS loader payload.
=> fix: add eMMC device type in platform device

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/HdaI2sCodec.asl
Export the correct ID for RT5660 (10EC5660) codec, instead of ID INTC1027.
CRB SOF Audio function is verified.
=> fix: [EHL] export the correct ID for RT5660 (10EC5660) codec

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Stage2/Stage2.c, BootloaderCorePkg/Stage2/Stage2.inf, Platform/ElkhartlakeBoardPkg/BoardConfig.py, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
The FSP may request for a reboot when some features are enable/disable. The SiliconInit FW update is one case for the "FSP requested boot". Without the patch, SBL has no way to get the notification from CallFspNotifyPhase.
The patch introduces a feature, PcdEnableFwuNotify, to allow SBL to keep BoardNotifyPhase during firmware update.
On EHL, the feature can be enabled by "disable BIOS Lock".
Verify: EHL-CRB
=> feat: [EHL] enable BoardNotifyPhase during FWU

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Update same config value as BIOS code.
Address unused value (CWE 563)
=> fix: [ADLN] fix SPI and I2C mode in ACPI NVS

.azurepipelines/azure-pipelines.yml
It looks link https://acpica.org/sites/acpica/files/iasl-win-20190509.zip is not available. Update to use iasl-win-20221020_Signed.zip using its link https://cdrdv2.intel.com/v1/dl/getContent/774881
=> feat: Fix CI build caused by iasl link

Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml
OpioRecenter was enabled in default FSP UPD, but after adding this in SBL CfgData, the default was mistakenly set to disabled. This was breaking S0ix on RPL-P and likely other platforms. Restoring the CfgData value to enabled.
=> fix: [RPL/ADL] Enable OpioRecenter by default.

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
New ADL FSP changed TSN UPD from PchTsnEnable to PchTsnEnable[2]. So need update the code to fix the build failure.
=> feat: Fix ADLS build failure

Platform/AlderlakeBoardPkg/BoardConfig.py, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py
Adjust FV image sizes for different combination of FSPDEBUG_MODE, ENABLE_SOURCE_DEBUG and ENABLE_FAST_BOOT
=> fix: [ADL] fix build errors for some board configs

BootloaderCommonPkg/Library/NvmExpressLib/NvmExpress.c
There is a NVMe regression caused by https://github.com/slimbootloader/slimbootloader/pull/1958. The NVMe device enumerated should not be freed since it will be used in other APIs.
=> feat: Fix device enumerate in NVMe library

Platform/AlderlakeBoardPkg/BoardConfigAdlP.py, Platform/AlderlakeBoardPkg/Script/StitchIfwiConfig_adlp.py, Silicon/AlderlakePkg/Microcode/Microcode.inf
- update FSP version to IoT ADL-P MR4 (0C.01.A4.12)
- update microcode version to 42A
- update platform version to 1.4
- Add ChipInitBinary.bin update in stitch process
=> [ADLP] Update FSP/UCODE/platform version for MR4 release

Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Silicon/AlderlakePkg/Microcode/Microcode.inf
- update FSP version to IoT ADL-S MR5 (0C.00.A4.13)
- update microcode version to 2E
- update platform version to 1.5
=> [ADLS] Update FSP/UCODE/platform version for MR5 release

BootloaderCommonPkg/Library/IppCryptoLib/hmac.c, BootloaderCommonPkg/Library/ShellLib/CmdPci.c
Fixes following compiler warnings
```
BootloaderCommonPkg/Library/ShellLib/CmdPci.c:25:1: warning: type of ‘MmRead’ does not match original declaration [-Wlto-type-mismatch]
25 | MmRead (
| ^
BootloaderCommonPkg/Library/ShellLib/CmdMm.c:107:1: note: type mismatch in parameter 2
107 | MmRead (
| ^
BootloaderCommonPkg/Library/ShellLib/CmdMm.c:107:1: note: type ‘UINT32’ should match type ‘UINTN’
BootloaderCommonPkg/Library/ShellLib/CmdMm.c:107:1: note: ‘MmRead’ was previously declared here
BootloaderCommonPkg/Include/Library/CryptoLib.h:241:1: warning: type of ‘HmacSha256’ does not match original declaration [-Wlto-type-mismatch]
241 | HmacSha256 (
| ^
BootloaderCommonPkg/Library/IppCryptoLib/hmac.c:19:1: note: ‘HmacSha256’ was previously declared here
19 | HmacSha256 (const Ipp8u* pMsg, …
```
=> Fix compiler warnings in x64 build

Platform/IdavilleBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/IdavilleBoardPkg/Library/TmeVarLib/TmeVarLib.c, Silicon/IdavillePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c, Silicon/IdavillePkg/Library/PsdLib/PsdLib.c, Silicon/IdavillePkg/Library/VTdLib/VTdLib.c
Fixed missing break in switch (CID 1444785)
Fixed Uninitialized scalar variable (CID 1444786)
Fixed missing break in switch (CID 1444787)
Fixed Uninitialized scalar variable (CID 1444788)
Fixed Uninitialized scalar variable (CID 1444789)
Fixed Uninitialized scalar variable (CID 1444790)
Fixed Logically dead code (CID 1444791)
Fixed missing break in switch (CID 1444794)
=> fix: [ICX-D] Fix Coverity issues

Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/PciTree.asl
The DevIntConfigPtr table sets the IRQ for I2C3 to 30 for ADP-S/P while ACPI DSDT _PRT is reporting IRQ 43. ACPI IRQ corrected to 30. This was resulting in decreased performance in benchmarks.
=> fix: [ADL/RPL-S/P/PS] I2C3 IRQ reported in ACPI is incorrect.

BootloaderCommonPkg/Library/MultibootLib/Multiboot.c
LoadMultibootModString() checks the module index against MultiBoot-> MbModuleNumber, which value has not been assigned when called, causing failure when loading multiboot image with modules. Remove the check to fix it.
Fixes c9d70e74dcfe ("fix: multiboot mod string in zero-terminated ASCII format #1913")
=> MultibootLib: Fix unable to load multiboot image with modules

BootloaderCommonPkg/Library/MultibootLib/Multiboot.c
LoadMultibootModString shall check the index before using it.
=> fix: multiboot bound check

BootloaderCommonPkg/Library/ShellLib/CmdReset.c, Platform/ElkhartlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c, Platform/ElkhartlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.inf, Silicon/ElkhartlakePkg/Include/Register/PmcRegs.h
The patch handles EfiResetShutdown. With the patch, one can test "reset off" under OS Loader.
The patch also fixes a wrong reference error in ResetSystemLib.inf.
=> feat: [EHL] add EfiResetShutdown in ResetSystemLib

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Update the PcdTccEnabled check from run time to compile time. 
And move the PcdTccEnabled pcd to fixedPcd as declared in BootloaderCorePkg.dsc file.
This change is needed for those platforms where TCC is not supported and CfgData_Tcc.yaml file is not used in CfgDataDef.yaml.
=> fix: [ADL] Check PcdTccEnabled at compile time

BootloaderCorePkg/Tools/BuildUtility.py
Currently the build tool always find the config data yaml file from the brd_name path.
With this update, it will first search yaml file from brd_name_override path,  if yaml file could not be found, then it will search yaml file from brd_name path.
And currently it would generate ConfigDataStruct.h and ConfigDataDynamic.h in brd_name path. With this change, generate them in board common path.
With this change, full config data could be in brd_name or in brd_name_override path.
=> [TOOL]: Enhance build tool for CFG data

Silicon/MeteorlakePkg/Library/BootGuardLibCBnT/BootGuardLibCBnT.inf
Fix SBL build failure:
Update BootGuardCBnt.inf to include Silicon common dec file
=> fix: [MTL] Fix header missing build failure

Platform/CoffeelakeBoardPkg/BoardConfig.py, Platform/CoffeelakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c, Platform/CoffeelakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.inf, Silicon/CoffeelakePkg/Include/Register/PchRegsPmc.h
A recent commit (b9057d) changed the FspResetHandler by seperating FSP_STATUS_RESET_REQUIRED_COLD from the other undefined cases with EfiResetPlatformSpecific reset. The common ResetSystemLib (BootloaderCommonPkg/Library/ResetSystemLib) does not handle EfiResetPlatformSpecific.
On CFL, FSP may register a EfiResetPlatformSpecific reset if some platform configuration changed, including but not limited to the case:
- CSME update resulting in HECI FW EOP requsting for a reset Therefore, EfiResetPlatformSpecific must be handled.
The patch also adds support of EfiResetShutdown.
=> feat: [CFL] add ResetSystemLib

BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
Since # of PROCESSOR_LOCAL_APICs are
Madt Local Apic # is 1.
Madt X2 Local Apic # is 9.
Need to update # of structure type of X2Apic.
=> feat: Update # of X2Apic Processor Local APIC

BootloaderCorePkg/Stage2/Stage2.c
In current implementation all FSP notification are sent in SBL. When using universal UEFI payload with SMM enabled, it is expected to send ReadyToBoot and EndOfFirmware event in payload. This patch just skip the FSP notification in SBL. Universal UEFI payload should make sure FSP notification would be sent.
=> Send FSP notification in universal UEFI payload

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h, BootloaderCommonPkg/Library/ShellLib/CmdBoot.c, PayloadPkg/Library/SblParameterLib/SblParameterLib.c, PayloadPkg/OsLoader/KeyManagement.c, Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/SeedSupport.c
Allow ImageType to be edited in boot command in shell and Fix typo EnumImageTypeAdroid
=> Allow editing ImageType in boot command in shell

PayloadPkg/Library/AbSupportLib/AbSupport.h
Previous patch used GCC extension "attribute__((packed))" which caused windows build failure. This patch fixes it by using #pragma pack().
=> Fix windows build failure

Platform/AlderlakeBoardPkg/BoardConfigAzb.py
Some FSPm parameters not able to set and DMAR ACPI table was not populated due to VTD was set as 0. As a result, OS able to detect the modem but modem connectivity failed.
=> fix: [AZB] Fix modem connectivity issue

BuildLoader.py
FIT4 Entry is needed for PCH-less Server platforms to execute CBnT and/or PFR. By default, FIT4 Entry will not come into the scenario. It needs to enable from BoardConfig.py for specific platforms.
=> feat: Added FIT4 Entry in FIT table

Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Sync up FSP UPD value to BIOS v3323_48
This UPD sync fixed DXE assert error when booting Ubuntu on pendrive
=> fix:[MTL-P] Sync FSP Upd value with BIOS

Platform/MeteorlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
The UPD name of PlatformDebugConsent has been changed to PlatformDebugOption and by default is disabled.
=> fix: [MTL] Correction on UPD naming of PlatformDebugOption

Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/BoardSaConfigPreMem.h
SBL MTL-P DDI config update to support RVP rev2 board
TEST: Able to boot into Ubuntu with HDMI display
=> fix: [MTLP] DDI config update for RVP rev2 board

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.h
Windows memory test failed with write back cacheable setting for memory address above maximum usable address.
The fix programs one MTRR register for memory range above max usable address to override default MTRR register setting after temp ram exit.
=> fix: [ADLN] program memory range above max address uncacheable

BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLibInternal.h
Update the FPDT header length to include the length of boot records. This way we could easily get all the boot records from dumped ACPI FPDT table.
=> Update FPDT Table

Silicon/CommonSocPkg/Include/GpioV2Config.h, Silicon/CommonSocPkg/Include/Library/GpioTopologyLib.h, Silicon/CommonSocPkg/Include/Library/GpioV2ControllerInterface.h, Silicon/CommonSocPkg/Include/Library/GpioV2Lib.h, Silicon/CommonSocPkg/Include/Library/GpioV2Pad.h, Silicon/CommonSocPkg/Include/Library/GpioV2Virtual.h, Silicon/CommonSocPkg/Include/Library/P2SbController.h, Silicon/CommonSocPkg/Include/Library/P2SbSidebandAccessLib.h, Silicon/CommonSocPkg/Include/Library/PcrDefine.h, Silicon/CommonSocPkg/Include/Library/RegisterAccess.h, Silicon/CommonSocPkg/Include/Register/GpioV2VirtualRegs.h, Silicon/CommonSocPkg/Include/Register/P2sbRegs.h, Silicon/CommonSocPkg/Library/GpioV2Lib/GpioV2Init.c, Silicon/CommonSocPkg/Library/GpioV2Lib/GpioV2Lib.inf, Silicon/CommonSocPkg/Library/GpioV2Lib/GpioV2Virtual.c, Silicon/CommonSocPkg/Library/PchP2sbLib/PchP2sbLib.c, Silicon/CommonSocPkg/Library/PchP2sbLib/PchP2sbLib.inf
GPIO V2 library uses sideband access to read and write a particular GPIO also adds support for Virtual GPIO (These GPIO can not have external connections,These are mainly used to integrate discrete GPIO devices present on board)
=> feat: Addition of GPIO V2 library support

Platform/AlderlakeBoardPkg/BoardConfigAzb.py
_LP_SUPPORT was disabled as a result,  GPIO programming was faulty from the Linux side. Enable the _LP_SUPPORT to select the proper ACPI to fix the issue.
=> fix: [AZB] fix GPIO definition issue from linux

Platform/AlderlakeBoardPkg/BoardConfigAdlS.py
Increase OsLoader FD size to 0x58000 for ADL-S to resolve build error.
=> AlderlakeBoardPkg: Increase OsLoader FD size for ADL-S

Platform/IdavilleBoardPkg/Script/StitchIfwi.py, Platform/IdavilleBoardPkg/Script/StitchIfwiConfig.py
Adding a dedicated stitching option to create
IFWI images with flash descriptor verification enabled. and signed accordingly.
=> [ICX-D] Configuration knob for flash descriptor verification

Silicon/ElkhartlakePkg/Include/Register/GpioPinsVer3.h
add missing GPIO and PinMux definitions
=> fix: [EHL] add missing GPIO definitions

Platform/AlderlakeBoardPkg/Script/StitchIfwiConfig_adln.py
The patch adds "rvp_ddr5" stitch option for ADLN RVP (DDR5). Also adds "tsn" in get_xml_change_list() to separate tsn enablement from board stitch.
Verify: ADLN RVP
=> feat: [ADLN] add stitch option for RVP (DDR5)

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
GetContainerHeaderSize() parses header component entries to find the offset of the end of the last component entry and checks this against ContainerHdr->DataOffset. However, there is a valid case where this can exactly equal to ContainerHdr->DataOffset, when the component alignment is small enough and there is no component auth data (AuthType is none). This check is changed to fail on greater than instead of greater or equal to cover this case. fixes #2053
=> fix: Container header parsing failure in some cases.

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
With an external graphics card, windows boot through ACPI_BIOS_ERROR. To fix it SaNvs.IgdOpRegionAddress needs to be set properly. In the AZB case, the IgdOpRegionPlatformInit() was not getting called due to the flag PcdAzbSupport.
=> fix:[AZB] fix ACPI_BIOS_ERR issue in windows boot

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
When 64bit MMIO above 4GB is enabled, ACPI resource descriptor needs to be filled in to describe it.
=> fix: [ADL/RPL] fill in 64bit MMIO resources in ACPI when enabled.

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
S3 registers and SMRR are required to restore for UEFI payload.
Additional change to PR#2075
=> [ADLN] Check UEFI payload for register restore in S3

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Universal UEFI payload used a different structure for the SMI info. So parse the universal payload data structure and set SMI EN in SBL.
=> Fix SMRR setting for universal UEFI payload

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/SioChip.c, Silicon/AlderlakePkg/Include/Register/PchRegsLpc.h
As part of ITE8659 SIO init, HwMon device is enabled, but eSPI decode was not enabled for the IO address range.
=> fix: [ADL/RPL] ITE8659 HwMon initialization fails.

Silicon/AlderlakePkg/FspBin/FspBin.inf
The Silicon\AlderlakePkg\Include\MemInfoHob.h is not updated per platform, so copy the header file from GitHub FSP repo.
=> [ADL] copy MemInfoHob.h from GitHub FSP repo

BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
Fixed debug message to print cpu index, APIC ID and cpu state in order.
=> fix: [Common] Fix debug message to print cpu state

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
Increase the size of the UEFI payload container to accommodate increased payload size from Edk2 network driver and UNDI driver.
=> feat: [RPL-S] Increase UEFI payload container size to accommodate PXE.

Silicon/AlderlakePkg/FspBin/FspBin.inf
Source of the missing VBT Json files:
- ADL-S: IoT ADL-S MR6 (4115_09)
- ADL-N: IoT ADL-N PV (4031_00)
=> [ADL] add missing VBT Json files

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
The CPU PCIe 1x8 (B0:D1.F0) requres HsPhy.
Verified: H-series CPU (ADL-P 4+4+2 45W) on ADL-P RVP
=> [ADLP] support CPU PCIe 1x8 for H-series CPU

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/CfgData/CfgData_BootOption.yaml, Platform/TigerlakeBoardPkg/Script/StitchIfwiConfig_tglu.py
1. Enable the self.ENABLE_PRE_OS_CHECKER in Platform/TigerlakeBoardPkg/BoardConfig.py
2. Put the POSC binary in Platform/TigerlakeBoardPkg/Binaries/PreOsChecker.bin It will stitch in the SBL binary.
3. Assign the boot flag in dlt file: 
BOOT_OPTION_CFG_DATA_0.BootFlags_0 | 20 
BOOT_OPTION_CFG_DATA_2.BootFlags_2 | 20 
BOOT_OPTION_CFG_DATA_4.BootFlags_4 | 20 
During booting, system will load POSC before enter kernel.
=> feat: [TGL] Support loading POSC binary

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py, Platform/RaptorlakeBoardPkg/Rpls/Fsp/FspBinRpls.inf, Platform/RaptorlakeBoardPkg/Rpls/Microcode/MicrocodeRpls.inf
- update FSP version to IoT RPLS MR2 (0C00C650)
- Update platform version to 1.2
- Update ucode to 11f
- 
Signed-off-by: Randy <randy.lin@intel.com>
=> [RPLS] Update FSP/ucode for MR2 release

BootloaderCommonPkg/Include/Library/GraphicsLib.h, BootloaderCommonPkg/Library/GraphicsLib/BmpFormat.c, BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/AcpiInitLib/AcpiBgrt.c, BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf, BootloaderCorePkg/Stage2/Stage2.inf, BootloaderCorePkg/Stage2/Stage2Support.c, BuildLoader.py
The SBL logo is verified as part of Stage2 verification, so untrusted logos won't be parsed, but it's still good to prevent dereferencing BMP header pointers that may fall outside of BMP file.
=> feat: Validate BMP headers to protect against LogoFAIL.

Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardLibrary.c
added support for server platfrom which do not have ME to skip the ME FW status check by comparing HeciBaseAddress.
=> fix: [BootGuardLibrary] TPM intialization for ME less platform

Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Correct the BAR for accessing the PMC MMIO register GEN_PMCON_A
=> fix: [EHL] correct the access to DISB of GEN_PMCON_A

Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
=> [ADL-LP] GPIO: Add missing GPIO definitions

Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/Pep.asl, Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
1) Updated NVS value to match with MTL-P BIOS
2) Nvme device causing S0ix to fail. Added workaround in Pep.asl to
power off NVME related root port (RP01, RP09 and RP11)
=> fix:[MTL-P] Fixed S0ix on MTL-P

Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
Correct 2 GPP_Hx and fill out remaining GPIO definitions for ADL-LP.
=> [ADL-LP] GPIO: Add missing GPIO defines

BootloaderCommonPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c
Resolve a hard hang seen during boot when X2APIC is enabled.
=> [MTL Test SKU] Resolve MPInit hang

BootloaderCommonPkg/Library/TpmLib/TpmLib.c, BootloaderCorePkg/Stage1B/Stage1B.c
This reverts commit 2f277eb9f1bacac9e51b705e81dd1fde3c41d44d.
=> Revert "fix: [TPM] correcting cfg data and key hash"

Platform/MeteorlakeBoardPkg/AcpiTables/AcpiTables.inf, Platform/MeteorlakeBoardPkg/AcpiTables/AcpiTablesPs.inf, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/Pep.asl, Silicon/MeteorlakePkg/MeteorlakePkg.dec
1) Added WA in pep.asl to put blocking NVME RP into standby/wakeup 
2) Added PcdMTLPSSupport to support platform specific register value
=> -fix: [MTL] Fix S0ix on MTL-PS CRB

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c, Platform/TigerlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.inf, Silicon/TigerlakePchPkg/Include/Register/PmcRegs.h
The patch installs reset handlers for FSP requested reboot.
The implementation of ResetShutdown and ResetPlatformSpecific are different from the common lib (i.e., BootloaderCommonPkg/Library/ResetSystemLib), so it results in a platform-specific implementation.
Verified with Issue #2118.
=> feat: [TGL] add ResetSystemLib (#2118)

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/LowPowerSupport.c, Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Size of PepSerialIoI2c array is 6 and NHLT table is 1 
Hence, removing cases where its possible to access out of bound index
=> fix: [MTL] fix coverity issues

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py
When use universal payload, the size is too large. 
Exception: File 'EPAYLOAD.bin' size 0x1D8FD0 is greater than padding size 0x161000 !
=> feat: ADLN: Increase uefipld FD size for ADL-N

Platform/MeteorlakeBoardPkg/Script/StitchIfwiConfig_mtlps.py
Secure flash uses PCH binding region for storing signature. Used Region 13 for secure flash.
=> feat: [MTLPS] Enable PCH binding region for secure flash

Platform/RaptorlakeBoardPkg/BoardConfigRplp.py
EPAYLOAD size was accidentally reverted during upstream. Increasing it back to 2MB.
=> fix: [RPL-P] Epayload size too small for UEFI payload with PXE support.

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Not all root bridges have a physical device at dev 0 func 0 of the root bus, and this requirement prevents some platforms from being fully scanned. From this point, PciEnumerationLib doesn't access the root bridge configuration space at all, so this is an unnecessary check.
Instead, root bus scanning will continue without dev 0 func 0 present. If no devices are found on the root bus, scanning will continue to the next root bridge.
=> fix: Remove check for physical root bridge device before scanning.

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Registering logical root bridges with no devices can cause unexpected behavior for platforms that use _PCI_ENUM_BUS_SCAN_TYPE = "range", since all empty buses in the range will be compared against the resource allocation table entries.
=> fix: Only register root bridges with actual devices, not empty ones.

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/AlderlakeBoardPkg/Script/StitchIfwiConfig_adln.py
Add ChipInitBinary and align ISH size in StitchIfwiConfig.
Adjust payload memory allocation to accommodate Ubuntu kernel image.
=> feat: [ADLN] update Stitch config and payload heap size from ASL.

Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/MtlPchHda.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/MtlSoc.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/MtlSocCnvi.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/PcieMtl.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/SerialIoDevices.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/WwanFlash.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Ssdt/MtlPSCrbRtd3.asl
Remove unused ASL Includes which is causing build failure after basetool updates
=> fix: [MTL] Removed unused ASL Includes

Silicon/MeteorlakePkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
Fixing build issue due to automatic cast conversion warnings from 64-bit unsigned integers to 32-bit unsigned integers
=> fix: [MTL] Fix build issue due to cast conversion warnings

.azurepipelines/azure-pipelines.yml
Added the build of MTL/MTLPS to automation.
Build in ubuntu 22.04 because 
1. new acpica-tools depends on libc6 (>= 2.34).
2. acpi tool require to update to avoid build error.
=> feat: [MTL] Updated automation file to include MTL/MTLPS

BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLibGeneric.c
This addresses an issue noticed when attempting to initialise the eMMC in DDR, 52MHz, 8-bit bus width mode. Specifically, the error occurred as the switch routine for the bus_width mode in the device's EXT_CSD was deemed unsuccessful. The relevant error logs are shown below: 
```shell
MmcSetBusMode: HsTiming 1 ClockFreq 52 BusWidth 8 Ddr TRUE
MmcCheckSwitchStatus: The switch operation fails as DevStatus is 0x00000980
MmcCheckSwitchStatus: Check status fails with Device Error
MmcSetBusMode: Switch to HighSpeed Device Error
MmcSetBusMode Fail Status = 0x80000007
``` 
Please refer to the JEDEC Embedded Multi-Media Card Electrical Standard (5.1) JESD84-B51 Section 7.4.67 (pg. 203) Table 145: "HS_TIMING must be set to “0x1” before setting BUS_WIDTH for dual data rate operation 
(values 5 or …
=> Switch to HS clock frequency before switching bus width for DDR mode

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py, Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf, Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf
- FSP version: IoT RPL-S MR3 (0C.00.CC.20)
- Microcode version: 120
- VBT version: 250
- platform version: 1.3
=> [RPLS] Update FSP/UCODE for MR3 release

BaseTools/Scripts/PatchCheck.py, MdePkg/Library/BaseLib/SafeString.c
The current BaseTools aligned with edk2-stable202311 introduces the replacement of __FUNCTION__ with __func__, which causes compiler failure since VS2015 don't support __func__. This patch reverts the change and its checker to continue the VS2015 support.
Reference commit IDs from edk2 repo: b17a3a1 and c9fb11f
=> fix: [Common] build failed with VS2015

BootloaderCorePkg/Library/StageLib/StageLib.c, BootloaderCorePkg/Library/StageLib/StageLib.inf
This will increase time of Board PostMemoryInit hook and TempRamExit, but improve the performance of PostTempRamExit hook, PreSiliconInit hook and FSP-S.
In total, the boot time can be reduced by ~20ms.
=> Let Stage1B run in memory accoss all stages in fast boot mode

Platform/MeteorlakeBoardPkg/Script/StitchIfwi.py, Platform/MeteorlakeBoardPkg/Script/StitchLoader.py
The commit refactors stitch scripts to not assume "SblOpen" is the the root of SBL source. It also corrects minor typos, including incorrect usage of WHL/CFL/ADL identifiers.
=> [MTL] fix stitch scripts

BuildLoader.py
ACM FIT version for legacy platforms use 0x100.
Newere platforms use version 0x200
=> Add configurable option for ACM FIT version

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c, BootloaderCorePkg/IncludePrivate/BootloaderCoreGlobal.h, BootloaderCorePkg/Stage1B/Stage1B.c
length of external config data and hash keys extended to the TPM was incorrect. This commit fixes this issue.
=> fix: [Stage1B] Extending correct cfg data and hash length in tpm

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
This commit updates the stack settings from hardcoded values to runtime calculated ones to prevent potential stack corruption in Stage1B for certain customizations.
Additionally, the commit enlarges the FD sizes for STAGE1B_SIZE and PAYLOAD_SIZE to accommodate the new changes. It also increases the sizes for STAGE2_SIZE and OS_LOADER_FD_SIZE to support 64-bit Linux builds.
Verified: TGL LPDDR4 RVP with the following smoke tests:
- OSLoader (debug, fsp debug, release, 64-bit) to Yocto
- Uefi payload (debug, fsp debug, release, 64-bit) to Windows
=> [TGL] fix Stage1B stack corruption

BootloaderCorePkg/Library/FspApiLib/FspMemoryInit.c, BootloaderCorePkg/Library/FspApiLib/FspSiliconInit.c
1) Some FSP 2.4 implementations are non-conforming and use FSPM_ARCH_UPD instead of FSPM_ARCH2_UPD as indicated by the specification. Logic is changed to check FSPM UPD header revision for structure version instead of FSP spec revision.
2) MultiPhase FSP PhaseIndex is one-based so loop comparisons need to take this into account. Side effect is that the last phase may be missed. No current platform FSP is utilizing this.
=> fix: FSP 2.4 issues

Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
Gpio pad enabled for SCI need not be in unlocked
state.Hence removing the condition check.
=> fix: Remove Gpio lock state check for SCI

Platform/RaptorlakeBoardPkg/BoardConfigRplp.py, Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
EPAYLOAD_SIZE increased to accomodate Uefi Payload built based on edk2-stable202311.
=> fix: [RPL-P/S] increased EPAYLOAD size for latest UefiPld.

Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
MultiPhaseSiInit was fixed in pull #2171 to correctly interpret NumberOfPhases as 1-based instead of zero based. This exposed an issue in TGL where FSP returns that there is 1 phase supported in MultiPhaseSi init, but it actually supports zero phases. The bug fixed by #2171 was masking this issue.
The workaround in TGL is to override the FSP-S Info header so it appears to SBL that MultiPhaseSiInit isn't supported (since it isn't supported properly) so the MultiPhaseSiInit is skipped entirely.
=> fix: [TGL] FSP returns incorrect number of phases for SiInit

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/MeteorlakeBoardPkg/BoardConfigMtlp.py
EPAYLOAD_SIZE increased to accommodate UEFI payload built based on edk2-stable202311
=> fix: [ADLN/MTL] increased EPAYLOAD size for latest UefiPld

Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ElkhartlakePkg/Include/Register/PmcRegs.h, Silicon/ElkhartlakePkg/Include/Register/RtcRegs.h, Silicon/ElkhartlakePkg/Library/Stage2SocInitLib/Stage2SocInitLib.c
This commit resolves the issue where the SMI handler was not being triggered during S3 resume. The problem was due to the functions RestoreS3RegInfo and TriggerPayloadSwSmi not being called.
In addition, the commit also:
1. unset the PME_B0_EN as UEFI Payload does not have its handler
2. remove the ClearSmbuStatus() because
- the HSTS.B_SMBUS_IO_SMBALERT_STS in SMBUS (B0:D31:F4) should be
handled and cleared by device driver or an appropriate SMI handler.
- the ClearSmi() will clear GPE0_STS_127_96.SMB_WAK_STS if it is set
3. unset (FSPS) PeiGraphicsPeimInit and GraphicsConfigPtr during S3 resume
4. narrow the var scope of mSmmBaseInfo and mS3SaveReg
5. add required bitfield declaration
Verified with:
1. UEFI Payload + Ubuntu on EHL CRB (release build)
2. OSLoader (release build)
when …
=> [EHL] trigger SMI handler in S3 resume

BootloaderCommonPkg/Library/MultibootLib/Multiboot.c
After moving multiboot module to a 4k-aligned address, the end address of that module should be changed accordingly.
=> MultibootLib: Fix incorrect end address in AlignMultibootModules()

Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/PchFru.asl, Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/ScsEmmc.asl, Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/ScsEmmcAdl.asl, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
To indicate eMMC is enabled in ACPI, the patch
1. set EMCE and EMH4 in PchNvs
2. add EMMC device
The patch is applicable for ADL-N only
Verified: ADL-N CRB by Vincent Chen <vincent.chen@intel.com>
=> enable eMMC in ACPI

BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c, BootloaderCommonPkg/Library/AhciLib/AhciDevice.c, BootloaderCommonPkg/Library/AhciLib/AhciMode.c, BootloaderCommonPkg/Library/AhciLib/AhciMode.h, Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/AlderlakeBoardPkg/BoardConfigAdlPs.py, Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
This commit fixes two AHCI operations:
1. AhciWriteBlocks: caused by wrong command
2. AhciGetMediaInfo: caused by wrong offset
The patches also updates the EFI_ATA_IDENTIFY_DATA to align with the ATA8-ACS.
In addition, this commit ports the following changes from EDK2, to enhance the command completion and trace:
1. cc28ab7a1d7: MdeModulePkg/AtaAtapiPassThru: Check IS to check for command completion
2. b465a811006: MdeModulePkg/AtaAtapiPassThru: Add SATA error recovery flow
3. 64e25d4b062: MdeModulePkg/AtaAtapiPassThru: Restart failed packets
4. 91d95113d07: MdeModulePkg/AtaAtapiPassThru: Trace ATA packets
5. 4c7ce0d285b: MdeModulePkg AtaAtapiPassThru: Skip the potential NULL pointer access
Last, the commit adjusts OS_LOADER_FD_SIZE for several platforms for x64 build
Verified: Using …
=> ahci: fix AhciWriteBlocks and update Ahci code

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/StageLib/StageLib.c, BootloaderCorePkg/Library/StageLib/StageLib.inf, BuildLoader.py, Platform/ApollolakeBoardPkg/BoardConfig.py, Platform/QemuBoardPkg/BoardConfig.py
Adding new Board Config item REMAP_STAGE1B to control remapping Stage1B into permanent memory after FSP-M. Decouple this from ENABLE_FAST_BOOT and STAGE1B_XIP. This makes it simpler to enable this remap when the slight performance boost may be needed, and leave it disabled by default.
=> feat: Add BoardConfig field to control Stage1B remap

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/AlderlakeBoardPkg/BoardConfigAdlN50.py
While loading the DEBUG build universal payload size around 10MB, system hang with this log: ASSERT [Stage2] BootloaderCorePkg\Library\MemoryAllocationLib\MemoryAllocationLib.c(61): LdrGlobal->MemPoolCurrTop >= Bottom
fail on https://github.com/slimbootloader/slimbootloader/blob/c0530d37af2485df8f3e9734507d7524704648b9/BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c#L846
=> fix: [ADLN] increase RSVD_MEM_SIZE

Platform/AlderlakeBoardPkg/Script/StitchIfwi.py, Platform/CommonBoardPkg/Script/BtgSign.py, Platform/CommonBoardPkg/Script/security_stitch_help.py, Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py, Platform/IdavilleBoardPkg/Script/BtGUtility.py, Platform/MeteorlakeBoardPkg/Script/StitchIfwi.py, Platform/MeteorlakeBoardPkg/Script/security_stitch_help_mtl.py, Platform/RaptorlakeBoardPkg/Script/StitchIfwi.py, Platform/TigerlakeBoardPkg/Script/StitchIfwi.py
Python imp module is removed in 3.12+ and will cause a build error. Replace with importlib.machinery.SourceFileLoader.
=> fix: Remove deprecated python imp module

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arls.py
Updated BpmStrutVersion and CnbsInclude in BpmGen2 params for BTG5 to work with ACM 1.20.17
=> fix: [ARLS] Updated BpmGen2 params for ACM 1.20.17

BootloaderCommonPkg/Include/Library/MultibootLib.h, BootloaderCommonPkg/Library/MultibootLib/Multiboot.c, BootloaderCommonPkg/Library/MultibootLib/Multiboot2.c, PayloadPkg/OsLoader/OsLoader.c
There is a flag in both multiboot and multiboot2 image indicating modules must be loaded to page boundaries. Currently this flag is not handled when loading multiboot images in ELF format. Check this flag and move the loaded modules if needed before SetupMultibootInfo().
=> OsLoader: Handle module align flag for multiboot images in ELF format

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLibAzb.c, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/RaptorlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/RaptorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
The patch improves the dev experience for configuring FSP-M UPDs: RsvdSmbusAddressTablePtr and PchNumRsvdSmbusAddresses: Prior to this patch, developers had to apply a memory patch at address 0xfffc3ff8, which was cumbersome and inconvenient. With the introduction of this patch, developers can now directly modify the DLT, simplifying the configuration steps and improving workflow efficiency.
=> fix: improve the DX for RsvdSmbusAddressTablePtr #2207

Platform/AlderlakeBoardPkg/BoardConfigAdlN50.py, Platform/AlderlakeBoardPkg/BoardConfigAdlP.py, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Platform/AlderlakeBoardPkg/BoardConfigAzb.py, Silicon/AlderlakePkg/FspBin/FspBin.inf, Silicon/AlderlakePkg/FspBin/FspBinAzb.inf, Silicon/AlderlakePkg/FspBin/FspBinIpu.inf
When the fsp.git commit id is updated,
it will update all platform fsp versions without testing. 
Also adjust the fd size in adln50 project to avoid build break.
=> feat: [ADL] Separate Fsp version by project

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Silicon/AlderlakePkg/FspBin/FspBin.inf, Silicon/AlderlakePkg/Microcode/Microcode.inf
* Update FSP/UCODE/for MR5 release
- update FSP version to IoT ADL-N MR5 (0C028940)
- update Microcode version to 17
- update platform version to 1.5
Basic boot tested on ADL-N CRB.
=> feat: [ADLN] MR5 update

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
When editing a boot option entry, new SwPart value is only assgined to FileImage or LbaImage struct, while BootOption->SwPart is cleared, breaking traditional linux boot as it uses SwPart there. Assign the new value to BootOption->SwPart to keep compatibility.
=> ShellLib: Assign BootOption->SwPart on editing boot option

BootloaderCorePkg/Stage1A/Ia32/UpdateSelectors.nasm, BootloaderCorePkg/Stage1A/Stage1A.c, BootloaderCorePkg/Stage1A/Stage1A.h, BootloaderCorePkg/Stage1A/Stage1A.inf, BootloaderCorePkg/Stage1A/X64/UpdateSelectors.nasm
If ResetVector GDT is different from that loaded in Stage1A SecStartup() then segment selectors need to be reloaded after GDT is updated.
=> fix: Reload segment selectors after GDT Load in Stage1a

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/PchPse.asl, Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
Ethernet auto-negotiation failed since the ACPI calling method of Windows GbE driver is changed from "_IPC" to "IPCG", starting from version 5.123.23.601. Hence, in INTC1033 ACPI device, change the ACPI method name accordingly.
=> fix: [EHL] modify ACPI method name to resolve GbE auto-negotiation issue

Platform/TigerlakeBoardPkg/BoardConfig.py, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
To avoid the POSC module loading by default build.
=> fix: [TGL] Disable Fusa by default

BootloaderCommonPkg/Library/XhciLib/XhcPeim.c, BootloaderCommonPkg/Library/XhciLib/XhcPeim.h, BootloaderCommonPkg/Library/XhciLib/XhciReg.h, BootloaderCommonPkg/Library/XhciLib/XhciSched.c, BootloaderCommonPkg/Library/XhciLib/XhciSched.h
Prior to this series of patches, the SBL USB subsystem relied on the edk2 codebase, specifically the MdeModulePkg/Bus/Pci/XhciPei module, as of sometime in 2020. Since that time, numerous corrections have been made. Moreover, there were critical fixes implemented in XhciDxe that had not been incorporated. This set of patches brings over most of the stability and reliability improvements from both the XhciPei and XhciDxe modules within edk2:
b97243dea3c95ad923fa4ca190940158209e8384: Check return value of XHC_PAGESIZE register
b5379899b38ed84561db6dc07dc4641a049ae238: Fix TRT when data length is 0
2363c6926098ee5c75c8780d07f88f5c21010683: Retry device slot init on failure
a3212009d95bbcba7d08076aba2eee51eb1f8e7c: Error handle for USB slot initialization failure …
=> fix: [xhci] sync edk2 usb subsystem

BootloaderCommonPkg/Include/Library/DebugAgentLib.h, BootloaderCommonPkg/Library/DebugAgentLib/DebugAgentLib.inf, BootloaderCommonPkg/Library/DebugAgentLib/PeCoffExtraActionLib.c, BootloaderCommonPkg/Library/DebugAgentLib/PeCoffExtraActionLibNull.c, BootloaderCommonPkg/Library/DebugAgentLib/X64/ArchDebugSupport.c, BootloaderCommonPkg/Library/DebugAgentLib/X64/ArchDebugSupport.h, BootloaderCommonPkg/Library/DebugAgentLib/X64/AsmFuncs.nasm, BootloaderCommonPkg/Library/DebugAgentLib/X64/DebugException.h, BootloaderCommonPkg/Library/DebugAgentLib/X64/IntHandler.nasm, BootloaderCommonPkg/Library/DebugAgentLib/X64/IntHandlerFuncs.c, BootloaderCommonPkg/Library/DebugAgentLib/X64/ProcessorContext.h
Adding 64-bit DebugAgentLib source files, header files and nasm files to build SBL image with ENABLE_SOURCE_DEBUG=1
=> fix: [ARL] Fixing 64-bit build with ENABLE_SOURCE_DEBUG

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableEhl.h
modify GPIO GPP_U0 (RGMII2_INT) for PCH GbE
=> fix: [EHL] WOL is not working in PCH GbE port

Platform/RaptorlakeBoardPkg/BoardConfigRplp.py, Platform/RaptorlakeBoardPkg/Script/StitchIfwi.py, Platform/RaptorlakeBoardPkg/Script/StitchIfwiConfig_rplp.py
Cause by cefbf78daed2e8609bb248fb740f381427ce07df. 
The default build will include the DACM region and the replace file should be present during stitch step.
Add fusa stitch option for users who want to replace that component in the BIOS.
=> fix: [RPLP] Stitch fail when missing diag acm binary

Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf, Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf, Silicon/ArrowlakePkg/Include/CpuPcieInfo.h, Silicon/ArrowlakePkg/Include/Library/CpuPcieHsPhyInitLib.h, Silicon/ArrowlakePkg/Include/Library/PcieRpLib.h, Silicon/ArrowlakePkg/Include/PchLimits.h, Silicon/ArrowlakePkg/Include/PchPcieRpConfig.h, Silicon/ArrowlakePkg/Include/PcieConfig.h, Silicon/ArrowlakePkg/Include/PcieRegs.h, Silicon/ArrowlakePkg/Include/Register/PchPcieRpRegs.h, Silicon/ArrowlakePkg/Include/Register/PcieSipRegs.h, Silicon/ArrowlakePkg/Library/BasePchPciBdfLib/PchPciBdfLib.c, Silicon/ArrowlakePkg/Library/BasePcieHelperLib/BasePcieHelperLib.c, Silicon/ArrowlakePkg/Library/BasePcieHelperLib/BasePcieHelperLib.inf, Silicon/ArrowlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.c, Silicon/ArrowlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.h, Silicon/ArrowlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.inf, Silicon/ArrowlakePkg/Library/PciePm/PciePm.c, Silicon/ArrowlakePkg/Library/PciePm/PciePm.inf, Silicon/ArrowlakePkg/Library/PcieRpLib/PcieRpLib.c, Silicon/ArrowlakePkg/Library/PcieRpLib/PcieRpLib.inf
S0ix failed when NVME attached due to incorrect PCI device configuration
Ported RootPortDownStreamPmConfiguration and related Libraries
To fix incorrect PCIE ASPM and L1 Configuration
Implementation is silicon-dependent due to registers definition
This implementation is using the following ADL PCIE PM PATCH as reference
https://github.com/slimbootloader/slimbootloader/commit/3bbfe44bec72931e8088e2bdd7af417589003e3e
=> fix: [ARL-S] Fixed S0ix failing due to incorrect PCI ASPM and L1 config

Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Issue: fsp debug log goes to EC port on RVP.
This fix also require FSP update to BIOS version 4053_51 or newer.
=> fix: [MTL] Debug fsp log go to wrong port

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Accidental removal of EFIAPI from CalculateRelativePower function in Stage2BoardInitLib.c caused GCC to issue incompatible-pointer-types error. This patch addresses the build issue.
=> fix: [ARL] Fix SBL build issue in Linux

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arlh.py
BiosRedAssistance setting is added to stitch config. By default it is disabled. Enable for FW resiliancy.
=> fix:[ARL-H] Added BiosRedAssistance setting in stitch config

BuildLoader.py
When multiple versions of Visual Studio (VS) were installed, the BaseTools would be built with the latest version, regardless of user preference (i.e., specified by the "-t" option). This behavior was incorrect for users needing to build with a specific VS. This commit addresses the issue by aligning the BaseTools to build with the user-specified version of VS.
Test steps:
1.   Two versions of VS are installed: VS2017 and VS2022
2.   Default build: python BuildLoader.py build tgl   # also verified with "mtl"
3.   Build with specific version: python BuildLoader.py build tgl -t vs2022
=> fix: [Tool] BaseTools built with specified VS on Windows

BootloaderCorePkg/Tools/GenContainer.py
When no auth parameter is specified on the command line, gen_layout chooses auth type based on provided key, but this does not get correctly applied to the monolithic signing component because of an order of operations issue.
=> fix: GenContainer.py not setting default auth type correctly

Platform/ArrowlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
The FSP UPD code region should try to cover SBL Stage1A and Stage1B with a minimum region size. It would impact MTRR settings before memory init and the MTRR settings would be updated after FspTempRamExit().
Reduce the code region size could improve boot performance for some SKUs.
=> ARL: Update FSP-T UPD code region

Platform/ArrowlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Check EC device existence before sending command.
The patch prevents waiting for timeout when reading BoardId.
=> fix [ARL] Check EC device existence on board

Platform/ArrowlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Platform/ArrowlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf, Silicon/ArrowlakePkg/Include/CpuRegs.h
This patch adjusted MTRR settings during PostTempRamInit notification to cover full flash code region if Boot Guard profile 0 is used or Fast Boot is enabled.
=> feat: [ARL] Adjust MTRR to cover full flash

MdePkg/Library/BaseFdtLib/libfdt/libfdt/fdt_rw.c
When build with this command python BuildLoader.py build tgl -a x64
Build error found:
MdePkg\Library\BaseFdtLib\libfdt\libfdt\fdt_rw.c(194) : error C2220: the following warning is treated as an error MdePkg\Library\BaseFdtLib\libfdt\libfdt\fdt_rw.c(111) : warning C4706: assignment within conditional expression MdePkg\Library\BaseFdtLib\libfdt\libfdt\fdt_rw.c(194) : warning C4706: assignment within conditional expression MdePkg\Library\BaseFdtLib\libfdt\libfdt\fdt_rw.c(89) : error C2220: the following warning is treated as an error
ref: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4706?view=msvc-170
cc flag change to: DEBUG_VS2019_X64_CC_FLAGS     = /nologo /c /WX /GS- /W4 /Gs32768 /D UNICODE /Gy /FIAutoGen.h /EHs-c- /GR- /GF /Z7 /Od
=> Fix: disable opt build cause error

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c, Platform/RaptorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
The PLATFORM_{NAME} macro is dynamically defined by BuildUtility.py, which is based on the board file name. Since ASL has been merged into ADL-N, the PLATFORM_ASL macro has become obsolete and is no longer valid. This commit removes all instances of the deprecated PLATFORM_ASL.
Additionally, this commit addresses an issue where PLATFORM_ADLN was not defined in Stage1ABoardInitLib.c during the build process for ADL-N. The cause was that ConfigDataStruct.h was not included.
=> fix: [ASL] remove deprecated PLATFORM_ASL

Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
The debug fsp report:
SDI#0: No matching HD-Audio codec verb table found for codec (0x10EC0897).
fix and can see
SDI#0: Detected HD-Audio Codec 0x10EC0897 rev 0x04
Found Verb Table for VendorID 0x10EC, DeviceId 0x0897, RevisionID 0xFF (SDI:FF, size: 4 dwords)
Verified on MCL
=> fix: [MCL] HDA Verb table set fail

BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.c, BootloaderCommonPkg/Library/GraphicsLib/GraphicsLib.c, BootloaderCommonPkg/Library/LinuxLib/LinuxLib.c, BootloaderCommonPkg/Library/PagingLib/PagingLib.c, BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c, BootloaderCommonPkg/Library/ShellLib/CmdMm.c
Address following coverity issues
1. Integer Overflow or Wraparound (CWE 190)
2. Unexpected Sign Extension (CWD 194)
Test = boot up Windows and Ubuntu
=> fix: [Common] Fix coverity issues for x64 build

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
Some important pinmux definitions are missing, e.g., Both H4/H5 and E12/E13 are for I2C0.
=> fix: [ADL-P] add missing pinmux definitions

BootloaderCommonPkg/Library/DebugAgentLib/DebugAgent.h, BootloaderCommonPkg/Library/DebugAgentLib/DebugAgentLib.c
DebugAgentLib was using its own IDT Entry structure definition that didn't adjust for x64. Removed this definition and switched to built in definition from ProcessorBind.h which does adjust for architecture correctly.
=> fix: Source Level Debug breaks in X64.

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.h, BootloaderCorePkg/Library/PciEnumerationLib/PciCommand.c, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c, BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf, BootloaderCorePkg/Library/PciEnumerationLib/PciResizableBar.c
This commit adds support for PCIe resizable BARsupport. 
The feature can be enabled by setting PcdResizableBarSupport for the board build script and its disabled by default.
=> feat: [common] Enable PCIe resizable BAR support

Silicon/RaptorlakePkg/Rplp/Fsp/FspBinRplp.inf, Silicon/RaptorlakePkg/Rplp/Microcode/MicrocodeRplp.inf
- FSP version is NEX RPL-P MR2 Hotfix (0C.01.DE.40)
- Microcode version is 4123
=> [RPLP] Update for MR2 Hotfix release

Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf, Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf
BIOS version is NEX RPL-S MR4/RPL-S Refresh MR2 Hotfix (5134_05) FSP FSP version is 0C00DE40
platform version is 1.4
Microcode Files are: ['m_07_90672_00000036.pdb', 'm_32_b0671_00000129.pdb']
Basic boot verified on Linux/Windows.
=> feat: [RPLS] Update MR4_hotfix Release

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
When checking whether to update the RTD3 SSDT table for ADL RVP/CRB SKUs, the GetPlatformId() return values are compared against the board id that was probed from the hardware (instead of the platform id to which the board id was mapped; cf. EcSupport.c).
=> fix: [ADLN] Correct platform id values in ACPI tables update

BootloaderCommonPkg/Library/ShellLib/CmdFs.c
When OsLoader shell "fs load" failed to read file, the assertion happened with the error log "CR has Bad Signature". It's caused when FreePool() tried to free the memory allocated by AllocatePages(). So modify the free memory function to FreePages()
=> fix: [Common] correct the free memory function for fs load command

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/ArrowlakePkg/Library/GpioV2Lib/GpioV2Init.c, Silicon/ArrowlakePkg/Library/MtlPchPcieRpLib/MtlPchPcieRpLib.c, Silicon/ArrowlakePkg/Library/PcieRpSocLib/PcieRpSocLib.c
FSP might produce a HOB to report PCH P2SB SBREG_BAR, but FSP doesn't program it to P2SB PCI device yet. So need update the logic on how to use it.
This PR also clean up the debug message.
=> ARL: Fix PCH SBREG_BAR update logic

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/MeteorlakeBoardPkg/AcpiTables/Dsdt/PcieAdl.asl, Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Some TCC codes are separated with the directive #if FeaturePcdGet(PcdTccEnabled), which might be evaluated as False especially during C preprocessing.
Besides, the PcdTccEnabled is declared as FixedPcd. So changed the directive to #if FixedPcdGetBool.
=> fix: [Common] fix some TCC codes didn't take effect

Platform/AlderlakeBoardPkg/BoardConfigAzb.py, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf, Silicon/AlderlakePkg/AlderlakePkg.dec
Link Width degrade when performing Reset. Expected to be x4, but degrade to x2. The solution to clear the bit DRXTERMDQ for these specific devices.
=> feat: [AZB] X710 Loss Issue on AZB CPU PCIe x4 Bus

Silicon/ArrowlakePkg/Library/TopSwapLib/TopSwapLib.c
After enabled GPIOV2, TopSwap library used new P2sbLib. For ARL-P, it looks P2SB SBI method doesn't work for P2sb registers, so changed to use MMIO method.
With this change, it could boot to shell using legacy UART (0xFF) or SOC UART (0).
=> ARLP: Fix ARL-P/H/U boot issue

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Update the GfxInfo HOB FrameBufferBase after the IGD BAR is reallocated during PCI enumeration. This resolves an issue where video output doesn't work for the UEFI payload with newer FSP versions.
=> fix: [ARL] Update GfxDeviceInfo after PCI Enumeration.

Silicon/MeteorlakePkg/FspBin/FspBin.inf, Silicon/MeteorlakePkg/Microcode/Microcode.inf
BIOS version is NEX MTL-UH_MTL-PS MR1 (4053_58) FSP FSP version is 0DE0BA41
platform version is 1.1
Microcode Files are: ['m_e6_a06a4_0000001f.pdb']
Boot tested on ubuntu/win11.
=> feat: [MTLP] Update MR1 hotfix Release

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h
Ext2Fs->Ext2FsFeaturesIncompat report EXT2F_INCOMPAT_CSUM_SEED so that fail into not support.
boot tested with old/new yocto image, ubuntu.
=> fix: osloader can't boot on new yocto build

Silicon/CommonSocPkg/Library/PchPcrLib/PchPcrLib.inf
Resolve the GetPchPcrAddress reference when build with CSME update driver.
=> fix: [ADLN] Revert reference lib in PchPcrLib

MdePkg/Library/BaseFdtLib/libfdt/libfdt/fdt_overlay.c
Check fdt_getprop_by_offset() return value for NULL pointer (like all other callers) to prevent a Coverity issue (CWE-476).
=> fix: [common] Fix Coverity issue

Platform/ArrowlakeBoardPkg/AcpiTables/EcSsdt/EcBaseMethod.asl
Adding a 3ms delay before any EC Read from ACPI resolves the windows boot delay. Still following up on root cause.
=> fix: [ARL-S] Workaround for windows boot delay

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
When platform chooses BusScanTypeList for PCI enumeration, the BusLimit should be set to PCI_MAX_BUS. The BusScanItems defines primary bus for PCie root port. If there is device attached to root port, which will present on secondary bus, in the meantime the bus number is greater than Buslimit, this device cannot be found from enumeration. Assign PCI_MAX_BUS to BusLimit to prevent this issue.
=> fix: [Common] Assign PCI_MAX_BUS to BusLimit for BusScanTypeList type

Silicon/CommonSocPkg/Library/MeChipsetLib/MeChipsetLib.c
Setting MeHeciTimeoutsEnabled to TRUE so that Heci packet read timeout is enabled.
=> fix:[MeChipsetLib] Fix the issue of HECI read timeout

Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/Bat0Virt.asl, Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/Bat1Real.asl, Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcDevice.asl, Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcNvs.asl, Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcSsdt.asl, Platform/MeteorlakeBoardPkg/AcpiTables/Ecdt/Ecdt.act, Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/MeteorlakePkg/Include/EcNvsAreaDef.h
Windows system log will report Event 13, ACPI error several times and cause windows slow booting issue.
This patch contains:
1. EC data can't be read/updated.
2. fixed ACPI error in Linux system
3. Include NVS def and sync NVS definition. Without this, the EC ACPI device is disappear in windows.
=> fix: [MTL-P] EC timeout issues/ACPI error on RVP.

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arls.py
Changes include modifying some XML path and value list for RVP S02 board and adding XML path and value list specific to RVP S03 and S04 board. These XML values should match with the BIOS IFWI for respectively RVP boards.
No changes to StitchIfwi.py command for RVP S02 board. As for RVP S03 and S04 boards, append the StitchIfwi.py command with "-o s03" and "-o s04" respectively.
=> feat: [ARLS] Adding RVP S03 and S04 board in StitchIfwi script

Platform/AlderlakeBoardPkg/CfgData/CfgData_BootOption_Azb.yaml, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Resolved hardware issue where USB instance 0, mapped to eMMC, needs initialization and deinitialization to detect a USB flash drive.
=> fix:[AZB] Fix USB drive detection issue on CRB

BootloaderCorePkg/Stage2/Stage2Hob.c
If Verified Boot is disabled, the data pointed by HashStorePtr is not well-defined, so is the content of the KeyHash Hob. In this case, when fwupdate tries to verify the PUBKEY_FWU hash of the FwuImage, the result will be non-deterministic.
=> fix: [COMMON] build KeyHash Hob only when Verified Boot is enabled

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
The print statement just a value print that is not required in release build. Hence, change the print priority.
=> fix:[ADL] Remove extra print in release build

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml, Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
The FSP-M UPD has an option .PchHdaAudioLinkSspEnable to enable HD Audio SSP_N/I2S links; however, this cannot be modified from SBL configuration. This change adds the MEMORY_CFG_DATA.PchHdaAudioLinkSspEnable option to set the UPD value. (Default setting is all channel disabled as before).
=> feat: [ADLN] Expose FSP-M .PchHdaAudioLinkSspEnable UPD to SBL config

BootloaderCorePkg/BootloaderCorePkg.dec, BootloaderCorePkg/BootloaderCorePkg.dsc, BootloaderCorePkg/Library/MpInitLib/MpInitLib.c, BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf, BuildLoader.py
Some silicon requires longer than provided for all APs to enter the wakeup routine. This change makes this platform configurable. The default wait time is none and can be increased for platforms with higher core count Si.
=> feat: Add Board flag for AP Init Wait time

Platform/ArrowlakeBoardPkg/AcpiTables/EcSsdt/EcBaseMethod.asl
Updated the 3ms delay after EC Read and 5ms after EC Write. Give EC time to complete RAM access. Added missing EC mutex release
=> fix: [ARLS] Workaround for Windows boot and shutdown

.gitmodules, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2Lib.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2LibE9.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2LibL9.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2LibM7.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2LibU8.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCrypto2LibY8.inf, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCryptoSupport.c, BootloaderCommonPkg/Library/IppCrypto2Lib/IppCryptoSupport.h, BootloaderCommonPkg/Library/IppCrypto2Lib/README.md, BootloaderCommonPkg/Library/IppCrypto2Lib/hmac.c, BootloaderCommonPkg/Library/IppCrypto2Lib/immintrin.h, BootloaderCommonPkg/Library/IppCrypto2Lib/intrin.h, BootloaderCommonPkg/Library/IppCrypto2Lib/rsa_verify.c, BootloaderCommonPkg/Library/IppCrypto2Lib/sha256.c, BootloaderCommonPkg/Library/IppCrypto2Lib/sha384.c, BootloaderCommonPkg/Library/IppCrypto2Lib/sm3.c, BootloaderCommonPkg/Library/IppCrypto2Lib/stdlib.h, BootloaderCommonPkg/Library/IppCrypto2Lib/x86intrin.h, BootloaderCorePkg/Tools/BuildUtility.py
Latest ipp-crytpo code is FIPS compliant. Need to add it as a submodule to maintain FIPS compliance. This requires adding each ASM optimized implementation as a separate .inf file and selecting at the platform level. Old IppCryptoLib instance needs to be kept for backwards compatibility.
=> feat: Add FIPS compliant IppCryptoLib instance.

.azurepipelines/azure-pipelines.yml
acpica-tools_20200925-8_amd64.deb is not available from http://archive.ubuntu.com/ubuntu/pool/universe/a/acpica-unix Change to acpica-tools_20200925-6_amd64.deb instead.
=> CI: Fix the Linux CI Build

Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c
If the init table passed to GPIO initialization contains an invalid pin number, debug builds of the init library would terminate silently (i.e. no entries after the offending one would be processed at all, and common config registers like HOSTSW_OWN and unlock data might not get updated). Note that release builds would not detect (and thus simply skip) invalid entries.
This change:
- aligns the debug to the release build behavior: handle all valid GPIO pins passed to the initialization routine;
- complain about invalid pins (debug builds only).
Signed-off-by: Bruno Achauer <bruno.achauer@intel.com>
=> fix: [Common/GpioLib] Don't let invalid pin stop GPIO initialization

Platform/ArrowlakeBoardPkg/AcpiTables/AcpiTablesP.inf, Platform/ArrowlakeBoardPkg/AcpiTables/Ssdt/MtlPRvpRtd3.asl, Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c, Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/LowPowerSupport.c
Enable S0ix feature on ARLH RVP
Updated Fspm and Fsps to include the BIOS settings required for s0ix
=> feat: [ARLH] Enable s0ix on ARLH RVP

Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
FSP no longer supports value of 4 (Auto) for DmiAspm. Setting this breaks Package C10 and S0ix. Fallback to YAML config value (currently 2 for "L1").
=> fix: [ARL] DmiAspm value "4" no longer supported by FSP

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c, PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.h
- According to the Intel 64 and IA-32 Architectures Software Developer's Manual, Volume 3A, Section 10.11.1 titled "Microcode Update", the microcode header does not include an SVN (Security Version Number) field. Additionally, the subsequent section does not reference the SVN either, it only mentions the update revision.
- Added check to ensure UpdateRevision is not lower than the minimum required version.
- If UpdateRevision is lower, an error is logged and appropriate action is taken.
- This prevents unauthorized rollback to older, potentially insecure versions of microcode.
=> feat: [RPL-A] Deny the update of older microcode versions.

Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
This commit addresses the GCC build issue in Linux, where aggresive-loop-optimizations warning was reported in FspsUpdUpdateLib.c.
=> fix: [ARL] Fix Linux GCC build issue

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c, BootloaderCorePkg/Tools/GenContainer.py, Platform/AlderlakeBoardPkg/BoardConfigAdlPs.py, Platform/ApollolakeBoardPkg/BoardConfig.py
Prevent GenContainer.py from creating monolithic signed containers with no component authorization data. Prevent ContainerLib from authenticating such containers when verified boot is enabled.
=> fix: Prevent creation or authentication of containers with no comp auth

Platform/CommonBoardPkg/CfgData/CfgData_Common.yaml
Insert the attribute "type : Combo" for the parameter "EnableCrashMode", to make it to be displayed in Config Editor.
Verified: GEN_CFG_DATA.EnableCrashMode can be changed.
=> Fix: EnableCrashMode missing the Combo attribute.

Platform/MeteorlakeBoardPkg/Script/StitchIfwiConfig_mcl.py, Platform/MeteorlakeBoardPkg/Script/StitchIfwiConfig_mtlps.py
PS is EC-less design, don't need that FW.
=> fix: [MTLPS] exclude the EC FW in mtl-ps build

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Verified on mtl-p rvp.
*SILICON_CFG_DATA.SerialIoUartMode               | {0x03, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00}
*self.DEBUG_PORT_NUMBER = 0xff
->Win11 can see 3 com ports.
=> [MTL] UARTn Device Mode can't set to SerialIoUartCom

Platform/TigerlakeBoardPkg/BoardConfig.py
EPAYLOAD_SIZE increased to accommodate UEFI payload built with different toolchain
=> fix: [TGL] increased EPAYLOAD size for UefiPld

BootloaderCorePkg/Tools/GenCfgData.py, BootloaderCorePkg/Tools/SblSetup.py
Fix loading and saving issues with SblSetup payload when Config Data layout differs from ConfigDataDef.json file. ConfigDataDef.json used by setup payload has config data order based on defaults, while actual binary config values retrieved from ConfigLib can have order changes triggered by board deltas.
=> fix: SblSetup payload issues with loading and saving data.

BootloaderCommonPkg/Include/Guid/LoaderFspInfoGuid.h, BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c, BootloaderCommonPkg/Library/ShellLib/CmdHob.c, BootloaderCorePkg/Stage2/Stage2Hob.c, Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ArrowlakeBoardPkg/Library/ShellExtensionLib/CmdGpio.c, Silicon/ApollolakePkg/Library/BootMediaPayloadLib/BootMediaLib.c
Remove clear FSP hob from Uefi payload boot path because Fsp NotifyPhase needs FSP hob to work. Fixed 32bit address FspHotList in FSP INFO. UEFI payload consumes ths info to clear FSP hob.
=> fix: remove clear FSP hob from Uefi payload boot path

BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressPassthru.c
After timeout occurs, reset the controller and return error.
=> NvmExpressPassThru: handle command timeout

BootloaderCorePkg/Tools/SblSetup.py, PayloadPkg/OsLoader/OsLoader.c
Mismatch between YAML config type and value was causing setup to crash. Handle it gracefully and print an error instead.
Stack alignment issues in x64.
=> fix: Setup payload yaml processing and x64 fixes

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arlh.py, Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arlu.py
ARL-U and ARL-H ingredients are the same, except for ACM and EC binaries. Updating ingredient list in StitchIfwiConfig script for ARL-U and ARL-H.
=> feat: [ARLUH] Updating merged ingredient list for ARL-U/H

Silicon/ElkhartlakePkg/FspBin/FspBin.inf
BIOS version is Elkhart Lake IPU2025.2 FSP
FSP version is 09064941
Platform version is 1.7
Microcode Files are: ['m_01_90661_0000001a.pdb']
=> feat: [EHL] Update IPU2025.2 Release

BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.c, BootloaderCorePkg/Tools/SblSetup.py
CfgDataTool de-dupes config data in some circumstances when using the "merge" command. In such a case, the CDATA_FLAG_TYPE_REFER flag is set in the header, and a special REFERENCE_CFG_DATA struct is added after the conditions that points to the reference Config Data. ConfigDataLib's BuildConfigData() triggers a config data corruption when handling these that needed to be fixed. Instead, the setup payload will expand these de-duped configs using the reference data so they can be modified independently. This will cause an increase in Config Data size when saving data from setup in these cases.
=> fix: Setup Payload incorrectly handles config data with the refer flag

Silicon/AlderlakePkg/FspBin/FspBinIpu.inf, Silicon/AlderlakePkg/Microcode/Microcode.inf
BIOS version is NEX ADL-S IPU 2025.2 (5402_01) FSP
FSP version is 0C.00.F8.21
platform version is 1.7
Microcode Files are: ['m_07_90672_0000003a.pdb]
=> feat: [ADLS] Update IPU2025.2 Release

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
Verified on adl-s rvp, adl-h crb
*SILICON_CFG_DATA.SerialIoUartMode               | {0x03, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00}
*self.DEBUG_PORT_NUMBER = 0xff
->Win11 can see 3 com ports.
=> fix: [ARL] SerialIoUartMode can't set to SerialIoUartCom

BootloaderCommonPkg/Library/ElfLib/ElfLib.c, BootloaderCommonPkg/Library/UniversalPayloadLib/UniversalPayloadLib.c
Current implementation only supports the case that ELF file doesn't reload. If the ELF file has to be reload (e.g.: to meet alignment requirement), SBL need copy it to a different location and run.
Recently EDKII updated universal payload ELF image link script, and the new ELF text alignment was changed to 0x1000 from 0x40. Mostly the default file load location could not meet this requirement. So enhancement SBL to copy it to a new location for this case.
=> Enhance ELF loading

Silicon/QemuSocPkg/FspBin/Patches/0001-Build-QEMU-FSP-2.0-binaries.patch
Using Ubuntu 24.04 (gcc 13.3.0), build QEMU has this faulure when building QEMU FSP: Unknown symbol FspSecCoreT:_TempRamInitApi !
The root cause is in the generated map file, it uses 8 bytes address for the symbol while current script search 16 bytes address.
This patch update the build script to support both 8 and 16 bytes address.
=> Qemu: Fix build failure on Ubuntu 24.04

.gitattributes, BootloaderCorePkg/Tools/PrepareBuildComponentBin.py, Silicon/QemuSocPkg/FspBin/Patches/0002-BaseTools-GCC-newer-versions-fix-Synced-with-EDK2.patch
When building using newer toolchains, there are a few changes required that were already patched in EDK2.
Those changes are documented in the two links from EDK2 group discussion:
https://edk2.groups.io/g/devel/topic/89997410
https://edk2.groups.io/g/devel/topic/89997412
With this small change and fix for QEMU FSP: Unknown symbol FspSecCoreT:_TempRamInitApi !, it is possible now to build successfully on Fedora 41 additionally to Ubuntu 24.04.
=> EDK2 Patch to fix QEMU build on new toolchain

Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlp_DDR5_CRB.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlp_DDR5_MCL.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlp_DDR5_Rvp.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlp_LPDDR5_Rvp.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlps_DDR5_CRB.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Int_Mtlps_DDR5_RVP.dlt, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Power.yaml, Platform/MeteorlakeBoardPkg/CfgData/CfgData_Silicon.yaml, Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c, Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
The FSP-S UPD has an option .OcLock that cannot be modified from SBL configuration. Need this for controlling the max turbo frequency.
Tested on mtl-ps crb with those config changed.
SILICON_CFG_DATA.TurboRatioLimitRatio           | {0x2A, 0x2A, 0x28, 0x28, 0x26, 0x26, 0x26, 0x26}
SILICON_CFG_DATA.AtomTurboRatioLimitRatio       | {0x1F, 0x1F, 0x1F, 0x1F, 0x1C, 0x1C, 0x1C, 0x1C}
POWER_CFG_DATA.OcLock                         | 0
=> feat: [MTL] expose fsp-m .OcLock UPD option to SBL config data

Silicon/RaptorlakePkg/Btls/Fsp/FspBinBtls.inf
Wrong VBT path in FSP INF copy list was causing a build failure.
=> fix: [BTL-S] Build error from bad VBT path in CopyList

.azurepipelines/azure-pipelines.yml
This reverts commit 86358b031f580a10712d55b8a924c33239295efb. 
nasm.us is back, revert it.
=> Revert "fix: ci build fail cause by nasm url 404"

BootloaderCommonPkg/Library/ElfLib/ElfLib.c
- Uninitialized scalar variable (CWE-457) on SegAlignment
=> fix: [common] Fix Coverity issues in in ElfLib

Platform/RaptorlakeBoardPkg/BoardConfigBtls.py
edk2-stable202411 based UEFI payload requires Smm Rebase without setting SMRR. Set this new auto mode for compatibility with this and newer uefi payload.
=> fix: [BTL-S] Change SmmRebase mode to "Auto NoSmrr" for edk2 202411

Platform/ArrowlakeBoardPkg/BoardConfigArlh.py, Platform/ArrowlakeBoardPkg/BoardConfigArls.py, Platform/MeteorlakeBoardPkg/BoardConfigMtlp.py
edk2-stable202411 based UEFI payload requires Smm Rebase without setting SMRR. Set this new auto mode for compatibility with this and newer uefi payload.
=> fix: [ARL][MTL] Change SmmRebase mode to Auto NoSmrr for edk2 202411

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
BTL-S TCC design matches RPL-S so there is no RTCT and no TCC tuning table.
=> fix: [BTL-S] Remove TCC ACPI Platform code for BTL-S to match RPL-S

Platform/AlderlakeBoardPkg/BoardConfig.py, Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Platform/AlderlakeBoardPkg/BoardConfigAdlN50.py, Platform/AlderlakeBoardPkg/BoardConfigAdlS.py, Platform/AlderlakeBoardPkg/BoardConfigAzb.py, Platform/RaptorlakeBoardPkg/BoardConfigRplp.py, Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
edk2-stable202411 based UEFI payload requires Smm Rebase without setting SMRR. Set this new auto mode for compatibility with this and newer uefi payload.
=> fix: [ADL][RPL] Change SmmRebase mode to Auto NoSmrr for edk2 202411

Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
This can lead to critical code executing in situations where it should not.
=> fix [ARL]: Fix FspsUpdUpdateLib for Omitted Break Statement in Switch"

Silicon/CommonSocPkg/Library/IgdOpRegionLib/IgdOpRegionLib30/IgdOpRegionLib30.c
Set Lid state open as default in Igd OpRegion 30 library
=> fix: Set Lid state open

PayloadPkg/OsLoader/BootOption.c, Silicon/AlderlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.c, Silicon/AlderlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.inf, Silicon/ElkhartlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.c, Silicon/TigerlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.c
This commit refines the UpdateResetReason for ADL with the following improvements:
1. Replacing IsRebootByWdt with WasBootCausedByTcoTimeout. Previously, ADL utilized IsRebootByWdt, which was incorrect and redundant. The incorrect aspect involved checking a non-existent bit field (TCO_STS_NO_REBOOT), while the redundancy lay in its functionality being identical to WasBootCausedByTcoTimeout(). Consequently, this commit removes IsRebootByWdt and substitutes IsRebootByWdt with WasBootCausedByTcoTimeout.
2. Prioritizing S3/S4 for RstCause assignment in UpdateResetReason. The original code assigned ResetWakeS3 or ResetWakeS4 or S3/S4 resume at the end of the check logic. However, ResetWakeS3 and ResetWakeS4 already imply a successful resume, allowing us to move these checks to the beginning of …
=> fix: [ADL] rework the UpdateResetReason #2442

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Set SMI Lock bit at ReadyToBoot for OsLoader before jumping to OS
verified on EHL CRB.
=> fix: [EHL] Set SMI Lock bit for OsLoader

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Set SMI Lock bit at ReadyToBoot for OsLoader before jumping to OS
=> fix: [MTL] Set SMI Lock bit for OsLoader

BootloaderCommonPkg/Library/ThunkLib/X64/DispatchExecute.c, Platform/MeteorlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c, Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/SmbiosInit.c, Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/MeteorlakePkg/Include/Library/PchInfoLib.h, Silicon/MeteorlakePkg/Library/PchInfoLib/PchInfoLibMtl.c
ARL
- Execute32BitCode: CWE-476 Deference null return value
MTL
- PlatformUpdateAcpiGnvs: CWE-563 Unused value
- InitializeSmbiosInfo: CWE-476 Dereference null return value
- EarlyPlatformDataCheck: CWE-569 Operands don't affect result
=> fix: [ARL][MTL] Fix Coverity issues

Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Set SMI lock bit at ReadyToBoot for Osloader
=> fix: [TGL] Set SMI lock bit for Osloader

Platform/IdavilleBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Test info: Confirmed SMI_LOCK setting in OSLoader shell
=> ICXD:Set SMI lock bit at ReadyToBoot for Osloader.

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c
When changing a boot option from a non-RAW type to RAW, the boot command does not set the valid field of the LbaImage.
=> fix: OSLoader shell boot command doesn't set Valid status of RAW LBA

Platform/ArrowlakeBoardPkg/Script/StitchIfwi.py, Platform/ArrowlakeBoardPkg/Script/StitchLoader.py
This commit addresses the issue of hard dependency on the SblOpen folder, allowing stitching to proceed without it.
=> fix: [ARL] Remove dependency on SblOpen folder for stitching

Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf, Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf
BIOS version is Raptor Lake-S IPU2025.3 FSP
FSP version is 0C.00.F9.20
Microcode Files are: ['m_32_b0671_0000012f.pdb']
=> feat: [RPLS] Community Update FSP/UCODE for IPU2025.3

.gitattributes, BaseTools/Conf/tools_def.template, BootloaderCorePkg/Tools/PrepareBuildComponentBin.py, Silicon/QemuSocPkg/FspBin/Patches/0002-BaseTools-GCC-newer-versions-fix-Synced-with-EDK2.patch, Silicon/QemuSocPkg/FspBin/Patches/0003-Update-CFLAGS-so-compilation-works-on-Fedora-42.patch
Fedora 42 updates GCC toolchain to version 15 which now defaults to higher versions of C standard with stricter rules that prevent SBL from building successful. Given official supported OS/Toolchains are not yet moved to later C standard, it should be no harm to pin to C17 which makes SBL build successfully.
With that this PR adds -std=c17 for GCC5 templates to solve the compatibility issue.
Additionally it was not possible to build QEMU FSP due to incompatibilities in the toolchain of older EDK2 tag used. This PR also fixes the QEMU build by applying later changes from EDK2 BaseTools. The change consists in using -std=gnu11 in the Makefile for https://github.com/tianocore/edk2/blob/master/BaseTools/Source/C/VfrCompile/Pccts/dlg/makefile and …
=> Enable Fedora 42 Build

Silicon/RaptorlakePkg/Rplp/Fsp/FspBinRplp.inf, Silicon/RaptorlakePkg/Rplp/Microcode/MicrocodeRplp.inf
FSP sync to BIOS version 6073_03
Microcode update to 0x4129
=> feat: RPLP IPU 2025.3 community update

BootloaderCommonPkg/Library/ShellLib/CmdSetup.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.c, BootloaderCommonPkg/Library/ShellLib/ShellCmds.h, BootloaderCommonPkg/Library/ShellLib/ShellLib.inf
Added a new 'setup' command to OS Loader shell to launch the setup payload available when the feature is enabled.
=> feat: OS loader shell command to launch setup payload

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py, Silicon/AlderlakePkg/FspBin/FspBin.inf
- FSP: IoT TWL MR1/ASL MR4 (0C.02.89.40)
- Microcode: m_19_b06e0_0000001d
- VBT: 256
- platform version: SB_ASL-1.4
=> [ASL/TWL] Update for ASL MR4, TWL MR1

Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c, Silicon/CommonSocPkg/Include/Library/TxtLib.h, Silicon/TigerlakePkg/Library/TxtLib/TxtLib.c
SSDT table will create a TXT device conditionally
based on CPU_NVS TxtEnable value when txt is enabled.
=> [TGL][TXT] Exposing the TXT ACM device in ACPI table

BootloaderCorePkg/Tools/SblSetup.py
When keyboard input is read too quickly, 2-byte scancodes can be misinterpreted as the ESC key alone if the 2nd byte isn't ready yet. Add an adjustable timeout to prevent this.
=> fix: [Setup Payload] Spurious ESC keys in setup
