.travis.yml
Dockerfile

These patches enable automated builds via Travis CI.

Enable Travis CI automation

---

BuildLoader.py

Make sure the build tool only search current SBL folder by default.
TEST=Build APL success.

Update Platform package search path

---

BootloaderCommonPkg/Library/UsbIoLib/UsbIoLib.c

Current XHCI library does initialization without checking the
controller PCI class and interface type. It will cause assertion
in late phase if the device is not a real XHCI controller. This
patch added the class and interface type check for XHCI controller.
Also more error handling was added to deal with the initialization
failure.

Add XHCI controller check during initialization

---

IntelFsp2Pkg/Tools/SplitFspBin.py

Enhance FSP split tool to support PE32+ format

Enhance SplitFspBin Tools

---

Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ApollolakePkg/Library/FlashDescriptorLib/FlashDescriptorLib.c
Silicon/ApollolakePkg/Library/SpiFlashLib/SpiFlashLib.c

Signed-off-by: Grandhi <sindhura.grandhi@intel.com>

Add code modifications to match the new Device Table concept.

---

BootloaderCorePkg/Tools/BuildUtility.py

Update the path to to include internal platform folders also
to search for IAS images to be stitched in final SBL image.

Enhance BuildUtility tool

---

Platform/ApollolakeBoardPkg/Script/StitchLoader.py

Current stitching script assumes the flash layout must be redundant
layout. But the layout could be non-redundant layout if the user
wants. This patch added non-redundant flash layout support for the
APL stitching.

[APL] Support non-redundant flash layout stitching

---

Licenses/Python_License.txt

Signed-off-by: Huang Jin <huang.jin@intel.com>

Include complete Python license

---

BootloaderCommonPkg/Include/Guid/SmmInformationGuid.h
BootloaderCorePkg/Include/Library/BootloaderCoreLib.h

Match the strcture definition with payload

Enhance SMMBASE_INFO communication structure

---

Platform/ApollolakeBoardPkg/Script/StitchLoader.py

The APL StitchLoader.py script has its own limitation. For example,
if Boot Guard is enabled in the base image, the final stitched image
with this script might not boot due to security reason. It is better
to check this during stitching process so that it can error out earlier
to notify the user.

[APL] Update StitchLoader.py to check Boot Guard status

---

BootloaderCorePkg/Stage1B/Stage1B.c
BootloaderCorePkg/Stage2/Stage2.c

This patch add code to handle fsp requested reset after silicon init API call

This patch add code to handle fsp requested reset after silicon init API call

---

BootloaderCommonPkg/Include/Guid/SmmInformationGuid.h
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ApollolakePkg/Include/ScRegs/RegsPmc.h

Update LDR_SMM_INFO on SMM control and enable information
Add comments to LDR_SMM_INFO HOB

Update SMM Information HOB

---

BootloaderCommonPkg/Include/Library/SmbiosInitLib.h
BootloaderCommonPkg/Library/SmbiosInitLib/SmbiosInitLib.c
BootloaderCommonPkg/Library/SmbiosInitLib/SmbiosInitLib.inf
BootloaderCommonPkg/Library/SmbiosInitLib/SmbiosTables.h
BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
BootloaderCorePkg/Stage2/Stage2.c
BootloaderCorePkg/Stage2/Stage2.h
BootloaderCorePkg/Stage2/Stage2.inf
BootloaderCorePkg/Stage2/Stage2Support.c
BuildLoader.py
MdePkg/Include/IndustryStandard/SmBios.h

Initial Smbios support infrastructure

Add Smbios support

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c
PayloadPkg/FirmwareUpdate/GetCapsuleImage.c

This patch fixed some minor debug message print issue.  It also added
some more debug prints to help identify potentical issue in firmware
update flow.

[APL] Fix print message for firmware update

---

Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Set SPI flash EISS and LE for UEFI payload in EndOfStages().
Some clean up on UPDs and create a common function for security check.
Set SMM_FLAGS_4KB_COMMUNICATION flag

Enable EISS for UEFI payload

---

Platform/ApollolakeBoardPkg/Script/StitchLoader.py

On APL the last 256KB flash address space (4GB-256KB to 4GB) is
remapped to CSME SRAM read-only region. During stitching due to space
limitation, if a component gets pushed into this region, then direct
memory mapped access might not work since it will be decoded by CSME.
To access components within this region, SPI command based interfaces
has to be used instead of memory mapped interface.
This patch added warning message when this condition is detected in
the stitching process.

Add warning if component is in CSME mapped flash region

---

BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLibGeneric.c

- CMD23(SET_BLOCK_COUNT) is for only MMC.
- CMD17(READ_SINGLE_BLOCK) must be used when reading a single block
with SD card
Verified on qemu and apl boards.

[MmcAccessLib] Fix SD card single block read failure

---

BootloaderCorePkg/Tools/GenCapsuleFirmware.py

Fix error during capsule generation

---

.travis.yml

Enable cfl target on travis pre-commit checker

---

Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

Determine Firmware Update boot mode at post tempram exit

---

BootloaderCommonPkg/Library/SpiFlashLib/SpiFlashLib.c

1. Add region type FlashRegionAll support
2. Add Hardware sequence check

Enhance SPI Flash Library

---

PayloadPkg/OsLoader/LoadImage.c

OsLoader shall allow Linux kernel to boot without initrd. But
current code returns an error if initrd is not provided. This
patch added extra logic to return success if initrd cannot be
found.

Allow initrd to be optional for Linux boot

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Platform/CoffeelakeBoardPkg/Script/StitchLoader.py

This patch will add support for StitchIfwi.py to generate
Boot Guard enabled IFWI images for WHL/CFL platforms

Added StitchIfwi support for WHL/CFL platforms

---

Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Current code will check if the first 4 bytes of the existing
MRC training data, if it is 0xFFFFFFFF then MRC training data
will be saved otherwise even though there is change in the
training data, it will not be saved.
Modified the code to compare the incoming training data to the
saved data, if they do not match, save the incoming training data.

[CFL] MRC data save is ignored after first boot

---

BootloaderCommonPkg/Include/Guid/LoaderPlatformInfoGuid.h
BootloaderCorePkg/Stage2/Stage2Support.c
Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Update TpmType to LoaderPlatform info hob based on
Type updated in Platform Info.

CFL: Add TPMType param to Loader Platform info HOB

---

BootloaderCorePkg/Tools/CfgDataTool.py
BootloaderCorePkg/Tools/IfwiUtility.py

This patch added IfwiHelper.py script to help parse the IFWI layout
and locate components. It can be used to swap component listed in
the SBL flashmap, such as CFGDATA, MRCDATA, ACM, etc. It can support
different IFWI layout. For exmaple,
APL MRC data flash layout path:
IFWI/BIOS/NRD/MRCD
CFL MRC data flash layout path:
IFWI/BP0/BPDT/BpdtIbb/MRCD
To determine a compoment flash layout path, please just use:
python IfwiHelper.py -i IfwiImage.bin

[TOOLS] Add IFWI helper script

---

BootloaderCorePkg/Tools/BuildUtility.py
BootloaderCorePkg/Tools/IfwiUtility.py
BuildLoader.py
Platform/ApollolakeBoardPkg/BoardConfig.py
Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
Platform/ApollolakeBoardPkg/Script/StitchLoader.py
Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Platform/CoffeelakeBoardPkg/Script/StitchLoader.py

This patch cleaned APL and CFL stitching script.
- Shared common code for stitching functions on flash map process
- Converted coding style to snake_case for consistent naming convention

[TOOLS] Clean up stitching scripts for flash map

---

PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.c
PayloadPkg/OsLoader/KeyManagement.c
PayloadPkg/OsLoader/LoadImage.c
Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c

Klocwork scanning reported several issues in the
PayloadPkg and Platform code folders, this commit
aims to resolve all of the issues currently being
reported in these folders.

Resolve Klocwork issues in Payload & Platform

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py

This patch will use a list of xml changes required and
patch them in a loop rather than patching each change
seperately.
This patch also add parameter to indicate platform for which
ifwi is getting build.

Simplify xml patching in stitchifwi

---

BootloaderCorePkg/Tools/IfwiUtility.py
BuildLoader.py

Signed-off-by: Grandhi <sindhura.grandhi@intel.com>

Add ACM3 binary into BIOS region

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py

This patch will patch parameters for BpmGen2
based on the example file provided in the BpmGen2
package.

Generate BPMGen2 parameters for CFL/WHL

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py

This patch added support for CFLS and CFLH stitching by patching
proper xml file for the platforms.

Added XML patching for CFLS and CFLH platforms

---

BootloaderCorePkg/Stage1A/Ia32/Vtf0/ReadMe.txt

- Update paths for VTF0 source and binary output.
- Upgrade Python dependency version.
Signed-off-by: Himanshu Sahdev aka CunningLearner <sahdev.himan@gmail.com>

BootloaderCorePkg/Stage1A/Ia32/Vtf0/ReadMe.txt: Update ReadMe

---

BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
BootloaderCorePkg/Stage2/Stage2.c

To make PlatformUpdateAcpiTable() hook its contents and length easily,
allocate a memory from low to high and appends each tables to higher direction

[AcpiInitLib] Allocate ACPI tables from low to high memory

---

BootloaderCorePkg/Include/Library/MpInitLib.h
BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c
BootloaderCorePkg/Stage2/Stage2.c
BootloaderCorePkg/Stage2/Stage2Support.c

Signed-off-by: Ravi Rangarajan <ravi.p.rangarajan@intel.com>

Minor cleanup

---

BaseTools/Scripts/PatchCheck.py

The PatchCheck.py does basic rule check on commit message and code.
This can be used as one of pre-commit checker before doing PR.
ex) N: the number of commits from HEAD
python BaseTools/Scripts/PatchChecker.py -N

Add PatchCheck.py from EDK2 BaseTools

---

BootloaderCorePkg/Tools/BuildUtility.py
BootloaderCorePkg/Tools/GenContainer.py
Platform/QemuBoardPkg/BoardConfig.py

GenContainer.py tool can be used to create a container
with the boot files as follows:
python %SBL_ROOT%\BootloaderCorePkg\Tools\GenContainer.py create
-cl CMDL:<cmdline.txt> KRNL:<vmlinuz> INRD:<initrd>
-od <OutDir> -kd %SBL_ROOT%\BootloaderCorePkg\Tools\Keys
<cmdline.txt> = command line file
<vmlinuz> = kernel image
<initrd> = initrd image
<OutDir> = dir where final PodsImage.bin is copied

Update GenContainer.py to prepare PODS image

---

Platform/QemuBoardPkg/Script/gdbinit
Platform/QemuBoardPkg/Script/loadthis.py

Add GDB helper scripts for 'Debug SBL on QEMU with GDB'.
Here is step-by-step tutorial.
https://slimbootloader.github.io/tutorials/ex_debug_sbl_on_qemu_with_gdb.html

Add GDB helper scripts

---

BootloaderCorePkg/Stage2/Stage2.c

There is an issue in current SBL Stage2 code to check if the UEFI
payload is built from open source. It was done by checking the
1st DWORD using Dst[0]. However, during the FV loading, the value
at Dst[0] might have been changed since LoadFvImage() can move the
FV to a new location. This patch cached Dst[0] before calling
LoadFvImage() so that it can always get the oringal value.
It fixed #343.

Fix logic for open source UEFI payload check

---

Platform/CoffeelakeBoardPkg/Library/ShellExtensionLib/CmdFwUpdate.c

CoffeelakeBoardPkg/Library/ShellExtensionLib/CmdFwUpdate.c: Fix minor typo
Signed-off-by: Himanshu Sahdev aka CunningLearner <sahdev.himan@gmail.com>

[CFL] Fix minor typo

---

BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.h

EXT2/3 library has some limiatation to support
hardware block sizes larger than 512 (e.g. 4KB)
and also does not currently support the flag
INCOMPAT_64BIT which indicates larger group
descriptor sizes. This patch adds flexibility
to support 512 and 4KB block sizes as well as
64bit EXT file systems.

Support 64bit EXT FS & non-512 block sizes

---

BootloaderCorePkg/Tools/ConfigEditor.py

This patch added mouse wheel scroll event handler so that mouse can
be used to scroll the configuration items on the page.

Add mouse scroll event handler for ConfigEditor

---

BootloaderCorePkg/Tools/ConfigEditor.py

Current ConfigEditor uses multiple Entry widgets to build a Table
widget since Tkinter does not support Table widget. However, when
the table is big, the loading performance is very slow because of
large mount of Entry widgets. This patch switched to use Treeview
widget to build a table widget, and it is much more faster than the
original implementation.

Use Treeview widget to display table in ConfigEditor

---

BootloaderCorePkg/Tools/ConfigEditor.py

ConfigEditor can load binary into Table widget. It has a boundary
check issue which results in the last byte left out. This patch
fixed this and also added code to roll back invalid inputs to its
last known good value for Table widget cell.

Minor fixes for ConfigEditor tool

---

PayloadPkg/OsLoader/LoadImage.c

Current SBL code assumes the image to load on raw partition follows
IAS format. Since container format is added recently, the code should
support both. This patch added support for container format as well.

Add support for loading container image from raw partition

---

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c

The OS Loader 'boot' shell command does
not allow a user to skip data entry for
a given input field which can be tedious.
To make it easier allow users to press
enter to re-use the current value for
the boot option being modified to skip
to the options that they actually want
to update.
Also remove the '-a' option, no one will
typically re-enter all of the boot options.

Provide default values to boot command

---

BootloaderCommonPkg/Library/GraphicsLib/GraphicsLib.c
BootloaderCommonPkg/Library/ShellLib/CmdCls.c
BootloaderCommonPkg/Library/ShellLib/ShellCmds.c
BootloaderCommonPkg/Library/ShellLib/ShellCmds.h
BootloaderCommonPkg/Library/ShellLib/ShellLib.inf

This patch set added Shell CLS command to clear screen.  As part of it, it also implement clear screen for GFX console.

Add Shell command to clear console

---

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c

The 'boot' command has been updated to add
an option to update the current boot option
to be booted next, e.g. mCurrentBoot. To
change the current boot option just need to
run 'boot' and then select 'c' and the
index to change the current boot option to.

Add change current boot option to boot cmd

---

PayloadPkg/OsLoader/OsLoader.c

After trying out all boot options, if it still fails to boot,
current SBL code will do CpuHalt(). A better approach is to boot
into Shell and reset the current boot option to 0. In this way,
it allows user to try boot option again after modifying boot
option parameters. However, for release build, it does not change
the original behavior. System will still halt in this condition.

Allow restarting OsLoader after trying out all boot options

---

BootloaderCommonPkg/BootloaderCommonPkg.dec
BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
PayloadPkg/Include/Library/PayloadLib.h
PayloadPkg/OsLoader/OsLoader.c
PayloadPkg/OsLoader/OsLoader.h
PayloadPkg/OsLoader/OsLoader.inf
PayloadPkg/OsLoader/PreOsChecker.c
PayloadPkg/OsLoader/PreOsChecker.h

Split PreOsChecker in a separate file and add minimum APIs
- IsPreOsCheckerLoaded ()
- LoadPreOsChecker ()
- StartPreOsChecker ()

[OsLoader] Clean-up PreOsChecker

---

Platform/ApollolakeBoardPkg/BoardConfig.py
Platform/ApollolakeBoardPkg/Script/StitchLoader.py

This patch fixes the issued identified in #393

OemKm and Bpm are not a MUST

---

PayloadPkg/OsLoader/OsLoader.c

Current OsLoader used many "goto" to enforce the flow, and it also
used RestartOsLoader() to allow OsLoader re-entry. This patch cleaned
these and produce a linear boot flow for PayloadMain().

Clean up OsLoader main boot flow

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py

Added a option in CFL StitchIfwi script to pass the TPM type to
be selected for Intel FIT tool stitching.
[TEST] = Run StitchIfwi.py with -tpm=dtpm for WHL
and verify use of dTPM.

[CFL] TPM selection type support to StitchIfwi

---

BootloaderCorePkg/Library/DebugDataLib/DebugDataLib.c
BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
BootloaderCorePkg/Stage1B/Stage1B.c
BootloaderCorePkg/Stage2/Stage2.c

This patches fixed several Klocwork scanning reports in
BootloaderCorePkg.

Misc Klocwork scanning fixes in BootloaderCorePkg

---

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
BootloaderCommonPkg/Library/FatLib/FatLib.c
BootloaderCommonPkg/Library/FileSystemLib/FileSystemLib.c
BootloaderCommonPkg/Library/GraphicsLib/BmpFormat.c
BootloaderCommonPkg/Library/IppCryptoLib/hmac.c
BootloaderCommonPkg/Library/SeedListInfoLib/SeedListInfoLib.c
BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c
BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c

This patches fixed several Klocwork scanning reports in
BootloaderCommonPkg.

Misc Klocwork scanning fixes in BootloaderCommonPkg

---

BootloaderCommonPkg/Library/FullMemoryAllocationLib/FullMemoryAllocationLib.c
BootloaderCommonPkg/Library/SeedListInfoLib/SeedListInfoLib.c

This patches fixed additional Klocwork scanning reports in
BootloaderCommonPkg.

Additional Klocwork scanning fixes in BootloaderCommonPkg

---

BootloaderCommonPkg/Library/IppCryptoLib/auth/gsmodmethod.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpngrsaencodec.c

This patches fixed Klocwork scanning reports in IppCryptoLib.

Klocwork scanning fixes for IppCryptoLib

---

BootloaderCommonPkg/Library/ShellLib/Shell.c

@mauricema this is the patch fot uart buffer flush as per discussion

uart buffer flush during reboot

---

BootloaderCommonPkg/Library/FullMemoryAllocationLib/FullMemoryAllocationLib.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpngrsaencodec.c

This patches fixed Klocwork scanning reports in SBL common code.

Klocwork scanning fixes for SBL common code

---

BootloaderCommonPkg/Include/Library/ShellLib.h
BootloaderCommonPkg/Library/ShellLib/Shell.c
BootloaderCommonPkg/Library/ShellLib/ShellCmds.c
PayloadPkg/OsLoader/OsLoader.c

This lists the supported Shell commands in alphabetical order.

ShellLib: 'help' lists Shell commands sorted by name

---

BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf
BootloaderCommonPkg/Library/IppCryptoLib/auth/ippcp.h
BootloaderCommonPkg/Library/IppCryptoLib/auth/owncp.h
BootloaderCommonPkg/Library/IppCryptoLib/auth/owndefs.h
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpbnu32arith.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpbnuarith.h
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpngrsamontstuff.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpngrsamontstuff.h
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha256ca.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsha512ca.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpsm3ca.c
BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpvariant_abl.h

SHA512_384 and SM3 crypto functions were referenced from
https://github.com/intel/ipp-crypto.git
Selectively taken Ipp Hash methods

Port IPP SHA384 and SM3 algorithms to SlimBootloader

---

PayloadPkg/Library/SblParameterLib/SblParameterLib.c
PayloadPkg/OsLoader/LoadImage.c

Signed-off by Ravi Rangarajan.

Klocwork cleanup for PayloadPkg

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

Fixed condition check based on KW report
Signed-off-by: Ravi Rangarajan <ravi.p.rangarajan@intel.com>

Fixed condition check based on klocwork scan

---

BootloaderCorePkg/Library/MpInitLib/Ia32/MpInitLib.c

This patch sorts the CPU info entry according to their thread distances.
It is required to list CPU thread with furthest distance first in MADT
so as to better utilize CPU resources.

Re-arrange CPU info entry order so MpInitLib

---

BootloaderCorePkg/Tools/GenContainer.py

sigining hash type parameter added with command line
args for create, replace and sign component image.

Add hash type param to GenContainer tool

---

Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

MRC re-init happens in next boot when an warm reset is issued in MRC
fast boot path. DRAM Initialization Scratchpad Bit is one of warm reset
detection logics, but the bit is not updated at fast boot path.

Fix MRC re-training at warm reset

---

BootloaderCorePkg/Tools/IfwiUtility.py

This patch added extraction support in IfwiUtility tool so that
component in IFWI can be easily extracted into binary file.

Add extraction support for IfwiUtility script

---

Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/Gpe.asl
Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/Sc.asl
Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/ScPcie.asl

Test: WoL works on Leaf Hill CRB
Signed-off-by: Ursula Maplehurst <ursula@kangatronix.co.uk>

[APL] Enable Wake-on-LAN for Leaf Hill CRB (#394)

---

PayloadPkg/OsLoader/LoadImage.c

Kernel cmdline data from config.cfg or grub config files were copied
to invalid address.
This is only for traditional linux boot in debug build.

Fix invalid cmdline reading from config file

---

BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c
BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c
BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
PayloadPkg/OsLoader/BootConfig.c
Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/SeedSupport.c
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/GpioTables.h
Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ApollolakePkg/Library/GpioLib/GpioLib.c
Silicon/ApollolakePkg/Library/HeciLib/HeciLib.c
Silicon/CommonSocPkg/Library/SpiFlashLib/SpiFlashLib.c
Silicon/QemuSocPkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Silicon/QemuSocPkg/Library/SpiFlashLib/SpiFlashLib.c

This patch fixes klocwork scanning reports in qemu, apl and cfl builds.

Misc Klocwork scanning fixes

---

BootloaderCorePkg/Tools/CommonUtility.py

Current gen_pub_key only supports private key in PEM support.  In
many cases, private key might not be available and only public key
is available. This patch enhanced this function to handle both
private and public key in PEM format.

Add support for both private and public PEM key format

---

Platform/ApollolakeBoardPkg/Script/StitchIfwi.py
Platform/ApollolakeBoardPkg/Script/StitchLoader.py

This patch added KEYH component into the IFWI stitching process.

[APL] Add KEYH component in StitchIfwi script

---

Licenses/IPP_License.txt

IPP License file update

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

CSME update is working only from primary partition, added
code to check the current boot partition and if booting from
back up partition, switch to primary partition.

Execute CSME update only from primary partition

---

BuildLoader.py

Update Hash type to string.

---

BootloaderCorePkg/Tools/GenCapsuleFirmware.py

This patch updated GenCapsuleFirmware.py to Python 3
compatible.

Added python 3 support for GenCapsuleFirmware.py

---

BootloaderCorePkg/Tools/CommonUtility.py
BootloaderCorePkg/Tools/GenContainer.py
Platform/QemuBoardPkg/BoardConfig.py

This patch added following enhancement to GenContainer script:
- Fixed python3 errors in some specific condition
- Added more error handling to notifce the user on failure
- Removed -od option and use directory of -o option instead

Enhance GenContainer tool

---

BootloaderCommonPkg/Include/Library/BootloaderCommonLib.h
BootloaderCommonPkg/Include/Library/ContainerLib.h
BootloaderCommonPkg/Include/Library/IasImageLib.h
BootloaderCommonPkg/Include/Library/TpmLib.h
BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.inf
BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
BootloaderCommonPkg/Library/IasImageLib/IasImage.c
BootloaderCommonPkg/Library/TpmLib/TpmLib.c
BootloaderCorePkg/Stage1B/Stage1B.c
BootloaderCorePkg/Stage2/Stage2.c
PayloadPkg/OsLoader/OsLoader.c
PayloadPkg/OsLoader/OsLoader.inf

Unified interface is added to extend OS Image digest.
For Container OS Image this interface is added as
callback functionality. IAS image utilizes same
functionality to extend TPM digest.

Measured boot update for Linux OS Image

---

BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c

Add logs for RSA and Hash verification params

---

BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.c
BootloaderCommonPkg/Library/IppCryptoLib/rsa_verify.c
BootloaderCommonPkg/Library/TpmLib/TpmLib.c

KlocWork issue fixes in security libraries

---

BootloaderCommonPkg/Include/Library/IasImageLib.h
BootloaderCommonPkg/Library/IasImageLib/IasImage.c

IAS Library KlocWork fixes

---

.travis.yml
Dockerfile
Platform/QemuBoardPkg/Script/qemu_fwu.py
Platform/QemuBoardPkg/Script/qemu_test.py

This patch added QEMU test scripts for firmware update and enabled it in Travis.

[QEMU] Add QEMU test script and enable Travis

---

BootloaderCommonPkg/Include/Guid/SmmInformationGuid.h
BootloaderCorePkg/Stage2/Stage2Support.c
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ApollolakePkg/Include/ScRegs/RegsPmc.h
Silicon/CoffeelakePkg/Include/Register/PchRegsPmc.h

Add SMI status register
Add SMI lock register
Add REG_TYPE_MMIO register type
Zero SMM HOB

Update SMM HOB support

---

.travis.yml

This patch will enable X64 Build on QEMU as a pre-checker.

[Travis] Enable X64 Build on QEMU

---

BootloaderCommonPkg/Library/PagingLib/PagingMap.c

In X64 mode, current stage unmapping implementation does not
restore the original identical address mapping. It will cause
issue in some condition. This patch fixed this unmapping issue.

Fix stage unmaping issue

---

Platform/QemuBoardPkg/Script/TestCases/firmware_update.py
Platform/QemuBoardPkg/Script/TestCases/linux_boot.py
Platform/QemuBoardPkg/Script/TestCases/test_base.py
Platform/QemuBoardPkg/Script/qemu_test.py

This patch added test script for Linux boot test in travis for QEMU.

Add linux boot test in travis

---

BootloaderCommonPkg/Library/ShellLib/Shell.c

SBL Shell allocated memory during the command registeration phase.
However, these memory is not de-allocated after Shell exits. This
patch added code to de-allocate the memory. It also rearranged the
code a little bit so that function declarations are not required
any more.

[Shell] Add memory de-allocation for Shell commands

---

Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py
Platform/CoffeelakeBoardPkg/Script/StitchIfwiConfig.py

This patch simplified ingredient folder structure
required for stitchifwi. Also created a config file
with all the configuration in one file and this file
will now be input to stitchifwi

Simplified stitchifwi.py for CoffeLake

---

BootloaderCorePkg/Tools/GenCfgData.py

This patch added parameter error check for macro passed into the
template.

Add macro parameter check for GenCfgData.py

---

BootloaderCommonPkg/Library/UsbInitLib/UsbInitLib.c

This issue is seen on a WHL board on X64 build when high 32-bit
BAR does not exist. In that case, MmioRead64 returns (UINT64)(-1).
To avoid this, read low and high 32-bit BAR separately.

[X64] Fix XHCI init failure

---

BootloaderCommonPkg/Library/PagingLib/PagingMap.c

Klocwork reports a potential dereferencing of a NULL
pointer. This patch addresses the issue.

Fix Klockwork issue flagged in PagingMap lib

---

BootloaderCommonPkg/Library/AhciLib/AhciBlkIo.c

This will fix an unexpected exception when AhciHcPciBase is invalid
or the PCI config space is not enabled.

Check SATA controller at Ahci Init

---

BootloaderCorePkg/Library/PciEnumerationLib/InternalPciEnumerationLib.c
BootloaderCorePkg/Library/PciEnumerationLib/PciIov.c
BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
Silicon/CoffeelakePkg/Library/SgxLib/SgxLib.c

Suppress KW warnings

---

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
Silicon/CoffeelakePkg/Include/Library/IgdOpRegionLib.h
Silicon/CoffeelakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Silicon/CoffeelakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c

Fixed several Klocwork issues reported for CFL build.

Fixed several Klocwork scanning issue

---

Platform/ApollolakeBoardPkg/BoardConfig.py
Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
Silicon/ApollolakePkg/Include/Library/InternalIpcLib.h
Silicon/ApollolakePkg/Include/Library/PmcIpcLib.h
Silicon/ApollolakePkg/Include/Library/SaCommonDefinitions.h
Silicon/ApollolakePkg/Include/Library/SideBandLib.h
Silicon/ApollolakePkg/Include/ScRegs/RegsPcu.h
Silicon/ApollolakePkg/Include/ScRegs/RegsPmc.h
Silicon/ApollolakePkg/Include/ScRegs/SscRegs.h
Silicon/ApollolakePkg/Library/BaseIpcLib/BaseIpcLib.c
Silicon/ApollolakePkg/Library/BaseIpcLib/BaseIpcLib.inf
Silicon/ApollolakePkg/Library/BaseIpcLib/InternalIpcLib.c
Silicon/ApollolakePkg/Library/BaseIpcLib/SideBandLib.c

- Created BaseIpcLib
- Sideband Interface picked from
tianocore/edk2-platforms
branch: devel-IntelAtomProcessorE3900
commit: 181f9e6c6ccde6e3fa62278b3a8b39cfb5844a7c
- IPC Interface picked from
tianocore/edk2-platforms
branch: devel-IntelAtomProcessorE3900
commit: 181f9e6c6ccde6e3fa62278b3a8b39cfb5844a7c
- Updated Stage1BBoardInitLib.C with a test function
Signed-off-by: Andrey Vinokurtsev <avinok@gmail.com>

IPC and SideBand Interfaces - Adding IPC/Sideband

---

BootloaderCorePkg/Tools/BuildUtility.py
BootloaderCorePkg/Tools/SingleSign.py

Udated error handling for SBL Key dir and error
messages to guide user to use GenerateKeys tool.

Single signings scripts improvements

---

BuildLoader.py

Add option -k with SBL build for key generation.
This is to enable user who do not generate keys
for signing as pre-build step.

Default key generation option with build

---

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c

Initialize variables for container svn

---

BootloaderCommonPkg/Library/MultibootLib/Multiboot.c

The current MulitBoot loading code in SBL did not follow the specifiction.
Spec stated "The offset in the OS image file at which to start loading
is defined by the offset at which the header was found, minus
(header_addr - load_addr)". However, the current code always copies from
offset 0 of the image file. It caused exception when loading some valid
mulitboot image.

Fix MultiBoot image loading issue

---

BootloaderCorePkg/Stage2/Stage2.c

Current Linux payload support in SBL only loads command line and
kernel image, and it does not load InitRd image. It is possible
to have the InitRd image built into the keneral image, but it is
more convenient to have separate InitRd support. This patch added
this.

Add InitRd loading for Linux payload

---

BootloaderCorePkg/Tools/CommonUtility.py

This patch improved some function implementation in CommonUtility.py.

Enhance efficiency some basic common python functions

---

BootloaderCorePkg/Tools/GenCfgData.py

The final generated YAML file under Build folder should include
everything required. However, current tool will not expand the
embedded binary file. This patch addressed it.

Expland embedded file value in generated YAML file

---

BootloaderCorePkg/Library/MpInitLib/MpInitLib.c
PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

This patch fixed some Klocwork scanning issues reported by the new
version.

Fix some Klocwork scanning issues

---

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c
Platform/ApollolakeBoardPkg/BoardConfig.py
Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

This patch adjusted some alignment on PCI resource allocation so
that PCI resource is more efficently utilized.

PCI resource allocation minor adjustment

---

BootloaderCorePkg/Tools/GenCfgData.py
BootloaderCorePkg/Tools/GenContainer.py

This patch set enhanced following :
- Generate CFGDATA json file during the build process
- Adjust search path for GenContainer script

Tool enhancement for build

---

BuildLoader.py

Current SBL build script can only be used to build SBL image.
It would be helpful if it can be extended to support build individual
DSC component, such as some other standalone payload. This patch
introduced a new subcommand "build_dsc" to enable this capability.

Extend SBL build process to build individual component

---

BootloaderCorePkg/Tools/BuildUtility.py

This patch added VS2019 build support.

Add VS2019 build support

---

BootloaderCommonPkg/Library/LiteVariableLib/LiteVariableLib.c
BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.c

This will resolve some issues reported by
the Klocwork scan.

Fixed improper use of sizeof with pointer

---

BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c
BootloaderCommonPkg/Library/Ext23Lib/Ext2Fs.c
BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.c

This patch fixed some new reported klocwork scanning issues.

Fix new Klocwork scanning issues

---

Platform/CoffeelakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/CoffeelakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

This patch adds necessary check to avoid NULL pointer dereference
Signed-off-by: Praveen HP <praveen.hodagatta.pranesh@intel.com>

[CFL] Fix Klockwork scanning issues

---

.gitignore
BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
BootloaderCommonPkg/Include/Library/ContainerLib.h
BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.c
BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.inf
BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
BootloaderCorePkg/Stage1B/Stage1B.c
BootloaderCorePkg/Stage1B/Stage1B.inf
BootloaderCorePkg/Tools/SblSetup.py
BuildLoader.py
PayloadPkg/Include/PayloadModule.h
PayloadPkg/OsLoader/ModService.c
PayloadPkg/OsLoader/OsLoader.c
PayloadPkg/OsLoader/OsLoader.h
PayloadPkg/OsLoader/OsLoader.inf
PayloadPkg/PayloadPkg.dec
Platform/ApollolakeBoardPkg/BoardConfig.py
Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.c
Platform/QemuBoardPkg/BoardConfig.py
Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf

This patch set added basic infrastructure to support SBL setup through MicroPython payload module.

Add SBL setup support for QEMU

---

Platform/CoffeelakeBoardPkg/BoardConfig.py

update VERINFO_BUILD_DATE to actual build date instead of hardcoded
value.

[CFL][MR1 rel] Revise up SBL minor verison to 1

---

Platform/CometlakeBoardPkg/BoardConfig.py
Platform/CometlakevBoardPkg/BoardConfig.py
Silicon/CometlakePkg/Microcode/Microcode.inf
Silicon/CometlakevPkg/Microcode/Microcode.inf

1. Fix payload size.
2. Fix microcode clone command.

[CML] Fix travis build fail

---

Platform/CometlakeBoardPkg/BoardConfig.py
Platform/CometlakevBoardPkg/BoardConfig.py

Fix payload size to 0x00028000.

[CML] Fix travis build fail in linux system

---

BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.c
BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLibGeneric.c
BootloaderCommonPkg/Library/MmcAccessLib/SdMmcPciHcDxe.h

Improve the HS200 switch code to set bus mode
correctly on some eMMC cards.

Enhance eMMC driver

---

Platform/CommonBoardPkg/Tools/GpioDataConvert.py

GpioConvert Tool converts Gpio config data between following
sets of formats:
[.h, .csv, .txt] ---> [.yaml, .dlt] and vice-versa
.dsc related conversion is deprecated starting from this commit.

Support YAML and drop DSC for GpioConvert tool

---

BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
BuildLoader.py

With this flag, platform could update the settings to
get the expected boot performance data

Add a build config for fastboot

---

BuildLoader.py

Current SBL build needs the actual FSP binary to pass the build.
This patch enables a mode to test the build without the actual FSP
bianry. It is useful for test before the FSP binary is available.
It is controlled by HAVE_FSP_BIN option. It can be overriden in
BoardConfig.py file.

Enable build without FSP binary

---

BootloaderCorePkg/Include/Library/BootloaderCoreLib.h
BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderArch.c
Silicon/CommonSocPkg/Include/MeBiosPayloadDataCommon.h
Silicon/CommonSocPkg/Library/HeciLib/HeciLib.c
Silicon/CommonSocPkg/Library/HeciLib/HeciLib.inf

Made changes to ensure the ME BIOS data information
is correctly reported.
Signed-off-by: Singh Nitin G <nitin.g.singh@intel.com>

Fix HeciGetFwCapsSkuMsg api to update MBP

---

BootloaderCorePkg/Stage2/Stage2.c

Add more debug prints to defferentiate first flash boot and fast boot.

Add Extra MRC save debug logs

---

BootloaderCommonPkg/Library/PartitionLib/PartitionLib.c

Added check for swpart to avoid accessing out of array elements
Signed-off-by: Perni <ramesh.chandra.perni@intel.com>

TGL KW issue 19321

---

BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformancePrintLib.c

This patch prints the correct ModuleGuid in FPDT.
Signed-off-by: Talamudupula <sai.kiran.talamudupula@intel.com>

Fix ModuleGuid print in FPDT record

---

PayloadPkg/PayloadPkg.dsc

Add required library for HelloWorld build.

Fix the HelloWord build failure

---

BootloaderCorePkg/Tools/CommonUtility.py
BootloaderCorePkg/Tools/GenContainer.py

After GenContainer script was created, there ware more changes
introduced for signing and compression. However, GenContainer
was not updated to match those new changes. This patch addressed
this issue.

Fix GenContainer python scripts

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Silicon/ElkhartlakePkg/Include/Register/PchRegsPcr.h

Fix build issue that cause by missing
HASH_USAGE and ACPI register

[EHL] Fix EHL Build issue

---

Platform/TigerlakeBoardPkg/Script/StitchIfwiConfig_tglu.py
Platform/TigerlakeBoardPkg/Script/security_stitch_help.py

This patch will fix the linux stitch error
using StitchIfwi.py

[TGL] Fix linux stitch using StitchIfwi.py

---

Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4_Tcc_Mode.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4_Tcc_Mode.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Add SBL configuration data for TCC GPIO.
Update TCC GPIO UPD and ACPI NVS data based
on SBL configuration data.

[TGL] Add TCC GPIO support

---

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ElkhartlakePkg/Include/Register/PchRegsSpi.h

Set SPI flash EISS and LE in EHL.

[EHL] Set SPI flash EISS and LE

---

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/HostBus.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/PchPcie.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/PlatformNvs.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/SsdtRtd3/EhlCrbRtd3.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/SsdtRtd3/Rtd3Pcie.asl
Silicon/ElkhartlakePkg/Include/PlatformNvsAreaDef.h

Fixes an issue where S4 is not working in
Windows when a PCIE card is attached.

[EHL] Fix S4 issue in Windows

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Platform/ElkhartlakeBoardPkg/Script/BtgSign.py
Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py

1. Fix jenkins build causes by some binaries
2. Fix Stitchifwi script

[EHL] Fix Jenkins build and stitch

---

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/EcLite.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/EcLiteDsm.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/PlatformNvs.asl
Silicon/ElkhartlakePkg/Include/EcLite.h

Enable ECLITE support in SBL EHL

[EHL] ECLITE support

---

Silicon/ElkhartlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c

ported changes from commit 46e4a98cd1dec37853e72b92917b57bd55b2504a
to EHL.

[EHL] Get SVN ver from capsule during firmware update

---

Platform/ElkhartlakeBoardPkg/AcpiTables/AcpiTables.inf
Platform/ElkhartlakeBoardPkg/AcpiTables/CpuSsdt/ApHwp.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/CpuSsdt/Cpu0Hwp.asl

Add ACPI HWP files to support Yocto acpi_cpufreq

[EHL] Add require ACPI files for Yocto cpufreq

---

Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Memory.yaml
Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Set UPD ConfigTdpLevel in FSPM instead FSPS
Remove unused CFG data

[TGL] Update ConfigTdpLevel

---

Platform/ApollolakeBoardPkg/BoardConfig.py
Silicon/ApollolakePkg/FspBin/FspBin.inf

Increase the size of Stage1b
to avoid build failing issue in Linux debug.
Signed-off-by: tongyana <tong.yan.au@intel.com>

[APL] Update to latest FSP

---

Silicon/TigerlakePkg/Library/Stage2SocInitLib/Stage2SocInitLib.c
Silicon/TigerlakePkg/Library/VTdLib/VTdLib.c

GNVS should be aligned with VTD PCD
Fix a DMR check issue.

[TGL] Update Vtd support

---

BootloaderCommonPkg/Library/DebugAgentLib/DebugAgent.h
BootloaderCommonPkg/Library/DebugAgentLib/DebugMp.c
Platform/ApollolakeBoardPkg/BoardConfig.py

This patch fixes the multiple build issues which are observed
when ENABLE_SOURCE_DEBUG config is set to 1.

[APL] Fix Build error when SOURCE_DEBUG is enabled

---

Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

vbt table update is aligned with bios.
Signed-off-by: Mutha <naga.naveen.mutha@intel.com>

[TGL-U] Aligned with IOTG BIOS for lp4 vbt update.

---

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/LpcDev.asl
Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/TimeAndAlarmDevice.asl
Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Silicon/ElkhartlakePkg/Include/Register/PmcRegs.h
Silicon/ElkhartlakePkg/Include/Register/RtcRegs.h

RTC initialization everytime CMOS battery refresh.

[EHL] RTC Initialization

---

Dockerfile

Docker file configuration extended to:
-- Avoid host environment related compilation errors
-- install Stitching dependencies

Update docker file configuration

---

BootloaderCommonPkg/Include/Library/SecureBootLib.h
BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c

Updated param and error code descriptions.

Fix comments in for DoHashVerify and DoRsaVerify apis

---

Platform/CometlakeBoardPkg/AcpiTables/Ecdt/Ecdt.act
Platform/CometlakevBoardPkg/AcpiTables/Ecdt/Ecdt.act

It takes more than 3 minutes to enter the home screen and also
restart/shutdown.

[CML] Fix Windows take a very long time to boot

---

Platform/ElkhartlakeBoardPkg/AcpiTables/AcpiTables.inf
Platform/ElkhartlakeBoardPkg/AcpiTables/Ssdt/Thermal.asl

Enable EHL SBL thermal module in ECLITE

[EHL] ECLITE thermal enable

---

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

Changes of Fsp Upd below:
1. DAM
2. DciModphyPg and Trace hub
3. PchPse SPI and I2C

[EHL] Fsp Upd update

---

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_BootOption.yaml

Modify boot option in EHL for PreOS support.

[EHL] Boot option for PreOS support

---

Platform/CommonBoardPkg/CfgData/Template_BootOption.yaml

Update Boot Flags to list PreOs and Extra image.
Hide other options when preOS or Extra Image is selected.

Update boot option Template

---

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Power.yaml
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py

Update stitchIfwi script with below softstraps settings:
|Offset | Start Bit | Strap Size | Value | Comment      |
0x183    0x1          0x2         0x0     DMI/OPD_LVO
0x1cc    0x4          0x4         0x0     FIA/LOSL8
Update fsp upd below:
PchFivrExtV1p05RailCtrlRampTmr -> 0x1
TdcTimeWindow -> {0x00, 0x00, 0x00, 0x00, 0x01}

[EHL] FSP UPD and stitchifwi update

---

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Modify boot option dynamically to support non-FuSa SKU

[EHL] Modify boot option to support non-FuSa SKU

---

BootloaderCorePkg/Stage2/Stage2.c

Need to set an initial value for SmmRebaseMode in
order to resolve a klocwork issue regarding
unitialized usage.

Resolve SmmRebaseMode klocwork issue

---

Platform/CometlakeBoardPkg/BoardConfig.py
Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/CometlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Platform/CometlakevBoardPkg/BoardConfig.py
Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/CometlakevBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf

Set SMM related PCD early and update platform
to enable SMM rebase

[CML] enable SMM rebase

---

Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

QEMU currently set PayloadId in Post PCI enumeration. To be in
sync with other platform, this patch moves it to PreSiliconInit
hook point.

Set PayloadId earlier in Stage2

---

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Add NULL checking for FeaturesCfgData.

[TGL] Fix KW issue

---

BootloaderCorePkg/Tools/BuildUtility.py
BuildLoader.py

This will check the minimum required toolchain versions
before starting build process.
If any of these toolchains does not meet the required version,
the build process will stop immediately.
Here are the initial minimum toolchain versions.
- python : 3.6.0
- nasm   : 2.12.02
- iasl   : 20160422
- openssl: 1.1.0g
- git    : 2.20.0
- vs     : 2015
- gcc    : 7.3
- clang  : 9.0.0

[Build] Verify toolchain versions

---

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/ElkhartlakePkg/Include/PchLimits.h

Add FSP UPD to CfgData_Silicon.yaml so it can be
modified using Config Editor tool.

[EHL] Add FSP UPD in CfgData

---

BootloaderCorePkg/Tools/BuildUtility.py

The build system is using 'git', it doesn't require the latest git.
This will show 'git' recommend version if not met,
and will address issue#1136.

[Build] Make 'git' version checking optional

---

Platform/ElkhartlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

1. Copy the FIVR settings in CfgData for user to configure
the desire value.
2. Removed fsp upd PmSupport for Fusa sku

[EHL] Update FIVR settings in CfgData

---

Silicon/CommonSocPkg/Include/Library/PchSbiAccessLib.h
Silicon/CommonSocPkg/Library/PchSbiAccessLib/PchSbiAccessLib.c
Silicon/CommonSocPkg/Library/PchSbiAccessLib/PchSbiAccessLib.inf

This patch adds a common PchSbiAccessLib that
all platforms can use. Changes for platforms will
be done in a separate patch. This common lib is
not currently linked to any project.

Add common PchSbiAccessLib

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Silicon/ElkhartlakePkg/FspBin/FspBin.inf
Silicon/ElkhartlakePkg/Microcode/Microcode.inf

1. Clone FSP from
https://github.com/intel/FSP/tree/master/ElkhartLakeFspBinPkg
2. Clone microcode from
https://github.com/tianocore/edk2-non-osi/tree/master/Silicon/Intel/ElkhartlakeSiliconBinPkg

[EHL] Clone FSP and Microcode from open source repo

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py

Update EHL BoardPkg version to 1.1 to allign with current
software package version:
PROJ_MAJOR_VER -> 1 (Production Release candidate)
PROJ_MINOR_VER -> 1 (2nd revision of PV release)
Signed-off-by: LeanSheng <lean.sheng.tan@intel.com>

[EHL] Update the EHL BoardPkg version to 1.1

---

Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_Ddr4_Tcc_Mode.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4.dlt
Platform/TigerlakeBoardPkg/CfgData/CfgData_Int_Tglu_DdrLp4_Tcc_Mode.dlt

Update PayloadId to "AUTO" to align with other platforms to
have consistent behavior.

[TGL] Set PayloadId to "AUTO" by default

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

Removed TCC FSP UPD and Increased stage2B size to adpot
the changes in FSP 09.03.19.22

[EHL] Removed TCC FSP UPD

---

Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/HidPlatformEventDev.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Use the ECEnable cfgdata, to disable all the EC
related code.

[TGL] Add EC config data for EC enable/disable

---

BuildLoader.py

The SBL core revision has not been updated since the creation of
the project. Now with more and more platforms being enabled with
SBL, it is the proper time to upgrade the core revision to be 1.0.

Update SBL core revision to 1.0

---

Platform/ElkhartlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

Check PlatformID before proceed to detect from SMBus
Moved PlatformIdInitialize to PostConfigInit

[EHL] PlatformID fix

---

BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.c

When adding UefiVariableLib code, there is build issue.
Fix the build issue.
Signed-off-by: CSHur <cs.hur@intel.com>

Fix UefiVariableLib code

---

BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.c

When adding UefiVariableLib, there is a build issue in Linux.
Fix the build issue.
Signed-off-by: CSHur <cs.hur@intel.com>

Fix Linux build issue when adding UefiVariableLib

---

BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.c

This patch addresses KW issues reported from UefiVarialbeLib.
Signed-off-by: Sai T <stalamudupula@gmail.com>

Fix UefiVarialbeLib KW issues

---

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c

TSB GBE PMECTRLSTATUS register returned 0x3 after
booting into OS and only occured in Fusa sku
This fix will check TSN PMECTRLSTATUS register and
update value to 0x0 if non-zero value was returned
Only applicable if TSN is enabled

[EHL] Fix for Gbe device status for Fusa

---

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/HdaVerbTable.h
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Use PchHdaEnable in cfgdata for user to configure the desire value.
TEST=Verified audio function on tglu platform

[TGL] Support HDA Audio

---

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

SiCfgData return NULL will be dereferenced

[TGL] Fix klockwork scanning issue

---

BootloaderCommonPkg/Library/ShellLib/CmdBoot.c

There is a bug when user use boot->idx command in OSL
shell to modify boot option which contained extra images
(eg. POSC or RTCM etc.)
Current CmdBoot didnt cover for extra images in idx command.
This patch cover for extra images.

[COMMON] Fix Pre-OS and extra image bug in OSL shell

---

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
Platform/QemuBoardPkg/BoardConfig.py
Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLibInternal.h
Silicon/CommonSocPkg/Include/Library/GraphicsInitLib.h
Silicon/CommonSocPkg/Library/EmuGfxInitLib/EmuGfxInitLib.c
Silicon/CommonSocPkg/Library/EmuGfxInitLib/EmuGfxInitLib.h
Silicon/CommonSocPkg/Library/EmuGfxInitLib/EmuGfxInitLib.inf

This patch set enables native graphics initialization on QEMU.

Qemu native graphics initialization

---

BootloaderCorePkg/Tools/SblSetup.py

This patch fixed several minor issues to make SblSetup script work
properly on the latest SBL and MicroPython. It added string encode
and decode function to address the python unicode issue. Some help
message were added as well.
Tested with both host and target execution mode, and it worked as
expected.

Fix some issues in SblSetup on MicroPython

---

Silicon/ElkhartlakePkg/FspBin/FspBin.inf

Update FSP version to MR2 in inf file
Signed-off-by: kokweich <kok.wei.chan@intel.com>

[EHL] Update FSP to MR2

---

Platform/TigerlakeBoardPkg/AcpiTables/CpuSsdt/CpuSsdt.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Cnvi.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Cpu.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Dsdt.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/EC.ASL
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Pch.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchClockControl.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchImgClkOutVer2.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchSerialIo.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchSerialIoI2c.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchSerialIoSpi.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchSerialIoUart.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchTraceHub.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PciTree.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Pep.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Platform.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/Pmc.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/RstRaid.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/SerialIoDevices.asl
Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/TraceHubDebug.asl
Platform/TigerlakeBoardPkg/AcpiTables/SsdtRtd3/TglURvpRtd3.asl

[TGL] Fix ASL compile warnings

---

Silicon/ElkhartlakePkg/Microcode/Microcode.inf

Update microcode version to MR2 in inf files
Signed-off-by: kokweich <kok.wei.chan@intel.com>

[EHL] Microcode MR2 update

---

Silicon/CometlakevPkg/Library/PchInfoLib/PchInfoLibCmlv.c

Fix the wrong bootmode comparision.

[CFL] Fix Klocwork scanning issue

---

Platform/CometlakeBoardPkg/AcpiTables/Dsdt/Gpe.asl
Platform/CometlakevBoardPkg/AcpiTables/Dsdt/Gpe.asl

RTD3 table isn't ready so that comment _L6F out.

[CML] Fix ACPI GPE 0x6F interrupt storm

---

BootloaderCorePkg/IncludePrivate/BootloaderCoreGlobal.h

Revert the WA for POSC issue in commit below:
9cd53b65fdfa66270eb81f0dfc2c93f2e5b14e85

[EHL] Revert the WA for POSC issue

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

This patch updated UPD params to match latest FSP

[ADL] Update FSP UPD params

---

BootloaderCorePkg/Tools/CfgDataTool.py

This patch added configuration array data size check to ensure it
is DWORD aligned. It will prevent some unexpected errors later on
while merging the configuration data.

Add configuration data length check in CfgDataTool

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
Silicon/AlderlakePkg/Library/PciExpressHelpersLibrary/PciExpressHelpersLibrary.c

Removed unused functions and redundant code.

[ADL] Fix Linux build issues

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Silicon/AlderlakePkg/Include/PchLimits.h

This patch fixed issues reported by Klockwork

[ADL] Fix Klockwork issues

---

Dockerfile

Update the iasl version in Dockerfile to 20200925
Current iasl version in Dockerfile out-dated and
causing build error in Docker

[Common] Docker file iasl version update

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf

This patch fixed a build issue in adl

[ADLP] Fix build issue in adl

---

Platform/TigerlakeBoardPkg/AcpiTables/Dsdt/PchSata.asl
Platform/TigerlakeBoardPkg/AcpiTables/SsdtRtd3/TglURvpRtd3.asl

This patch series fixed the ACPI errors reported by Linux kernel.

[TGL] Fix ACPI error reported by Linux kernel

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlNPostMem.h
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/AlderlakePkg/Include/GpioPinsVer2Lp.h
Silicon/AlderlakePkg/Library/IgdOpRegionLib/GopConfigLib.h
Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c

Added more changes required for RVP support.

[ADLN] Additional RVP support changes

---

PayloadPkg/FirmwareUpdate/GetCapsuleImage.c

This patch will try to find capsule image from each of connected USB
devices if the HwPart of CapsuleInformation is set to 0xFF.
When multiple USB devices are attached, current SBL will try to
find the capsule image from the device with index specified by HwPart
in the CapsuleInformation option. However, it is hard to determine
the USB device index order since it depends on which port the device
is connected to.
This patch extends the feature of "boot from multiple USB device" from
OS Loader to capsule update.
Verified: TGL-UP3 RVP

Add capsule update from multiple USB devices

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

This patch updated UPD to latest BIOS release

[ADLS] Sync UPD to latest BIOS release

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

[ADLS] Latest Tcc updates

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c

This patch updated some more FSPM upd's using
config data.

[ADLS] Update fspm upds using config data

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/SmbiosInit.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.h
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf

This patch adds the missing version info for ADL.

[ADL] Add version info

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Add TEST-S platform to program the TSN GPIO table.

[ADL-TEST] Program TSN GPIO

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/CpuInfoLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Adl update4

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Power.yaml
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c

Update FSP UPDs and VBT changes as part of the ADLP MR release.
TEST=Tested to boot to OS.

[ADLP] Update FSP ingredients

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

This patch enabled UFS configuration on ADLP platform

[ADLP] Enable UFS configuration

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

FSP UPDs update for PV milestone release

[ADLPS] FSP update for PV release

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/GpioTableAdlPsPostMem.h
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/CommonSocPkg/Library/GpioLib/GpioInit.c

Reverts slimbootloader/slimbootloader#1585

Revert "[WIP] [ADLPS] Process GPIO from Cfg Data"

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c

Add break statement in AcpiPlatform c file
for ADL_PS case.

[ADLPS] Add break statement

---

PayloadPkg/OsLoader/BlockIoTest.c
PayloadPkg/OsLoader/BlockIoTest.h
PayloadPkg/OsLoader/OsLoader.h

Fixed build and running issues.
Signed-off-by: Gavin Xue <gavin.xue@intel.com>

Improve BlockIo test code

---

BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.c
BootloaderCorePkg/Library/SmbiosInitLib/SmbiosTables.h
BootloaderCorePkg/Library/SmbiosInitLib/SmbiosTemplate.c
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Updating SMBIOS Type3 on Common package and EHL package.
Signed-off-by: Aiman Rosli <muhammad.aiman.rosli@intel.com>

[Common][EHL] Adding SMBIOS Type3

---

BaseTools/Source/C/GenFfs/GenFfs.c
BaseTools/Source/C/GenSec/GenSec.c

Fix two instances of printf("%s")'ing a FILE * instead of a char *

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

[ADLN] TSN enabling

---

Platform/AlderlakeBoardPkg/Script/StitchIfwiConfig_adls.py

[ADLS] Disable DAM by default

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Features.yaml
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/SioChip.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/SioChip.h
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf

Ported IT8659 Sio (Super IO) and DTT (Dynamic Tuning Technology) for
ADL platform
Added CfgData to disable or enable the SIO feature

[ADLN] IT8659 Sio DTT porting

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Silicon/AlderlakePkg/Library/PchInfoLib/PchInfoLibAdl.c

Aligned FSPS UPD settings with BIOS

[ADLN] UPD config update

---

Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

[TGL] Ignore TCC DSO tuning on FW update process

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

The patch fixes potential infinite FWU loop if InitFirmwareUpdate fails.
An infinite FWU loop occurs when (Count != MAX_FW_COMPONENTS). Thus,
without this patch, it increases the error-handling complexity in
InitFirmwareUpdate in the future (i.e., all early-return/abort cases must
take care of FW_UPDATE_SM_DONE by themselves).
The fixes simplfes the end firmware update by:
1. set SM as FW_UPDATE_SM_DONE at EndFirmwareUpdate
2. move reboot to EndFirmwareUpdate
Verified: EHL CRB

FWU: clean up the end firmware update

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

This patch fixed KW issue for FindImage failed

FWU: Fix Klocwork issue

---

Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py
Platform/ElkhartlakeBoardPkg/Script/StitchIfwiConfig.py

- add required flash image region 5=EC for new FIT (15.40.26.2632)
- remove 'sata' stitch option
- add only items whose features are enabled by default in replace_list

[EHL] Update StitchIfwiConfig.py

---

Platform/ElkhartlakeBoardPkg/AcpiTables/Dsdt/PchPse.asl

Signed-off-by: Gavin Xue <gavin.xue@intel.com>

[EHL] Fix incorrect PSE DMA2 BAR in ACPI code

---

Platform/CoffeelakeBoardPkg/BoardConfig.py

Increase the payload size to fix the build failure.

[CFL] Increase payload size

---

Platform/AlderlakeBoardPkg/Include/PlatformBoardId.h
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c

[RPLP] Add RPL-P PR01 board support

---

Platform/AlderlakeBoardPkg/Include/PlatformBoardId.h
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/AlderlakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.c

Added support for RPL-P DDR5 RVP board ID from EC.

[RPL-P] RPL-P DDR5 RVP Board/Platform ID support.

---

BuildLoader.py
Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/CmdGpio.c
Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/ShellExtension.c
Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf

This patch supports GPIO read and write through shell command.
Signed-off-by: M Karuppasamy <karuppasamy.m@intel.com>
Signed-off-by: Akshatha Thekkade <akshatha.thekkade@intel.com>

[ADL] GPIO shell command for ADL platform

---

Platform/AlderlakeBoardPkg/Include/PlatformBoardId.h
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/BoardSaConfigPreMem.h
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

Update BoardID and PlatformID for CRB board
Added ddi config for CRB board
Update FSPM UPD due to common value across all sku

[ADLPS] CRB PV release update

---

Platform/AlderlakeBoardPkg/BoardConfig.py

[ADLP] Fix build issue

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.inf
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.h
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf
Silicon/AlderlakePkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.c
Silicon/AlderlakePkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.inf

This changes ADL-N specific code for the SBL resiliency functionality.

Add SBL resiliency support to ADL-N

---

Silicon/AlderlakePkg/Include/MkhiMsgsAdl.h
Silicon/AlderlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Silicon/AlderlakePkg/Library/HeciMeExtLib/HeciMeExtLib.c

KM,BPM,ACM SVN are not commit at EOM.
End user has to perform this commit by doing
FwUpdate CMDI mode for ARB SVN commit.

[ADL] ARB SVN commit for Bootguard components

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Aligned FSPM and FSPS UPD settings with BIOS

[ADLPS] UPD config update

---

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

TPM is intialized by ACM with profiles 3 & 5.
This patch enables the TPM in bootloader when boot guard
is not enabled. HAVE_MEASURED_BOOT in platform
board config controls the TPM in SBL.

[ADL][RPL] Initialize TPM and Measured boot with btg profile 0

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Updated FSP-M and FSP-S parameters to match with BIOS
Signed-off-by: Atharva Lele <atharva.lele@intel.com>

[ADLN] Update FSP UPD Parameters

---

BootloaderCorePkg/Tools/GenCfgData.py

CFGDATA regions (each CFG tag) needs to be 4-byte aligned since this CFGDATA header field uses the low two bytes of the length for ConditionNum. Without this change, unaligned CFG region yaml files will cause a build error and need to be manually padded. This change adds a field "__reserved" to each CFG structure that requires padding.

[Tools] Automatically pad CFGDATA regions to 4 byte boundary.

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Features.yaml
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/AlderlakePkg/Include/Library/HeciMeExtLib.h
Silicon/AlderlakePkg/Include/MkhiMsgsAdl.h
Silicon/AlderlakePkg/Library/HeciMeExtLib/HeciMeExtLib.c
Silicon/CommonSocPkg/Include/MkhiMsgs.h

Implement a function to support FIPS mode enablement in ADL
Test: Booted with Windows and Yocto
Verified with FIPS enablement support in ADLN

[ADL] ME FIPS Mode Enablement

---

BootloaderCorePkg/Tools/CorruptComponentUtility.py

Enhance argument descriptions for CorruptComponentUtility

---

BootloaderCommonPkg/Library/ShellLib/CmdMm.c

Updated the help section of mm shell command.
Signed-off-by: Chirag Vijay Kolhe <chirag.vijay.kolhe@intel.com>

Update mm shell command description

---

Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/CmdGpio.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Fixing 2 Klocwork issues for ADL.

[ADL] Fix KW issue

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py

Increase payload size to fix build issues.

[EHL] Fix build error

---

BuildLoader.py

During the build process, SG1A is built
for BP0 and a copy is made for BP1. Then,
the parameters of the BP1 SG1A are adjusted
to reflect that it is in BP1. One of the
parameters that gets adjusted during this
process is the uCode base. It was noticed
that this uCode base does not get updated
at all for platforms using FSP spec 2.2, but 
another parameter gets updated instead.
Specifically, the error is in the FSP-T UPD
struct. The offset of the uCode base in
the FSP-T UPD struct is 0x40 for platforms using
FSP spec 2.2. However, the offset that actually
gets updated for platforms using FSP spec 2.2 is
0x20. This change corrects this offset for the
relevant platforms.

Fix erroneous uCode base offset in BP1 SG1A

---

Platform/IdavilleBoardPkg/Script/BtGUtility.py
Platform/IdavilleBoardPkg/Script/StitchIfwi.py
Platform/IdavilleBoardPkg/Script/StitchIfwiConfig.py

Update Script files to move tcc binaries.
Signed-off-by: cshur <cs.hur@intel.com>

[ICXD] Move Tcc binaries to Utilities

---

Platform/IdavilleBoardPkg/Script/BtGUtility.py
Platform/IdavilleBoardPkg/Script/StitchIfwi.py
Platform/IdavilleBoardPkg/Script/StitchLoader.py

[ICXD] Fix stitching process by getting rid of SblOpen remnants

---

Platform/IdavilleBoardPkg/CfgData/CfgData_SgxConfig.yaml
Silicon/IdavillePkg/Library/SgxLib/SgxLib.c

Added SgxLeWr and the hashes as configurable parameters in sgxconfig.yaml.
Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

ICXD: SGX: Added SGX launch control to SBL.

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

Currently, when a power failure occurs during update of a BP1 component, the corresponding BP0 component does not get updated on next boot. This is because the redundant component check only occurs at the very beginning of the FW update process.
This change corrects this behavior, so that the BP1 component gets updated along with its corresponding BP0 component on boot after BP1 component update with power failure.

Force redundant component check on every FW update iteration

---

Platform/IdavilleBoardPkg/CfgData/CfgData_SgxConfig.yaml
Silicon/IdavillePkg/Library/SgxLib/SgxLib.c

Reverts slimbootloader/slimbootloader#1736

Revert "ICXD: SGX: Added SGX launch control to SBL."

---

BuildLoader.py

The FIT allows for some empty uCode slots to be defined in anticipation of future uCode updates. This change adds as many empty slots as possible after the non-empty slots in the uCode region.

Allocate empty uCode slots for future uCode updates

---

BootloaderCommonPkg/Include/UniversalPayload/UniversalPayload.h

Update the universal payload ID to align with
the universal payload specification.

Update universal payload ID

---

BootloaderCommonPkg/Include/Library/ContainerLib.h
BootloaderCorePkg/Tools/GenContainer.py
PayloadPkg/OsLoader/OsLoader.c
PayloadPkg/OsLoader/OsLoader.h
PayloadPkg/OsLoader/PerformanceData.c
Platform/QemuBoardPkg/CfgData/CfgData_BootOption.yaml

These series of commits remove deprecated IAS functionality.
There are more traces of IAS left in the code but those need to be looked at closer before removing them.

OsLoader Cleanup (IAS)

---

Silicon/IdavillePkg/FspBin/FspBin.inf

FSP updated with the latest changes.
Tested to Boot Yocto.
Signed-off-by: Aakash Panwar <aakash.panwar@intel.com>

feat: [ICX-D] FSP Update

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

New FSP would have 2 TSN configs. So just update them.

[RPL] Update UPD settings for new FSP

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Aligned FSPS UPD settings with BIOS

feat: [ADLN] UPD config update

---

BootloaderCommonPkg/Library/ShellLib/CmdUsbDev.c

instance 0 was hardcoded, so not able to read the devices from other instances. 
Now read the instances number from the device table and enumerate all USB instances one by one.
Signed-off-by: Biswas Arghya <arghya.biswas@intel.com>

fix: enumerate all USB instances to search devices

---

Silicon/IdavillePkg/Include/Register/PchRegsGpioCdf.h

ICXD: Fix R_CDF_PCH_GPIO_PCR_GPP_N_PADCFGLOCKTX register offset

---

Platform/IdavilleBoardPkg/BoardConfig.py
Platform/IdavilleBoardPkg/BoardConfigHcc.py
Silicon/IdavillePkg/Microcode/Microcode.inf

Version update 1.1 to 1.2.
Update Microcode 201 to 230

[ICXD][LCC] Update Microcode for both LCC and HCC

---

Platform/IdavilleBoardPkg/Script/StitchIfwi.py

Ignition fw requires new parameter for IRC.
(In Ignition FW MR2 V E5.05.00.04.96.0)

[ICX-D] Update StitchScript for new IGFW

---

BootloaderCorePkg/Include/Library/FspSupportLib.h
BootloaderCorePkg/Library/FspSupportLib/FspSupportLib.c
BootloaderCorePkg/Library/FspSupportLib/FspSupportLib.inf
IntelFsp2Pkg/Include/Guid/FspNonVolatileStorageHob2.h

Support FSP 2.3 FSP_NON_VOLATILE_STORAGE_HOB2

Added FspNonVolatileStorageHob2 support in FspSupportLib

---

BootloaderCommonPkg/Library/TpmLib/Tpm2Capability.c
BootloaderCommonPkg/Library/TpmLib/TpmLib.c
BootloaderCorePkg/Stage1B/Stage1B.c

These changes include the following:
- Log config data TPM2 event as the correct type
- Log secure boot policy TPM2 event as the correct type
- Improve logs in SBL code relating to TPM2

Improve TPM2 Event Logging

---

Platform/AlderlakeBoardPkg/BoardConfigAdlP.py
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Silicon/AlderlakePkg/FspBin/FspBin.inf

- update FSP version to IoT ADL-P MR3 (0C.01.75.10)
- update platform version to 1.3

[ADLP] Update FSP/platform version for MR3 release

---

Silicon/AlderlakePkg/AlderlakePkg.dec

Define PCD PcdCrashLogDataPtr for Crash log.

feat: (RPL) Add Crash log data PCD

---

.azurepipelines/azure-pipelines.yml
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.h
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

- Adding pre-commit checks for the missing ADL SKUs.
- Resolve build issues

feat: [ADLP/ADLPS] Add pre-commit checks for ADL SKUs

---

Platform/AlderlakeBoardPkg/CfgData/CfgData_Memory.yaml
Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c

Add config data for FSP post code

feat: (ADL/RPL) Config FSP post code via Port80 or I2C

---

BootloaderCorePkg/Tools/PrepareBuildComponentBin.py
BuildLoader.py

Update Build scripts to take a different file path and Name for
-- microcode_inf_file
-- fsp_inf_file

[ALL Platforms] Update Build tools impact all platforms

---

.azurepipelines/azure-pipelines.yml
Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
Platform/RaptorlakeBoardPkg/Rpls/Fsp/FspBinRpls.inf

upstream RPL-S and added the build of RPL-S to
automation

[RPL-S] Updated automation file to include RPL-S

---

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/HdaVerbTable.h
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Test config on CRB:
Set PchHdaEnable=1 in CfgData_GpuConfig.yaml
Linux OS, test by speaker-test -c 2 -D hw:0,7

feat: Support HDMI audio playback on EHL

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/CpuInfoLib.c
Silicon/AlderlakePkg/Include/Register/SaRegsHostBridge.h

[ASL] ASL Device ID changes

---

Platform/TigerlakeBoardPkg/BoardConfig.py
Silicon/TigerlakePkg/FspBin/FspBin.inf

- update FSP version to IoT FSP 6033_00_MR8 (0A.00.7E.70)
- update TGL platform version to 1.7

[TGL] Update FSP/platform version for MR8 release

---

BootloaderCommonPkg/Include/Guid/DeviceTableHobGuid.h
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Silicon/AlderlakePkg/Include/Register/PchBdfAssignment.h

- Add ISH to platform device list.
- Set the ISH address in Post Config phase.

[ADL] Add ISH device to Platform Device list

---

Platform/AlderlakeBoardPkg/BoardConfig.py

fix: [ADL] increase stage2 size for debug FSP

---

BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

[TGL/EHL] add debug prints for TSN components loading
It was not easy to figure out from boot log whether TSN components are loaded successfully or not. Add debug prints to indicate the loading status.

[TGL/EHL] add debug prints for TSN components loading

---

Silicon/AlderlakePkg/Include/Library/HeciMeExtLib.h
Silicon/AlderlakePkg/Library/HeciMeExtLib/HeciMeExtLib.c
Silicon/CommonSocPkg/Include/MkhiMsgs.h

HECI interface for getting extended support license period. Efi test is added to call the EPS API for validation.

feat: [ADL/RPL] API for getting extended support period info

---

Platform/RaptorlakeBoardPkg/CfgData/CfgDataInt_Rpls_Rvp_Ddr5.dlt
Platform/RaptorlakeBoardPkg/CfgData/CfgDataInt_Rpls_Rvp_SODdr5.dlt

updated delta files s14and s17

fix [RPL-S] upstream fix for TSN that was missing

---

BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.c
BootloaderCorePkg/Stage2/Stage2Support.c

- Add a null check for Rsdp pointer before accessing it
- Initialize ResetVectorTime, Time to some value before using it
- Add debug print for success / failure

fix: resolve FPDT related Klocwork issues

---

MdePkg/Include/Library/DebugLib.h

Fixed CWE 476 NULL Pointer Dereference

fix: [Common] Fix Coverity issues

---

Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/ApollolakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/CoffeelakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/CometlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/CometlakevBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/ElkhartlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/IdavilleBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/TigerlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c

Assign initial values for fixing coverity issues. (CWE-457)

fix: [Common] EFI_CPUID_REGISTE variable uninitialized.

---

BootloaderCorePkg/Library/AcpiInitLib/AcpiFpdt.c

Fix the issue - Uninitialized Variable ResetVectorTime

feat: fix Klocwork issue

---

PayloadPkg/FirmwareUpdate/FirmwareUpdate.c

The current fwupdate design processes the capsule with redundant updates in two passes. The first pass updates the primary partition, and the second pass updates the backup partition. In either pass, multiple redundant components will be updated.
This patch fixed the existing issues:
1. If BIOS payload is not the final one, the boot partition will not be switched in the second pass, resulting in infinite update loop.
2. If the system boots in BP1 and tries to update BIOS payload, the fwupdate will not run the second pass.
This patch addressed the following concepts:
1. The ResetRequired flag indicates whether a component needs a reboot to take effect after it has completed both partition updates; while the Reboot flag in FwPolicy indicates whether a component needs a reboot to switch …

fix: fwupdate failed to update backup partition for BIOS payload

---

BootloaderCommonPkg/Library/TpmLib/Tpm2Capability.c
BootloaderCommonPkg/Library/TpmLib/Tpm2CommandLib.h
BootloaderCommonPkg/Library/TpmLib/Tpm2Ptp.c

The changes include:
- Adding a retry mechanism for TPM commands
- Adding a mechanism to put TPM in idle state after CRB command

Sync TpmLib with latest EDK2 stable release

---

Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/CmdPappend.c
Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/ShellExtension.c
Platform/AlderlakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf

Update BSD license to BSD+Patent license

fix: [ADL] Update BSD license

---

.azurepipelines/azure-pipelines.yml

Reverts slimbootloader/slimbootloader#1965

Revert "feat: Fix CI build caused by iasl link"

---

.azurepipelines/azure-pipelines.yml

Reverts slimbootloader/slimbootloader#1969

Revert "Revert "feat: Fix CI build caused by iasl link""

---

.azurepipelines/azure-pipelines.yml

There is an error to get nasm from the log.
It looks the URL is not used correctly.
Since its URL is not changed recently, make some changes to previous commit to check if it could be fixed.

feat: update CI build

---

.azurepipelines/azure-pipelines.yml

Add some debug message to check where it failed.

feat: test the CI build

---

BootloaderCommonPkg/Library/IppCryptoLib/auth/pcpbnu32arith.c
BootloaderCommonPkg/Library/SecureBootLib/SecureBootHash.c
BootloaderCommonPkg/Library/SecureBootLib/SecureBootRsa.c
Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c

Fix a variety of Coverity issues, specifically those in security-related modules

Fix Coverity issues

---

BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.c

Assert check was one off causing problem for corner cases. Upated the check.

fix: [PCIe] Fix assert check

---

Platform/IdavilleBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Silicon/IdavillePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c

Fixed Resource leak (CID 1229238)
Fixed Dereference null return value (CID 1515533)

fix: [ICX-D] Fix Coverity issues

---

BootloaderCommonPkg/Library/UefiVariableLib/UefiVariableLib.c

Fixed Untrusted loop bound (CWE 606)

fix: [Common] Fix coverity issue

---

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c

Add Platform Flag for RPL-PS to add ADL-PS RVP board

fix:[RPL-PS] add board id to support RVP

---

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c

fix incorrect experssion coverity error

fix: [RPL-PS] Fix Coverity Issue

---

Silicon/CommonSocPkg/Library/IgdOpRegionLib/IgdOpRegionLib30/IgdOpRegionLib30.c

Fix Linux build error by assigning return status to PcdSet32S macro

fix: [MTL] Fix Linux build error

---

BootloaderCorePkg/Include/IgdOpRegionDefines30.h
Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c
Silicon/CommonSocPkg/Library/IgdOpRegionLib/IgdOpRegionLib30/IgdOpRegionLib30.c

Added IgdOpRegionDefine 3.0 header file
Removed unsed IgdPlatformInfo in Stage2BoardInit file
TEST: Booted into Ubuntu and Windows

fix: [MTL] Add IgdOpRegionDefine 3.0 header

---

Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Silicon/MeteorlakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.c
Silicon/MeteorlakePkg/Library/GpioV2Lib/GpioV2Init.c
Silicon/MeteorlakePkg/Library/PsdLib/PsdLib.c

Fix for coverity scan issues
TEST: Able to boot with Windows and Ubuntu

fix: [MTL] Fix coverity issue

---

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Fix lowercase typo which causes linux build to fail

fix: [MTL] Fix Linux build issue

---

Silicon/IdavillePkg/Microcode/Microcode.inf

Update Microcode from 270 to 280

[ICXD][LCC][HCC] Update Microcode for both LCC and HCC

---

BootloaderCommonPkg/Include/Guid/OsBootOptionGuid.h
PayloadPkg/Library/SblParameterLib/SblParameterLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Silicon/AlderlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.c
Silicon/AlderlakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.inf

Add reset reason caused by S4.
Update ADL to set reset reason.

[ADL/RPL] Update reset reason

---

BootloaderCommonPkg/Library/ElfLib/ElfLib.c

Verify on booting with universal payload.

fix: IsElfFormat doesn't correctly check the ELF header (#2036)

---

Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c

This change corrects the authority measure calculation in the common BootGuardTpmEventLogLib
If BtG KM is signed using RSA 3K key, a SHA384 hash should be added to the authority PCR structure
If BtG KM is signed using RSA 2K key, a SHA256 hash (padded to 384 bits) should be added to the authority PCR structure
The entire authority PCR structure should be initialized to zero before being populated

Fix authority measure calculation for PCR[7]

---

BootloaderCommonPkg/Library/ShellLib/CmdAcpi.c
BootloaderCommonPkg/Library/ShellLib/ShellCmds.c
BootloaderCommonPkg/Library/ShellLib/ShellCmds.h
BootloaderCommonPkg/Library/ShellLib/ShellLib.inf

It could help debug ACPI related issues.

Add "acpi" shell command

---

Platform/MeteorlakeBoardPkg/CfgData/CfgData_BootOption.yaml

Update SwPart to align with latest Ubuntu OS

fix: [MTL] Update SwPart in Boot Option

---

Silicon/MeteorlakePkg/Library/GpioV2Lib/GpioV2Lib.inf

Move MeteorlakePkg.dec order to resolve build error

fix: [MTL] Resolve build error with latest GPIOV2 changes

---

Silicon/MeteorlakePkg/Library/GpioV2Lib/GpioV2Lib.inf

Fix missing .dec typo in inf file

fix: [MTL] Fix typo in inf file

---

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Silicon/AlderlakePkg/FspBin/FspBin.inf
Silicon/AlderlakePkg/Microcode/Microcode.inf

[ADLN] Upstream MR2 release

---

PayloadPkg/FirmwareUpdate/FirmwareUpdateHelper.c

If the component in SPI flash could not be memory-mapped, it need access using SPI library.
If the component is registered using memory address, it means it need use SPI library to access. It would read required info using SPI library.

feat: Enhance firmware Update

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.inf
Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/AcpiPlatform.c

Updated FSP UPDs
Removed TCC subregion

feat: [ASL] Updated FSP UPD

---

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

fix: [MTL] Removed Unused Variables

---

Platform/MeteorlakeBoardPkg/Library/FspmUpdUpdateLib/BoardSaConfigPreMem.h

DDI config update for MTL-PS CRB board to support Fab B board
TEST: Able to boot into Ubuntu

[MTLPS] DDI config update for MTL-PS CRB board

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Moved SMRR restore SMI prior to MP init done.
It resolved failure from programming SMRR on AP.

[ADLN] Fix SMRR base restore on AP

---

Platform/AlderlakeBoardPkg/AcpiTables/Dsdt/PciTree.asl

Update interrupts  in PciTree to be the same as UPD Platform PCH-P interrupts in FspsUpUpdateLib.c

fix: [RPL-PS] Fix S3 Issue

---

Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/MeteorlakeBoardPkg/Script/StitchIfwiConfig_mtlps.py

Updated UPD and TCSS soft strap to fix USB hub pendrive detection issue

fix: [MTL-PS] Fixed USB hub pendrive intermittent detection issue

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

set UPD cpufeaturess3override this allows
the display to retun in required time

fix:[RPL-PS] Fix S3 not returning display

---

Silicon/AlderlakePkg/Microcode/MicrocodeAzb.inf

Update microcode version to 00000007.

[AZB] Update UCODE for MR13 release

---

Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/Bat0Virt.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/Bat1Real.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/ConvertibleIndicator.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/DockingIndicator.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/Devices/Lid0.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcNvs.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcQevent.asl
Platform/MeteorlakeBoardPkg/AcpiTables/EcSsdt/EcSsdt.asl

Update latest EC ACPI table reference
from BIOS.

fix: [MTL] Update EC ACPI table

---

Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
Silicon/MeteorlakePkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c

This change accomplishes the following:
- Logs BtG authority measure events in TPM event log whenever enabled
- Cleans up the equivalent code for earlier platforms

[MTL] Add Optional BtG Authority Measure

---

Platform/ElkhartlakeBoardPkg/BoardConfig.py
Silicon/ElkhartlakePkg/FspBin/FspBin.inf

- Update FSP version to IoT EHL MR7 (09.05.20.41)
- Update platform version to 1.7

[EHL] Update FSP for MR7 release

---

Platform/MeteorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Enable TCO timer in FSPS Upd for Watchdog

fix: [MTL] Enable TCO timer for Watchdog

---

Platform/TigerlakeBoardPkg/CfgData/CfgData_Silicon.yaml
Platform/TigerlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

remove CfgData for FuSa Display, Graphics, OPIO, PSF

[TGL] remove unavailable FuSa features

---

BootloaderCommonPkg/Library/TpmLib/TpmLib.c
BootloaderCorePkg/Stage1B/Stage1B.c

issue: https://jira.devtools.intel.com/browse/IOTGSECSW-2031

fix: [TPM] correcting cfg data and key hash

---

Silicon/CommonSocPkg/Library/GpioV2Lib/GpioV2Init.c

Optimized debug print in GpioV2Init.c

fix: [Common] Optimized debug print

---

Platform/AlderlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c

issue found on FSPM file, reference PR: https://github.com/slimbootloader/slimbootloader/pull/2093

fix: [ADL] fix coverity issue out-of-bound

---

Silicon/IdavillePkg/FspBin/FspBin.inf

FSP revision updated and aligned for MR4.
Tested to Boot Yocto.

feat: [ICX-D] FSP revision updated

---

Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf

Boot time of FSP-M will reduce 90~100ms.

[ADL] Make MRC data cache-able to improve performence

---

BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
BootloaderCorePkg/Tools/BuildUtility.py
BuildLoader.py

For platforms with seperate actm binary added code to copy actm binary in build folder

feat: copying actm binary to build folder

---

BuildLoader.py

Support for adding multiple ACM entries for different CPU FMS in FIT table.

feat: Added support for CPU FMS in ACM fit entry

---

Licenses/BSD2_License.txt
Licenses/README.md

Add BSD-2-Clause license file
Add readme in License folder

feat: [Common] BSD-2 clause license

---

Silicon/MeteorlakePkg/Include/Register/PchRegsLpc.h
Silicon/MeteorlakePkg/Include/Register/SaRegsHostBridge.h
Silicon/MeteorlakePkg/Library/PlatformHookLib/PlatformHookLib.c

Verified on MTL-P platform with set self.DEBUG_PORT_NUMBER = 0xFF

fix: [MTL] Can't output log to EC port.

---

Silicon/.gitignore
Silicon/AlderlakePkg/Microcode/MicrocodeAzb.inf

Updated the Microcode for AZB platform from 0x07 to 0x08

feat:[AZB] Update new Microcode pointer to 0x08

---

Silicon/ElkhartlakePkg/FspBin/FspBin.inf
Silicon/ElkhartlakePkg/Microcode/Microcode.inf

- update FSP version to IPU2024.3 (09.06.15.21)
- update Microcode version to 1A

feat: [EHL] Community Update FSP/UCODE for IPU2024.3

---

Silicon/CommonSocPkg/Library/IgdOpRegionLib/IgdOpRegionLib30/IgdOpRegionLib30.c

Fixed the function defination to match the
declaration in header file.

fix:[GCC Build] fix compile error

---

Platform/QemuBoardPkg/BoardConfig.py

Increase the payload size to fix the build failure with gcc

fix: [QEMU] Increase payload size

---

Silicon/TigerlakePkg/FspBin/FspBin.inf
Silicon/TigerlakePkg/Microcode/Microcode.inf

- Update FSP version to IPU2024.3 (0A.00.84.70)
- Update Microcode version:
TGL-U        m_80_806c1_000000b8
TGL-H        m_c2_806d1_00000052

feat: [TGL] Community Update FSP/UCODE for IPU2024.3

---

Platform/AlderlakeBoardPkg/BoardConfigAzb.py
Silicon/AlderlakePkg/FspBin/FspBin.inf

Updated SBL Project Minor version and FSP git hash for IPU24.4 (5254_00).

feat: [AZB] Update SBL version and FSP git hash

---

Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Initialize spi's mode according to configuration data

[ADL] Add spi mode initialization

---

Platform/ArrowlakeBoardPkg/Include/PlatformBoardId.h
Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/BoardSaConfigPreMem.h
Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/ArrowlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c
Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Adding support for ARL-S RVP S-04 board

feat:[ARL-S] adding support for ARL-S RVP S-04 board

---

Platform/ArrowlakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.c

Removed commented code and debug port80 output.
UART debug port is hard-coded to 2. this should come from the board configuration.

[ARL]: clean up the code and correct debug port setting

---

Platform/ArrowlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c
Platform/ArrowlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.inf

Add logic to actually trigger a full reset of the system.

[ARL]: Fix for PCH Global reset

---

Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arls.py
Silicon/ArrowlakePkg/Include/Library/TcoTimerLib.h
Silicon/ArrowlakePkg/Include/Register/RegsSmbus.h
Silicon/ArrowlakePkg/Include/Register/TcoRegs.h
Silicon/ArrowlakePkg/Library/TcoTimerLib/TcoTimerLib.c
Silicon/ArrowlakePkg/Library/TcoTimerLib/TcoTimerLib.inf

Changing TcoBase for Tco timer for sbl resiliancy

feat : [ARLS] Enabling sbl resiliancy

---

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arlh.py

Changed BpmStrutVersion and CnbsInclude bpmgen2 params

fix: [ARL-H] Updated BPMGEN2 struct version

---

Platform/RaptorlakeBoardPkg/BoardConfigRplp.py
Platform/RaptorlakeBoardPkg/Script/StitchIfwiConfig_rplp.py

feat: [RPLP] support loading diagnostic acm binary

---

Platform/AlderlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf
Platform/RaptorlakeBoardPkg/BoardConfigRplp.py
Silicon/RaptorlakePkg/Rplp/Fsp/FspBinRplp.inf

- FSP version is NEX RPL-P MR2 (0C.01.DE.40)
- Microcode version is 411d
- VBT version is 253
- platform version is 1.2

[RPLP] Update for MR2 release

---

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf
Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf

FSP version is 0C00DE40
platform version is 1.4
Microcode Files are: ['m_07_90672_00000036.pdb', 'm_32_b0671_00000123.pdb']

feat: [RPLS] Update MR4 Release

---

Silicon/ArrowlakePkg/Library/PcieRpLib/PcieRpLib.c

Added EFIAPI modifier to fix conflicting function types with .h file

fix: [ARL] Fix conflicting function types

---

SECURITY.md

Add initial SECURITY.md file following OS PDT template

fix: [Common] Initial Security Policy

---

Platform/ElkhartlakeBoardPkg/Library/Stage2BoardInitLib/UpdateAcpiGnvs.c

modified the EMH4 object in ACPI PCH NVS area

feat: [EHL] enable eMMC HS400 mode by default

---

Silicon/AlderlakePkg/FspBin/FspBinIpu.inf
Silicon/AlderlakePkg/Microcode/Microcode.inf

BIOS version is NEX ADL-S IPU 2024.4 (5045_03) FSP FSP version is 0C00D550
platform version is 1.7
Microcode Files are: ['m_07_90672_00000036.pdb', 'm_80_906a3_00000434.pdb', 'm_11_b06e0_00000017.pdb']

feat: [ADLS] Update IPU2024.4 Release

---

BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c

Address Reliance on Data/Memory Layout (CWE 188)

fix: [Common] Fix coverity issues CWE 188

---

BootloaderCommonPkg/Library/AhciLib/AhciDevice.c
Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Address following coverity issues
1. Integer Overflow or Wraparound (CWE 190)
2. NULL Pointer Dereference (CWD 476)

fix: [ARLS] Fix coverity issues

---

Platform/AlderlakeBoardPkg/BoardConfig.py
Silicon/AlderlakePkg/Include/Library/SerialIoI2cLib.h
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/BaseSerialIoI2cLib.inf
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/SerialIoI2cLib.c
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/SerialIoI2cPrivateLib.c
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/SerialIoI2cPrivateLib.h
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/SerialIoI2cRegs.h
Silicon/AlderlakePkg/Library/BaseSerialIoI2cLib/SerialIoI2cRegsVer2.h

feat:[ADL-P] Add i2c library

---

Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/MaxLedInit.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.h
Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf

- add MaxLed Module support for Max6950
- send POST code over I2C

feat:[ADL-P] Add MaxLed support for send POST code over I2C

---

BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.c

- UFS device would clear fDeviceInit flag once the device initialization is completed.
- This change is polling to check the flag is cleared or not with specific timeout (UFS_INIT_COMPLETION_TIMEOUT - 600ms).

fix: [common] Extend Ufs devices waiting for fDeviceInit

---

Platform/RaptorlakeBoardPkg/BoardConfigRplPs.py
Platform/RaptorlakeBoardPkg/Script/StitchIfwiConfig_rplps.py

feat:[RPL-PS] pfr enablement

---

BootloaderCommonPkg/Library/ShellLib/CmdPerf.c

Add a parameter to show the boot performance data
in MicroSecond. By default it uses MilliSecond as-is.

Enhance OsLoader shell perf command

---

Platform/MeteorlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Sync with other platforms to restore SMM info into the PostPciEnumeration phase for S3 path and call
ClearS3SaveRegion() in normal path to avoid appending multiple restore records

fix: [MTL] move SMM info restore into PostPciEnumeration

---

Platform/ArrowlakeBoardPkg/Script/StitchIfwiConfig_arls.py

This commit is to address feedback as stated in https://github.com/slimbootloader/slimbootloader/pull/2322

fix: [ARLS] Update XML change list for RVP boards

---

Silicon/ElkhartlakePkg/FspBin/FspBin.inf

BIOS version is Elkhart Lake IPU2025.1 FSP
FSP version is 09063141
platform version is 1.7
Microcode Files are: ['m_01_90661_0000001a.pdb']

feat: [EHL] Update IPU2025.1 Release

---

Platform/RaptorlakeBoardPkg/BoardConfigRplp.py
Silicon/RaptorlakePkg/Rplp/Fsp/FspBinRplp.inf

- FSP: NEX RPL-P MR3 (0C.01.F7.20)
- platform version: 1.3

[RPLP] Update for MR3 release

---

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf
Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf

BIOS version is NEX RPL-S MR5/RPL-S Refresh MR3 (5401_01) FSP FSP version is 0C00F720
platform version is 1.5
Microcode Files are: ['m_07_90672_00000036.pdb', 'm_32_b0671_0000012c.pdb']

feat: [RPLS] Update MR5 Release

---

Platform/RaptorlakeBoardPkg/BoardConfigRplPs.py
Silicon/RaptorlakePkg/Rplps/Fsp/FspBinRplps.inf
Silicon/RaptorlakePkg/Rplps/Microcode/MicrocodeRplps.inf

BIOS version is IoT RPL-PS MR1 (5274_42) FSP
FSP version is 0C01EC40
platform version is 1.1
Microcode Files are: ['m_e0_b06a2_00004123.pdb', 'm_80_906a3_00000434.pdb']

feat: [RPLPS] Update MR1 Release

---

Platform/ArrowlakeBoardPkg/Library/FspmUpdUpdateLib/FspmUpdUpdateLib.c
Platform/ArrowlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c

Update PCH Pcie UPD from config data
Align ARLS SODIMM RVP UPD with BIOS

fix: [ARLS] Update FSP UPD

---

Silicon/TigerlakePkg/FspBin/FspBin.inf

BIOS version for IPU 2025.1
TGL-U : 7354_01
TGL-H: 7355_01
FSP version is 0A.00.84.71

[TGL] Community Update FSP for IPU2025.1

---

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Update ARLH NVS to sync with BIOS value.

feat: [ARLH] Sync NVS value with BIOS

---

Platform/ArrowlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c

Add S5 support in ARL reset system library.

ARL: Add shutdown support

---

Silicon/MeteorlakePkg/FspBin/FspBin.inf

BIOS version is NEX MTL-UH_MTL-PS MR2 (4122_56) FSP
FSP version is 0DE0CC30

feat: [MTL] Update FSP for MR2

---

BootloaderCommonPkg/Library/BuildFdtLib/BuildFdtLib.c

- NULL Pointer Dereference (CWE-476) on the PciRootBridgeInfo
- Assignment to Variable without Use (CWE-563) on Status
- The return value of AsciiSPrint should be UINTN, so remove Status

fix: [common] Fix Coverity issues in BuildFdtLib

---

Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arlp_Lpddr5_Rvp.dlt
Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arlp_Sodimm_Crb.dlt
Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arlp_Sodimm_Rvp.dlt
Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arls_Sodimm_Rvp_S04.dlt
Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arls_UDimm_Rvp_S02.dlt
Platform/ArrowlakeBoardPkg/CfgData/CfgDataInt_Arls_UDimm_Rvp_S03.dlt

Upstream delta files for:
1. ARLP LPDDR5 RVP
2. ARLP SODIMM CRB
3. ARLP SODIMM RVP
4. ARLS SODIMM RVP S04
5. ARLS UDIMM RVP S02
6. ARLS UDIMM RVP S03

feat: [ARL] Upstream delta files for ARL platform

---

Platform/AlderlakeBoardPkg/BoardConfigAdlN50.py

fix: [UP7000] fix ADLN50 build failure

---

Platform/AlderlakeBoardPkg/BoardConfigAzb.py

Update the AZB SBL version to 1.5 for IPU 25.2.

feat: [AZB] Update AZB SBL version to 1.5

---

Platform/AlderlakeBoardPkg/Script/StitchIfwi.py

Update python scripts as per Bandit guidance

fix: mitigate Bandit issue

---

Silicon/ArrowlakePkg/Arlh/Fsp/FspBin.inf
Silicon/ArrowlakePkg/Arls/Fsp/FspBin.inf

Create FspBin.inf to fetch FSP binaries and VBT for Arrowlake platform.

feat:[ARL] Create FspBin.inf to fetch FSP binaries

---

Platform/ArrowlakeBoardPkg/BoardConfigArlh.py
Platform/ArrowlakeBoardPkg/BoardConfigArls.py
Platform/ArrowlakeBoardPkg/BoardConfigArlu.py

Updated board config fsp and ucode file
Aligned with the path set in FspBin.inf

fix: [ARL] Update Board Config FSP and Ucode path

---

Silicon/ArrowlakePkg/Arlh/Microcode/Microcode.inf
Silicon/ArrowlakePkg/Arlh/Microcode/MicrocodeArlu.inf
Silicon/ArrowlakePkg/Arls/Microcode/Microcode.inf

Upstream Arrowlake Microcode.inf to fetch microcode for ARLS and ARLH/U

feat: [ARL] Upstream Microcode.inf

---

Silicon/ArrowlakePkg/Arlh/Fsp/FspBin.inf
Silicon/ArrowlakePkg/Arlh/Microcode/MicrocodeArlu.inf
Silicon/ArrowlakePkg/Arls/Fsp/FspBin.inf

Update microcode file path and FSP repo commit ID to fix build failure

fix: [ARLH] fixed build failure in ARLH/U

---

.azurepipelines/azure-pipelines.yml

Enable Azure pipeline CI build for ARLH, ARLS and ARLU Platform

feat: [ARL] Enable Azure pipeline CI build

---

BootloaderCorePkg/Tools/SblSetup.py

Fixed the issue of parsing combobox in array in SblSetup.py

fix:[Common] Parsing combobox in array issue fix

---

Silicon/TigerlakePkg/FspBin/FspBin.inf
Silicon/TigerlakePkg/Microcode/Microcode.inf

[TGL] Community Update FSP/UCODE for IPU2025.2

---

BaseTools/Source/C/Lz4Compress/Sdk/lz4.c
BaseTools/Source/C/Lz4Compress/Sdk/lz4.h
BaseTools/Source/C/Lz4Compress/Sdk/lz4frame.c
BaseTools/Source/C/Lz4Compress/Sdk/lz4frame.h
BaseTools/Source/C/Lz4Compress/Sdk/lz4frame_static.h
BaseTools/Source/C/Lz4Compress/Sdk/lz4hc.c
BaseTools/Source/C/Lz4Compress/Sdk/lz4hc.h
BaseTools/Source/C/Lz4Compress/Sdk/xxhash.c
BaseTools/Source/C/Lz4Compress/Sdk/xxhash.h

feat: upgrade lz4 version

---

Platform/AlderlakeBoardPkg/BoardConfigAdlN.py
Silicon/AlderlakePkg/FspBin/FspBin.inf

- FSP: IoT ADL-N MR7 (0C.02.89.40)
- Microcode: m_19_b06a0_0000001c
- VBT: 256
- platform version: SB_ADLN-1.7

[ADLN/ASL/TWL] Update for ADLN MR7, ASL MR3, TWL PV

---

BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCorePkg/Library/FspApiLib/FspMisc.c
Platform/AlderlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c
Platform/ArrowlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c
Platform/CoffeelakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c
Platform/ElkhartlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c
Platform/MeteorlakeBoardPkg/Library/ResetSystemLib/ResetSystemLib.c

Update PcdFspResetStatus size to support 64Bit FSP return status.

fix: [Common] Update PcdFspResetStatus size

---

Silicon/AlderlakePkg/Microcode/Microcode.inf

- Microcode: m_19_b06e0_0000001d

[ADLN/ASL/TWL] Update UCODE for ADLN MR7, ASL MR3, TWL PV

---

Platform/RaptorlakeBoardPkg/BoardConfigRpls.py
Silicon/RaptorlakePkg/Rpls/Fsp/FspBinRpls.inf
Silicon/RaptorlakePkg/Rpls/Microcode/MicrocodeRpls.inf

- FSP: Edge Platforms RPL-S IPU 2025.2 (0C.01.F7.20)
- Microcode: m_32_b0671_0000012e

[RPLS] Update for MR6

---

Platform/RaptorlakeBoardPkg/BoardConfigBtls.py
Platform/RaptorlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c
Platform/RaptorlakeBoardPkg/Script/StitchIfwi.py
Platform/RaptorlakeBoardPkg/Script/StitchIfwiConfig_btls.py
Silicon/RaptorlakePkg/Btls/Fsp/FspBinBtls.inf
Silicon/RaptorlakePkg/Btls/Microcode/MicrocodeBtls.inf

Add support for BTL-S Hybrid platform and collateral.

[BTL-S] Upstream BTL-S Hybrid platform.

---

.azurepipelines/azure-pipelines.yml
Platform/RaptorlakeBoardPkg/BoardConfigRpls.py

Add BTL-S build targets to azure build tests for pre-commit check.

feat: [BTL-S] Add BTL-S builds to Azure CI pipelines

---

Platform/ArrowlakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c

Set SMI lock bit at ReadyToBoot for Osloader

fix: [ARL] Set SMI lock bit for Osloader

---

Silicon/CommonSocPkg/Include/BupMsgs.h
Silicon/CommonSocPkg/Include/CoreBiosMsg.h
Silicon/CommonSocPkg/Include/Library/HeciMeExtLib.h
Silicon/CommonSocPkg/Include/PcieRegs.h
Silicon/CommonSocPkg/Include/Register/HeciRegs.h
Silicon/CommonSocPkg/Library/HeciMeExtLib/HeciMeExtLib.c
Silicon/CommonSocPkg/Library/HeciMeExtLib/HeciMeExtLib.inf

Make HeciMeExtLib common.
Add Arl HeciMeExtLib to CommonSocPk and remove silicon dependency.

feat:[Common] Add  HeciMeExtLib to CommonSocPkg

---

Platform/AlderlakeBoardPkg/BoardConfig.py
Silicon/AlderlakePkg/FspBin/FspBin.inf

Fsp sync  to BIOS version 6114_00

feat: ADL-N/ASL IPU 2025.3 community update

---

Silicon/RaptorlakePkg/Rplp/Fsp/FspBinRplp.inf
Silicon/RaptorlakePkg/Rplp/Microcode/MicrocodeRplp.inf

FSP sync to BIOS version 6073_03
Microcode update to 0x4129

feat: RPLP IPU 2025.3 community update

---

Platform/CommonBoardPkg/Tools/GpioV2DataConvert.py

GpioV2DataConvert.py tool assumes the data value defined in .h file using decimal format. This enhancement adds hex format support.

Enhance GPIO data convert Tool

---

Silicon/RaptorlakePkg/Btls/Fsp/FspBinBtls.inf

Update FSP and microcode to BTL-S MR1 release.

feat: [BTL-S] Hybrid MR1 FSP and microcode

---

Platform/AlderlakeBoardPkg/BoardConfigAzb.py
Silicon/AlderlakePkg/Microcode/MicrocodeAzb.inf

Updated Microcode commit id and SBL version to 1.7

feat: [AZB] Updated Microcode commit id and SBL Version  IPU 26.1

---

Silicon/CommonSocPkg/Include/Library/FusaConfigLib.h
Silicon/CommonSocPkg/Library/FusaConfigLibNull/FusaConfigLibNull.c

Add FuSa boot option hook in null library

feat: [Common] Add FuSa boot option hook

---

Silicon/TigerlakePkg/Library/TxtLib/Txt.h

Update BIOS_OS_DATA_REGION structure.
This has to be defined as per the TXT MLE spec

[TGL][TXT] Update BIOS_OS_DATA_REGION structure

---

BootloaderCommonPkg/BootloaderCommonPkg.dec
BootloaderCorePkg/BootloaderCorePkg.dsc
BootloaderCorePkg/Stage2/Stage2.c
BootloaderCorePkg/Stage2/Stage2.inf
BuildLoader.py

Enable/Disable ELFlib through boardconfig.

Code changes to enable/disable ELF Lib Support
